import {
  DISTANCE_UNITS,
  EXCLUSION_NOTE_MAX,
  EXCLUSION_REASONS,
  EXPENSE_SOURCES,
  EXPENSE_STATUSES,
  LINE_KINDS,
  MEMBER_ROLES,
  ORGANIZATION_SIZES,
  REPORT_STATUSES,
  newId,
} from '@expensewise/domain';
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  char,
  check,
  date,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

/*
 * Schema v1. Conventions (docs/05-architecture.md, ADR-0008):
 * - Every tenant table carries org_id. Row-level security in migration 0001 enforces it.
 * - References between tenant tables are composite (org_id, id) foreign keys, so a row
 *   can never point at another organization's row, even though FK checks bypass RLS.
 * - Money is bigint minor units plus a char(3) ISO 4217 code. Never numeric, never float.
 * - Transaction and travel dates are local calendar dates; instants are timestamptz.
 * - IDs are UUIDv7, generated by the application.
 */

export const memberRole = pgEnum('member_role', MEMBER_ROLES);
export const expenseStatus = pgEnum('expense_status', EXPENSE_STATUSES);
export const expenseSource = pgEnum('expense_source', EXPENSE_SOURCES);
export const reportStatus = pgEnum('report_status', REPORT_STATUSES);
export const distanceUnit = pgEnum('distance_unit', DISTANCE_UNITS);
export const organizationSize = pgEnum('organization_size', ORGANIZATION_SIZES);
export const tripStatus = pgEnum('trip_status', ['planned', 'active', 'closed']);
export const receiptStatus = pgEnum('receipt_status', [
  'processing',
  'extracted',
  'needs_review',
  'failed',
]);
export const extractionOutcome = pgEnum('extraction_outcome', ['confident', 'unsure', 'failed']);
export const approvalDecision = pgEnum('approval_decision', ['pending', 'approved', 'returned']);
export const mileageMethod = pgEnum('mileage_method', ['manual', 'route', 'gps']);
export const actorType = pgEnum('actor_type', ['user', 'system']);
export const aiProvider = pgEnum('ai_provider', ['anthropic', 'openai']);
export const aiAuthScheme = pgEnum('ai_auth_scheme', ['api_key', 'bearer']);

const id = () => uuid('id').primaryKey().$defaultFn(newId);
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
const isoCurrency = (column: unknown) => sql`${column} ~ '^[A-Z]{3}$'`;

export const organizations = pgTable(
  'organizations',
  {
    id: id(),
    name: text('name').notNull(),
    /** Reports opened from now on are in it; a change converts nothing already made (FR-PLT-11). */
    homeCurrency: char('home_currency', { length: 3 }).notNull(),
    createdAt: createdAt(),
    /** ISO 3166-1 alpha-2. The details below are the owner's to keep, each optional (FR-PLT-11). */
    country: char('country', { length: 2 }),
    /** A BCP 47 language tag, such as en-US. */
    locale: text('locale'),
    /**
     * An IANA time zone, checked against Postgres's own list when set. With organization
     * settings on, it says when the organization's day ends: when trips and local expenses join
     * a report, and which day is day 28 (ADR-0037).
     */
    timeZone: text('time_zone'),
    /** The postal address, as the owner writes it. */
    address: text('address'),
    industry: text('industry'),
    size: organizationSize('size'),
    /**
     * How many minutes apart two receipts at one place can be and still be one purchase, as
     * the owner set it (FR-INT-19). Empty means the default of 30, which lives in the domain.
     */
    duplicateWindowMinutes: integer('duplicate_window_minutes'),
  },
  (t) => [
    check('organizations_home_currency_iso', isoCurrency(t.homeCurrency)),
    check('organizations_country_code', sql`${t.country} IS NULL OR ${t.country} ~ '^[A-Z]{2}$'`),
    check(
      'organizations_duplicate_window_range',
      sql`${t.duplicateWindowMinutes} IS NULL OR ${t.duplicateWindowMinutes} BETWEEN 0 AND 120`,
    ),
  ],
);

const orgId = () =>
  uuid('org_id')
    .notNull()
    .references(() => organizations.id);

export const members = pgTable(
  'members',
  {
    id: id(),
    orgId: orgId(),
    /** The member's first sign-in (identity provider subject). Access uses member_sign_ins. */
    userId: text('user_id').notNull(),
    email: text('email').notNull(),
    displayName: text('display_name').notNull(),
    role: memberRole('role').notNull().default('member'),
    managerMemberId: uuid('manager_member_id'),
    /**
     * The currency the member is reimbursed in, chosen in Settings (FR-EXP-13, Q23). Null until
     * they choose one: then it is the organization's home currency.
     */
    reimbursementCurrency: char('reimbursement_currency', { length: 3 }),
    createdAt: createdAt(),
    /**
     * When an owner removed them (FR-PLT-07): they no longer sign in here, and their records
     * and history stay. Null while they are a member.
     */
    deactivatedAt: timestamp('deactivated_at', { withTimezone: true }),
  },
  (t) => [
    unique('members_org_id_id_key').on(t.orgId, t.id),
    unique('members_org_user_key').on(t.orgId, t.userId),
    foreignKey({
      name: 'members_manager_fk',
      columns: [t.orgId, t.managerMemberId],
      foreignColumns: [t.orgId, t.id],
    }),
    check(
      'members_reimbursement_currency_iso',
      sql`${t.reimbursementCurrency} IS NULL OR ${isoCurrency(t.reimbursementCurrency)}`,
    ),
  ],
);

/**
 * How a member signs in. A person can have several sign-ins, such as a personal and a work
 * email; each one reaches the same member, so approvals and separation of duties still see
 * one person. A sign-in belongs to exactly one member (Phase 1). Access goes through this
 * table; members.user_id records only the member's first sign-in.
 */
export const memberSignIns = pgTable(
  'member_sign_ins',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    /** Subject from the identity provider (Supabase Auth `sub`). */
    userId: text('user_id').notNull(),
    email: text('email').notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('member_sign_ins_org_id_id_key').on(t.orgId, t.id),
    unique('member_sign_ins_user_key').on(t.userId),
    foreignKey({
      name: 'member_sign_ins_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    index('member_sign_ins_member_idx').on(t.orgId, t.memberId),
  ],
);

/**
 * A link that lets one person join the organization with a role (FR-PLT-07, ADR-0035). Only
 * the SHA-256 of its token is kept: the link itself is shown once, to the owner who made it.
 * It works once, until it expires or is revoked; an accepted or revoked invite stays as a
 * record of who let whom in.
 */
export const memberInvites = pgTable(
  'member_invites',
  {
    id: id(),
    orgId: orgId(),
    /** The role the person joins with. */
    role: memberRole('role').notNull(),
    /** The owner's note of who it is for, shown only to the organization's owners. */
    label: text('label'),
    /** SHA-256 of the token in the link, as hex. The token itself is never stored. */
    tokenHash: char('token_hash', { length: 64 }).notNull(),
    createdByMemberId: uuid('created_by_member_id').notNull(),
    createdAt: createdAt(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
    acceptedByMemberId: uuid('accepted_by_member_id'),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
  },
  (t) => [
    unique('member_invites_org_id_id_key').on(t.orgId, t.id),
    unique('member_invites_token_hash_key').on(t.tokenHash),
    foreignKey({
      name: 'member_invites_created_by_fk',
      columns: [t.orgId, t.createdByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'member_invites_accepted_by_fk',
      columns: [t.orgId, t.acceptedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('member_invites_token_hash_hex', sql`${t.tokenHash} ~ '^[0-9a-f]{64}$'`),
    check(
      'member_invites_accepted_by_someone',
      sql`(${t.acceptedAt} IS NULL) = (${t.acceptedByMemberId} IS NULL)`,
    ),
    check(
      'member_invites_accepted_or_revoked',
      sql`${t.acceptedAt} IS NULL OR ${t.revokedAt} IS NULL`,
    ),
    check('member_invites_expires_after_made', sql`${t.expiresAt} > ${t.createdAt}`),
    check('member_invites_label_short', sql`${t.label} IS NULL OR length(${t.label}) <= 80`),
    index('member_invites_org_created_idx').on(t.orgId, t.createdAt),
  ],
);

export const trips = pgTable(
  'trips',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    name: text('name').notNull(),
    purpose: text('purpose'),
    startDate: date('start_date', { mode: 'string' }).notNull(),
    endDate: date('end_date', { mode: 'string' }).notNull(),
    primaryCity: text('primary_city'),
    status: tripStatus('status').notNull().default('planned'),
    /**
     * The report it is on: it joins 24 hours after its return date, or a person moves it
     * (FR-EXP-05). Its expenses go with it.
     */
    reportId: uuid('report_id'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('trips_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'trips_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'trips_report_fk',
      columns: [t.orgId, t.memberId, t.reportId],
      foreignColumns: [reports.orgId, reports.memberId, reports.id],
    }),
    index('trips_report_idx').on(t.orgId, t.reportId),
    check('trips_dates_ordered', sql`${t.endDate} >= ${t.startDate}`),
    index('trips_member_dates_idx').on(t.orgId, t.memberId, t.startDate),
  ],
);

/**
 * The categories an organization codes its expenses to, with their general ledger and tax codes
 * (FR-EXP-11, Q7, ADR-0036). They nest, and each allows a set of types (category_types). An
 * organization starts with a ready-made set, seeded by seed_starter_catalog(), that owners and
 * finance admins rename, add to or retire.
 */
export const categories = pgTable(
  'categories',
  {
    id: id(),
    orgId: orgId(),
    /** The category it sits under; null at the top. */
    parentId: uuid('parent_id'),
    name: text('name').notNull(),
    glCode: text('gl_code'),
    taxCode: text('tax_code'),
    /** False once retired: no longer offered, but kept by every expense that has it. */
    active: boolean('active').notNull().default(true),
    /** The ready-made category it started as, such as `travel`; null for one a person added. */
    starterKey: text('starter_key'),
    /**
     * Who last added or changed it; null while it is as the ready-made set left it, so an
     * untouched set is no one's work.
     */
    updatedByMemberId: uuid('updated_by_member_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('categories_org_id_id_key').on(t.orgId, t.id),
    unique('categories_org_name_key').on(t.orgId, t.name),
    unique('categories_org_starter_key').on(t.orgId, t.starterKey),
    foreignKey({
      name: 'categories_parent_fk',
      columns: [t.orgId, t.parentId],
      foreignColumns: [t.orgId, t.id],
    }),
    foreignKey({
      name: 'categories_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('categories_not_own_parent', sql`${t.parentId} IS NULL OR ${t.parentId} <> ${t.id}`),
  ],
);

/**
 * The types an organization's expenses are, such as Airfare or Business meal: what was bought,
 * where rules will attach (FR-EXP-11, Q7, ADR-0036). A list of its own that nests, beside the
 * categories; a category allows some of them.
 */
export const expenseTypes = pgTable(
  'expense_types',
  {
    id: id(),
    orgId: orgId(),
    /** The type it sits under; null at the top. */
    parentId: uuid('parent_id'),
    name: text('name').notNull(),
    /** False once retired: no longer offered, but kept by every expense that has it. */
    active: boolean('active').notNull().default(true),
    /**
     * The ready-made type it started as, such as `airfare`. Keyword suggestions find a type by
     * it, so a renamed one keeps its suggestions.
     */
    starterKey: text('starter_key'),
    /** Who last added or changed it; null while it is as the ready-made set left it. */
    updatedByMemberId: uuid('updated_by_member_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expense_types_org_id_id_key').on(t.orgId, t.id),
    unique('expense_types_org_name_key').on(t.orgId, t.name),
    unique('expense_types_org_starter_key').on(t.orgId, t.starterKey),
    foreignKey({
      name: 'expense_types_parent_fk',
      columns: [t.orgId, t.parentId],
      foreignColumns: [t.orgId, t.id],
    }),
    foreignKey({
      name: 'expense_types_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('expense_types_not_own_parent', sql`${t.parentId} IS NULL OR ${t.parentId} <> ${t.id}`),
  ],
);

/** Which types each category allows (Q7): choosing a category narrows the types to these. */
export const categoryTypes = pgTable(
  'category_types',
  {
    id: id(),
    orgId: orgId(),
    categoryId: uuid('category_id').notNull(),
    typeId: uuid('type_id').notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('category_types_org_id_id_key').on(t.orgId, t.id),
    unique('category_types_pair_key').on(t.orgId, t.categoryId, t.typeId),
    foreignKey({
      name: 'category_types_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'category_types_type_fk',
      columns: [t.orgId, t.typeId],
      foreignColumns: [expenseTypes.orgId, expenseTypes.id],
    }),
    index('category_types_type_idx').on(t.orgId, t.typeId),
  ],
);

/**
 * A member's expense report: trips, which join 24 hours after their return date, and local
 * expenses (FR-EXP-05, FR-EXP-14, ADR-0029). A trip points at its report, and a local
 * expense too; an expense on a trip goes with its trip.
 */
export const reports = pgTable(
  'reports',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    title: text('title').notNull(),
    status: reportStatus('status').notNull().default('open'),
    /**
     * The currency it is reimbursed in: its member's reimbursement currency, which it follows
     * until it is submitted (FR-EXP-13). Every amount on it is converted to this.
     */
    currency: char('currency', { length: 3 }).notNull(),
    /** When an open report closes itself: 28 days after opening, later if reopened. */
    closesAt: timestamp('closes_at', { withTimezone: true }).notNull(),
    /** When it last closed, by the person or on day 28; null while open. */
    closedAt: timestamp('closed_at', { withTimezone: true }),
    submittedAt: timestamp('submitted_at', { withTimezone: true }),
    approvedAt: timestamp('approved_at', { withTimezone: true }),
    settledAt: timestamp('settled_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('reports_org_id_id_key').on(t.orgId, t.id),
    // What points at a report names its member too, so a report holds only its member's.
    unique('reports_org_member_id_key').on(t.orgId, t.memberId, t.id),
    foreignKey({
      name: 'reports_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('reports_currency_iso', isoCurrency(t.currency)),
    check('reports_closed_when_closed', sql`(${t.status} = 'open') = (${t.closedAt} IS NULL)`),
    index('reports_member_status_idx').on(t.orgId, t.memberId, t.status),
  ],
);

export const expenses = pgTable(
  'expenses',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    tripId: uuid('trip_id'),
    /** The report a local expense is on (FR-EXP-14); null for one on a trip. */
    reportId: uuid('report_id'),
    /**
     * The category and type a person chose for it (FR-EXP-11), the type one the category
     * allowed then. A suggestion is never stored here; it is worked out when shown (FR-INT-10).
     */
    categoryId: uuid('category_id'),
    typeId: uuid('type_id'),
    /** When a person last chose its category and type; it orders their history for suggestions. */
    classifiedAt: timestamp('classified_at', { withTimezone: true }),
    status: expenseStatus('status').notNull(),
    source: expenseSource('source').notNull(),
    merchant: text('merchant'),
    transactionDate: date('transaction_date', { mode: 'string' }),
    amountMinor: bigint('amount_minor', { mode: 'number' }),
    currency: char('currency', { length: 3 }),
    homeAmountMinor: bigint('home_amount_minor', { mode: 'number' }),
    fxRate: numeric('fx_rate', { precision: 20, scale: 10 }),
    fxRateDate: date('fx_rate_date', { mode: 'string' }),
    fxSource: text('fx_source'),
    /**
     * When it was bought, as local time HH:MM, and the IANA time zone that time is in: read
     * from its receipt (FR-INT-17), the zone worked out from the place, or set by a person.
     */
    transactionTime: text('transaction_time'),
    timeZone: text('time_zone'),
    /** Where it was bought: the merchant's address as printed, and what was picked out of it. */
    merchantAddress: text('merchant_address'),
    merchantCity: text('merchant_city'),
    merchantRegion: text('merchant_region'),
    /** ISO 3166-1 alpha-2. */
    merchantCountry: char('merchant_country', { length: 2 }),
    notes: text('notes'),
    /**
     * Why a local expense, one on no trip, was for business. Its report can't close without
     * it (FR-EXP-14).
     */
    justification: text('justification'),
    /**
     * When a person last edited the values. From then on a reading of the receipt never
     * overwrites them (ADR-0022); a difference from the receipt shows instead.
     */
    editedAt: timestamp('edited_at', { withTimezone: true }),
    /**
     * A person chose its trip, or chose no trip. From then on filing by date never moves it
     * (ADR-0023).
     */
    tripPinned: boolean('trip_pinned').notNull().default(false),
    /** Corrections to approved expenses are a reversal plus a new version. */
    version: integer('version').notNull().default(1),
    reversalOfId: uuid('reversal_of_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expenses_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'expenses_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'expenses_trip_fk',
      columns: [t.orgId, t.tripId],
      foreignColumns: [trips.orgId, trips.id],
    }),
    // Only a local expense points at a report itself; one on a trip goes with its trip.
    foreignKey({
      name: 'expenses_report_fk',
      columns: [t.orgId, t.memberId, t.reportId],
      foreignColumns: [reports.orgId, reports.memberId, reports.id],
    }),
    check('expenses_report_only_when_local', sql`${t.reportId} IS NULL OR ${t.tripId} IS NULL`),
    check(
      'expenses_time_of_day',
      sql`${t.transactionTime} IS NULL OR ${t.transactionTime} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'`,
    ),
    check(
      'expenses_country_code',
      sql`${t.merchantCountry} IS NULL OR ${t.merchantCountry} ~ '^[A-Z]{2}$'`,
    ),
    foreignKey({
      name: 'expenses_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'expenses_type_fk',
      columns: [t.orgId, t.typeId],
      foreignColumns: [expenseTypes.orgId, expenseTypes.id],
    }),
    // A category and a type are chosen together, and when.
    check(
      'expenses_classified_whole',
      sql`(${t.categoryId} IS NULL AND ${t.typeId} IS NULL AND ${t.classifiedAt} IS NULL) OR (${t.categoryId} IS NOT NULL AND ${t.typeId} IS NOT NULL AND ${t.classifiedAt} IS NOT NULL)`,
    ),
    foreignKey({
      name: 'expenses_reversal_fk',
      columns: [t.orgId, t.reversalOfId],
      foreignColumns: [t.orgId, t.id],
    }),
    check('expenses_currency_iso', sql`${t.currency} IS NULL OR ${isoCurrency(t.currency)}`),
    // From Ready onward an expense is complete: amount, currency and date are known.
    check(
      'expenses_complete_when_ready',
      sql`${t.status} IN ('processing', 'needs_review') OR (${t.amountMinor} IS NOT NULL AND ${t.currency} IS NOT NULL AND ${t.transactionDate} IS NOT NULL)`,
    ),
    // A converted amount is only auditable with its rate, date and source.
    check(
      'expenses_fx_complete',
      sql`(${t.fxRate} IS NULL AND ${t.fxRateDate} IS NULL AND ${t.fxSource} IS NULL) OR (${t.fxRate} IS NOT NULL AND ${t.fxRateDate} IS NOT NULL AND ${t.fxSource} IS NOT NULL AND ${t.homeAmountMinor} IS NOT NULL)`,
    ),
    index('expenses_member_date_idx').on(t.orgId, t.memberId, t.transactionDate),
    index('expenses_trip_idx').on(t.orgId, t.tripId),
    index('expenses_report_idx').on(t.orgId, t.reportId),
    index('expenses_status_idx').on(t.orgId, t.status),
    index('expenses_member_classified_idx').on(t.orgId, t.memberId, t.classifiedAt),
  ],
);

export const conversionOutcome = pgEnum('conversion_outcome', ['converted', 'unavailable']);

/**
 * An expense's amount converted to the currency its report is reimbursed in (FR-EXP-13,
 * ADR-0034): what was converted, and the reference rate it was converted at with that rate's
 * date and source, copied on so a later rate never changes it (NFR-DAT-02, NFR-DAT-04); or that
 * the source has no rate for it. One per expense: once its amount, currency, date or
 * reimbursement currency changes, the next conversion replaces it, and each is in the audit
 * trail. It goes with its expense when that is deleted.
 */
export const expenseConversions = pgTable(
  'expense_conversions',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    /** What was converted: the amount as spent, in its currency's minor units. */
    amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    /** The purchase date, whose reference rate applies (Q25). */
    purchaseDate: date('purchase_date', { mode: 'string' }).notNull(),
    /** The currency it was converted to: its report's. */
    reimbursementCurrency: char('reimbursement_currency', { length: 3 }).notNull(),
    /** converted, or unavailable: the source publishes no rate for it. */
    outcome: conversionOutcome('outcome').notNull(),
    /** The amount in the reimbursement currency's minor units: `amount_minor` times `rate`. */
    convertedMinor: bigint('converted_minor', { mode: 'number' }),
    /** What one unit of `currency` is in the reimbursement currency, exactly as applied. */
    rate: numeric('rate'),
    /** The day the rate was published: the purchase date, or the last day before it. */
    rateDate: date('rate_date', { mode: 'string' }),
    /** Who published the rate, or has none: `ECB`. */
    source: text('source').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expense_conversions_org_id_id_key').on(t.orgId, t.id),
    unique('expense_conversions_expense_key').on(t.orgId, t.expenseId),
    foreignKey({
      name: 'expense_conversions_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }).onDelete('cascade'),
    check('expense_conversions_currency_iso', isoCurrency(t.currency)),
    check('expense_conversions_into_iso', isoCurrency(t.reimbursementCurrency)),
    check('expense_conversions_two_currencies', sql`${t.currency} <> ${t.reimbursementCurrency}`),
    // A converted amount is only auditable with its rate, the rate's date and its source.
    check(
      'expense_conversions_rate_complete',
      sql`(${t.outcome} = 'converted' AND ${t.convertedMinor} IS NOT NULL AND ${t.rate} IS NOT NULL AND ${t.rate} > 0 AND ${t.rateDate} IS NOT NULL AND ${t.rateDate} <= ${t.purchaseDate}) OR (${t.outcome} = 'unavailable' AND ${t.convertedMinor} IS NULL AND ${t.rate} IS NULL AND ${t.rateDate} IS NULL)`,
    ),
    check('expense_conversions_source_named', sql`length(trim(${t.source})) > 0`),
  ],
);

export const lineKind = pgEnum('line_kind', LINE_KINDS);
export const exclusionReason = pgEnum('exclusion_reason', EXCLUSION_REASONS);
export const splitBasis = pgEnum('split_basis', ['lines', 'amounts']);

/**
 * A receipt's itemized lines as its expense keeps them (FR-INT-22, ADR-0041): the currency,
 * total and subtotal of the reading they were copied from. Copied when the expense is filed,
 * and again with each new reading, until a person edits the expense, excludes a line or splits
 * it; from then on they stay as they were, as the expense's values do (ADR-0022). One per
 * expense; it goes with its expense when that is deleted.
 */
export const expenseItemizations = pgTable(
  'expense_itemizations',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    /** The receipt's total and subtotal as read, in `currency`'s minor units; null when unread. */
    totalMinor: bigint('total_minor', { mode: 'number' }),
    subtotalMinor: bigint('subtotal_minor', { mode: 'number' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expense_itemizations_org_id_id_key').on(t.orgId, t.id),
    unique('expense_itemizations_expense_key').on(t.orgId, t.expenseId),
    // What each line points at, so its currency is the itemization's.
    unique('expense_itemizations_expense_currency_key').on(t.orgId, t.expenseId, t.currency),
    foreignKey({
      name: 'expense_itemizations_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }).onDelete('cascade'),
    check('expense_itemizations_currency_iso', isoCurrency(t.currency)),
  ],
);

/**
 * One line of an expense's receipt, numbered from 1 as printed: each item (a discount is a
 * negative item), then each tax, each fee and the tip. An item line can be excluded from the
 * claim with a reason, and a note that other needs (FR-EXP-16, Q40), and given a category and
 * type of its own, which makes it a part of the expense (FR-EXP-15, Q38).
 */
export const expenseLines = pgTable(
  'expense_lines',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    position: integer('position').notNull(),
    kind: lineKind('kind').notNull(),
    /** As printed. */
    description: text('description').notNull(),
    quantity: text('quantity'),
    /** As read, in `currency`'s minor units; negative for a discount. */
    amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    /** Why it is left out of the claim, with a note, and when; null while it is claimed. */
    excludedReason: exclusionReason('excluded_reason'),
    excludedNote: text('excluded_note'),
    excludedAt: timestamp('excluded_at', { withTimezone: true }),
    /** The category and type a person gave it in a split by line; null: the expense's own. */
    categoryId: uuid('category_id'),
    typeId: uuid('type_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expense_lines_org_id_id_key').on(t.orgId, t.id),
    unique('expense_lines_position_key').on(t.orgId, t.expenseId, t.position),
    foreignKey({
      name: 'expense_lines_itemization_fk',
      columns: [t.orgId, t.expenseId, t.currency],
      foreignColumns: [
        expenseItemizations.orgId,
        expenseItemizations.expenseId,
        expenseItemizations.currency,
      ],
    }).onDelete('cascade'),
    foreignKey({
      name: 'expense_lines_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'expense_lines_type_fk',
      columns: [t.orgId, t.typeId],
      foreignColumns: [expenseTypes.orgId, expenseTypes.id],
    }),
    check('expense_lines_position_positive', sql`${t.position} > 0`),
    check('expense_lines_currency_iso', isoCurrency(t.currency)),
    // Only an item is excluded or split off; tax, tip and fees go with the items.
    check(
      'expense_lines_items_only',
      sql`${t.kind} = 'item' OR (${t.excludedReason} IS NULL AND ${t.categoryId} IS NULL)`,
    ),
    check(
      'expense_lines_excluded_whole',
      sql`(${t.excludedReason} IS NULL AND ${t.excludedNote} IS NULL AND ${t.excludedAt} IS NULL) OR (${t.excludedReason} IS NOT NULL AND ${t.excludedAt} IS NOT NULL)`,
    ),
    check(
      'expense_lines_other_needs_note',
      sql`${t.excludedReason} IS DISTINCT FROM 'other' OR coalesce(length(trim(${t.excludedNote})), 0) > 0`,
    ),
    check(
      'expense_lines_note_length',
      sql`${t.excludedNote} IS NULL OR char_length(${t.excludedNote}) <= ${sql.raw(String(EXCLUSION_NOTE_MAX))}`,
    ),
    check(
      'expense_lines_split_whole',
      sql`(${t.categoryId} IS NULL AND ${t.typeId} IS NULL) OR (${t.categoryId} IS NOT NULL AND ${t.typeId} IS NOT NULL)`,
    ),
  ],
);

/**
 * The parts of a split expense (FR-EXP-15, Q37): one expense with one receipt, each part with
 * its own category and type and an amount, in the expense's currency, adding up to its claim.
 * Split by line, the parts are worked out from its lines' categories and types whenever they or
 * its exclusions change, and a part with no category and type is the lines left with the
 * expense's own; split by amount, a person typed each one. It goes with its expense.
 */
export const expenseParts = pgTable(
  'expense_parts',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    position: integer('position').notNull(),
    basis: splitBasis('basis').notNull(),
    categoryId: uuid('category_id'),
    typeId: uuid('type_id'),
    amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('expense_parts_org_id_id_key').on(t.orgId, t.id),
    unique('expense_parts_position_key').on(t.orgId, t.expenseId, t.position),
    foreignKey({
      name: 'expense_parts_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }).onDelete('cascade'),
    foreignKey({
      name: 'expense_parts_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'expense_parts_type_fk',
      columns: [t.orgId, t.typeId],
      foreignColumns: [expenseTypes.orgId, expenseTypes.id],
    }),
    check('expense_parts_position_positive', sql`${t.position} > 0`),
    check('expense_parts_currency_iso', isoCurrency(t.currency)),
    check('expense_parts_amount_positive', sql`${t.amountMinor} > 0`),
    check(
      'expense_parts_classified_whole',
      sql`(${t.categoryId} IS NULL AND ${t.typeId} IS NULL) OR (${t.categoryId} IS NOT NULL AND ${t.typeId} IS NOT NULL)`,
    ),
    // A part typed by amount has its own category and type; only lines stay with the expense's.
    check(
      'expense_parts_amounts_classified',
      sql`${t.basis} = 'lines' OR ${t.categoryId} IS NOT NULL`,
    ),
  ],
);

export const receipts = pgTable(
  'receipts',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    expenseId: uuid('expense_id'),
    source: expenseSource('source').notNull(),
    storageKey: text('storage_key').notNull(),
    contentType: text('content_type').notNull(),
    byteSize: integer('byte_size').notNull(),
    sha256: char('sha256', { length: 64 }).notNull(),
    perceptualHash: text('perceptual_hash'),
    status: receiptStatus('status').notNull().default('processing'),
    /**
     * When it was last compared with its member's other receipts for possible duplicates
     * (FR-INT-18). Null for a receipt read before that check existed, which the release
     * checks once.
     */
    duplicatesCheckedAt: timestamp('duplicates_checked_at', { withTimezone: true }),
    /**
     * When its first reading settled, Ready, needing a look or not read: with `created_at`,
     * the time from capture to read (NFR-PERF-01). Reading it again leaves it. Null while it is
     * first read.
     */
    settledAt: timestamp('settled_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('receipts_org_id_id_key').on(t.orgId, t.id),
    check(
      'receipts_settled_after_capture',
      sql`${t.settledAt} IS NULL OR ${t.settledAt} >= ${t.createdAt}`,
    ),
    // Exact-duplicate detection: the same file can't be filed twice in one organization.
    unique('receipts_org_sha256_key').on(t.orgId, t.sha256),
    foreignKey({
      name: 'receipts_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'receipts_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }),
    check('receipts_sha256_hex', sql`${t.sha256} ~ '^[0-9a-f]{64}$'`),
    check('receipts_byte_size_positive', sql`${t.byteSize} > 0`),
  ],
);

export const extractionRuns = pgTable(
  'extraction_runs',
  {
    id: id(),
    orgId: orgId(),
    receiptId: uuid('receipt_id').notNull(),
    /** Which implementation read the receipt, e.g. "claude" or a benchmark vendor. */
    extractor: text('extractor').notNull(),
    model: text('model').notNull(),
    promptVersion: text('prompt_version').notNull(),
    schemaVersion: text('schema_version').notNull(),
    outcome: extractionOutcome('outcome').notNull(),
    output: jsonb('output'),
    fieldConfidence: jsonb('field_confidence'),
    error: text('error'),
    latencyMs: integer('latency_ms'),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    costMicroUsd: bigint('cost_micro_usd', { mode: 'number' }),
    /**
     * The outbox event that asked for this reading. With the model it makes a workflow retry
     * a no-op instead of a second row; a new request (read again) gets a new id.
     */
    requestId: uuid('request_id'),
    /**
     * Why this model read, under the organization's AI model settings (FR-INT-16): primary,
     * or backup when the models before it produced no reading. Null for readings made side
     * by side (ADR-0017), where the model itself says whether it was compared or the fallback.
     */
    role: text('role'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('extraction_runs_request_key').on(t.orgId, t.receiptId, t.model, t.requestId),
    check('extraction_runs_role_known', sql`${t.role} IN ('primary', 'backup')`),
    foreignKey({
      name: 'extraction_runs_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    index('extraction_runs_receipt_idx').on(t.orgId, t.receiptId),
  ],
);

/**
 * A member confirming a reading that needed a look, as it was or with fields corrected
 * (FR-INT-15, ADR-0021). The values are what the receipt is filed with; each correction keeps
 * what the model read, so it can join the eval set. Append-only: reading the receipt again
 * and confirming again adds a row.
 */
export const receiptReviews = pgTable(
  'receipt_reviews',
  {
    id: id(),
    orgId: orgId(),
    receiptId: uuid('receipt_id').notNull(),
    memberId: uuid('member_id').notNull(),
    /** The reading request confirmed; the review applies while it is the latest. */
    requestId: uuid('request_id'),
    /** The model whose reading was confirmed or corrected. */
    model: text('model').notNull(),
    merchant: text('merchant').notNull(),
    transactionDate: date('transaction_date', { mode: 'string' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    totalMinor: bigint('total_minor', { mode: 'number' }).notNull(),
    taxMinor: bigint('tax_minor', { mode: 'number' }),
    tipMinor: bigint('tip_minor', { mode: 'number' }),
    /** [{ field, read, corrected }]: empty when the reading was confirmed as it was. */
    corrections: jsonb('corrections')
      .notNull()
      .default(sql`'[]'::jsonb`),
    createdAt: createdAt(),
  },
  (t) => [
    unique('receipt_reviews_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'receipt_reviews_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    foreignKey({
      name: 'receipt_reviews_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('receipt_reviews_currency_code', sql`${t.currency} ~ '^[A-Z]{3}$'`),
    check(
      'receipt_reviews_amounts_not_negative',
      sql`${t.totalMinor} >= 0 AND coalesce(${t.taxMinor}, 0) >= 0 AND coalesce(${t.tipMinor}, 0) >= 0`,
    ),
    index('receipt_reviews_receipt_idx').on(t.orgId, t.receiptId),
  ],
);

export const duplicateState = pgEnum('duplicate_state', ['open', 'dismissed']);

/**
 * A receipt held as a possible duplicate of an earlier one of its member's (FR-INT-18,
 * ADR-0028): the same currency and total, a day apart at most, a similar merchant. While open,
 * the receipt needs a look and its expense counts in no total. Dismissed means the person said
 * the two are different purchases, so the pair is never flagged again. A merge or a deletion
 * removes the pair with the receipt it deletes.
 */
export const receiptDuplicates = pgTable(
  'receipt_duplicates',
  {
    id: id(),
    orgId: orgId(),
    /** The receipt held: the later of the two. */
    receiptId: uuid('receipt_id').notNull(),
    /** The earlier receipt it looks like. */
    otherReceiptId: uuid('other_receipt_id').notNull(),
    state: duplicateState('state').notNull().default('open'),
    /** What the held receipt's reading settled to, which it returns to once resolved. */
    settledStatus: receiptStatus('settled_status').notNull(),
    createdAt: createdAt(),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  },
  (t) => [
    unique('receipt_duplicates_org_id_id_key').on(t.orgId, t.id),
    unique('receipt_duplicates_pair_key').on(t.orgId, t.receiptId, t.otherReceiptId),
    foreignKey({
      name: 'receipt_duplicates_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    foreignKey({
      name: 'receipt_duplicates_other_fk',
      columns: [t.orgId, t.otherReceiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    check('receipt_duplicates_two_receipts', sql`${t.receiptId} <> ${t.otherReceiptId}`),
    index('receipt_duplicates_other_idx').on(t.orgId, t.otherReceiptId),
  ],
);

export const inboundEmailStatus = pgEnum('inbound_email_status', [
  'filed',
  'no_attachments',
  'unverified',
]);

/**
 * An email a member sent to the receipts address (FR-CAP-02, ADR-0026): who sent it, what it
 * was about, and what came of it. Kept once per provider message, so a retried delivery adds
 * nothing. Mail from anyone who doesn't sign in here is never kept.
 */
export const inboundEmails = pgTable(
  'inbound_emails',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    /** Who delivered it, and their id for the message: bird, rem_… */
    provider: text('provider').notNull(),
    providerMessageId: text('provider_message_id').notNull(),
    fromAddress: text('from_address').notNull(),
    subject: text('subject'),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    /**
     * filed: its attachments, or with none its own text as a PDF, became receipts (ADR-0027).
     * no_attachments: nothing attached and no text, so nothing to file. unverified: no DKIM
     * signature proved the sender, so nothing was filed and no body kept.
     */
    status: inboundEmailStatus('status').notNull(),
    /** The email's own text as read, at most 64 KiB, kept only for a proved sender. */
    bodyText: text('body_text'),
    /** How many receipts it filed; a file already filed before is not counted again. */
    receiptCount: integer('receipt_count').notNull().default(0),
    createdAt: createdAt(),
  },
  (t) => [
    unique('inbound_emails_org_id_id_key').on(t.orgId, t.id),
    unique('inbound_emails_message_key').on(t.orgId, t.provider, t.providerMessageId),
    foreignKey({
      name: 'inbound_emails_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('inbound_emails_receipt_count', sql`${t.receiptCount} >= 0`),
    index('inbound_emails_member_idx').on(t.orgId, t.memberId, t.createdAt),
  ],
);

export const mileageLogs = pgTable(
  'mileage_logs',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    method: mileageMethod('method').notNull(),
    travelDate: date('travel_date', { mode: 'string' }).notNull(),
    purpose: text('purpose').notNull(),
    origin: text('origin'),
    destination: text('destination'),
    waypoints: jsonb('waypoints').notNull().default([]),
    distance: numeric('distance', { precision: 10, scale: 2 }).notNull(),
    unit: distanceUnit('unit').notNull(),
    // Rate snapshot: a later rate change never alters this claim.
    rateCurrency: char('rate_currency', { length: 3 }).notNull(),
    ratePerUnit: numeric('rate_per_unit', { precision: 12, scale: 4 }).notNull(),
    rateEffectiveFrom: date('rate_effective_from', { mode: 'string' }).notNull(),
    rateSource: text('rate_source').notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('mileage_logs_expense_key').on(t.orgId, t.expenseId),
    foreignKey({
      name: 'mileage_logs_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }),
    check('mileage_logs_distance_nonnegative', sql`${t.distance} >= 0`),
    check('mileage_logs_rate_currency_iso', isoCurrency(t.rateCurrency)),
  ],
);

export const approvalSteps = pgTable(
  'approval_steps',
  {
    id: id(),
    orgId: orgId(),
    reportId: uuid('report_id').notNull(),
    sequence: integer('sequence').notNull(),
    approverMemberId: uuid('approver_member_id').notNull(),
    decision: approvalDecision('decision').notNull().default('pending'),
    comment: text('comment'),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('approval_steps_report_sequence_key').on(t.orgId, t.reportId, t.sequence),
    foreignKey({
      name: 'approval_steps_report_fk',
      columns: [t.orgId, t.reportId],
      foreignColumns: [reports.orgId, reports.id],
    }),
    foreignKey({
      name: 'approval_steps_approver_fk',
      columns: [t.orgId, t.approverMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check(
      'approval_steps_return_needs_comment',
      sql`${t.decision} <> 'returned' OR length(trim(coalesce(${t.comment}, ''))) > 0`,
    ),
  ],
);

/** Append-only and hash-chained per organization. Migration 0001 blocks UPDATE, DELETE and TRUNCATE. */
export const auditEvents = pgTable(
  'audit_events',
  {
    id: id(),
    orgId: orgId(),
    sequence: bigint('sequence', { mode: 'number' }).notNull(),
    actorType: actorType('actor_type').notNull(),
    actorId: text('actor_id'),
    entityType: text('entity_type').notNull(),
    entityId: text('entity_id').notNull(),
    action: text('action').notNull(),
    payload: jsonb('payload').notNull().default({}),
    occurredAt: timestamp('occurred_at', { withTimezone: true, mode: 'date' }).notNull(),
    prevHash: char('prev_hash', { length: 64 }).notNull(),
    hash: char('hash', { length: 64 }).notNull(),
  },
  (t) => [
    unique('audit_events_org_sequence_key').on(t.orgId, t.sequence),
    unique('audit_events_hash_key').on(t.hash),
    index('audit_events_entity_idx').on(t.orgId, t.entityType, t.entityId),
  ],
);

/** Transactional outbox: written in the same transaction as the change it announces. */
export const outboxEvents = pgTable(
  'outbox_events',
  {
    id: id(),
    orgId: orgId(),
    topic: text('topic').notNull(),
    payload: jsonb('payload').notNull(),
    createdAt: createdAt(),
    claimedAt: timestamp('claimed_at', { withTimezone: true }),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    attempts: integer('attempts').notNull().default(0),
  },
  (t) => [
    index('outbox_events_unpublished_idx')
      .on(t.createdAt)
      .where(sql`published_at IS NULL`),
  ],
);

/**
 * Each organization's own API keys for AI providers (ADR-0015). The key is stored only as
 * AES-256-GCM ciphertext bound to (org_id, provider); the plaintext never leaves the server
 * and is never returned by the API. key_hint is the last four characters, for display.
 */
export const aiProviderKeys = pgTable(
  'ai_provider_keys',
  {
    id: id(),
    orgId: orgId(),
    provider: aiProvider('provider').notNull(),
    ciphertext: text('ciphertext').notNull(),
    keyHint: text('key_hint').notNull(),
    /** How the provider accepted the key: as an API key header or as a bearer token. */
    authScheme: aiAuthScheme('auth_scheme').notNull(),
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    updatedByMemberId: uuid('updated_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('ai_provider_keys_org_id_id_key').on(t.orgId, t.id),
    unique('ai_provider_keys_org_provider_key').on(t.orgId, t.provider),
    foreignKey({
      name: 'ai_provider_keys_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('ai_provider_keys_hint_short', sql`length(${t.keyHint}) <= 4`),
  ],
);

/**
 * A feature switched on or off for one organization by its owner (Q5, NFR-DEL-05). A feature
 * with no row is off. FLAG_OVERRIDES in the environment still wins, as a kill switch.
 */
export const orgFeatures = pgTable(
  'org_features',
  {
    id: id(),
    orgId: orgId(),
    /** A key from the flag registry in @expensewise/flags, such as `expenses.mileage`. */
    flag: text('flag').notNull(),
    enabled: boolean('enabled').notNull(),
    updatedByMemberId: uuid('updated_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('org_features_org_id_id_key').on(t.orgId, t.id),
    unique('org_features_org_flag_key').on(t.orgId, t.flag),
    foreignKey({
      name: 'org_features_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('org_features_flag_format', sql`${t.flag} ~ '^[a-z]+\\.[a-z-]+$'`),
  ],
);

/**
 * Which AI models read one organization's receipts, once its owner has switched on AI model
 * settings (FR-INT-16, ADR-0033): one row per model, on or off, in the order back-ups are
 * tried. Exactly one model that is on is the primary, or none when every model is off. An
 * organization with no rows reads with the defaults in @expensewise/extraction.
 */
export const orgAiModels = pgTable(
  'org_ai_models',
  {
    id: id(),
    orgId: orgId(),
    /** A model id from @expensewise/extraction, such as `claude-sonnet-5-5`. */
    model: text('model').notNull(),
    enabled: boolean('enabled').notNull(),
    isPrimary: boolean('is_primary').notNull().default(false),
    /** Its place in the order back-ups are tried, from 0. */
    position: integer('position').notNull(),
    updatedByMemberId: uuid('updated_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('org_ai_models_org_id_id_key').on(t.orgId, t.id),
    unique('org_ai_models_org_model_key').on(t.orgId, t.model),
    uniqueIndex('org_ai_models_one_primary')
      .on(t.orgId)
      .where(sql`is_primary`),
    foreignKey({
      name: 'org_ai_models_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('org_ai_models_model_format', sql`${t.model} ~ '^[a-z0-9][a-z0-9.-]*$'`),
    check('org_ai_models_primary_is_on', sql`${t.enabled} OR NOT ${t.isPrimary}`),
    check('org_ai_models_position_not_negative', sql`${t.position} >= 0`),
  ],
);
