import {
  DISTANCE_UNITS,
  EXPENSE_SOURCES,
  EXPENSE_STATUSES,
  MEMBER_ROLES,
  REPORT_STATUSES,
  newId,
} from '@expensewise/domain';
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  char,
  check,
  date,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from 'drizzle-orm/pg-core';

/*
 * Schema v1. Conventions (docs/05-architecture.md, ADR-0008):
 * - Every tenant table carries org_id. Row-level security in migration 0001 enforces it.
 * - References between tenant tables are composite (org_id, id) foreign keys, so a row
 *   can never point at another organization's row, even though FK checks bypass RLS.
 * - Money is bigint minor units plus a char(3) ISO 4217 code. Never numeric, never float.
 * - Transaction and travel dates are local calendar dates; instants are timestamptz.
 * - IDs are UUIDv7, generated by the application.
 */

export const memberRole = pgEnum('member_role', MEMBER_ROLES);
export const expenseStatus = pgEnum('expense_status', EXPENSE_STATUSES);
export const expenseSource = pgEnum('expense_source', EXPENSE_SOURCES);
export const reportStatus = pgEnum('report_status', REPORT_STATUSES);
export const distanceUnit = pgEnum('distance_unit', DISTANCE_UNITS);
export const tripStatus = pgEnum('trip_status', ['planned', 'active', 'closed']);
export const receiptStatus = pgEnum('receipt_status', [
  'processing',
  'extracted',
  'needs_review',
  'failed',
]);
export const extractionOutcome = pgEnum('extraction_outcome', ['confident', 'unsure', 'failed']);
export const approvalDecision = pgEnum('approval_decision', ['pending', 'approved', 'returned']);
export const mileageMethod = pgEnum('mileage_method', ['manual', 'route', 'gps']);
export const actorType = pgEnum('actor_type', ['user', 'system']);
export const aiProvider = pgEnum('ai_provider', ['anthropic', 'openai']);
export const aiAuthScheme = pgEnum('ai_auth_scheme', ['api_key', 'bearer']);

const id = () => uuid('id').primaryKey().$defaultFn(newId);
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
const isoCurrency = (column: unknown) => sql`${column} ~ '^[A-Z]{3}$'`;

export const organizations = pgTable(
  'organizations',
  {
    id: id(),
    name: text('name').notNull(),
    homeCurrency: char('home_currency', { length: 3 }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [check('organizations_home_currency_iso', isoCurrency(t.homeCurrency))],
);

const orgId = () =>
  uuid('org_id')
    .notNull()
    .references(() => organizations.id);

export const members = pgTable(
  'members',
  {
    id: id(),
    orgId: orgId(),
    /** The member's first sign-in (identity provider subject). Access uses member_sign_ins. */
    userId: text('user_id').notNull(),
    email: text('email').notNull(),
    displayName: text('display_name').notNull(),
    role: memberRole('role').notNull().default('member'),
    managerMemberId: uuid('manager_member_id'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('members_org_id_id_key').on(t.orgId, t.id),
    unique('members_org_user_key').on(t.orgId, t.userId),
    foreignKey({
      name: 'members_manager_fk',
      columns: [t.orgId, t.managerMemberId],
      foreignColumns: [t.orgId, t.id],
    }),
  ],
);

/**
 * How a member signs in. A person can have several sign-ins, such as a personal and a work
 * email; each one reaches the same member, so approvals and separation of duties still see
 * one person. A sign-in belongs to exactly one member (Phase 1). Access goes through this
 * table; members.user_id records only the member's first sign-in.
 */
export const memberSignIns = pgTable(
  'member_sign_ins',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    /** Subject from the identity provider (Supabase Auth `sub`). */
    userId: text('user_id').notNull(),
    email: text('email').notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('member_sign_ins_org_id_id_key').on(t.orgId, t.id),
    unique('member_sign_ins_user_key').on(t.userId),
    foreignKey({
      name: 'member_sign_ins_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    index('member_sign_ins_member_idx').on(t.orgId, t.memberId),
  ],
);

export const trips = pgTable(
  'trips',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    name: text('name').notNull(),
    purpose: text('purpose'),
    startDate: date('start_date', { mode: 'string' }).notNull(),
    endDate: date('end_date', { mode: 'string' }).notNull(),
    primaryCity: text('primary_city'),
    status: tripStatus('status').notNull().default('planned'),
    /**
     * The report it is on: it joins 24 hours after its return date, or a person moves it
     * (FR-EXP-05). Its expenses go with it.
     */
    reportId: uuid('report_id'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('trips_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'trips_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'trips_report_fk',
      columns: [t.orgId, t.memberId, t.reportId],
      foreignColumns: [reports.orgId, reports.memberId, reports.id],
    }),
    index('trips_report_idx').on(t.orgId, t.reportId),
    check('trips_dates_ordered', sql`${t.endDate} >= ${t.startDate}`),
    index('trips_member_dates_idx').on(t.orgId, t.memberId, t.startDate),
  ],
);

export const categories = pgTable(
  'categories',
  {
    id: id(),
    orgId: orgId(),
    name: text('name').notNull(),
    glCode: text('gl_code'),
    taxCode: text('tax_code'),
    active: boolean('active').notNull().default(true),
    createdAt: createdAt(),
  },
  (t) => [
    unique('categories_org_id_id_key').on(t.orgId, t.id),
    unique('categories_org_name_key').on(t.orgId, t.name),
  ],
);

/**
 * A member's expense report: trips, which join 24 hours after their return date, and local
 * expenses (FR-EXP-05, FR-EXP-14, ADR-0029). A trip points at its report, and a local
 * expense too; an expense on a trip goes with its trip.
 */
export const reports = pgTable(
  'reports',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    title: text('title').notNull(),
    status: reportStatus('status').notNull().default('open'),
    currency: char('currency', { length: 3 }).notNull(),
    /** When an open report closes itself: 28 days after opening, later if reopened. */
    closesAt: timestamp('closes_at', { withTimezone: true }).notNull(),
    /** When it last closed, by the person or on day 28; null while open. */
    closedAt: timestamp('closed_at', { withTimezone: true }),
    submittedAt: timestamp('submitted_at', { withTimezone: true }),
    approvedAt: timestamp('approved_at', { withTimezone: true }),
    settledAt: timestamp('settled_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('reports_org_id_id_key').on(t.orgId, t.id),
    // What points at a report names its member too, so a report holds only its member's.
    unique('reports_org_member_id_key').on(t.orgId, t.memberId, t.id),
    foreignKey({
      name: 'reports_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('reports_currency_iso', isoCurrency(t.currency)),
    check('reports_closed_when_closed', sql`(${t.status} = 'open') = (${t.closedAt} IS NULL)`),
    index('reports_member_status_idx').on(t.orgId, t.memberId, t.status),
  ],
);

export const expenses = pgTable(
  'expenses',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    tripId: uuid('trip_id'),
    /** The report a local expense is on (FR-EXP-14); null for one on a trip. */
    reportId: uuid('report_id'),
    categoryId: uuid('category_id'),
    status: expenseStatus('status').notNull(),
    source: expenseSource('source').notNull(),
    merchant: text('merchant'),
    transactionDate: date('transaction_date', { mode: 'string' }),
    amountMinor: bigint('amount_minor', { mode: 'number' }),
    currency: char('currency', { length: 3 }),
    homeAmountMinor: bigint('home_amount_minor', { mode: 'number' }),
    fxRate: numeric('fx_rate', { precision: 20, scale: 10 }),
    fxRateDate: date('fx_rate_date', { mode: 'string' }),
    fxSource: text('fx_source'),
    /**
     * When it was bought, as local time HH:MM, and the IANA time zone that time is in: read
     * from its receipt (FR-INT-17), the zone worked out from the place, or set by a person.
     */
    transactionTime: text('transaction_time'),
    timeZone: text('time_zone'),
    /** Where it was bought: the merchant's address as printed, and what was picked out of it. */
    merchantAddress: text('merchant_address'),
    merchantCity: text('merchant_city'),
    merchantRegion: text('merchant_region'),
    /** ISO 3166-1 alpha-2. */
    merchantCountry: char('merchant_country', { length: 2 }),
    notes: text('notes'),
    /**
     * Why a local expense, one on no trip, was for business. Its report can't close without
     * it (FR-EXP-14).
     */
    justification: text('justification'),
    /**
     * When a person last edited the values. From then on a reading of the receipt never
     * overwrites them (ADR-0022); a difference from the receipt shows instead.
     */
    editedAt: timestamp('edited_at', { withTimezone: true }),
    /**
     * A person chose its trip, or chose no trip. From then on filing by date never moves it
     * (ADR-0023).
     */
    tripPinned: boolean('trip_pinned').notNull().default(false),
    /** Corrections to approved expenses are a reversal plus a new version. */
    version: integer('version').notNull().default(1),
    reversalOfId: uuid('reversal_of_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expenses_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'expenses_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'expenses_trip_fk',
      columns: [t.orgId, t.tripId],
      foreignColumns: [trips.orgId, trips.id],
    }),
    // Only a local expense points at a report itself; one on a trip goes with its trip.
    foreignKey({
      name: 'expenses_report_fk',
      columns: [t.orgId, t.memberId, t.reportId],
      foreignColumns: [reports.orgId, reports.memberId, reports.id],
    }),
    check('expenses_report_only_when_local', sql`${t.reportId} IS NULL OR ${t.tripId} IS NULL`),
    check(
      'expenses_time_of_day',
      sql`${t.transactionTime} IS NULL OR ${t.transactionTime} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'`,
    ),
    check(
      'expenses_country_code',
      sql`${t.merchantCountry} IS NULL OR ${t.merchantCountry} ~ '^[A-Z]{2}$'`,
    ),
    foreignKey({
      name: 'expenses_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'expenses_reversal_fk',
      columns: [t.orgId, t.reversalOfId],
      foreignColumns: [t.orgId, t.id],
    }),
    check('expenses_currency_iso', sql`${t.currency} IS NULL OR ${isoCurrency(t.currency)}`),
    // From Ready onward an expense is complete: amount, currency and date are known.
    check(
      'expenses_complete_when_ready',
      sql`${t.status} IN ('processing', 'needs_review') OR (${t.amountMinor} IS NOT NULL AND ${t.currency} IS NOT NULL AND ${t.transactionDate} IS NOT NULL)`,
    ),
    // A converted amount is only auditable with its rate, date and source.
    check(
      'expenses_fx_complete',
      sql`(${t.fxRate} IS NULL AND ${t.fxRateDate} IS NULL AND ${t.fxSource} IS NULL) OR (${t.fxRate} IS NOT NULL AND ${t.fxRateDate} IS NOT NULL AND ${t.fxSource} IS NOT NULL AND ${t.homeAmountMinor} IS NOT NULL)`,
    ),
    index('expenses_member_date_idx').on(t.orgId, t.memberId, t.transactionDate),
    index('expenses_trip_idx').on(t.orgId, t.tripId),
    index('expenses_report_idx').on(t.orgId, t.reportId),
    index('expenses_status_idx').on(t.orgId, t.status),
  ],
);

export const receipts = pgTable(
  'receipts',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    expenseId: uuid('expense_id'),
    source: expenseSource('source').notNull(),
    storageKey: text('storage_key').notNull(),
    contentType: text('content_type').notNull(),
    byteSize: integer('byte_size').notNull(),
    sha256: char('sha256', { length: 64 }).notNull(),
    perceptualHash: text('perceptual_hash'),
    status: receiptStatus('status').notNull().default('processing'),
    /**
     * When it was last compared with its member's other receipts for possible duplicates
     * (FR-INT-18). Null for a receipt read before that check existed, which the release
     * checks once.
     */
    duplicatesCheckedAt: timestamp('duplicates_checked_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('receipts_org_id_id_key').on(t.orgId, t.id),
    // Exact-duplicate detection: the same file can't be filed twice in one organization.
    unique('receipts_org_sha256_key').on(t.orgId, t.sha256),
    foreignKey({
      name: 'receipts_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'receipts_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }),
    check('receipts_sha256_hex', sql`${t.sha256} ~ '^[0-9a-f]{64}$'`),
    check('receipts_byte_size_positive', sql`${t.byteSize} > 0`),
  ],
);

export const extractionRuns = pgTable(
  'extraction_runs',
  {
    id: id(),
    orgId: orgId(),
    receiptId: uuid('receipt_id').notNull(),
    /** Which implementation read the receipt, e.g. "claude" or a benchmark vendor. */
    extractor: text('extractor').notNull(),
    model: text('model').notNull(),
    promptVersion: text('prompt_version').notNull(),
    schemaVersion: text('schema_version').notNull(),
    outcome: extractionOutcome('outcome').notNull(),
    output: jsonb('output'),
    fieldConfidence: jsonb('field_confidence'),
    error: text('error'),
    latencyMs: integer('latency_ms'),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    costMicroUsd: bigint('cost_micro_usd', { mode: 'number' }),
    /**
     * The outbox event that asked for this reading. With the model it makes a workflow retry
     * a no-op instead of a second row; a new request (read again) gets a new id.
     */
    requestId: uuid('request_id'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('extraction_runs_request_key').on(t.orgId, t.receiptId, t.model, t.requestId),
    foreignKey({
      name: 'extraction_runs_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    index('extraction_runs_receipt_idx').on(t.orgId, t.receiptId),
  ],
);

/**
 * A member confirming a reading that needed a look, as it was or with fields corrected
 * (FR-INT-15, ADR-0021). The values are what the receipt is filed with; each correction keeps
 * what the model read, so it can join the eval set. Append-only: reading the receipt again
 * and confirming again adds a row.
 */
export const receiptReviews = pgTable(
  'receipt_reviews',
  {
    id: id(),
    orgId: orgId(),
    receiptId: uuid('receipt_id').notNull(),
    memberId: uuid('member_id').notNull(),
    /** The reading request confirmed; the review applies while it is the latest. */
    requestId: uuid('request_id'),
    /** The model whose reading was confirmed or corrected. */
    model: text('model').notNull(),
    merchant: text('merchant').notNull(),
    transactionDate: date('transaction_date', { mode: 'string' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    totalMinor: bigint('total_minor', { mode: 'number' }).notNull(),
    taxMinor: bigint('tax_minor', { mode: 'number' }),
    tipMinor: bigint('tip_minor', { mode: 'number' }),
    /** [{ field, read, corrected }]: empty when the reading was confirmed as it was. */
    corrections: jsonb('corrections')
      .notNull()
      .default(sql`'[]'::jsonb`),
    createdAt: createdAt(),
  },
  (t) => [
    unique('receipt_reviews_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'receipt_reviews_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    foreignKey({
      name: 'receipt_reviews_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('receipt_reviews_currency_code', sql`${t.currency} ~ '^[A-Z]{3}$'`),
    check(
      'receipt_reviews_amounts_not_negative',
      sql`${t.totalMinor} >= 0 AND coalesce(${t.taxMinor}, 0) >= 0 AND coalesce(${t.tipMinor}, 0) >= 0`,
    ),
    index('receipt_reviews_receipt_idx').on(t.orgId, t.receiptId),
  ],
);

export const duplicateState = pgEnum('duplicate_state', ['open', 'dismissed']);

/**
 * A receipt held as a possible duplicate of an earlier one of its member's (FR-INT-18,
 * ADR-0028): the same currency and total, a day apart at most, a similar merchant. While open,
 * the receipt needs a look and its expense counts in no total. Dismissed means the person said
 * the two are different purchases, so the pair is never flagged again. A merge or a deletion
 * removes the pair with the receipt it deletes.
 */
export const receiptDuplicates = pgTable(
  'receipt_duplicates',
  {
    id: id(),
    orgId: orgId(),
    /** The receipt held: the later of the two. */
    receiptId: uuid('receipt_id').notNull(),
    /** The earlier receipt it looks like. */
    otherReceiptId: uuid('other_receipt_id').notNull(),
    state: duplicateState('state').notNull().default('open'),
    /** What the held receipt's reading settled to, which it returns to once resolved. */
    settledStatus: receiptStatus('settled_status').notNull(),
    createdAt: createdAt(),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  },
  (t) => [
    unique('receipt_duplicates_org_id_id_key').on(t.orgId, t.id),
    unique('receipt_duplicates_pair_key').on(t.orgId, t.receiptId, t.otherReceiptId),
    foreignKey({
      name: 'receipt_duplicates_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    foreignKey({
      name: 'receipt_duplicates_other_fk',
      columns: [t.orgId, t.otherReceiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    check('receipt_duplicates_two_receipts', sql`${t.receiptId} <> ${t.otherReceiptId}`),
    index('receipt_duplicates_other_idx').on(t.orgId, t.otherReceiptId),
  ],
);

export const inboundEmailStatus = pgEnum('inbound_email_status', [
  'filed',
  'no_attachments',
  'unverified',
]);

/**
 * An email a member sent to the receipts address (FR-CAP-02, ADR-0026): who sent it, what it
 * was about, and what came of it. Kept once per provider message, so a retried delivery adds
 * nothing. Mail from anyone who doesn't sign in here is never kept.
 */
export const inboundEmails = pgTable(
  'inbound_emails',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    /** Who delivered it, and their id for the message: bird, rem_… */
    provider: text('provider').notNull(),
    providerMessageId: text('provider_message_id').notNull(),
    fromAddress: text('from_address').notNull(),
    subject: text('subject'),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    /**
     * filed: its attachments, or with none its own text as a PDF, became receipts (ADR-0027).
     * no_attachments: nothing attached and no text, so nothing to file. unverified: no DKIM
     * signature proved the sender, so nothing was filed and no body kept.
     */
    status: inboundEmailStatus('status').notNull(),
    /** The email's own text as read, at most 64 KiB, kept only for a proved sender. */
    bodyText: text('body_text'),
    /** How many receipts it filed; a file already filed before is not counted again. */
    receiptCount: integer('receipt_count').notNull().default(0),
    createdAt: createdAt(),
  },
  (t) => [
    unique('inbound_emails_org_id_id_key').on(t.orgId, t.id),
    unique('inbound_emails_message_key').on(t.orgId, t.provider, t.providerMessageId),
    foreignKey({
      name: 'inbound_emails_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('inbound_emails_receipt_count', sql`${t.receiptCount} >= 0`),
    index('inbound_emails_member_idx').on(t.orgId, t.memberId, t.createdAt),
  ],
);

export const mileageLogs = pgTable(
  'mileage_logs',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    method: mileageMethod('method').notNull(),
    travelDate: date('travel_date', { mode: 'string' }).notNull(),
    purpose: text('purpose').notNull(),
    origin: text('origin'),
    destination: text('destination'),
    waypoints: jsonb('waypoints').notNull().default([]),
    distance: numeric('distance', { precision: 10, scale: 2 }).notNull(),
    unit: distanceUnit('unit').notNull(),
    // Rate snapshot: a later rate change never alters this claim.
    rateCurrency: char('rate_currency', { length: 3 }).notNull(),
    ratePerUnit: numeric('rate_per_unit', { precision: 12, scale: 4 }).notNull(),
    rateEffectiveFrom: date('rate_effective_from', { mode: 'string' }).notNull(),
    rateSource: text('rate_source').notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('mileage_logs_expense_key').on(t.orgId, t.expenseId),
    foreignKey({
      name: 'mileage_logs_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }),
    check('mileage_logs_distance_nonnegative', sql`${t.distance} >= 0`),
    check('mileage_logs_rate_currency_iso', isoCurrency(t.rateCurrency)),
  ],
);

export const approvalSteps = pgTable(
  'approval_steps',
  {
    id: id(),
    orgId: orgId(),
    reportId: uuid('report_id').notNull(),
    sequence: integer('sequence').notNull(),
    approverMemberId: uuid('approver_member_id').notNull(),
    decision: approvalDecision('decision').notNull().default('pending'),
    comment: text('comment'),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('approval_steps_report_sequence_key').on(t.orgId, t.reportId, t.sequence),
    foreignKey({
      name: 'approval_steps_report_fk',
      columns: [t.orgId, t.reportId],
      foreignColumns: [reports.orgId, reports.id],
    }),
    foreignKey({
      name: 'approval_steps_approver_fk',
      columns: [t.orgId, t.approverMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check(
      'approval_steps_return_needs_comment',
      sql`${t.decision} <> 'returned' OR length(trim(coalesce(${t.comment}, ''))) > 0`,
    ),
  ],
);

/** Append-only and hash-chained per organization. Migration 0001 blocks UPDATE, DELETE and TRUNCATE. */
export const auditEvents = pgTable(
  'audit_events',
  {
    id: id(),
    orgId: orgId(),
    sequence: bigint('sequence', { mode: 'number' }).notNull(),
    actorType: actorType('actor_type').notNull(),
    actorId: text('actor_id'),
    entityType: text('entity_type').notNull(),
    entityId: text('entity_id').notNull(),
    action: text('action').notNull(),
    payload: jsonb('payload').notNull().default({}),
    occurredAt: timestamp('occurred_at', { withTimezone: true, mode: 'date' }).notNull(),
    prevHash: char('prev_hash', { length: 64 }).notNull(),
    hash: char('hash', { length: 64 }).notNull(),
  },
  (t) => [
    unique('audit_events_org_sequence_key').on(t.orgId, t.sequence),
    unique('audit_events_hash_key').on(t.hash),
    index('audit_events_entity_idx').on(t.orgId, t.entityType, t.entityId),
  ],
);

/** Transactional outbox: written in the same transaction as the change it announces. */
export const outboxEvents = pgTable(
  'outbox_events',
  {
    id: id(),
    orgId: orgId(),
    topic: text('topic').notNull(),
    payload: jsonb('payload').notNull(),
    createdAt: createdAt(),
    claimedAt: timestamp('claimed_at', { withTimezone: true }),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    attempts: integer('attempts').notNull().default(0),
  },
  (t) => [
    index('outbox_events_unpublished_idx')
      .on(t.createdAt)
      .where(sql`published_at IS NULL`),
  ],
);

/**
 * Each organization's own API keys for AI providers (ADR-0015). The key is stored only as
 * AES-256-GCM ciphertext bound to (org_id, provider); the plaintext never leaves the server
 * and is never returned by the API. key_hint is the last four characters, for display.
 */
export const aiProviderKeys = pgTable(
  'ai_provider_keys',
  {
    id: id(),
    orgId: orgId(),
    provider: aiProvider('provider').notNull(),
    ciphertext: text('ciphertext').notNull(),
    keyHint: text('key_hint').notNull(),
    /** How the provider accepted the key: as an API key header or as a bearer token. */
    authScheme: aiAuthScheme('auth_scheme').notNull(),
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    updatedByMemberId: uuid('updated_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('ai_provider_keys_org_id_id_key').on(t.orgId, t.id),
    unique('ai_provider_keys_org_provider_key').on(t.orgId, t.provider),
    foreignKey({
      name: 'ai_provider_keys_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('ai_provider_keys_hint_short', sql`length(${t.keyHint}) <= 4`),
  ],
);
