import {
  APPROVAL_NOTE_MAX,
  DISTANCE_UNITS,
  EXCLUSION_NOTE_MAX,
  EXCLUSION_REASONS,
  SET_ASIDE_NOTE_MAX,
  SET_ASIDE_REASONS,
  EXPENSE_SOURCES,
  EXPENSE_STATUSES,
  LINE_KINDS,
  MEMBER_ROLES,
  ORGANIZATION_SIZES,
  REPORT_STATUSES,
  ROUTE_PROVIDERS,
  ROUTE_STATUSES,
  newId,
} from '@expensewise/domain';
import { sql } from 'drizzle-orm';
import {
  bigint,
  boolean,
  char,
  check,
  date,
  foreignKey,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';

/*
 * Schema v1. Conventions (docs/05-architecture.md, ADR-0008):
 * - Every tenant table carries org_id. Row-level security in migration 0001 enforces it.
 * - References between tenant tables are composite (org_id, id) foreign keys, so a row
 *   can never point at another organization's row, even though FK checks bypass RLS.
 * - Money is bigint minor units plus a char(3) ISO 4217 code. Never numeric, never float.
 * - Transaction and travel dates are local calendar dates; instants are timestamptz.
 * - IDs are UUIDv7, generated by the application.
 */

export const memberRole = pgEnum('member_role', MEMBER_ROLES);
export const expenseStatus = pgEnum('expense_status', EXPENSE_STATUSES);
export const expenseSource = pgEnum('expense_source', EXPENSE_SOURCES);
export const reportStatus = pgEnum('report_status', REPORT_STATUSES);
export const distanceUnit = pgEnum('distance_unit', DISTANCE_UNITS);
export const organizationSize = pgEnum('organization_size', ORGANIZATION_SIZES);
export const tripStatus = pgEnum('trip_status', ['planned', 'active', 'closed']);
export const receiptStatus = pgEnum('receipt_status', [
  'processing',
  'extracted',
  'needs_review',
  'failed',
]);
export const extractionOutcome = pgEnum('extraction_outcome', ['confident', 'unsure', 'failed']);
export const approvalDecision = pgEnum('approval_decision', ['pending', 'approved', 'returned']);
export const mileageMethod = pgEnum('mileage_method', ['manual', 'route', 'gps']);
export const actorType = pgEnum('actor_type', ['user', 'system']);
export const aiProvider = pgEnum('ai_provider', ['anthropic', 'openai']);
export const aiAuthScheme = pgEnum('ai_auth_scheme', ['api_key', 'bearer']);
export const routeProvider = pgEnum('route_provider', ROUTE_PROVIDERS);
export const routeStatus = pgEnum('route_status', ROUTE_STATUSES);

const id = () => uuid('id').primaryKey().$defaultFn(newId);
const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();
const isoCurrency = (column: unknown) => sql`${column} ~ '^[A-Z]{3}$'`;

export const organizations = pgTable(
  'organizations',
  {
    id: id(),
    name: text('name').notNull(),
    /** Reports opened from now on are in it; a change converts nothing already made (FR-PLT-11). */
    homeCurrency: char('home_currency', { length: 3 }).notNull(),
    createdAt: createdAt(),
    /** ISO 3166-1 alpha-2. The details below are the owner's to keep, each optional (FR-PLT-11). */
    country: char('country', { length: 2 }),
    /** A BCP 47 language tag, such as en-US. */
    locale: text('locale'),
    /**
     * An IANA time zone, checked against Postgres's own list when set. With organization
     * settings on, it says when the organization's day ends: when trips and local expenses join
     * a report, and which day is day 28 (ADR-0037).
     */
    timeZone: text('time_zone'),
    /** The postal address, as the owner writes it. */
    address: text('address'),
    industry: text('industry'),
    size: organizationSize('size'),
    /**
     * How many minutes apart two receipts at one place can be and still be one purchase, as
     * the owner set it (FR-INT-19). Empty means the default of 30, which lives in the domain.
     */
    duplicateWindowMinutes: integer('duplicate_window_minutes'),
  },
  (t) => [
    check('organizations_home_currency_iso', isoCurrency(t.homeCurrency)),
    check('organizations_country_code', sql`${t.country} IS NULL OR ${t.country} ~ '^[A-Z]{2}$'`),
    check(
      'organizations_duplicate_window_range',
      sql`${t.duplicateWindowMinutes} IS NULL OR ${t.duplicateWindowMinutes} BETWEEN 0 AND 120`,
    ),
  ],
);

const orgId = () =>
  uuid('org_id')
    .notNull()
    .references(() => organizations.id);

export const members = pgTable(
  'members',
  {
    id: id(),
    orgId: orgId(),
    /**
     * The member's first sign-in (identity provider subject): the one they were made with, on
     * their first sign-in or by accepting their invite. Access uses member_sign_ins. While none of
     * their emails is let in, only this one is let in on its own (#91, Q45); the app never
     * changes it (trigger `keep_first_sign_in`), only the schema owner, by the runbook.
     */
    userId: text('user_id').notNull(),
    email: text('email').notNull(),
    displayName: text('display_name').notNull(),
    role: memberRole('role').notNull().default('member'),
    /**
     * The approver an owner chose for their reports in Settings › People (#86): someone else
     * in the organization. Empty means Automatic. While this person can't approve, routing
     * passes them over and finds one as built (ADR-0043).
     */
    managerMemberId: uuid('manager_member_id'),
    /**
     * The currency the member is reimbursed in, chosen in Settings (FR-EXP-13, Q23). Null until
     * they choose one: then it is the organization's home currency.
     */
    reimbursementCurrency: char('reimbursement_currency', { length: 3 }),
    createdAt: createdAt(),
    /**
     * When an owner removed them (FR-PLT-07): they no longer sign in here, and their records
     * and history stay. Null while they are a member.
     */
    deactivatedAt: timestamp('deactivated_at', { withTimezone: true }),
  },
  (t) => [
    unique('members_org_id_id_key').on(t.orgId, t.id),
    unique('members_org_user_key').on(t.orgId, t.userId),
    foreignKey({
      name: 'members_manager_fk',
      columns: [t.orgId, t.managerMemberId],
      foreignColumns: [t.orgId, t.id],
    }),
    check(
      'members_reimbursement_currency_iso',
      sql`${t.reimbursementCurrency} IS NULL OR ${isoCurrency(t.reimbursementCurrency)}`,
    ),
    check(
      'members_manager_not_self',
      sql`${t.managerMemberId} IS NULL OR ${t.managerMemberId} <> ${t.id}`,
    ),
  ],
);

/**
 * How a member signs in. A person can have several sign-ins, such as a personal and a work
 * email; each one reaches the same member, so approvals and separation of duties still see
 * one person. A sign-in belongs to exactly one member (Phase 1). Access goes through this
 * table; members.user_id records only the member's first sign-in.
 */
export const memberSignIns = pgTable(
  'member_sign_ins',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    /** Subject from the identity provider (Supabase Auth `sub`). */
    userId: text('user_id').notNull(),
    email: text('email').notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('member_sign_ins_org_id_id_key').on(t.orgId, t.id),
    unique('member_sign_ins_user_key').on(t.userId),
    foreignKey({
      name: 'member_sign_ins_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    index('member_sign_ins_member_idx').on(t.orgId, t.memberId),
  ],
);

/**
 * The sign-ins a person has let in (#90, Q44, ADR-0044). While their organization has the
 * second factor on and they have an authenticator, only an email let in opens the app; the
 * others still forward receipts. The email they first signed in with is let in once it passes
 * its code, having passed it (#91); another is let in from an email let in that passed its code,
 * and waits, until it passes its own or the time runs out. Removing the sign-in removes it too.
 * Only the person, from a session that passed the code, changes it (trigger `enforce_let_in`).
 */
export const letInSignIns = pgTable(
  'let_in_sign_ins',
  {
    id: id(),
    orgId: orgId(),
    /** The sign-in let in. */
    signInId: uuid('sign_in_id').notNull(),
    /** When it was let in. */
    letInAt: timestamp('let_in_at', { withTimezone: true }).notNull().defaultNow(),
    /**
     * When it passed its own code while let in: as it was let in for the first, later for one
     * let in from another email. Empty while it waits.
     */
    passedAt: timestamp('passed_at', { withTimezone: true }),
    /**
     * When letting it in lapses unless it passes its own code first, 24 hours on
     * (`LET_IN_HOURS`); empty once it has. A lapsed one counts for nothing.
     */
    lapsesAt: timestamp('lapses_at', { withTimezone: true }),
  },
  (t) => [
    unique('let_in_sign_ins_org_id_id_key').on(t.orgId, t.id),
    unique('let_in_sign_ins_sign_in_key').on(t.orgId, t.signInId),
    foreignKey({
      name: 'let_in_sign_ins_sign_in_fk',
      columns: [t.orgId, t.signInId],
      foreignColumns: [memberSignIns.orgId, memberSignIns.id],
    }).onDelete('cascade'),
    // Passed for good, or waiting until it lapses: one or the other.
    check(
      'let_in_sign_ins_passed_or_waiting',
      sql`(${t.passedAt} IS NULL) <> (${t.lapsesAt} IS NULL)`,
    ),
  ],
);

/**
 * A link that lets one person join the organization with a role (FR-PLT-07, ADR-0035). Only
 * the SHA-256 of its token is kept: the link itself is shown once, to the owner who made it.
 * It works once, until it expires or is revoked; an accepted or revoked invite stays as a
 * record of who let whom in.
 */
export const memberInvites = pgTable(
  'member_invites',
  {
    id: id(),
    orgId: orgId(),
    /** The role the person joins with. */
    role: memberRole('role').notNull(),
    /** The owner's note of who it is for, shown only to the organization's owners. */
    label: text('label'),
    /** SHA-256 of the token in the link, as hex. The token itself is never stored. */
    tokenHash: char('token_hash', { length: 64 }).notNull(),
    createdByMemberId: uuid('created_by_member_id').notNull(),
    createdAt: createdAt(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    acceptedAt: timestamp('accepted_at', { withTimezone: true }),
    acceptedByMemberId: uuid('accepted_by_member_id'),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
  },
  (t) => [
    unique('member_invites_org_id_id_key').on(t.orgId, t.id),
    unique('member_invites_token_hash_key').on(t.tokenHash),
    foreignKey({
      name: 'member_invites_created_by_fk',
      columns: [t.orgId, t.createdByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'member_invites_accepted_by_fk',
      columns: [t.orgId, t.acceptedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('member_invites_token_hash_hex', sql`${t.tokenHash} ~ '^[0-9a-f]{64}$'`),
    check(
      'member_invites_accepted_by_someone',
      sql`(${t.acceptedAt} IS NULL) = (${t.acceptedByMemberId} IS NULL)`,
    ),
    check(
      'member_invites_accepted_or_revoked',
      sql`${t.acceptedAt} IS NULL OR ${t.revokedAt} IS NULL`,
    ),
    check('member_invites_expires_after_made', sql`${t.expiresAt} > ${t.createdAt}`),
    check('member_invites_label_short', sql`${t.label} IS NULL OR length(${t.label}) <= 80`),
    index('member_invites_org_created_idx').on(t.orgId, t.createdAt),
  ],
);

export const trips = pgTable(
  'trips',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    name: text('name').notNull(),
    purpose: text('purpose'),
    startDate: date('start_date', { mode: 'string' }).notNull(),
    endDate: date('end_date', { mode: 'string' }).notNull(),
    primaryCity: text('primary_city'),
    status: tripStatus('status').notNull().default('planned'),
    /**
     * The report it is on: it joins 24 hours after its return date, or a person moves it
     * (FR-EXP-05). Its expenses go with it.
     */
    reportId: uuid('report_id'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('trips_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'trips_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'trips_report_fk',
      columns: [t.orgId, t.memberId, t.reportId],
      foreignColumns: [reports.orgId, reports.memberId, reports.id],
    }),
    index('trips_report_idx').on(t.orgId, t.reportId),
    check('trips_dates_ordered', sql`${t.endDate} >= ${t.startDate}`),
    index('trips_member_dates_idx').on(t.orgId, t.memberId, t.startDate),
  ],
);

/**
 * The categories an organization codes its expenses to, with their general ledger and tax codes
 * (FR-EXP-11, Q7, ADR-0036). They nest, and each allows a set of types (category_types). An
 * organization starts with a ready-made set, seeded by seed_starter_catalog(), that owners and
 * finance admins rename, add to or retire.
 */
export const categories = pgTable(
  'categories',
  {
    id: id(),
    orgId: orgId(),
    /** The category it sits under; null at the top. */
    parentId: uuid('parent_id'),
    name: text('name').notNull(),
    glCode: text('gl_code'),
    taxCode: text('tax_code'),
    /** False once retired: no longer offered, but kept by every expense that has it. */
    active: boolean('active').notNull().default(true),
    /** The ready-made category it started as, such as `travel`; null for one a person added. */
    starterKey: text('starter_key'),
    /**
     * Who last added or changed it; null while it is as the ready-made set left it, so an
     * untouched set is no one's work.
     */
    updatedByMemberId: uuid('updated_by_member_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('categories_org_id_id_key').on(t.orgId, t.id),
    unique('categories_org_name_key').on(t.orgId, t.name),
    unique('categories_org_starter_key').on(t.orgId, t.starterKey),
    foreignKey({
      name: 'categories_parent_fk',
      columns: [t.orgId, t.parentId],
      foreignColumns: [t.orgId, t.id],
    }),
    foreignKey({
      name: 'categories_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('categories_not_own_parent', sql`${t.parentId} IS NULL OR ${t.parentId} <> ${t.id}`),
  ],
);

/**
 * The types an organization's expenses are, such as Airfare or Business meal: what was bought,
 * where rules will attach (FR-EXP-11, Q7, ADR-0036). A list of its own that nests, beside the
 * categories; a category allows some of them.
 */
export const expenseTypes = pgTable(
  'expense_types',
  {
    id: id(),
    orgId: orgId(),
    /** The type it sits under; null at the top. */
    parentId: uuid('parent_id'),
    name: text('name').notNull(),
    /** False once retired: no longer offered, but kept by every expense that has it. */
    active: boolean('active').notNull().default(true),
    /**
     * The ready-made type it started as, such as `airfare`. Keyword suggestions find a type by
     * it, so a renamed one keeps its suggestions.
     */
    starterKey: text('starter_key'),
    /**
     * The organization's policy that the company pays this type directly, such as Airfare
     * booked by an employer (FR-EXP-18, Q46): an expense of it is paid by the company unless a
     * person set it by hand. This type only, not those under it.
     */
    companyPays: boolean('company_pays').notNull().default(false),
    /** Who last added or changed it; null while it is as the ready-made set left it. */
    updatedByMemberId: uuid('updated_by_member_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expense_types_org_id_id_key').on(t.orgId, t.id),
    unique('expense_types_org_name_key').on(t.orgId, t.name),
    unique('expense_types_org_starter_key').on(t.orgId, t.starterKey),
    foreignKey({
      name: 'expense_types_parent_fk',
      columns: [t.orgId, t.parentId],
      foreignColumns: [t.orgId, t.id],
    }),
    foreignKey({
      name: 'expense_types_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('expense_types_not_own_parent', sql`${t.parentId} IS NULL OR ${t.parentId} <> ${t.id}`),
  ],
);

/** Which types each category allows (Q7): choosing a category narrows the types to these. */
export const categoryTypes = pgTable(
  'category_types',
  {
    id: id(),
    orgId: orgId(),
    categoryId: uuid('category_id').notNull(),
    typeId: uuid('type_id').notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('category_types_org_id_id_key').on(t.orgId, t.id),
    unique('category_types_pair_key').on(t.orgId, t.categoryId, t.typeId),
    foreignKey({
      name: 'category_types_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'category_types_type_fk',
      columns: [t.orgId, t.typeId],
      foreignColumns: [expenseTypes.orgId, expenseTypes.id],
    }),
    index('category_types_type_idx').on(t.orgId, t.typeId),
  ],
);

/**
 * A member's expense report: trips, which join 24 hours after their return date, and local
 * expenses (FR-EXP-05, FR-EXP-14, ADR-0029). A trip points at its report, and a local
 * expense too; an expense on a trip goes with its trip.
 */
export const reports = pgTable(
  'reports',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    title: text('title').notNull(),
    status: reportStatus('status').notNull().default('open'),
    /**
     * The currency it is reimbursed in: its member's reimbursement currency, which it follows
     * until it is submitted (FR-EXP-13). Every amount on it is converted to this.
     */
    currency: char('currency', { length: 3 }).notNull(),
    /** When an open report closes itself: 28 days after opening, later if reopened. */
    closesAt: timestamp('closes_at', { withTimezone: true }).notNull(),
    /** When it last closed, by the person or on day 28; null while open. */
    closedAt: timestamp('closed_at', { withTimezone: true }),
    submittedAt: timestamp('submitted_at', { withTimezone: true }),
    approvedAt: timestamp('approved_at', { withTimezone: true }),
    settledAt: timestamp('settled_at', { withTimezone: true }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('reports_org_id_id_key').on(t.orgId, t.id),
    // What points at a report names its member too, so a report holds only its member's.
    unique('reports_org_member_id_key').on(t.orgId, t.memberId, t.id),
    foreignKey({
      name: 'reports_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('reports_currency_iso', isoCurrency(t.currency)),
    check('reports_closed_when_closed', sql`(${t.status} = 'open') = (${t.closedAt} IS NULL)`),
    index('reports_member_status_idx').on(t.orgId, t.memberId, t.status),
  ],
);

export const expenses = pgTable(
  'expenses',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    tripId: uuid('trip_id'),
    /** The report a local expense is on (FR-EXP-14); null for one on a trip. */
    reportId: uuid('report_id'),
    /**
     * The category and type a person chose for it (FR-EXP-11), the type one the category
     * allowed then. A suggestion is never stored here; it is worked out when shown (FR-INT-10).
     */
    categoryId: uuid('category_id'),
    typeId: uuid('type_id'),
    /** When a person last chose its category and type; it orders their history for suggestions. */
    classifiedAt: timestamp('classified_at', { withTimezone: true }),
    status: expenseStatus('status').notNull(),
    source: expenseSource('source').notNull(),
    merchant: text('merchant'),
    transactionDate: date('transaction_date', { mode: 'string' }),
    amountMinor: bigint('amount_minor', { mode: 'number' }),
    currency: char('currency', { length: 3 }),
    homeAmountMinor: bigint('home_amount_minor', { mode: 'number' }),
    fxRate: numeric('fx_rate', { precision: 20, scale: 10 }),
    fxRateDate: date('fx_rate_date', { mode: 'string' }),
    fxSource: text('fx_source'),
    /**
     * When it was bought, as local time HH:MM, and the IANA time zone that time is in: read
     * from its receipt (FR-INT-17), the zone worked out from the place, or set by a person.
     */
    transactionTime: text('transaction_time'),
    timeZone: text('time_zone'),
    /** Where it was bought: the merchant's address as printed, and what was picked out of it. */
    merchantAddress: text('merchant_address'),
    merchantCity: text('merchant_city'),
    merchantRegion: text('merchant_region'),
    /** ISO 3166-1 alpha-2. */
    merchantCountry: char('merchant_country', { length: 2 }),
    /**
     * Where a ride, flight or train went, each end as its receipt prints it (FR-INT-20), and a
     * hotel stay's check-in and check-out days (FR-INT-21). Read only where Journeys and stays
     * is on. The nights are worked out from the two days when shown, never kept.
     */
    journeyFrom: text('journey_from'),
    journeyTo: text('journey_to'),
    /**
     * The day a ticket's first leg departs (FR-EXP-19, #94). The expense files to its trip by
     * this day when it is set, else by its transaction date, which stays the day it was charged.
     */
    departsOn: date('departs_on', { mode: 'string' }),
    checkIn: date('check_in', { mode: 'string' }),
    checkOut: date('check_out', { mode: 'string' }),
    notes: text('notes'),
    /**
     * Why a local expense, one on no trip, was for business. Its report can't close without
     * it (FR-EXP-14).
     */
    justification: text('justification'),
    /**
     * Why it claims less than its receipt, in the person's words (FR-EXP-10, Q6). A report
     * can't be submitted while an expense claims less without a reason, its own or the lines it
     * leaves out (FR-GOV-13).
     */
    claimReason: text('claim_reason'),
    /**
     * Its category's and type's names as they were when its report was last submitted, so
     * renaming either later never changes a submitted claim or its export (NFR-DAT-04, #70).
     */
    categoryName: text('category_name'),
    typeName: text('type_name'),
    /**
     * When a person last edited the values. From then on a reading of the receipt never
     * overwrites them (ADR-0022); a difference from the receipt shows instead.
     */
    editedAt: timestamp('edited_at', { withTimezone: true }),
    /**
     * A person chose its trip, or chose no trip. From then on filing by date never moves it
     * (ADR-0023).
     */
    tripPinned: boolean('trip_pinned').notNull().default(false),
    /**
     * The company paid it directly, such as airfare an employer books (FR-EXP-17): it stays on
     * its trip and in the trip's cost, and is never claimed. Set by the policy for its type,
     * or by a person.
     */
    companyPaid: boolean('company_paid').notNull().default(false),
    /**
     * A person set who paid it. From then on the policy leaves it alone, as `tripPinned` does
     * filing by date (Q46, ADR-0045), until it is handed back to the policy.
     */
    companyPaidPinned: boolean('company_paid_pinned').notNull().default(false),
    /** Corrections to approved expenses are a reversal plus a new version. */
    version: integer('version').notNull().default(1),
    reversalOfId: uuid('reversal_of_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expenses_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'expenses_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'expenses_trip_fk',
      columns: [t.orgId, t.tripId],
      foreignColumns: [trips.orgId, trips.id],
    }),
    // Only a local expense points at a report itself; one on a trip goes with its trip.
    foreignKey({
      name: 'expenses_report_fk',
      columns: [t.orgId, t.memberId, t.reportId],
      foreignColumns: [reports.orgId, reports.memberId, reports.id],
    }),
    check('expenses_report_only_when_local', sql`${t.reportId} IS NULL OR ${t.tripId} IS NULL`),
    check(
      'expenses_time_of_day',
      sql`${t.transactionTime} IS NULL OR ${t.transactionTime} ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'`,
    ),
    check(
      'expenses_country_code',
      sql`${t.merchantCountry} IS NULL OR ${t.merchantCountry} ~ '^[A-Z]{2}$'`,
    ),
    foreignKey({
      name: 'expenses_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'expenses_type_fk',
      columns: [t.orgId, t.typeId],
      foreignColumns: [expenseTypes.orgId, expenseTypes.id],
    }),
    // A category and a type are chosen together, and when.
    check(
      'expenses_classified_whole',
      sql`(${t.categoryId} IS NULL AND ${t.typeId} IS NULL AND ${t.classifiedAt} IS NULL) OR (${t.categoryId} IS NOT NULL AND ${t.typeId} IS NOT NULL AND ${t.classifiedAt} IS NOT NULL)`,
    ),
    foreignKey({
      name: 'expenses_reversal_fk',
      columns: [t.orgId, t.reversalOfId],
      foreignColumns: [t.orgId, t.id],
    }),
    check('expenses_currency_iso', sql`${t.currency} IS NULL OR ${isoCurrency(t.currency)}`),
    // A drive is paid at miles × its rate to the person who drove: never by the company (#95).
    check('expenses_drive_not_company_paid', sql`${t.source} <> 'mileage' OR NOT ${t.companyPaid}`),
    check(
      'expenses_claim_reason_length',
      sql`${t.claimReason} IS NULL OR char_length(${t.claimReason}) BETWEEN 1 AND ${sql.raw(String(APPROVAL_NOTE_MAX))}`,
    ),
    // From Ready onward an expense is complete: amount, currency and date are known.
    check(
      'expenses_complete_when_ready',
      sql`${t.status} IN ('processing', 'needs_review') OR (${t.amountMinor} IS NOT NULL AND ${t.currency} IS NOT NULL AND ${t.transactionDate} IS NOT NULL)`,
    ),
    // A converted amount is only auditable with its rate, date and source.
    check(
      'expenses_fx_complete',
      sql`(${t.fxRate} IS NULL AND ${t.fxRateDate} IS NULL AND ${t.fxSource} IS NULL) OR (${t.fxRate} IS NOT NULL AND ${t.fxRateDate} IS NOT NULL AND ${t.fxSource} IS NOT NULL AND ${t.homeAmountMinor} IS NOT NULL)`,
    ),
    index('expenses_member_date_idx').on(t.orgId, t.memberId, t.transactionDate),
    index('expenses_trip_idx').on(t.orgId, t.tripId),
    index('expenses_report_idx').on(t.orgId, t.reportId),
    index('expenses_status_idx').on(t.orgId, t.status),
    index('expenses_member_classified_idx').on(t.orgId, t.memberId, t.classifiedAt),
  ],
);

export const conversionOutcome = pgEnum('conversion_outcome', ['converted', 'unavailable']);

/**
 * An expense's amount converted to the currency its report is reimbursed in (FR-EXP-13,
 * ADR-0034): what was converted, and the reference rate it was converted at with that rate's
 * date and source, copied on so a later rate never changes it (NFR-DAT-02, NFR-DAT-04); or that
 * the source has no rate for it. One per expense: once its amount, currency, date or
 * reimbursement currency changes, the next conversion replaces it, and each is in the audit
 * trail. It goes with its expense when that is deleted.
 */
export const expenseConversions = pgTable(
  'expense_conversions',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    /** What was converted: the amount as spent, in its currency's minor units. */
    amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    /** The purchase date, whose reference rate applies (Q25). */
    purchaseDate: date('purchase_date', { mode: 'string' }).notNull(),
    /** The currency it was converted to: its report's. */
    reimbursementCurrency: char('reimbursement_currency', { length: 3 }).notNull(),
    /** converted, or unavailable: the source publishes no rate for it. */
    outcome: conversionOutcome('outcome').notNull(),
    /** The amount in the reimbursement currency's minor units: `amount_minor` times `rate`. */
    convertedMinor: bigint('converted_minor', { mode: 'number' }),
    /** What one unit of `currency` is in the reimbursement currency, exactly as applied. */
    rate: numeric('rate'),
    /** The day the rate was published: the purchase date, or the last day before it. */
    rateDate: date('rate_date', { mode: 'string' }),
    /** Who published the rate, or has none: `ECB`. */
    source: text('source').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expense_conversions_org_id_id_key').on(t.orgId, t.id),
    unique('expense_conversions_expense_key').on(t.orgId, t.expenseId),
    foreignKey({
      name: 'expense_conversions_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }).onDelete('cascade'),
    check('expense_conversions_currency_iso', isoCurrency(t.currency)),
    check('expense_conversions_into_iso', isoCurrency(t.reimbursementCurrency)),
    check('expense_conversions_two_currencies', sql`${t.currency} <> ${t.reimbursementCurrency}`),
    // A converted amount is only auditable with its rate, the rate's date and its source.
    check(
      'expense_conversions_rate_complete',
      sql`(${t.outcome} = 'converted' AND ${t.convertedMinor} IS NOT NULL AND ${t.rate} IS NOT NULL AND ${t.rate} > 0 AND ${t.rateDate} IS NOT NULL AND ${t.rateDate} <= ${t.purchaseDate}) OR (${t.outcome} = 'unavailable' AND ${t.convertedMinor} IS NULL AND ${t.rate} IS NULL AND ${t.rateDate} IS NULL)`,
    ),
    check('expense_conversions_source_named', sql`length(trim(${t.source})) > 0`),
  ],
);

export const lineKind = pgEnum('line_kind', LINE_KINDS);
export const exclusionReason = pgEnum('exclusion_reason', EXCLUSION_REASONS);
export const splitBasis = pgEnum('split_basis', ['lines', 'amounts']);

/**
 * A receipt's itemized lines as its expense keeps them (FR-INT-22, ADR-0041): the currency,
 * total and subtotal of the reading they were copied from. Copied when the expense is filed,
 * and again with each new reading, until a person edits the expense, excludes a line or splits
 * it; from then on they stay as they were, as the expense's values do (ADR-0022). One per
 * expense; it goes with its expense when that is deleted.
 */
export const expenseItemizations = pgTable(
  'expense_itemizations',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    /** The receipt's total and subtotal as read, in `currency`'s minor units; null when unread. */
    totalMinor: bigint('total_minor', { mode: 'number' }),
    subtotalMinor: bigint('subtotal_minor', { mode: 'number' }),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expense_itemizations_org_id_id_key').on(t.orgId, t.id),
    unique('expense_itemizations_expense_key').on(t.orgId, t.expenseId),
    // What each line points at, so its currency is the itemization's.
    unique('expense_itemizations_expense_currency_key').on(t.orgId, t.expenseId, t.currency),
    foreignKey({
      name: 'expense_itemizations_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }).onDelete('cascade'),
    check('expense_itemizations_currency_iso', isoCurrency(t.currency)),
  ],
);

/**
 * One of several separate purchases an expense's receipt holds (FR-INT-23, Q49), numbered from
 * 1 as printed, such as an airline ticket and a seat upgrade bought later on another card: its
 * description, the day it was bought, the card and what it charged with its own taxes and fees.
 * A receipt of one purchase has none. It goes with its itemization.
 */
export const expensePurchases = pgTable(
  'expense_purchases',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    position: integer('position').notNull(),
    /** As printed, such as "Seat upgrade". */
    description: text('description').notNull(),
    purchasedOn: date('purchased_on', { mode: 'string' }),
    cardLastFour: text('card_last_four'),
    /** What it charged with its own taxes and fees, in `currency`'s minor units; null unread. */
    totalMinor: bigint('total_minor', { mode: 'number' }),
    currency: char('currency', { length: 3 }).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('expense_purchases_org_id_id_key').on(t.orgId, t.id),
    unique('expense_purchases_position_key').on(t.orgId, t.expenseId, t.position),
    foreignKey({
      name: 'expense_purchases_itemization_fk',
      columns: [t.orgId, t.expenseId, t.currency],
      foreignColumns: [
        expenseItemizations.orgId,
        expenseItemizations.expenseId,
        expenseItemizations.currency,
      ],
    }).onDelete('cascade'),
    check('expense_purchases_position_positive', sql`${t.position} > 0`),
    check('expense_purchases_currency_iso', isoCurrency(t.currency)),
    check(
      'expense_purchases_card_last_four',
      sql`${t.cardLastFour} IS NULL OR ${t.cardLastFour} ~ '^[0-9]{4}$'`,
    ),
  ],
);

/**
 * One line of an expense's receipt, numbered from 1 as printed: each item (a discount or a
 * credit is a negative item, #92), then each tax, each fee and the tip; on a receipt of several
 * purchases, purchase by purchase, each line naming its own (FR-INT-23). An item line can be excluded from the
 * claim with a reason, and a note that other needs (FR-EXP-16, Q38), and given a category and
 * type of its own, which makes it a part of the expense (FR-EXP-15, Q36).
 */
export const expenseLines = pgTable(
  'expense_lines',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    position: integer('position').notNull(),
    kind: lineKind('kind').notNull(),
    /** As printed. */
    description: text('description').notNull(),
    quantity: text('quantity'),
    /** As read, in `currency`'s minor units; negative for a discount or a credit. */
    amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    /** The purchase it belongs to, from 1, on a receipt of several; null on one of one. */
    purchase: integer('purchase'),
    /** Why it is left out of the claim, with a note, and when; null while it is claimed. */
    excludedReason: exclusionReason('excluded_reason'),
    excludedNote: text('excluded_note'),
    excludedAt: timestamp('excluded_at', { withTimezone: true }),
    /** The category and type a person gave it in a split by line; null: the expense's own. */
    categoryId: uuid('category_id'),
    typeId: uuid('type_id'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('expense_lines_org_id_id_key').on(t.orgId, t.id),
    unique('expense_lines_position_key').on(t.orgId, t.expenseId, t.position),
    foreignKey({
      name: 'expense_lines_itemization_fk',
      columns: [t.orgId, t.expenseId, t.currency],
      foreignColumns: [
        expenseItemizations.orgId,
        expenseItemizations.expenseId,
        expenseItemizations.currency,
      ],
    }).onDelete('cascade'),
    foreignKey({
      name: 'expense_lines_purchase_fk',
      columns: [t.orgId, t.expenseId, t.purchase],
      foreignColumns: [
        expensePurchases.orgId,
        expensePurchases.expenseId,
        expensePurchases.position,
      ],
    }).onDelete('cascade'),
    foreignKey({
      name: 'expense_lines_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'expense_lines_type_fk',
      columns: [t.orgId, t.typeId],
      foreignColumns: [expenseTypes.orgId, expenseTypes.id],
    }),
    check('expense_lines_position_positive', sql`${t.position} > 0`),
    check('expense_lines_purchase_positive', sql`${t.purchase} IS NULL OR ${t.purchase} > 0`),
    check('expense_lines_currency_iso', isoCurrency(t.currency)),
    // Only an item is excluded or split off; tax, tip and fees go with the items.
    check(
      'expense_lines_items_only',
      sql`${t.kind} = 'item' OR (${t.excludedReason} IS NULL AND ${t.categoryId} IS NULL)`,
    ),
    check(
      'expense_lines_excluded_whole',
      sql`(${t.excludedReason} IS NULL AND ${t.excludedNote} IS NULL AND ${t.excludedAt} IS NULL) OR (${t.excludedReason} IS NOT NULL AND ${t.excludedAt} IS NOT NULL)`,
    ),
    check(
      'expense_lines_other_needs_note',
      sql`${t.excludedReason} IS DISTINCT FROM 'other' OR coalesce(length(trim(${t.excludedNote})), 0) > 0`,
    ),
    check(
      'expense_lines_note_length',
      sql`${t.excludedNote} IS NULL OR char_length(${t.excludedNote}) <= ${sql.raw(String(EXCLUSION_NOTE_MAX))}`,
    ),
    check(
      'expense_lines_split_whole',
      sql`(${t.categoryId} IS NULL AND ${t.typeId} IS NULL) OR (${t.categoryId} IS NOT NULL AND ${t.typeId} IS NOT NULL)`,
    ),
  ],
);

/**
 * The parts of a split expense (FR-EXP-15, Q35): one expense with one receipt, each part with
 * its own category and type and an amount, in the expense's currency, adding up to its claim.
 * Split by line, the parts are worked out from its lines' categories and types whenever they or
 * its exclusions change, and a part with no category and type is the lines left with the
 * expense's own; split by amount, a person typed each one. It goes with its expense.
 */
export const expenseParts = pgTable(
  'expense_parts',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    position: integer('position').notNull(),
    basis: splitBasis('basis').notNull(),
    categoryId: uuid('category_id'),
    typeId: uuid('type_id'),
    amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    /**
     * Its category's and type's names as they were when its expense's report was last
     * submitted (NFR-DAT-04, #70); null for a part of the lines left with the expense's own.
     */
    categoryName: text('category_name'),
    typeName: text('type_name'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('expense_parts_org_id_id_key').on(t.orgId, t.id),
    unique('expense_parts_position_key').on(t.orgId, t.expenseId, t.position),
    foreignKey({
      name: 'expense_parts_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }).onDelete('cascade'),
    foreignKey({
      name: 'expense_parts_category_fk',
      columns: [t.orgId, t.categoryId],
      foreignColumns: [categories.orgId, categories.id],
    }),
    foreignKey({
      name: 'expense_parts_type_fk',
      columns: [t.orgId, t.typeId],
      foreignColumns: [expenseTypes.orgId, expenseTypes.id],
    }),
    check('expense_parts_position_positive', sql`${t.position} > 0`),
    check('expense_parts_currency_iso', isoCurrency(t.currency)),
    check('expense_parts_amount_positive', sql`${t.amountMinor} > 0`),
    check(
      'expense_parts_classified_whole',
      sql`(${t.categoryId} IS NULL AND ${t.typeId} IS NULL) OR (${t.categoryId} IS NOT NULL AND ${t.typeId} IS NOT NULL)`,
    ),
    // A part typed by amount has its own category and type; only lines stay with the expense's.
    check(
      'expense_parts_amounts_classified',
      sql`${t.basis} = 'lines' OR ${t.categoryId} IS NOT NULL`,
    ),
  ],
);

export const receipts = pgTable(
  'receipts',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    expenseId: uuid('expense_id'),
    source: expenseSource('source').notNull(),
    storageKey: text('storage_key').notNull(),
    contentType: text('content_type').notNull(),
    byteSize: integer('byte_size').notNull(),
    sha256: char('sha256', { length: 64 }).notNull(),
    perceptualHash: text('perceptual_hash'),
    status: receiptStatus('status').notNull().default('processing'),
    /**
     * When it was last compared with its member's other receipts for possible duplicates
     * (FR-INT-18). Null for a receipt read before that check existed, which the release
     * checks once.
     */
    duplicatesCheckedAt: timestamp('duplicates_checked_at', { withTimezone: true }),
    /**
     * When its first reading settled, Ready, needing a look or not read: with `created_at`,
     * the time from capture to read (NFR-PERF-01). Reading it again leaves it. Null while it is
     * first read.
     */
    settledAt: timestamp('settled_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('receipts_org_id_id_key').on(t.orgId, t.id),
    check(
      'receipts_settled_after_capture',
      sql`${t.settledAt} IS NULL OR ${t.settledAt} >= ${t.createdAt}`,
    ),
    // Exact-duplicate detection: the same file can't be filed twice in one organization.
    unique('receipts_org_sha256_key').on(t.orgId, t.sha256),
    foreignKey({
      name: 'receipts_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'receipts_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }),
    check('receipts_sha256_hex', sql`${t.sha256} ~ '^[0-9a-f]{64}$'`),
    check('receipts_byte_size_positive', sql`${t.byteSize} > 0`),
  ],
);

export const extractionRuns = pgTable(
  'extraction_runs',
  {
    id: id(),
    orgId: orgId(),
    receiptId: uuid('receipt_id').notNull(),
    /** Which implementation read the receipt, e.g. "claude" or a benchmark vendor. */
    extractor: text('extractor').notNull(),
    model: text('model').notNull(),
    promptVersion: text('prompt_version').notNull(),
    schemaVersion: text('schema_version').notNull(),
    outcome: extractionOutcome('outcome').notNull(),
    output: jsonb('output'),
    fieldConfidence: jsonb('field_confidence'),
    error: text('error'),
    latencyMs: integer('latency_ms'),
    inputTokens: integer('input_tokens'),
    outputTokens: integer('output_tokens'),
    costMicroUsd: bigint('cost_micro_usd', { mode: 'number' }),
    /**
     * The outbox event that asked for this reading. With the model it makes a workflow retry
     * a no-op instead of a second row; a new request (read again) gets a new id.
     */
    requestId: uuid('request_id'),
    /**
     * Why this model read, under the organization's AI model settings (FR-INT-16): primary,
     * or backup when the models before it produced no reading. Null for readings made side
     * by side (ADR-0017), where the model itself says whether it was compared or the fallback.
     */
    role: text('role'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('extraction_runs_request_key').on(t.orgId, t.receiptId, t.model, t.requestId),
    check('extraction_runs_role_known', sql`${t.role} IN ('primary', 'backup')`),
    foreignKey({
      name: 'extraction_runs_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    index('extraction_runs_receipt_idx').on(t.orgId, t.receiptId),
  ],
);

/**
 * A member confirming a reading that needed a look, as it was or with fields corrected
 * (FR-INT-15, ADR-0021). The values are what the receipt is filed with; each correction keeps
 * what the model read, so it can join the eval set. Append-only: reading the receipt again
 * and confirming again adds a row.
 */
export const receiptReviews = pgTable(
  'receipt_reviews',
  {
    id: id(),
    orgId: orgId(),
    receiptId: uuid('receipt_id').notNull(),
    memberId: uuid('member_id').notNull(),
    /** The reading request confirmed; the review applies while it is the latest. */
    requestId: uuid('request_id'),
    /** The model whose reading was confirmed or corrected. */
    model: text('model').notNull(),
    merchant: text('merchant').notNull(),
    transactionDate: date('transaction_date', { mode: 'string' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    totalMinor: bigint('total_minor', { mode: 'number' }).notNull(),
    taxMinor: bigint('tax_minor', { mode: 'number' }),
    tipMinor: bigint('tip_minor', { mode: 'number' }),
    /** [{ field, read, corrected }]: empty when the reading was confirmed as it was. */
    corrections: jsonb('corrections')
      .notNull()
      .default(sql`'[]'::jsonb`),
    createdAt: createdAt(),
  },
  (t) => [
    unique('receipt_reviews_org_id_id_key').on(t.orgId, t.id),
    foreignKey({
      name: 'receipt_reviews_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    foreignKey({
      name: 'receipt_reviews_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('receipt_reviews_currency_code', sql`${t.currency} ~ '^[A-Z]{3}$'`),
    check(
      'receipt_reviews_amounts_not_negative',
      sql`${t.totalMinor} >= 0 AND coalesce(${t.taxMinor}, 0) >= 0 AND coalesce(${t.tipMinor}, 0) >= 0`,
    ),
    index('receipt_reviews_receipt_idx').on(t.orgId, t.receiptId),
  ],
);

export const duplicateState = pgEnum('duplicate_state', ['open', 'dismissed']);

/**
 * A receipt held as a possible duplicate of an earlier one of its member's (FR-INT-18,
 * ADR-0028): the same currency and total, a day apart at most, a similar merchant. While open,
 * the receipt needs a look and its expense counts in no total. Dismissed means the person said
 * the two are different purchases, so the pair is never flagged again. A merge or a deletion
 * removes the pair with the receipt it deletes.
 */
export const receiptDuplicates = pgTable(
  'receipt_duplicates',
  {
    id: id(),
    orgId: orgId(),
    /** The receipt held: the later of the two. */
    receiptId: uuid('receipt_id').notNull(),
    /** The earlier receipt it looks like. */
    otherReceiptId: uuid('other_receipt_id').notNull(),
    state: duplicateState('state').notNull().default('open'),
    /** What the held receipt's reading settled to, which it returns to once resolved. */
    settledStatus: receiptStatus('settled_status').notNull(),
    createdAt: createdAt(),
    resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  },
  (t) => [
    unique('receipt_duplicates_org_id_id_key').on(t.orgId, t.id),
    unique('receipt_duplicates_pair_key').on(t.orgId, t.receiptId, t.otherReceiptId),
    foreignKey({
      name: 'receipt_duplicates_receipt_fk',
      columns: [t.orgId, t.receiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    foreignKey({
      name: 'receipt_duplicates_other_fk',
      columns: [t.orgId, t.otherReceiptId],
      foreignColumns: [receipts.orgId, receipts.id],
    }),
    check('receipt_duplicates_two_receipts', sql`${t.receiptId} <> ${t.otherReceiptId}`),
    index('receipt_duplicates_other_idx').on(t.orgId, t.otherReceiptId),
  ],
);

export const inboundEmailStatus = pgEnum('inbound_email_status', [
  'filed',
  'no_attachments',
  'unverified',
]);

/**
 * Why an email from a member's address wasn't proved to be theirs (ADR-0026): no DKIM
 * signature; none that checks out, often because a mail system changed it after signing; a
 * good one by a domain other than the From address's; or one that leaves part of it unsigned.
 */
export const inboundEmailProblem = pgEnum('inbound_email_problem', [
  'unsigned',
  'signature_failed',
  'not_aligned',
  'partly_signed',
]);

/**
 * An email a member sent to the receipts address (FR-CAP-02, ADR-0026): who sent it, what it
 * was about, and what came of it. Kept once per provider message, so a retried delivery adds
 * nothing. Mail from anyone who doesn't sign in here is never kept.
 */
export const inboundEmails = pgTable(
  'inbound_emails',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    /** Who delivered it, and their id for the message: bird, rem_… */
    provider: text('provider').notNull(),
    providerMessageId: text('provider_message_id').notNull(),
    fromAddress: text('from_address').notNull(),
    subject: text('subject'),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    /**
     * filed: its attachments, or with none its own text as a PDF, became receipts (ADR-0027).
     * no_attachments: nothing attached and no text, so nothing to file. unverified: no DKIM
     * signature proved the sender, so nothing was filed and no body kept.
     */
    status: inboundEmailStatus('status').notNull(),
    /**
     * unverified: why its sender wasn't proved, shown in Needs you (#59). Null for a proved
     * sender, and for one kept before the reason was.
     */
    senderProblem: inboundEmailProblem('sender_problem'),
    /** The email's own text as read, at most 64 KiB, kept only for a proved sender. */
    bodyText: text('body_text'),
    /** How many receipts it filed; a file already filed before is not counted again. */
    receiptCount: integer('receipt_count').notNull().default(0),
    /**
     * When its member dismissed it from Needs you, where an email that filed nothing shows
     * (#59). Set once, by them, and never cleared; the row is otherwise as it arrived.
     */
    dismissedAt: timestamp('dismissed_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('inbound_emails_org_id_id_key').on(t.orgId, t.id),
    unique('inbound_emails_message_key').on(t.orgId, t.provider, t.providerMessageId),
    foreignKey({
      name: 'inbound_emails_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('inbound_emails_receipt_count', sql`${t.receiptCount} >= 0`),
    check(
      'inbound_emails_problem_unverified',
      sql`${t.senderProblem} is null or ${t.status} = 'unverified'`,
    ),
    check(
      'inbound_emails_dismissed_unfiled',
      sql`${t.dismissedAt} is null or ${t.status} <> 'filed'`,
    ),
    index('inbound_emails_member_idx').on(t.orgId, t.memberId, t.createdAt),
  ],
);

export const mileageLogs = pgTable(
  'mileage_logs',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    method: mileageMethod('method').notNull(),
    travelDate: date('travel_date', { mode: 'string' }).notNull(),
    purpose: text('purpose').notNull(),
    origin: text('origin'),
    destination: text('destination'),
    waypoints: jsonb('waypoints').notNull().default([]),
    distance: numeric('distance', { precision: 10, scale: 2 }).notNull(),
    unit: distanceUnit('unit').notNull(),
    // Rate snapshot: a later rate change never alters this claim.
    rateCurrency: char('rate_currency', { length: 3 }).notNull(),
    ratePerUnit: numeric('rate_per_unit', { precision: 12, scale: 4 }).notNull(),
    rateEffectiveFrom: date('rate_effective_from', { mode: 'string' }).notNull(),
    rateSource: text('rate_source').notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique('mileage_logs_expense_key').on(t.orgId, t.expenseId),
    foreignKey({
      name: 'mileage_logs_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }),
    check('mileage_logs_distance_nonnegative', sql`${t.distance} >= 0`),
    check('mileage_logs_rate_currency_iso', isoCurrency(t.rateCurrency)),
  ],
);

/**
 * The route behind a mileage expense logged by its stops (FR-CAP-04, ADR-0039): one per
 * drive, beside its mileage log, whose distance is the miles claimed. It keeps how the drive
 * was measured, copied on when it was (NFR-DAT-04), and is never measured again unless the
 * person changes its stops before it is submitted (Q33).
 */
export const mileageRoutes = pgTable(
  'mileage_routes',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    /** It returns to the start after the end. */
    roundTrip: boolean('round_trip').notNull().default(false),
    status: routeStatus('status').notNull(),
    /**
     * The measuring asked for last: its outbox event's id. A measurement made for an earlier
     * request, before the stops changed again, is never recorded.
     */
    requestId: uuid('request_id').notNull(),
    /** Why it could not be measured, in plain words, while it is not. */
    problem: text('problem'),
    /** Who measured it, how, and when: set together, only once it is measured. */
    provider: routeProvider('provider'),
    profile: text('profile'),
    measuredAt: timestamp('measured_at', { withTimezone: true }),
    /** The whole route in whole metres: the sum of its legs, the way back included. */
    distanceMetres: integer('distance_metres'),
    /** The way back from the end to the start, on a round trip, in whole metres. */
    returnMetres: integer('return_metres'),
    /** The metres in hundredths of a mile, rounded half up (ADR-0039). */
    measuredMiles: numeric('measured_miles', { precision: 10, scale: 2 }),
    /**
     * Why the miles claimed differ from those measured, or were entered by hand when it
     * could not be measured (Q33). Empty when the measured miles are claimed.
     */
    milesReason: text('miles_reason'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('mileage_routes_org_id_id_key').on(t.orgId, t.id),
    unique('mileage_routes_expense_key').on(t.orgId, t.expenseId),
    foreignKey({
      name: 'mileage_routes_log_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [mileageLogs.orgId, mileageLogs.expenseId],
    }),
    check(
      'mileage_routes_measured_whole',
      sql`(${t.status} = 'measured') = (${t.provider} IS NOT NULL AND ${t.profile} IS NOT NULL AND ${t.measuredAt} IS NOT NULL AND ${t.distanceMetres} IS NOT NULL AND ${t.measuredMiles} IS NOT NULL)`,
    ),
    check(
      'mileage_routes_problem_when_failed',
      sql`(${t.status} = 'failed') = (${t.problem} IS NOT NULL)`,
    ),
    check(
      'mileage_routes_distance_nonnegative',
      sql`${t.distanceMetres} >= 0 AND ${t.returnMetres} >= 0 AND ${t.measuredMiles} >= 0`,
    ),
    check(
      'mileage_routes_reason_length',
      sql`${t.milesReason} IS NULL OR length(${t.milesReason}) BETWEEN 1 AND 500`,
    ),
  ],
);

/**
 * A route drive's stops, in order: each address as the person typed it, which is what is
 * sent to be measured (Q32), and once measured the place it was found at and the leg to it.
 */
export const mileageRouteStops = pgTable(
  'mileage_route_stops',
  {
    id: id(),
    orgId: orgId(),
    expenseId: uuid('expense_id').notNull(),
    /** 0 is the start; the highest is the end. */
    position: integer('position').notNull(),
    address: text('address').notNull(),
    /** The place the address was found at, as the routing service names it. */
    label: text('label'),
    longitude: numeric('longitude', { precision: 9, scale: 6 }),
    latitude: numeric('latitude', { precision: 8, scale: 6 }),
    /** The leg from the stop before this one, in whole metres; none for the start. */
    legMetres: integer('leg_metres'),
    createdAt: createdAt(),
  },
  (t) => [
    unique('mileage_route_stops_org_id_id_key').on(t.orgId, t.id),
    unique('mileage_route_stops_position_key').on(t.orgId, t.expenseId, t.position),
    foreignKey({
      name: 'mileage_route_stops_route_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [mileageRoutes.orgId, mileageRoutes.expenseId],
    }),
    check('mileage_route_stops_position_range', sql`${t.position} BETWEEN 0 AND 24`),
    check('mileage_route_stops_address_length', sql`length(${t.address}) BETWEEN 1 AND 200`),
    check(
      'mileage_route_stops_place_whole',
      sql`(${t.label} IS NULL) = (${t.longitude} IS NULL) AND (${t.label} IS NULL) = (${t.latitude} IS NULL)`,
    ),
    check(
      'mileage_route_stops_coordinates_range',
      sql`${t.longitude} BETWEEN -180 AND 180 AND ${t.latitude} BETWEEN -90 AND 90`,
    ),
    check(
      'mileage_route_stops_leg',
      sql`${t.legMetres} >= 0 AND (${t.position} > 0 OR ${t.legMetres} IS NULL)`,
    ),
  ],
);

/**
 * A place a member keeps to pick for a drive's stops, such as Home or Office. Only its address
 * is ever used for a drive, copied onto the stop; its name is never sent anywhere (Q32).
 */
export const savedPlaces = pgTable(
  'saved_places',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    name: text('name').notNull(),
    address: text('address').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('saved_places_org_id_id_key').on(t.orgId, t.id),
    uniqueIndex('saved_places_member_name_key').on(t.orgId, t.memberId, sql`lower(${t.name})`),
    foreignKey({
      name: 'saved_places_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('saved_places_name_length', sql`length(${t.name}) BETWEEN 1 AND 40`),
    check('saved_places_address_length', sql`length(${t.address}) BETWEEN 1 AND 200`),
  ],
);

/**
 * One step of a report's approval (FR-GOV-02, #24): the approver it went to, then the decision,
 * when and with what comment; a return needs one. Single-step in Phase 1, so each submission adds
 * one step, numbered by `sequence`; the steps of earlier rounds stay as they were decided.
 */
export const approvalSteps = pgTable(
  'approval_steps',
  {
    id: id(),
    orgId: orgId(),
    reportId: uuid('report_id').notNull(),
    sequence: integer('sequence').notNull(),
    approverMemberId: uuid('approver_member_id').notNull(),
    decision: approvalDecision('decision').notNull().default('pending'),
    comment: text('comment'),
    decidedAt: timestamp('decided_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('approval_steps_org_id_id_key').on(t.orgId, t.id),
    unique('approval_steps_report_sequence_key').on(t.orgId, t.reportId, t.sequence),
    foreignKey({
      name: 'approval_steps_report_fk',
      columns: [t.orgId, t.reportId],
      foreignColumns: [reports.orgId, reports.id],
    }),
    foreignKey({
      name: 'approval_steps_approver_fk',
      columns: [t.orgId, t.approverMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check(
      'approval_steps_return_needs_comment',
      sql`${t.decision} <> 'returned' OR length(trim(coalesce(${t.comment}, ''))) > 0`,
    ),
  ],
);

/**
 * An expense rejected when its report was returned (FR-GOV-10 to FR-GOV-12, #24), with why: one
 * that differs from its receipt, rejected on its own, or one the approver rejected in their own
 * words. Kept with the step that returned it, so each round's rejections stay as they were. It
 * goes with its expense.
 */
export const expenseRejections = pgTable(
  'expense_rejections',
  {
    id: id(),
    orgId: orgId(),
    stepId: uuid('step_id').notNull(),
    expenseId: uuid('expense_id').notNull(),
    reason: text('reason').notNull(),
    /** True when the review rejected it on its own, because it differs from its receipt. */
    automatic: boolean('automatic').notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [
    unique('expense_rejections_org_id_id_key').on(t.orgId, t.id),
    unique('expense_rejections_step_expense_key').on(t.orgId, t.stepId, t.expenseId),
    foreignKey({
      name: 'expense_rejections_step_fk',
      columns: [t.orgId, t.stepId],
      foreignColumns: [approvalSteps.orgId, approvalSteps.id],
    }),
    foreignKey({
      name: 'expense_rejections_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }).onDelete('cascade'),
    check(
      'expense_rejections_reason_length',
      sql`char_length(trim(${t.reason})) BETWEEN 1 AND ${sql.raw(String(APPROVAL_NOTE_MAX))}`,
    ),
    index('expense_rejections_expense_idx').on(t.orgId, t.expenseId),
  ],
);

/** Append-only and hash-chained per organization. Migration 0001 blocks UPDATE, DELETE and TRUNCATE. */
export const auditEvents = pgTable(
  'audit_events',
  {
    id: id(),
    orgId: orgId(),
    sequence: bigint('sequence', { mode: 'number' }).notNull(),
    actorType: actorType('actor_type').notNull(),
    actorId: text('actor_id'),
    entityType: text('entity_type').notNull(),
    entityId: text('entity_id').notNull(),
    action: text('action').notNull(),
    payload: jsonb('payload').notNull().default({}),
    occurredAt: timestamp('occurred_at', { withTimezone: true, mode: 'date' }).notNull(),
    prevHash: char('prev_hash', { length: 64 }).notNull(),
    hash: char('hash', { length: 64 }).notNull(),
  },
  (t) => [
    unique('audit_events_org_sequence_key').on(t.orgId, t.sequence),
    unique('audit_events_hash_key').on(t.hash),
    index('audit_events_entity_idx').on(t.orgId, t.entityType, t.entityId),
  ],
);

/** Transactional outbox: written in the same transaction as the change it announces. */
export const outboxEvents = pgTable(
  'outbox_events',
  {
    id: id(),
    orgId: orgId(),
    topic: text('topic').notNull(),
    payload: jsonb('payload').notNull(),
    createdAt: createdAt(),
    claimedAt: timestamp('claimed_at', { withTimezone: true }),
    publishedAt: timestamp('published_at', { withTimezone: true }),
    attempts: integer('attempts').notNull().default(0),
  },
  (t) => [
    index('outbox_events_unpublished_idx')
      .on(t.createdAt)
      .where(sql`published_at IS NULL`),
  ],
);

/**
 * Each organization's own API keys for AI providers (ADR-0015). The key is stored only as
 * AES-256-GCM ciphertext bound to (org_id, provider); the plaintext never leaves the server
 * and is never returned by the API. key_hint is the last four characters, for display.
 */
export const aiProviderKeys = pgTable(
  'ai_provider_keys',
  {
    id: id(),
    orgId: orgId(),
    provider: aiProvider('provider').notNull(),
    ciphertext: text('ciphertext').notNull(),
    keyHint: text('key_hint').notNull(),
    /** How the provider accepted the key: as an API key header or as a bearer token. */
    authScheme: aiAuthScheme('auth_scheme').notNull(),
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    updatedByMemberId: uuid('updated_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('ai_provider_keys_org_id_id_key').on(t.orgId, t.id),
    unique('ai_provider_keys_org_provider_key').on(t.orgId, t.provider),
    foreignKey({
      name: 'ai_provider_keys_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('ai_provider_keys_hint_short', sql`length(${t.keyHint}) <= 4`),
  ],
);

/**
 * An organization's key for the routing service that measures route drives (Q31, ADR-0039):
 * ciphertext only, bound to the organization and the provider, with its last four characters
 * to tell it by. Owners and finance admins set and remove it.
 */
export const routeServiceKeys = pgTable(
  'route_service_keys',
  {
    id: id(),
    orgId: orgId(),
    provider: routeProvider('provider').notNull(),
    ciphertext: text('ciphertext').notNull(),
    keyHint: text('key_hint').notNull(),
    /** When the routing service last accepted it: on the check made as it was saved. */
    verifiedAt: timestamp('verified_at', { withTimezone: true }),
    updatedByMemberId: uuid('updated_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('route_service_keys_org_id_id_key').on(t.orgId, t.id),
    unique('route_service_keys_org_provider_key').on(t.orgId, t.provider),
    foreignKey({
      name: 'route_service_keys_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('route_service_keys_hint_short', sql`length(${t.keyHint}) <= 4`),
  ],
);

/**
 * A feature switched on or off for one organization by its owner (Q5, NFR-DEL-05). A feature
 * with no row is off. FLAG_OVERRIDES in the environment still wins, as a kill switch.
 */
export const orgFeatures = pgTable(
  'org_features',
  {
    id: id(),
    orgId: orgId(),
    /** A key from the flag registry in @expensewise/flags, such as `expenses.mileage`. */
    flag: text('flag').notNull(),
    enabled: boolean('enabled').notNull(),
    updatedByMemberId: uuid('updated_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('org_features_org_id_id_key').on(t.orgId, t.id),
    unique('org_features_org_flag_key').on(t.orgId, t.flag),
    foreignKey({
      name: 'org_features_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('org_features_flag_format', sql`${t.flag} ~ '^[a-z]+\\.[a-z-]+$'`),
  ],
);

/**
 * Which AI models read one organization's receipts, once its owner has switched on AI model
 * settings (FR-INT-16, ADR-0033): one row per model, on or off, in the order back-ups are
 * tried. Exactly one model that is on is the primary, or none when every model is off. An
 * organization with no rows reads with the defaults in @expensewise/extraction.
 */
export const orgAiModels = pgTable(
  'org_ai_models',
  {
    id: id(),
    orgId: orgId(),
    /** A model id from @expensewise/extraction, such as `claude-sonnet-5-5`. */
    model: text('model').notNull(),
    enabled: boolean('enabled').notNull(),
    isPrimary: boolean('is_primary').notNull().default(false),
    /** Its place in the order back-ups are tried, from 0. */
    position: integer('position').notNull(),
    updatedByMemberId: uuid('updated_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('org_ai_models_org_id_id_key').on(t.orgId, t.id),
    unique('org_ai_models_org_model_key').on(t.orgId, t.model),
    uniqueIndex('org_ai_models_one_primary')
      .on(t.orgId)
      .where(sql`is_primary`),
    foreignKey({
      name: 'org_ai_models_updated_by_fk',
      columns: [t.orgId, t.updatedByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('org_ai_models_model_format', sql`${t.model} ~ '^[a-z0-9][a-z0-9.-]*$'`),
    check('org_ai_models_primary_is_on', sql`${t.enabled} OR NOT ${t.isPrimary}`),
    check('org_ai_models_position_not_negative', sql`${t.position} >= 0`),
  ],
);

/**
 * What an organization pays drives at, as its owner or a finance admin set it (Q28, #77): from
 * each row's day, its own rate a mile, or, with no rate, the IRS business rate again. With no
 * row on or before a drive's date, the IRS rate. A drive copies the rate it is paid at onto its
 * mileage log, so changing these never alters one already logged (NFR-DAT-04).
 */
export const orgMileageRates = pgTable(
  'org_mileage_rates',
  {
    id: id(),
    orgId: orgId(),
    /** The first travel date it applies to. One change per organization and day. */
    effectiveFrom: date('effective_from', { mode: 'string' }).notNull(),
    /** Its own rate a mile, in major units of `currency`; null for the IRS rate again. */
    perMile: numeric('per_mile', { precision: 12, scale: 4 }),
    /** The organization's home currency when it was set; null with no rate of its own. */
    currency: char('currency', { length: 3 }),
    setByMemberId: uuid('set_by_member_id').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    unique('org_mileage_rates_org_id_id_key').on(t.orgId, t.id),
    unique('org_mileage_rates_org_day_key').on(t.orgId, t.effectiveFrom),
    foreignKey({
      name: 'org_mileage_rates_set_by_fk',
      columns: [t.orgId, t.setByMemberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check(
      'org_mileage_rates_currency_iso',
      sql`${t.currency} IS NULL OR ${isoCurrency(t.currency)}`,
    ),
    check(
      'org_mileage_rates_rate_and_currency',
      sql`(${t.perMile} IS NULL) = (${t.currency} IS NULL)`,
    ),
    check('org_mileage_rates_rate_positive', sql`${t.perMile} IS NULL OR ${t.perMile} > 0`),
  ],
);

export const statementSource = pgEnum('statement_source', ['upload', 'email', 'list']);
export const statementStatus = pgEnum('statement_status', [
  'reading',
  'read',
  'needs_look',
  'failed',
]);
export const setAsideReason = pgEnum('set_aside_reason', SET_ASIDE_REASONS);
export const matchedBy = pgEnum('matched_by', ['auto', 'person']);

/**
 * A card statement a member brought in (FR-CAP-10, #97): a PDF uploaded or emailed, read by a
 * model, or a transaction list downloaded from the card's site, read with none. It keeps what
 * the statement says of itself, whether it is read, needs a look or couldn't be read and why,
 * and which model read it at what cost. The same file is brought in once per member.
 */
export const cardStatements = pgTable(
  'card_statements',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    source: statementSource('source').notNull(),
    /** Where its file is kept; null for a list, which is read in the request and not kept. */
    storageKey: text('storage_key'),
    contentType: text('content_type').notNull(),
    byteSize: integer('byte_size').notNull(),
    sha256: char('sha256', { length: 64 }).notNull(),
    status: statementStatus('status').notNull().default('reading'),
    /** Why it needs a look or couldn't be read, said plainly; null otherwise. */
    problem: text('problem'),
    cardLastFour: text('card_last_four'),
    periodStart: date('period_start', { mode: 'string' }),
    periodEnd: date('period_end', { mode: 'string' }),
    currency: char('currency', { length: 3 }),
    /** Its own totals of charges and of credits, as printed, in minor units; null unprinted. */
    chargesMinor: bigint('charges_minor', { mode: 'number' }),
    creditsMinor: bigint('credits_minor', { mode: 'number' }),
    /** The model and instructions that read it, and what that cost; null for a list. */
    model: text('model'),
    version: text('version'),
    costNanoUsd: bigint('cost_nano_usd', { mode: 'number' }),
    /** How many transactions it brought in that weren't in already. */
    added: integer('added').notNull().default(0),
    readAt: timestamp('read_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('card_statements_org_id_id_key').on(t.orgId, t.id),
    unique('card_statements_member_sha256_key').on(t.orgId, t.memberId, t.sha256),
    foreignKey({
      name: 'card_statements_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    check('card_statements_sha256_hex', sql`${t.sha256} ~ '^[0-9a-f]{64}$'`),
    check('card_statements_byte_size_positive', sql`${t.byteSize} > 0`),
    check('card_statements_file_kept', sql`(${t.storageKey} IS NULL) = (${t.source} = 'list')`),
    check('card_statements_currency_iso', sql`${t.currency} IS NULL OR ${isoCurrency(t.currency)}`),
    check(
      'card_statements_card_last_four',
      sql`${t.cardLastFour} IS NULL OR ${t.cardLastFour} ~ '^[0-9]{4}$'`,
    ),
  ],
);

/**
 * One transaction on a member's card, brought in by the first statement that listed it and
 * kept once by its key, however often another lists it (US-CAP-07 AC4). It is matched to at most
 * one expense, by the matching or by the person, or set aside with a reason, such as a personal
 * charge; while neither, it is a missing receipt in Needs you (FR-INT-24).
 */
export const cardTransactions = pgTable(
  'card_transactions',
  {
    id: id(),
    orgId: orgId(),
    memberId: uuid('member_id').notNull(),
    statementId: uuid('statement_id').notNull(),
    /** The same each time it is printed (`transactionKeys`). */
    key: text('key').notNull(),
    transactionDate: date('transaction_date', { mode: 'string' }).notNull(),
    postedOn: date('posted_on', { mode: 'string' }),
    /** As the card prints it. */
    merchant: text('merchant').notNull(),
    /** In `currency`'s minor units; negative for a credit. */
    amountMinor: bigint('amount_minor', { mode: 'number' }).notNull(),
    currency: char('currency', { length: 3 }).notNull(),
    cardLastFour: text('card_last_four'),
    reference: text('reference'),
    expenseId: uuid('expense_id'),
    matchedBy: matchedBy('matched_by'),
    matchedAt: timestamp('matched_at', { withTimezone: true }),
    setAsideReason: setAsideReason('set_aside_reason'),
    setAsideNote: text('set_aside_note'),
    setAsideAt: timestamp('set_aside_at', { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    unique('card_transactions_org_id_id_key').on(t.orgId, t.id),
    unique('card_transactions_member_key').on(t.orgId, t.memberId, t.key),
    // An expense is paid by one card transaction at most.
    uniqueIndex('card_transactions_expense_key')
      .on(t.orgId, t.expenseId)
      .where(sql`${t.expenseId} IS NOT NULL`),
    index('card_transactions_member_open_idx').on(t.orgId, t.memberId, t.transactionDate),
    foreignKey({
      name: 'card_transactions_statement_fk',
      columns: [t.orgId, t.statementId],
      foreignColumns: [cardStatements.orgId, cardStatements.id],
    }).onDelete('cascade'),
    foreignKey({
      name: 'card_transactions_member_fk',
      columns: [t.orgId, t.memberId],
      foreignColumns: [members.orgId, members.id],
    }),
    foreignKey({
      name: 'card_transactions_expense_fk',
      columns: [t.orgId, t.expenseId],
      foreignColumns: [expenses.orgId, expenses.id],
    }),
    check('card_transactions_currency_iso', isoCurrency(t.currency)),
    check(
      'card_transactions_card_last_four',
      sql`${t.cardLastFour} IS NULL OR ${t.cardLastFour} ~ '^[0-9]{4}$'`,
    ),
    check(
      'card_transactions_matched_whole',
      sql`(${t.expenseId} IS NULL AND ${t.matchedBy} IS NULL AND ${t.matchedAt} IS NULL) OR (${t.expenseId} IS NOT NULL AND ${t.matchedBy} IS NOT NULL AND ${t.matchedAt} IS NOT NULL)`,
    ),
    check(
      'card_transactions_set_aside_whole',
      sql`(${t.setAsideReason} IS NULL AND ${t.setAsideNote} IS NULL AND ${t.setAsideAt} IS NULL) OR (${t.setAsideReason} IS NOT NULL AND ${t.setAsideAt} IS NOT NULL)`,
    ),
    // Matched or set aside, never both.
    check(
      'card_transactions_matched_or_set_aside',
      sql`${t.expenseId} IS NULL OR ${t.setAsideReason} IS NULL`,
    ),
    check(
      'card_transactions_other_needs_note',
      sql`${t.setAsideReason} IS DISTINCT FROM 'other' OR coalesce(length(trim(${t.setAsideNote})), 0) > 0`,
    ),
    check(
      'card_transactions_note_length',
      sql`${t.setAsideNote} IS NULL OR char_length(${t.setAsideNote}) <= ${sql.raw(String(SET_ASIDE_NOTE_MAX))}`,
    ),
  ],
);
