import type { Story } from '../model.ts';

const ADR13 = { by: 'blueprint', source: 'ADR-0013' } as const;
const ADR15 = { by: 'blueprint', source: 'ADR-0015' } as const;
const ADR16 = { by: 'blueprint', source: 'ADR-0016' } as const;

/** Sign-in, organizations, sign-ins and AI provider keys (FR-PLT-01 to FR-PLT-05, FR-GOV-01). */
export const ACCESS_STORIES: readonly Story[] = [
  {
    id: 'US-ACC-01',
    title: 'Sign in with my email and password',
    as: 'Alex, who travels for work',
    want: 'to sign in with my email and password',
    soThat: 'only I can reach my receipts and expenses',
    feature: 'F-01',
    requirements: ['FR-PLT-02'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I am signed out',
        when: 'I open Settings, or the app asks its API for anything of the organization’s',
        then: 'I am asked to sign in, with a link to the Sign in page, and nothing of the organization’s is shown or sent',
        decided: { by: 'claude', source: 'ADR-0013' },
        checks: [
          'e2e/settings › asks a signed-out visitor to sign in before showing any keys',
          'e2e/settings › asks a signed-out visitor to sign in before showing sign-ins',
          'e2e/settings › refuses the key endpoints without a signed-in user',
          'api/auth › asks for a token when none is sent',
        ],
      },
      {
        id: 'AC2',
        given: 'an account made for my email address',
        when: 'I enter my email and password on the Sign in page and press Sign in',
        then: 'I am signed in',
        decided: { by: 'blueprint', source: 'D-15' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'I have just signed in',
        when: 'the Sign in page finishes',
        then: 'it takes me to AI providers in Settings',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'a wrong email or password',
        when: 'I press Sign in',
        then: 'the page says why signing in failed, and I stay signed out',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'I am signed in',
        when: 'the app asks its API for anything of mine',
        then: 'the API knows who I am, and my email, from my sign-in alone',
        decided: ADR13,
        checks: ['api/auth › returns the identity proven by a valid token'],
      },
      {
        id: 'AC6',
        given:
          'a sign-in that ExpenseWise’s own sign-in service did not issue to a signed-in person: signed with another key or a shared secret, from another project, for another audience, anonymous, or a service key',
        when: 'it is used to call the API',
        then: 'it is refused as not signed in',
        decided: ADR13,
        checks: [
          'api/auth › rejects %s',
          'api/auth › rejects shared-secret (HS256) tokens: this backend holds no signing secret',
        ],
      },
      {
        id: 'AC7',
        given: 'my sign-in has expired',
        when: 'the app calls the API with it',
        then: 'it is refused, and the app is told the sign-in has expired rather than that it was never valid',
        decided: { by: 'claude' },
        checks: ['api/auth › distinguishes an expired token'],
      },
      {
        id: 'AC8',
        given: 'I am signed in',
        when: 'I press Sign out in Settings',
        then: 'I am signed out, and Settings asks me to sign in again',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
    ],
    note: 'There is no sign-up screen: accounts are made in the sign-in service’s dashboard and public sign-ups stay off. Sign-in is a password alone until the second factor arrives (F-11, #8). No test signs in through the Sign in page itself; the signed-in screen checks start from a session already made.',
  },
  {
    id: 'US-ACC-02',
    title: 'Have my organization ready the first time I sign in',
    as: 'Riley, a solo professional who self-attests',
    want: 'my own organization to be made the first time I sign in, with me as its owner',
    soThat: 'I can start at once, and the app can grow to a team later without moving my records',
    feature: 'F-02',
    requirements: ['FR-PLT-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I sign in for the first time',
        when: 'the app first opens for me',
        then: 'a one-person organization is made with me as its owner, and the audit trail records that it was made on my first sign-in',
        decided: ADR15,
        checks: [
          'api/workspace › creates the organization on first sign-in, then returns it',
          'db/ai-keys.int › creates a one-person organization with the user as owner, and an audit event',
        ],
      },
      {
        id: 'AC2',
        given: 'my email address is riley@example.com',
        when: 'my organization is made',
        then: 'it is named “riley’s organization”, with US dollars as its home currency',
        decided: { by: 'claude' },
        checks: [
          'db/ai-keys.int › creates a one-person organization with the user as owner, and an audit event',
        ],
      },
      {
        id: 'AC3',
        given: 'I already have an organization',
        when: 'I sign in again, on any screen or device',
        then: 'I reach the same organization, and no second one is made',
        decided: ADR15,
        checks: [
          'db/ai-keys.int › returns the existing membership on later sign-ins',
          'api/workspace › creates the organization on first sign-in, then returns it',
        ],
      },
      {
        id: 'AC4',
        given: 'my first sign-in opens several screens at the same moment',
        when: 'each asks for my organization',
        then: 'exactly one organization is made',
        decided: { by: 'claude' },
        checks: ['db/ai-keys.int › creates exactly one organization when first sign-ins race'],
      },
      {
        id: 'AC5',
        given: 'an account with no email address',
        when: 'it signs in for the first time',
        then: 'no organization is made, and it is told an email address is needed',
        decided: { by: 'claude' },
        checks: ['api/workspace › needs a signed-in user with an email address'],
      },
      {
        id: 'AC6',
        given: 'other organizations exist',
        when: 'I use the app',
        then: 'I see only my own organization and my own membership, never another’s',
        decided: { by: 'blueprint', source: 'ADR-0001' },
        checks: [
          'db/ai-keys.int › shows a user only their own memberships, across organizations',
          'db/ai-keys.int › shows no member rows at all without a user or an organization',
          'db/tenancy.int › sees only its own organization',
        ],
      },
    ],
  },
  {
    id: 'US-ACC-03',
    title: 'Reach the same receipts from each of my emails',
    as: 'Riley, a solo professional with a personal and a work email address',
    want: 'to link my other email address to my account',
    soThat:
      'whichever address I sign in with, I reach the same receipts, expenses and settings, as the same person',
    feature: 'F-03',
    requirements: ['FR-PLT-04'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given:
          'I enter my other email and its password under Add another email you use, on Settings → Sign-ins',
        when: 'I press Link this email',
        then: 'that email opens the same receipts, expenses and settings as the same person, the audit trail records the link, and linking it again changes nothing',
        decided: ADR16,
        checks: [
          'api/workspace › links a second sign-in with proof of both, once',
          'db/sign-ins.int › lets a fresh sign-in reach the same member and organization',
          'db/sign-ins.int › is idempotent',
        ],
      },
      {
        id: 'AC2',
        given: 'I link my other email',
        when: 'I enter its password',
        then: 'the password goes only to the sign-in service, never to ExpenseWise’s API, and I stay signed in as I was',
        decided: ADR16,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'I enter the wrong password for my other email',
        when: 'I press Link this email',
        then: 'I am told the email and password did not work, and nothing is linked',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given:
          'proof of the other email that can’t be verified, that is for the email I am using now, or that is for an account with no email address',
        when: 'it is sent to link',
        then: 'it is refused with the reason, and nothing is linked',
        decided: { by: 'claude', source: 'ADR-0016' },
        checks: ['api/workspace › refuses %s'],
      },
      {
        id: 'AC5',
        given: 'proof of the other email from a sign-in more than 10 minutes old',
        when: 'it is sent to link',
        then: 'it is refused, and nothing is linked',
        decided: { by: 'claude', source: 'ADR-0016' },
        checks: ['api/workspace › refuses %s'],
        rules: ['R-SIGN-IN-LINK'],
      },
      {
        id: 'AC6',
        given:
          'my other email signed in once before, so made its own organization, which is still empty',
        when: 'I link it',
        then: 'it moves to my account, and the organization it leaves keeps its history, which records the move',
        decided: ADR16,
        checks: [
          'db/sign-ins.int › moves a sign-in out of the empty organization its first sign-in created',
        ],
      },
      {
        id: 'AC7',
        given:
          'my other email’s own organization holds work, such as an expense, or the email belongs to someone else in my organization',
        when: 'I link it',
        then: 'it is refused and nothing changes: no work moves and no one is taken over',
        decided: ADR16,
        checks: [
          'db/sign-ins.int › refuses to move a sign-in whose organization holds work, and changes nothing',
          "db/sign-ins.int › never takes over another person's sign-in in the same organization",
          'api/workspace › refuses a sign-in that has its own work, or belongs to someone else',
        ],
      },
    ],
  },
  {
    id: 'US-ACC-04',
    title: 'See and remove the emails that open my account',
    as: 'Riley, a solo professional with a personal and a work email address',
    want: 'to see every email that opens my account, and remove one I no longer use',
    soThat: 'an address I have given up, such as an old work one, can no longer reach my receipts',
    feature: 'F-03',
    requirements: ['FR-PLT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I am signed in',
        when: 'I open Settings → Sign-ins',
        then: 'I see every email that opens my account, the one I am using marked as the one I am using now, and the others with the date each was linked',
        decided: { by: 'claude' },
        checks: [
          'api/workspace › lists the sign-ins that reach the caller, marking the current one',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'I have linked another email',
        when: 'I press Remove beside it',
        then: 'that email no longer opens my account, my other emails still do, and the audit trail records the removal',
        decided: ADR16,
        checks: [
          'api/workspace › removes another sign-in, but never the one making the request',
          'db/sign-ins.int › cuts that sign-in off, keeps the others, and never removes the last one',
        ],
      },
      {
        id: 'AC3',
        given: 'the email I am signed in with',
        when: 'I try to remove it',
        then: 'it is refused: only another of my emails can remove it',
        decided: ADR16,
        checks: ['api/workspace › removes another sign-in, but never the one making the request'],
      },
      {
        id: 'AC4',
        given: 'my account has one email left',
        when: 'anything tries to remove it',
        then: 'it stays, so I am never locked out',
        decided: ADR16,
        checks: [
          'db/sign-ins.int › cuts that sign-in off, keeps the others, and never removes the last one',
        ],
      },
      {
        id: 'AC5',
        given: 'other people and other organizations',
        when: 'sign-ins are listed or added',
        then: 'I see only my own emails, no one can add an email to another organization’s person, and each email opens exactly one person',
        decided: ADR16,
        checks: [
          'db/sign-ins.int › shows a user only their own sign-ins without an organization',
          "db/sign-ins.int › cannot add a sign-in to another organization's member",
          'db/sign-ins.int › gives each sign-in to exactly one member',
        ],
      },
    ],
  },
  {
    id: 'US-ACC-05',
    title: 'Give the app the organization’s AI keys',
    as: 'the organization’s owner',
    want: 'to give ExpenseWise the organization’s own Anthropic and OpenAI keys in Settings, checked as I save them',
    soThat:
      'receipts are read on the organization’s own provider accounts, and I know at once whether a key works',
    feature: 'F-04',
    requirements: ['FR-PLT-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I am the organization’s owner',
        when: 'I follow Settings from Home to AI providers',
        then: 'I see Anthropic and OpenAI, each showing No key, or the last four characters of its key and when it was last checked',
        decided: ADR15,
        checks: [
          'e2e/settings › links to settings from the home page',
          'api/workspace › lists every provider, none configured to begin with',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'I paste a key and press Check and save',
        when: 'the provider accepts it in a free check',
        then: 'it is stored encrypted, and shown only by its last four characters',
        decided: ADR15,
        checks: [
          'api/workspace › checks a key with the provider, stores it encrypted and never returns it',
          'db/ai-keys.int › saves, replaces, verifies and removes a key within one organization',
        ],
      },
      {
        id: 'AC3',
        given: 'a key is already stored for a provider',
        when: 'I save another for it',
        then: 'the new key replaces the old one: the organization keeps one key for each provider',
        decided: ADR15,
        checks: [
          'db/ai-keys.int › saves, replaces, verifies and removes a key within one organization',
        ],
      },
      {
        id: 'AC4',
        given: 'the provider rejects the key or can’t be reached',
        when: 'I press Check and save',
        then: 'nothing is stored',
        decided: ADR15,
        checks: [
          'api/workspace › stores nothing when the provider rejects the key or cannot be reached',
        ],
      },
      {
        id: 'AC5',
        given: 'a check that fails',
        when: 'the page tells me',
        then: 'it says what the provider answered, its status and its own message, or why there was no answer, so I can act on it',
        decided: { by: 'claude' },
        checks: [
          'api/workspace › says what the provider answered, so a failed check can be acted on',
          'api/ai-providers › calls a 400 refused, and a 429 or 5xx unreachable, keeping the status and message',
          'api/ai-providers › reports no answer as unreachable, without the error text or trying further',
        ],
      },
      {
        id: 'AC6',
        given:
          'a key pasted with spaces, line breaks, invisible characters, quotes, or the setting’s name in front as when copied from a settings file',
        when: 'I save it',
        then: 'those are removed before the check, and anything that still isn’t a key is refused before any provider is called',
        decided: { by: 'claude' },
        checks: [
          'api/workspace › cleans what copying adds to a key before checking it, and refuses what is not a key',
          'api/ai-providers › removes what copying adds and keys never contain',
          'api/workspace › rejects unknown providers and short keys before calling anyone',
        ],
      },
      {
        id: 'AC7',
        given: 'an Anthropic key of either kind Anthropic issues, an API key or a sign-in token',
        when: 'I save it',
        then: 'both ways of presenting a key to Anthropic are tried, and the one that works is kept with the key',
        decided: ADR15,
        checks: [
          'api/ai-providers › accepts an Anthropic API key sent as x-api-key',
          'api/ai-providers › falls back to a bearer token when Anthropic rejects the key as x-api-key',
          'api/ai-providers › tries the other scheme after any answer, not only a 401',
          "api/ai-providers › reports a key both schemes reject as rejected, with Anthropic's own message",
        ],
      },
    ],
  },
  {
    id: 'US-ACC-06',
    title: 'Keep the AI keys secret, checked and removable',
    as: 'the organization’s owner',
    want: 'the organization’s AI keys kept secret, and to check or remove them at any time',
    soThat:
      'no one can read a key back or spend the organization’s money with it, and a key that stops working is found before receipts fail',
    feature: 'F-04',
    requirements: ['FR-PLT-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a stored key',
        when: 'I press Test',
        then: 'it is checked again with the provider, the way that worked before first, I am told the key works, and its time is kept as when it last worked',
        decided: ADR15,
        checks: [
          'api/workspace › re-checks a stored key with its stored scheme, and records the check',
          'api/ai-providers › tries the stored scheme first when re-checking a key',
        ],
      },
      {
        id: 'AC2',
        given:
          'a stored key the provider no longer accepts, or one that can’t be decrypted because the encryption secret has changed',
        when: 'I press Test',
        then: 'I am told which, without an error, so I can save the key again',
        decided: ADR15,
        checks: [
          'api/workspace › reports a stored key that no longer works, or cannot be decrypted, without failing',
        ],
      },
      {
        id: 'AC3',
        given: 'a stored key',
        when: 'I press Remove',
        then: 'it is deleted; removing a key that isn’t there says there is none',
        decided: ADR15,
        checks: [
          'api/workspace › removes a key, and says when there is none',
          'db/ai-keys.int › saves, replaces, verifies and removes a key within one organization',
        ],
      },
      {
        id: 'AC4',
        given: 'a stored key',
        when: 'anyone asks for it',
        then: 'it is never sent back, only its last four characters, and a provider’s message that repeats the key has it masked',
        decided: ADR15,
        checks: [
          'api/workspace › checks a key with the provider, stores it encrypted and never returns it',
          'api/secret-box › shows only the last four characters as a hint',
          'db/ai-keys.int › stores at most four characters of the key as its hint',
          'api/ai-providers › never repeats the key, even if the provider echoes it',
        ],
      },
      {
        id: 'AC5',
        given: 'a stored key’s encrypted copy',
        when: 'it is moved to another organization’s or provider’s place, opened with another secret, or tampered with',
        then: 'it won’t open',
        decided: ADR15,
        checks: [
          'api/secret-box › refuses to open a ciphertext under another organization or provider',
          'api/secret-box › refuses to open with a different secret, or a tampered ciphertext',
          'api/secret-box › round-trips a secret, with a fresh nonce every time',
        ],
      },
      {
        id: 'AC6',
        given: 'another organization',
        when: 'it lists, saves or removes keys',
        then: 'it can never see, replace or remove ours, and a key is credited only to a member of its own organization',
        decided: ADR15,
        checks: [
          "db/ai-keys.int › keeps one organization's keys away from every other",
          'db/ai-keys.int › keeps a key attributed to a member of the same organization',
        ],
      },
      {
        id: 'AC7',
        given: 'I am a plain member, not an owner or finance admin',
        when: 'I open AI providers, or try to save, test or remove a key',
        then: 'I am refused: only an owner or finance admin can do this',
        decided: ADR15,
        checks: ['api/workspace › lets only owners and finance admins manage keys'],
      },
      {
        id: 'AC8',
        given: 'a key is saved, checked with Test or removed',
        when: 'anyone later looks at the audit trail',
        then: 'it records what was done, by whom and when, and never the key itself',
        decided: ADR15,
        checks: [],
        untested: 66,
      },
    ],
    note: 'The audit events for keys are written by the database store, which no test exercises: the API tests count them through a stand-in store, and the database tests save and remove keys without the audit step.',
  },
  {
    id: 'US-ACC-07',
    title: 'Keep admin actions to owners and finance admins',
    as: 'the organization’s owner',
    want: 'each person in the organization to hold a role, and only owners and finance admins to take admin actions',
    soThat:
      'someone who only files expenses can’t change the organization’s settings or spend its money with a provider',
    feature: 'F-04',
    requirements: ['FR-GOV-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'someone signs in for the first time',
        when: 'their organization is made',
        then: 'they hold the owner role',
        decided: ADR15,
        checks: [
          'db/ai-keys.int › creates a one-person organization with the user as owner, and an audit event',
          'api/workspace › creates the organization on first sign-in, then returns it',
        ],
      },
      {
        id: 'AC2',
        given: 'a role belongs to the person, not to an email address',
        when: 'I sign in with any of my linked emails',
        then: 'I hold the same role with each, such as owner',
        decided: { by: 'owner', source: 'Q24' },
        checks: ['db/sign-ins.int › lets a fresh sign-in reach the same member and organization'],
      },
      {
        id: 'AC3',
        given: 'a plain member, not an owner or finance admin',
        when: 'they try an admin action, such as managing the organization’s AI keys',
        then: 'they are refused: only an owner or finance admin can do this',
        decided: ADR15,
        checks: ['api/workspace › lets only owners and finance admins manage keys'],
      },
      {
        id: 'AC4',
        given: 'a finance admin',
        when: 'they open AI providers',
        then: 'they can save, test and remove keys as the owner can',
        decided: ADR15,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'someone signed in who belongs to no organization',
        when: 'they try an admin action or open Sign-ins',
        then: 'they are refused, and told they are not a member of an organization yet',
        decided: { by: 'claude' },
        checks: [
          'api/workspace › lets only owners and finance admins manage keys',
          'api/workspace › needs an organization first',
        ],
      },
    ],
    note: 'Today the only admin action is managing the AI keys. No one can yet be invited or given a role (#29), so every organization is one owner, and no test signs in as a finance admin. Inside an organization any member can see and change every member’s receipts, expenses and trips (GAP-20, #50); the auditor’s read-only access is not enforced yet.',
  },
  {
    id: 'US-ACC-08',
    title: 'Keep the organization’s details in Settings',
    as: 'the organization’s owner',
    want: 'to keep the organization’s details and demographics in Settings',
    soThat:
      'the organization is described as it really is, not as the app guessed on my first sign-in',
    feature: 'F-51',
    requirements: ['FR-PLT-11'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'I am the organization’s owner',
        when: 'I open Settings',
        then: 'I can change the organization’s details and demographics',
        decided: { by: 'owner', source: 'owner 2026-10-04' },
        checks: [],
      },
      {
        id: 'AC2',
        given: 'I am the organization’s owner',
        when: 'I change its details and demographics',
        then: 'the details are its name, home currency, country, locale, time zone and address, and the demographics its industry and size',
        decided: { by: 'claude' },
        checks: [],
      },
      {
        id: 'AC3',
        given: 'I am a member who is not an owner',
        when: 'I open Settings',
        then: 'I can’t change the organization’s details',
        decided: { by: 'claude' },
        checks: [],
      },
      {
        id: 'AC4',
        given: 'the owner has set the organization’s time zone',
        when: 'background work, such as a report opening or closing, decides what day it is',
        then: 'it goes by the organization’s time zone',
        decided: { by: 'claude' },
        checks: [],
      },
      {
        id: 'AC5',
        given: 'the owner changes a detail',
        when: 'anyone later looks at the audit trail',
        then: 'it records the change',
        decided: { by: 'claude' },
        checks: [],
      },
    ],
    note: 'Your requirement of Oct 4. Today a new organization is named after its owner’s email address and starts in US dollars, and nothing can change either (US-ACC-02).',
  },
];
