import type { Story } from '../model.ts';

const ADR13 = { by: 'blueprint', source: 'ADR-0013' } as const;
const ADR15 = { by: 'blueprint', source: 'ADR-0015' } as const;
const ADR16 = { by: 'blueprint', source: 'ADR-0016' } as const;
const OWNER_OCT_4 = { by: 'owner', source: 'owner 2026-10-04' } as const;
const ADR42 = { by: 'claude', source: 'ADR-0042' } as const;

/** Sign-in, organizations, sign-ins and AI provider keys (FR-PLT-01 to FR-PLT-05, FR-GOV-01). */
export const ACCESS_STORIES: readonly Story[] = [
  {
    id: 'US-ACC-01',
    title: 'Sign in with my email and password',
    as: 'Alex, who travels for work',
    want: 'to sign in with my email and password',
    soThat: 'only I can reach my receipts and expenses',
    feature: 'F-01',
    requirements: ['FR-PLT-02'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I am signed out',
        when: 'I open Settings, or the app asks its API for anything of the organization’s',
        then: 'I am asked to sign in, with a link to the Sign in page, and nothing of the organization’s is shown or sent',
        decided: { by: 'claude', source: 'ADR-0013' },
        checks: [
          'e2e/settings › asks a signed-out visitor to sign in before showing any keys',
          'e2e/settings › asks a signed-out visitor to sign in before showing sign-ins',
          'e2e/settings › refuses the key endpoints without a signed-in user',
          'api/auth › asks for a token when none is sent',
        ],
      },
      {
        id: 'AC2',
        given: 'an account made for my email address',
        when: 'I enter my email and password on the Sign in page and press Sign in',
        then: 'I am signed in',
        decided: { by: 'blueprint', source: 'D-15' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'I have just signed in',
        when: 'the Sign in page finishes',
        then: 'it takes me to AI providers in Settings',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'a wrong email or password',
        when: 'I press Sign in',
        then: 'the page says why signing in failed, and I stay signed out',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'I am signed in',
        when: 'the app asks its API for anything of mine',
        then: 'the API knows who I am, and my email, from my sign-in alone',
        decided: ADR13,
        checks: ['api/auth › returns the identity proven by a valid token'],
      },
      {
        id: 'AC6',
        given:
          'a sign-in that ExpenseWise’s own sign-in service did not issue to a signed-in person: signed with another key or a shared secret, from another project, for another audience, anonymous, or a service key',
        when: 'it is used to call the API',
        then: 'it is refused as not signed in',
        decided: ADR13,
        checks: [
          'api/auth › rejects %s',
          'api/auth › rejects shared-secret (HS256) tokens: this backend holds no signing secret',
        ],
      },
      {
        id: 'AC7',
        given: 'my sign-in has expired',
        when: 'the app calls the API with it',
        then: 'it is refused, and the app is told the sign-in has expired rather than that it was never valid',
        decided: { by: 'claude' },
        checks: ['api/auth › distinguishes an expired token'],
      },
      {
        id: 'AC8',
        given: 'I am signed in',
        when: 'I press Sign out in Settings',
        then: 'I am signed out, and Settings asks me to sign in again',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
    ],
    note: 'There is no sign-up screen: accounts are made in the sign-in service’s dashboard and public sign-ups stay off. Sign-in is a password alone unless the organization switches the second factor on and the person adds an authenticator app (F-11, US-ACC-11). No test signs in through the Sign in page itself; the signed-in screen checks start from a session already made.',
  },
  {
    id: 'US-ACC-02',
    title: 'Have my organization ready the first time I sign in',
    as: 'Riley, a solo professional who self-attests',
    want: 'my own organization to be made the first time I sign in, with me as its owner',
    soThat: 'I can start at once, and the app can grow to a team later without moving my records',
    feature: 'F-02',
    requirements: ['FR-PLT-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I sign in for the first time',
        when: 'the app first opens for me',
        then: 'a one-person organization is made with me as its owner, and the audit trail records that it was made on my first sign-in',
        decided: ADR15,
        checks: [
          'api/workspace › creates the organization on first sign-in, then returns it',
          'db/ai-keys.int › creates a one-person organization with the user as owner, and an audit event',
        ],
      },
      {
        id: 'AC2',
        given: 'my email address is riley@example.com',
        when: 'my organization is made',
        then: 'it is named “riley’s organization”, with US dollars as its home currency',
        decided: { by: 'claude' },
        checks: [
          'db/ai-keys.int › creates a one-person organization with the user as owner, and an audit event',
        ],
      },
      {
        id: 'AC3',
        given: 'I already have an organization',
        when: 'I sign in again, on any screen or device',
        then: 'I reach the same organization, and no second one is made',
        decided: ADR15,
        checks: [
          'db/ai-keys.int › returns the existing membership on later sign-ins',
          'api/workspace › creates the organization on first sign-in, then returns it',
        ],
      },
      {
        id: 'AC4',
        given: 'my first sign-in opens several screens at the same moment',
        when: 'each asks for my organization',
        then: 'exactly one organization is made',
        decided: { by: 'claude' },
        checks: ['db/ai-keys.int › creates exactly one organization when first sign-ins race'],
      },
      {
        id: 'AC5',
        given: 'an account with no email address',
        when: 'it signs in for the first time',
        then: 'no organization is made, and it is told an email address is needed',
        decided: { by: 'claude' },
        checks: ['api/workspace › needs a signed-in user with an email address'],
      },
      {
        id: 'AC6',
        given: 'other organizations exist',
        when: 'I use the app',
        then: 'I see only my own organization and my own membership, never another’s',
        decided: { by: 'blueprint', source: 'ADR-0001' },
        checks: [
          'db/ai-keys.int › shows a user only their own memberships, across organizations',
          'db/ai-keys.int › shows no member rows at all without a user or an organization',
          'db/tenancy.int › sees only its own organization',
        ],
      },
    ],
  },
  {
    id: 'US-ACC-03',
    title: 'Reach the same receipts from each of my emails',
    as: 'Riley, a solo professional with a personal and a work email address',
    want: 'to link my other email address to my account',
    soThat:
      'whichever address I sign in with, I reach the same receipts, expenses and settings, as the same person',
    feature: 'F-03',
    requirements: ['FR-PLT-04'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given:
          'I enter my other email and its password under Add another email you use, on Settings → Sign-ins',
        when: 'I press Link this email',
        then: 'that email opens the same receipts, expenses and settings as the same person, the audit trail records the link, and linking it again changes nothing',
        decided: ADR16,
        checks: [
          'api/workspace › links a second sign-in with proof of both, once',
          'db/sign-ins.int › lets a fresh sign-in reach the same member and organization',
          'db/sign-ins.int › is idempotent',
        ],
      },
      {
        id: 'AC2',
        given: 'I link my other email',
        when: 'I enter its password',
        then: 'the password goes only to the sign-in service, never to ExpenseWise’s API, and I stay signed in as I was',
        decided: ADR16,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'I enter the wrong password for my other email',
        when: 'I press Link this email',
        then: 'I am told the email and password did not work, and nothing is linked',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given:
          'proof of the other email that can’t be verified, that is for the email I am using now, or that is for an account with no email address',
        when: 'it is sent to link',
        then: 'it is refused with the reason, and nothing is linked',
        decided: { by: 'claude', source: 'ADR-0016' },
        checks: ['api/workspace › refuses %s'],
      },
      {
        id: 'AC5',
        given: 'proof of the other email from a sign-in more than 10 minutes old',
        when: 'it is sent to link',
        then: 'it is refused, and nothing is linked',
        decided: { by: 'claude', source: 'ADR-0016' },
        checks: ['api/workspace › refuses %s'],
        rules: ['R-SIGN-IN-LINK'],
      },
      {
        id: 'AC6',
        given:
          'my other email signed in once before, so made its own organization, which is still empty',
        when: 'I link it',
        then: 'it moves to my account, and the organization it leaves keeps its history, which records the move',
        decided: ADR16,
        checks: [
          'db/sign-ins.int › moves a sign-in out of the empty organization its first sign-in created',
        ],
      },
      {
        id: 'AC7',
        given:
          'my other email’s own organization holds work, such as an expense, or the email belongs to someone else in my organization',
        when: 'I link it',
        then: 'it is refused and nothing changes: no work moves and no one is taken over',
        decided: ADR16,
        checks: [
          'db/sign-ins.int › refuses to move a sign-in whose organization holds work, and changes nothing',
          "db/sign-ins.int › never takes over another person's sign-in in the same organization",
          'api/workspace › refuses a sign-in that has its own work, or belongs to someone else',
        ],
      },
    ],
  },
  {
    id: 'US-ACC-04',
    title: 'See and remove the emails that open my account',
    as: 'Riley, a solo professional with a personal and a work email address',
    want: 'to see every email that opens my account, and remove one I no longer use',
    soThat: 'an address I have given up, such as an old work one, can no longer reach my receipts',
    feature: 'F-03',
    requirements: ['FR-PLT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I am signed in',
        when: 'I open Settings → Sign-ins',
        then: 'I see every email that opens my account, the one I am using marked as the one I am using now, and the others with the date each was linked',
        decided: { by: 'claude' },
        checks: [
          'api/workspace › lists the sign-ins that reach the caller, marking the current one',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'I have linked another email',
        when: 'I press Remove beside it',
        then: 'that email no longer opens my account, my other emails still do, and the audit trail records the removal',
        decided: ADR16,
        checks: [
          'api/workspace › removes another sign-in, but never the one making the request',
          'db/sign-ins.int › cuts that sign-in off, keeps the others, and never removes the last one',
        ],
      },
      {
        id: 'AC3',
        given: 'the email I am signed in with',
        when: 'I try to remove it',
        then: 'it is refused: only another of my emails can remove it',
        decided: ADR16,
        checks: ['api/workspace › removes another sign-in, but never the one making the request'],
      },
      {
        id: 'AC4',
        given: 'my account has one email left',
        when: 'anything tries to remove it',
        then: 'it stays, so I am never locked out',
        decided: ADR16,
        checks: [
          'db/sign-ins.int › cuts that sign-in off, keeps the others, and never removes the last one',
        ],
      },
      {
        id: 'AC5',
        given: 'other people and other organizations',
        when: 'sign-ins are listed or added',
        then: 'I see only my own emails, no one can add an email to another organization’s person, and each email opens exactly one person',
        decided: ADR16,
        checks: [
          'db/sign-ins.int › shows a user only their own sign-ins without an organization',
          "db/sign-ins.int › cannot add a sign-in to another organization's member",
          'db/sign-ins.int › gives each sign-in to exactly one member',
        ],
      },
    ],
  },
  {
    id: 'US-ACC-05',
    title: 'Give the app the organization’s AI keys',
    as: 'the organization’s owner',
    want: 'to give ExpenseWise the organization’s own Anthropic and OpenAI keys in Settings, checked as I save them',
    soThat:
      'receipts are read on the organization’s own provider accounts, and I know at once whether a key works',
    feature: 'F-04',
    requirements: ['FR-PLT-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I am the organization’s owner',
        when: 'I follow Settings from Home to AI providers',
        then: 'I see Anthropic and OpenAI, each showing No key, or the last four characters of its key and when it was last checked',
        decided: ADR15,
        checks: [
          'e2e/settings › links to settings from the home page',
          'api/workspace › lists every provider, none configured to begin with',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'I paste a key and press Check and save',
        when: 'the provider accepts it in a free check',
        then: 'it is stored encrypted, and shown only by its last four characters',
        decided: ADR15,
        checks: [
          'api/workspace › checks a key with the provider, stores it encrypted and never returns it',
          'db/ai-keys.int › saves, replaces, verifies and removes a key within one organization',
        ],
      },
      {
        id: 'AC3',
        given: 'a key is already stored for a provider',
        when: 'I save another for it',
        then: 'the new key replaces the old one: the organization keeps one key for each provider',
        decided: ADR15,
        checks: [
          'db/ai-keys.int › saves, replaces, verifies and removes a key within one organization',
        ],
      },
      {
        id: 'AC4',
        given: 'the provider rejects the key or can’t be reached',
        when: 'I press Check and save',
        then: 'nothing is stored',
        decided: ADR15,
        checks: [
          'api/workspace › stores nothing when the provider rejects the key or cannot be reached',
        ],
      },
      {
        id: 'AC5',
        given: 'a check that fails',
        when: 'the page tells me',
        then: 'it says what the provider answered, its status and its own message, or why there was no answer, so I can act on it',
        decided: { by: 'claude' },
        checks: [
          'api/workspace › says what the provider answered, so a failed check can be acted on',
          'api/ai-providers › calls a 400 refused, and a 429 or 5xx unreachable, keeping the status and message',
          'api/ai-providers › reports no answer as unreachable, without the error text or trying further',
        ],
      },
      {
        id: 'AC6',
        given:
          'a key pasted with spaces, line breaks, invisible characters, quotes, or the setting’s name in front as when copied from a settings file',
        when: 'I save it',
        then: 'those are removed before the check, and anything that still isn’t a key is refused before any provider is called',
        decided: { by: 'claude' },
        checks: [
          'api/workspace › cleans what copying adds to a key before checking it, and refuses what is not a key',
          'api/ai-providers › removes what copying adds and keys never contain',
          'api/workspace › rejects unknown providers and short keys before calling anyone',
        ],
      },
      {
        id: 'AC7',
        given: 'an Anthropic key of either kind Anthropic issues, an API key or a sign-in token',
        when: 'I save it',
        then: 'both ways of presenting a key to Anthropic are tried, and the one that works is kept with the key',
        decided: ADR15,
        checks: [
          'api/ai-providers › accepts an Anthropic API key sent as x-api-key',
          'api/ai-providers › falls back to a bearer token when Anthropic rejects the key as x-api-key',
          'api/ai-providers › tries the other scheme after any answer, not only a 401',
          "api/ai-providers › reports a key both schemes reject as rejected, with Anthropic's own message",
        ],
      },
    ],
  },
  {
    id: 'US-ACC-06',
    title: 'Keep the AI keys secret, checked and removable',
    as: 'the organization’s owner',
    want: 'the organization’s AI keys kept secret, and to check or remove them at any time',
    soThat:
      'no one can read a key back or spend the organization’s money with it, and a key that stops working is found before receipts fail',
    feature: 'F-04',
    requirements: ['FR-PLT-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a stored key',
        when: 'I press Test',
        then: 'it is checked again with the provider, the way that worked before first, I am told the key works, and its time is kept as when it last worked',
        decided: ADR15,
        checks: [
          'api/workspace › re-checks a stored key with its stored scheme, and records the check',
          'api/ai-providers › tries the stored scheme first when re-checking a key',
        ],
      },
      {
        id: 'AC2',
        given:
          'a stored key the provider no longer accepts, or one that can’t be decrypted because the encryption secret has changed',
        when: 'I press Test',
        then: 'I am told which, without an error, so I can save the key again',
        decided: ADR15,
        checks: [
          'api/workspace › reports a stored key that no longer works, or cannot be decrypted, without failing',
        ],
      },
      {
        id: 'AC3',
        given: 'a stored key',
        when: 'I press Remove',
        then: 'it is deleted; removing a key that isn’t there says there is none',
        decided: ADR15,
        checks: [
          'api/workspace › removes a key, and says when there is none',
          'db/ai-keys.int › saves, replaces, verifies and removes a key within one organization',
        ],
      },
      {
        id: 'AC4',
        given: 'a stored key',
        when: 'anyone asks for it',
        then: 'it is never sent back, only its last four characters, and a provider’s message that repeats the key has it masked',
        decided: ADR15,
        checks: [
          'api/workspace › checks a key with the provider, stores it encrypted and never returns it',
          'api/secret-box › shows only the last four characters as a hint',
          'db/ai-keys.int › stores at most four characters of the key as its hint',
          'api/ai-providers › never repeats the key, even if the provider echoes it',
        ],
      },
      {
        id: 'AC5',
        given: 'a stored key’s encrypted copy',
        when: 'it is moved to another organization’s or provider’s place, opened with another secret, or tampered with',
        then: 'it won’t open',
        decided: ADR15,
        checks: [
          'api/secret-box › refuses to open a ciphertext under another organization or provider',
          'api/secret-box › refuses to open with a different secret, or a tampered ciphertext',
          'api/secret-box › round-trips a secret, with a fresh nonce every time',
        ],
      },
      {
        id: 'AC6',
        given: 'another organization',
        when: 'it lists, saves or removes keys',
        then: 'it can never see, replace or remove ours, and a key is credited only to a member of its own organization',
        decided: ADR15,
        checks: [
          "db/ai-keys.int › keeps one organization's keys away from every other",
          'db/ai-keys.int › keeps a key attributed to a member of the same organization',
        ],
      },
      {
        id: 'AC7',
        given: 'I am a plain member, not an owner or finance admin',
        when: 'I open AI providers, or try to save, test or remove a key',
        then: 'I am refused: only an owner or finance admin can do this',
        decided: ADR15,
        checks: ['api/workspace › lets only owners and finance admins manage keys'],
      },
      {
        id: 'AC8',
        given: 'a key is saved, checked with Test or removed',
        when: 'anyone later looks at the audit trail',
        then: 'it records what was done, by whom and when, and never the key itself',
        decided: ADR15,
        checks: [],
        untested: 66,
      },
    ],
    note: 'The audit events for keys are written by the database store, which no test exercises: the API tests count them through a stand-in store, and the database tests save and remove keys without the audit step.',
  },
  {
    id: 'US-ACC-07',
    title: 'Keep admin actions to owners and finance admins',
    as: 'the organization’s owner',
    want: 'each person in the organization to hold a role, and only owners and finance admins to take admin actions',
    soThat:
      'someone who only files expenses can’t change the organization’s settings or spend its money with a provider',
    feature: 'F-04',
    requirements: ['FR-GOV-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'someone signs in for the first time',
        when: 'their organization is made',
        then: 'they hold the owner role',
        decided: ADR15,
        checks: [
          'db/ai-keys.int › creates a one-person organization with the user as owner, and an audit event',
          'api/workspace › creates the organization on first sign-in, then returns it',
        ],
      },
      {
        id: 'AC2',
        given: 'a role belongs to the person, not to an email address',
        when: 'I sign in with any of my linked emails',
        then: 'I hold the same role with each, such as owner',
        decided: { by: 'owner', source: 'Q24' },
        checks: ['db/sign-ins.int › lets a fresh sign-in reach the same member and organization'],
      },
      {
        id: 'AC3',
        given: 'a plain member, not an owner or finance admin',
        when: 'they try an admin action, such as managing the organization’s AI keys',
        then: 'they are refused: only an owner or finance admin can do this',
        decided: ADR15,
        checks: ['api/workspace › lets only owners and finance admins manage keys'],
      },
      {
        id: 'AC4',
        given: 'a finance admin',
        when: 'they open AI providers',
        then: 'they can save, test and remove keys as the owner can',
        decided: ADR15,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'someone signed in who belongs to no organization',
        when: 'they try an admin action or open Sign-ins',
        then: 'they are refused, and told they are not a member of an organization yet',
        decided: { by: 'claude' },
        checks: [
          'api/workspace › lets only owners and finance admins manage keys',
          'api/workspace › needs an organization first',
        ],
      },
    ],
    note: 'The admin actions are managing the AI keys, for owners and finance admins, and managing people, for owners only (US-TEAM-01). No test signs in as a finance admin to manage keys. Since PR #58 each member sees and changes only their own records, and an auditor reads everyone’s and changes nothing (US-SEC-14 to US-SEC-16).',
  },
  {
    id: 'US-ACC-08',
    title: 'Keep the organization’s details in Settings',
    as: 'the organization’s owner',
    want: 'to keep the organization’s details and demographics in Settings',
    soThat:
      'the organization is described as it really is, not as the app guessed on my first sign-in',
    feature: 'F-51',
    requirements: ['FR-PLT-11'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I am the organization’s owner',
        when: 'I open Settings',
        then: 'I can change the organization’s details and demographics',
        decided: { by: 'owner', source: 'owner 2026-10-04' },
        checks: [
          'api/organization › shows every member the details and their own role, and lets only the owner change them',
          'db/organizations.int › keeps each detail the owner sets, with one audit event listing every change',
        ],
      },
      {
        id: 'AC2',
        given: 'I am the organization’s owner',
        when: 'I change its details and demographics',
        then: 'the details are its name, home currency, country, locale, time zone and address, and the demographics its industry and size',
        decided: { by: 'claude' },
        checks: [
          'domain/organization › sets each detail and demographic, tidied, and says what changed',
          'db/organizations.int › keeps each detail the owner sets, with one audit event listing every change',
        ],
      },
      {
        id: 'AC3',
        given: 'I am a member who is not an owner',
        when: 'I open Settings',
        then: 'I can’t change the organization’s details',
        decided: { by: 'claude' },
        checks: [
          'api/organization › shows every member the details and their own role, and lets only the owner change them',
        ],
      },
      {
        id: 'AC4',
        given: 'the owner has set the organization’s time zone',
        when: 'background work, such as a report opening or closing, decides what day it is',
        then: 'it goes by the organization’s time zone',
        decided: { by: 'claude' },
        checks: [
          'db/organizations.int › with organization settings on, joins a trip 24 hours after its return day ends there',
          'db/organizations.int › names a report by the day it opened where the organization is',
        ],
      },
      {
        id: 'AC5',
        given: 'the owner changes a detail',
        when: 'anyone later looks at the audit trail',
        then: 'it records the change',
        decided: { by: 'claude' },
        checks: [
          'db/organizations.int › keeps each detail the owner sets, with one audit event listing every change',
          'api/organization › shows every member the details and their own role, and lets only the owner change them',
        ],
      },
      {
        id: 'AC6',
        given: 'I am the owner',
        when: 'I save a value that isn’t one, such as a blank name, a three-letter country or a time zone nobody knows',
        then: 'nothing is saved, and I am told which field and why; saving what is already there records nothing',
        decided: { by: 'claude' },
        checks: [
          'domain/organization › refuses a value that isn’t one, naming the field',
          'db/organizations.int › refuses a value that isn’t one, and changes nothing',
          'api/organization › refuses a value that isn’t one, naming the field, and a request that changes nothing',
        ],
      },
      {
        id: 'AC7',
        given: 'organization settings are switched off',
        when: 'anyone opens Settings',
        then: 'there is no Organization page to change, and its routes answer as if they weren’t there',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/organization › answers 404 feature_off while organization settings are off, so they look absent',
        ],
      },
    ],
    note: 'Your requirement of Oct 4. A new organization is still named after its owner’s email address and starts in US dollars (US-ACC-02); now the owner can change both, and keep the rest, in Settings › Organization. The locale is kept, but nothing formats by it yet.',
  },
  {
    id: 'US-ACC-09',
    title: 'Reports keep my organization’s days',
    as: 'Alex, who travels for work',
    want: 'reports to open and close by the days where my organization is',
    soThat: 'a trip is on its report a day after I get home, not a day and a half',
    feature: 'F-51',
    requirements: ['FR-PLT-11'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'organization settings are on and the organization keeps a time zone',
        when: 'a trip’s return day, or a local expense’s day, ends there',
        then: 'it joins a report 24 hours later, rather than at noon UTC two days on',
        decided: { by: 'claude', source: 'ADR-0037' },
        checks: [
          'domain/reports › in the organization’s time zone, waits 24 hours after its day ends there (FR-PLT-11)',
          'db/organizations.int › with organization settings on, joins a trip 24 hours after its return day ends there',
        ],
        rules: ['R-REPORT-JOIN'],
      },
      {
        id: 'AC2',
        given: 'organization settings are on and the organization keeps a time zone',
        when: 'a report opens',
        then: 'its day 28 is 28 days on the organization’s calendar at the time it opened, so a clock change doesn’t move it to the day before',
        decided: { by: 'claude', source: 'ADR-0037' },
        checks: [
          'domain/reports › in the organization’s time zone, closes on its day 28 at the time it opened there',
          'db/organizations.int › with organization settings on, joins a trip 24 hours after its return day ends there',
        ],
        rules: ['R-REPORT-WINDOW'],
      },
      {
        id: 'AC3',
        given: 'organization settings are on and the organization keeps a time zone',
        when: 'a report opens',
        then: 'it is named by the date it opened where the organization is',
        decided: { by: 'claude', source: 'ADR-0037' },
        checks: [
          'db/organizations.int › names a report by the day it opened where the organization is',
        ],
      },
      {
        id: 'AC4',
        given: 'organization settings are off, or the organization keeps no time zone',
        when: 'the schedule decides what is due',
        then: 'it counts at UTC−12 as before, whatever time zone is kept',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'db/organizations.int › with organization settings off, goes by UTC−12 as before, whatever time zone is kept',
        ],
        rules: ['R-REPORT-JOIN'],
      },
      {
        id: 'AC5',
        given: 'the server’s override says organization settings are on or off',
        when: 'background work asks whether they are',
        then: 'the override wins over the owner’s switch, as it does for screens',
        decided: { by: 'blueprint', source: 'ADR-0032' },
        checks: [
          'db/organizations.int › is the server’s override first, then the organization’s switch, then off',
        ],
      },
    ],
    note: 'Claude’s reading of your requirement that the time zone tells background work what day it is (FR-PLT-11). In US Central time a trip used to join about 31 hours after its day ended; with the time zone kept it is 24, plus up to an hour for the schedule.',
  },
  {
    id: 'US-ACC-10',
    title: 'Change the home currency from now on',
    as: 'the organization’s owner',
    want: 'to change the organization’s home currency',
    soThat:
      'new reports are in the currency we work in, without rewriting what was already claimed',
    feature: 'F-51',
    requirements: ['FR-PLT-11'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I change the home currency',
        when: 'a report opens afterwards',
        then: 'it is in the new currency',
        decided: { by: 'claude', source: 'ADR-0037' },
        checks: [
          'db/organizations.int › opens reports from then on in a new home currency, and leaves those opened before as they were',
        ],
      },
      {
        id: 'AC2',
        given: 'reports already opened, and expenses already filed',
        when: 'I change the home currency',
        then: 'they keep the currency they had, and no amount is converted or rewritten',
        decided: { by: 'claude', source: 'ADR-0037' },
        checks: [
          'db/organizations.int › opens reports from then on in a new home currency, and leaves those opened before as they were',
        ],
      },
      {
        id: 'AC3',
        given: 'a currency ExpenseWise doesn’t support',
        when: 'I choose it as the home currency',
        then: 'it is refused, and the home currency stays as it was',
        decided: { by: 'claude' },
        checks: ['domain/organization › refuses a value that isn’t one, naming the field'],
      },
    ],
    note: 'Claude’s choice, yours to overturn: a change applies only to what is worked out afterwards. Converting each amount to the currency a person is reimbursed in is #62’s, which starts from the organization’s currency.',
  },
  {
    id: 'US-TEAM-01',
    title: 'Invite someone by link, with a role',
    as: 'the organization’s owner',
    want: 'to make a link that lets one person join my organization with the role I choose',
    soThat: 'my team can file their expenses in my organization without my setting up email',
    feature: 'F-23',
    requirements: ['FR-PLT-07', 'FR-GOV-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I am the owner and Invite people is switched on',
        when: 'I make an invite link with a role, and a note of who it is for',
        then: 'I am shown the link once, to copy and send myself; no email is sent, and only a hash of its secret is kept',
        decided: OWNER_OCT_4,
        checks: [
          'api/people › makes an invite link with a role, showing its secret only once',
          'db/people.int › keeps only the hash of a link, lists it until used, and records who made it',
        ],
      },
      {
        id: 'AC2',
        given: 'an invite link',
        when: '7 days have passed since it was made, or it was used once',
        then: 'it no longer works',
        decided: { by: 'claude', source: 'ADR-0035' },
        rules: ['R-INVITE-DAYS'],
        checks: [
          'domain/people › work for 7 days from when they are made',
          'db/people.int › refuses a link that has expired or been revoked, or that names no invite',
          'db/people.int › joins a person with the link’s role, once',
        ],
      },
      {
        id: 'AC3',
        given: 'a link not used yet',
        when: 'I revoke it',
        then: 'it no longer works, and it leaves the list of links not used yet',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'api/people › makes an invite link with a role, showing its secret only once',
          'db/people.int › refuses a link that has expired or been revoked, or that names no invite',
        ],
      },
      {
        id: 'AC4',
        given: 'sign-ups are off',
        when: 'I open People to invite someone',
        then: 'it tells me to make their account in the Supabase dashboard first, then send them the link',
        decided: { by: 'blueprint', source: 'D-15' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'anyone in the organization but an owner',
        when: 'they try to see or manage people or invite links',
        then: 'they are refused',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: ['api/people › lets only an owner manage people'],
      },
      {
        id: 'AC6',
        given: 'Invite people is switched off',
        when: 'anyone opens Settings or an invite link',
        then: 'People isn’t offered, and its operations and every link answer as if they didn’t exist',
        decided: { by: 'owner', source: 'Q5' },
        checks: ['api/people › answers 404 feature_off while inviting people is switched off'],
      },
    ],
    note: 'Your choice of Oct 4: invite by link, not email (#27 isn’t needed). The screens are checked for layout and accessibility, not for their words.',
  },
  {
    id: 'US-TEAM-02',
    title: 'Join an organization by its link',
    as: 'Sam, who has been invited to a team',
    want: 'to open the link I was sent, see what it offers and join',
    soThat: 'I file my expenses in my team’s organization, with the role the owner gave me',
    feature: 'F-23',
    requirements: ['FR-PLT-07'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I am signed in and hold a link that still works',
        when: 'I open it and join',
        then: 'I see the organization and role it offers, and I join with that role',
        decided: OWNER_OCT_4,
        checks: [
          'api/people › shows the organization and role it offers, and where the person stands',
          'api/people › joins the signed-in person with its role',
          'db/people.int › joins a person with the link’s role, once',
        ],
      },
      {
        id: 'AC2',
        given: 'my first sign-in made an empty organization of my own',
        when: 'I join by a link',
        then: 'the empty organization is left behind, and I am told so before I join',
        decided: ADR16,
        checks: [
          'db/people.int › replaces the empty organization a first sign-in made',
          'api/own-records.int › works for its owner as before, and joining another replaces it while it is empty',
        ],
      },
      {
        id: 'AC3',
        given: 'my own organization has receipts, settings, links or other people in it',
        when: 'I try to join by a link',
        then: 'I am told I can’t with this account and why, and nothing changes',
        decided: ADR16,
        checks: [
          'db/people.int › refuses someone whose own organization has work in it, and changes nothing',
          'api/people › says why it can’t join: used, expired, revoked, already in, or work of their own',
        ],
      },
      {
        id: 'AC4',
        given:
          'a link that was used, has expired or was revoked, or that I am already in the organization of',
        when: 'I open it',
        then: 'it says so, and asks me to get a new link where one is needed',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'api/people › says why it can’t join: used, expired, revoked, already in, or work of their own',
          'db/people.int › refuses a link that has expired or been revoked, or that names no invite',
        ],
      },
      {
        id: 'AC5',
        given: 'I am not signed in',
        when: 'I open the link',
        then: 'it says the owner made my account, asks me to sign in, and brings me back to the link',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given: 'a link',
        when: 'the person holding it opens it',
        then: 'they see that one invite and nothing else of the organization until they join',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'db/people.int › shows the holder of a link that one invite and nothing else of the organization',
        ],
      },
      {
        id: 'AC7',
        given: 'an account with no email address',
        when: 'it tries to join',
        then: 'it is refused',
        decided: { by: 'claude' },
        checks: ['api/people › needs an account with an email address to join'],
      },
    ],
  },
  {
    id: 'US-TEAM-03',
    title: 'Change someone’s role',
    as: 'the organization’s owner',
    want: 'to give someone in my organization another role',
    soThat: 'what they can see and do follows what they do for the organization',
    feature: 'F-23',
    requirements: ['FR-PLT-07', 'FR-GOV-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I am the owner',
        when: 'I give someone another role in People',
        then: 'it takes effect from their next request, and the audit trail records the change',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'api/people › changes a role and removes a member, never leaving the organization without an owner',
          'db/people.int › changes a role, and never leaves the organization without an owner',
        ],
      },
      {
        id: 'AC2',
        given: 'the organization’s only owner',
        when: 'anyone would give them another role, or remove them',
        then: 'it is refused: the organization always has an owner',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'db/people.int › changes a role, and never leaves the organization without an owner',
          'domain/people › never leaves an organization without an owner',
          'api/people › changes a role and removes a member, never leaving the organization without an owner',
        ],
      },
    ],
  },
  {
    id: 'US-TEAM-04',
    title: 'Remove someone, keeping their records',
    as: 'the organization’s owner',
    want: 'to remove someone who has left',
    soThat: 'they can no longer reach our data, while what they claimed stays on the record',
    feature: 'F-23',
    requirements: ['FR-PLT-07'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a member',
        when: 'I remove them',
        then: 'they can no longer reach the organization, and their receipts, expenses, trips and history stay',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'db/people.int › removes a member, keeping their records, and lets them back in as the same member',
          'api/own-records.int › lets the owner remove a member, who then reaches nothing, with their records kept',
        ],
      },
      {
        id: 'AC2',
        given: 'I am an owner',
        when: 'I try to remove myself',
        then: 'it is refused; another owner can remove me',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'api/people › changes a role and removes a member, never leaving the organization without an owner',
        ],
      },
      {
        id: 'AC3',
        given: 'someone I removed',
        when: 'I invite them again and they join',
        then: 'they come back as the same member, with their records and the new role',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'db/people.int › removes a member, keeping their records, and lets them back in as the same member',
        ],
      },
    ],
  },
  {
    id: 'US-TEAM-05',
    title: 'Keep a record of who let whom in',
    as: 'an auditor, who checks who can reach the organization',
    want: 'every invite, join, role change and removal in the audit trail',
    soThat: 'I can tell who gave whom access, and when, without the links themselves being kept',
    feature: 'F-23',
    requirements: ['FR-PLT-07'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an invite made, used or revoked, a role changed, or someone removed',
        when: 'anyone later looks at the audit trail',
        then: 'it records what was done, by whom and when, and never the link’s secret',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/people.int › keeps only the hash of a link, lists it until used, and records who made it',
          'db/people.int › joins a person with the link’s role, once',
          'db/people.int › removes a member, keeping their records, and lets them back in as the same member',
          'db/people.int › changes a role, and never leaves the organization without an owner',
        ],
      },
      {
        id: 'AC2',
        given: 'someone leaves an empty organization of their own to join',
        when: 'anyone looks at that organization’s audit trail',
        then: 'it records that their sign-in moved out',
        decided: ADR16,
        checks: ['db/people.int › replaces the empty organization a first sign-in made'],
      },
    ],
  },
  {
    id: 'US-ACC-11',
    title: 'Add an authenticator app, and enter its code when I sign in',
    as: 'Alex, who travels for work',
    want: 'to add an authenticator app and be asked for its code each time I sign in',
    soThat: 'my password alone no longer opens my receipts and expenses',
    feature: 'F-11',
    requirements: ['FR-PLT-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'my organization has the second factor switched on',
        when: 'I open Sign-ins in Settings and add an authenticator app',
        then: 'I name it, scan its QR code or type its key into the app, and enter the 6-digit code it shows; it is then listed with its name and the day I added it',
        decided: ADR13,
        rules: ['R-SECOND-FACTOR-CODE'],
        checks: [
          'e2e/signed-in › adding an authenticator app',
          'domain/second-factor › is offered to everyone while it is on, and suggests a second to someone with one',
        ],
      },
      {
        id: 'AC2',
        given: 'I have an authenticator app, and my organization has the second factor switched on',
        when: 'I sign in with my email and password',
        then: 'before anything else I am asked for its code on a screen of its own, with a way to sign out instead, and the app opens once the code is right',
        decided: ADR42,
        checks: [
          'domain/second-factor › asks someone with an authenticator who signed in with a password alone, while it is on',
          'e2e/signed-in › the code asked for after signing in',
        ],
      },
      {
        id: 'AC3',
        given: 'the code I type',
        when: 'it isn’t 6 digits',
        then: 'it is refused before it is sent; spaces or a dash in it, as some apps show, are ignored',
        decided: ADR42,
        rules: ['R-SECOND-FACTOR-CODE'],
        checks: [
          'domain/second-factor › is 6 digits, read without the spaces or dash an app shows',
          'domain/second-factor › is refused when it is anything but 6 digits',
        ],
      },
      {
        id: 'AC4',
        given: 'my organization has the second factor switched off, or the server’s override has',
        when: 'I sign in, whether or not I added an authenticator app',
        then: 'no code is asked for',
        decided: ADR42,
        checks: [
          'domain/second-factor › asks no one while the second factor is switched off, whatever they enrolled',
        ],
      },
      {
        id: 'AC5',
        given: 'I have no authenticator app, or this session already passed the code',
        when: 'I sign in or open any screen',
        then: 'no code is asked for',
        decided: ADR13,
        checks: [
          'domain/second-factor › asks no one without an authenticator, and no one who already passed it',
        ],
      },
      {
        id: 'AC6',
        given: 'my organization has the second factor switched off',
        when: 'I open Sign-ins',
        then: 'adding an authenticator app is offered only if I am the owner, so I can pass it before switching it on; anyone who already has one still sees it, to remove it',
        decided: ADR42,
        checks: [
          'domain/second-factor › is offered to the owner alone while it is off, so the owner can pass it before switching it on',
          'domain/second-factor › still shows someone their own while it is off, to remove, without offering another',
        ],
      },
      {
        id: 'AC7',
        given: 'authenticator apps I have added',
        when: 'I have one, or 10',
        then: 'with one, the page suggests adding a second so losing a phone doesn’t lock me out; at 10 it offers no more',
        decided: ADR42,
        rules: ['R-AUTHENTICATORS-MAX'],
        checks: [
          'domain/second-factor › is offered to everyone while it is on, and suggests a second to someone with one',
          'domain/second-factor › stops at 10, Supabase Auth’s own limit',
        ],
      },
      {
        id: 'AC8',
        given: 'an authenticator app I added',
        when: 'I remove it, or add another',
        then: 'I am asked for the code first if this session hasn’t passed it, as Supabase Auth requires; a removed one’s codes no longer work',
        decided: ADR13,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC9',
        given: 'the code screen, opened on the way to a page',
        when: 'the code is right',
        then: 'it goes on to that page if it is on this site, and Home otherwise',
        decided: ADR42,
        checks: [
          'domain/second-factor › goes back to the page that asked, on this site only',
          'domain/second-factor › goes Home for anything else: no page, another site, or the sign-in screens',
        ],
      },
    ],
    note: 'Your decision of Oct 5 (Q40): the second factor is built behind its own switch. When the code is asked, and that the owner may add one before switching it on, are Claude’s (ADR-0042), yours to confirm. Supabase Auth keeps each authenticator’s secret and checks each code; no test talks to Supabase itself, so removing or adding another after the code is owed to #66. A token used against the API directly can still read without the code (GAP-33, Q41).',
  },
  {
    id: 'US-ACC-12',
    title: 'Enter my code before changing how the organization works',
    as: 'the organization’s owner',
    want: 'every change to our settings, people and keys to need the code from an authenticator app while the second factor is on',
    soThat:
      'a stolen password alone can’t change who works here, what is paid, or which keys spend our money',
    feature: 'F-11',
    requirements: ['FR-GOV-04'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'the second factor is switched on',
        when: 'an owner or finance admin whose session hasn’t passed the code makes any admin change: a feature switch, the organization’s details or duplicate window, people or invite links, an AI key or the AI models, the route key, a mileage rate, or a category or type',
        then: 'it is refused as needing the second factor, and nothing changes',
        decided: { by: 'blueprint', source: 'arch §6.9' },
        checks: [
          'api/second-factor › refuses every admin action from a password-only session, and does nothing',
          'api/second-factor › asks a finance admin for the code too, and still tells a member it isn’t theirs',
        ],
      },
      {
        id: 'AC2',
        given: 'the second factor is switched on',
        when: 'the same change comes from a session that passed the code',
        then: 'it goes through',
        decided: { by: 'blueprint', source: 'arch §6.9' },
        checks: [
          'api/second-factor › lets every admin action through once the session passed the code',
        ],
      },
      {
        id: 'AC3',
        given: 'the second factor is switched off, or the server’s override has it off',
        when: 'any admin change comes from a password alone',
        then: 'it goes through as before',
        decided: { by: 'owner', source: 'Q40' },
        checks: [
          'api/second-factor › lets every admin action through on a password alone, as before',
          'api/second-factor › asks for nothing while the server’s override has it off, whatever the switch says',
          'api/second-factor › lets the server’s override switch it off for everyone, the kill switch',
        ],
      },
      {
        id: 'AC4',
        given: 'I am the owner and my session hasn’t passed my own code',
        when: 'I switch the second factor on in Features',
        then: 'it is refused, I am told to add an authenticator app in Sign-ins and enter its code first, and nothing is switched, so no one is locked out',
        decided: ADR42,
        checks: [
          'api/second-factor › refuses an owner whose own session has not passed the code, and switches nothing',
        ],
      },
      {
        id: 'AC5',
        given: 'my session passed my own code',
        when: 'I switch the second factor on, and later off',
        then: 'it switches on, and from then on admin changes need the code; switching it off needs the code too',
        decided: ADR42,
        checks: [
          'api/second-factor › switches it on for an owner who passed the code, then asks it of every admin action',
          'api/second-factor › needs the code to switch it off again, so a password alone can’t undo it',
        ],
      },
      {
        id: 'AC6',
        given: 'an admin change refused as needing the second factor',
        when: 'the screen I made it on hears so',
        then: 'the code is asked for on a screen of its own, the page kept underneath; without an authenticator app it says where to add one',
        decided: ADR42,
        rules: ['R-SECOND-FACTOR-CODE'],
        checks: ['e2e/signed-in › the code asked for before an admin change'],
      },
      {
        id: 'AC7',
        given: 'the code asked for in the middle of an admin change',
        when: 'I enter it, or cancel',
        then: 'entered, the change carries on as if never stopped; cancelled, the page says the change needs the code',
        decided: ADR42,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC8',
        given: 'a member who is not an owner or finance admin',
        when: 'they try an admin change, with or without the code',
        then: 'they are refused, as it isn’t theirs to make',
        decided: { by: 'blueprint', source: 'arch §6.9' },
        checks: [
          'api/second-factor › asks a finance admin for the code too, and still tells a member it isn’t theirs',
        ],
      },
      {
        id: 'AC9',
        given: 'the second factor is switched on',
        when: 'an owner or finance admin reads settings with a password alone',
        then: 'they are shown as before: only changes need the code',
        decided: ADR42,
        checks: ['api/second-factor › leaves reading the settings to a password alone'],
      },
    ],
    note: 'FR-GOV-04’s other half, approving someone else’s spend, calls the same check with approval (#24). Which changes count as admin actions, and that reading settings doesn’t, are Claude’s (ADR-0042), yours to confirm. The code asked for in the middle of a change is checked for how it shows, not yet for carrying the change on (#66).',
  },
  {
    id: 'US-TEAM-06',
    title: 'Choose who approves each person’s reports',
    as: 'the organization’s owner',
    want: 'to choose in People who approves each person’s reports, or leave it on Automatic',
    soThat:
      'each claim reaches whoever knows that person’s work, once more than one of us approves',
    feature: 'F-18',
    requirements: ['FR-GOV-02', 'FR-GOV-03', 'FR-PLT-07'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I am the owner, and approval is on',
        when: 'I open People',
        then: 'each person shows who approves their reports, Automatic or the one I chose, and who their reports go to now; I choose from everyone else whose role may approve (an approver, finance admin or owner), or Automatic again',
        decided: { by: 'owner', source: 'Q42' },
        checks: [
          'api/people › shows who approves each person’s reports while approval is on, and whom an owner may choose',
          'api/people › chooses a member’s approver, and goes back to Automatic, each change audited once',
          'domain/approvals › offers anyone else who can approve, never the member themselves',
          'e2e/signed-in › people settings, with who approves each person’s reports, one chosen who can’t approve now',
        ],
      },
      {
        id: 'AC2',
        given: 'an approver I chose for a member, or Automatic',
        when: 'the member submits a report',
        then: 'it goes to the one I chose; on Automatic, to the longest-standing approver, then finance admin, then owner, as before',
        decided: { by: 'owner', source: 'Q42' },
        checks: [
          'domain/approvals › sends a report to the approver an owner chose, over the routing as built',
          'db/approval.int › sends a report to the approver chosen for its member, and keeps one already submitted with the approver it went to',
          'api/approval.int › sends a member’s report to the approver the owner chose, keeping one already submitted where it went',
        ],
      },
      {
        id: 'AC3',
        given: 'a report already submitted',
        when: 'I choose another approver for its member',
        then: 'it stays with the approver it went to, who still decides it; only reports submitted afterwards go to the new one',
        decided: { by: 'claude', source: 'ADR-0043' },
        checks: [
          'db/approval.int › sends a report to the approver chosen for its member, and keeps one already submitted with the approver it went to',
          'api/approval.int › sends a member’s report to the approver the owner chose, keeping one already submitted where it went',
        ],
      },
      {
        id: 'AC4',
        given: 'a member',
        when: 'I would choose them as their own approver, or someone whose role can’t approve, or someone removed',
        then: 'it is refused and nothing changes: no one approves their own reports, in the database too',
        decided: { by: 'blueprint', source: 'ADR-0001' },
        checks: [
          'db/people.int › never chooses a member themselves, or anyone who can’t approve, and changes nothing',
          'db/people.int › keeps the choice to the member’s own organization and never to themselves, in the database too',
          'api/people › refuses a member as their own approver, and anyone who can’t approve',
          'domain/approvals › never sends a member’s report to themselves, even if chosen, and finds no one when no one else can',
        ],
      },
      {
        id: 'AC5',
        given: 'the approver I chose for someone',
        when: 'their role changes so they can’t approve, or they are removed',
        then: 'that person’s reports go where Automatic finds, and People says the one chosen can’t approve now and who reports go to instead; given an approving role again, they are the one again',
        decided: { by: 'claude' },
        checks: [
          'domain/approvals › passes over a chosen approver whose role changed, finding one as built',
          'domain/approvals › passes over a chosen approver who was removed, finding one as built',
          'db/approval.int › passes over a chosen approver whose role changed or who was removed, routing as built',
          'api/people › says when the approver chosen can no longer approve, and finds one as Automatic does',
          'e2e/signed-in › people settings, with who approves each person’s reports, one chosen who can’t approve now',
        ],
      },
      {
        id: 'AC6',
        given: 'anyone in the organization but an owner',
        when: 'they try to choose someone’s approver',
        then: 'they are refused',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'api/people › lets only an owner choose',
          'api/approval.int › sends a member’s report to the approver the owner chose, keeping one already submitted where it went',
        ],
      },
      {
        id: 'AC7',
        given: 'my organization has the second factor switched on',
        when: 'I choose an approver in a session that hasn’t passed it',
        then: 'the code is asked for first, as for every admin action, and nothing changes until it is entered',
        decided: ADR42,
        checks: [
          'api/people › asks the owner for the second factor while it is on',
          'api/second-factor › refuses every admin action from a password-only session, and does nothing',
        ],
      },
      {
        id: 'AC8',
        given: 'a choice made, or Automatic chosen again',
        when: 'anyone later looks at the audit trail',
        then: 'it records who chose, for whom, and the approver before and after',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/people.int › chooses a member’s approver, and Automatic again, each change audited once',
        ],
      },
      {
        id: 'AC9',
        given: 'approval is switched off',
        when: 'I open People',
        then: 'it is exactly as before, and choosing an approver answers as if it weren’t there (feature_off)',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/people › leaves People exactly as it was while approval is off, and answers 404 feature_off',
          'api/approval.int › sends a member’s report to the approver the owner chose, keeping one already submitted where it went',
        ],
      },
    ],
    note: 'Your answer to Q42 (Oct 5): keep the routing as built, and let an owner choose each member’s approver now (#86). The choice is kept while the one chosen can’t approve, and used again once they can. That a report already submitted keeps its approver, what People says then, and that only an owner chooses, as an admin action, are Claude’s, yours to confirm.',
  },
];
