import type { Story } from '../model.ts';

const OCT3 = { by: 'owner', source: 'owner 2026-10-03' } as const;

/** Capture: camera, upload and PDF (F-05), and email-in (F-16). */
export const CAPTURE_STORIES: readonly Story[] = [
  {
    id: 'US-CAP-01',
    title: 'Capture a receipt with my camera or from a file',
    as: 'Alex, who travels for work',
    want: 'to take a photo of a receipt, or choose a picture or PDF of one, and have it filed',
    soThat: 'every receipt is kept the moment I have it, before it is lost or faded',
    feature: 'F-05',
    requirements: ['FR-CAP-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I am on Home',
        when: 'I tap Capture',
        then: 'the Receipts screen opens, where I can Take a photo or Upload a file',
        decided: { by: 'blueprint', source: 'capmap P1' },
        checks: ['e2e/receipts › opens from the Capture button on the home page', 'e2e/signed-in'],
      },
      {
        id: 'AC2',
        given: 'a photo I take, or a picture or PDF I choose, of 10 MB or less',
        when: 'I add it',
        then: 'it is filed as my receipt, marked as from the camera or an upload, and shows as Reading… until the models have read it',
        decided: { by: 'blueprint', source: 'capmap P1' },
        checks: [
          'api/receipts › hands out a one-time upload for a path inside the organization',
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
          'workflows/receipts › recognizes %s',
        ],
        rules: ['R-RECEIPT-SIZE'],
      },
      {
        id: 'AC3',
        given:
          'a file over 10 MB, or one that isn’t a JPEG, PNG, WebP, GIF or PDF, such as a web page',
        when: 'I add it',
        then: 'it is refused and nothing is filed',
        decided: { by: 'claude' },
        checks: ['api/receipts › rejects files over 10 MB and types it cannot read'],
        rules: ['R-RECEIPT-SIZE'],
      },
      {
        id: 'AC4',
        given: 'a photo my browser can open',
        when: 'I add it',
        then: 'before it leaves my device it is scaled to about 2,000 pixels on its long edge and saved as a JPEG, which drops the location saved in it; a PDF goes as it is',
        decided: { by: 'blueprint', source: 'ADR-0017' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'I am not signed in, or not yet in an organization',
        when: 'I open Receipts or try to file a receipt',
        then: 'I am asked to sign in, and nothing is shown or filed',
        decided: { by: 'claude' },
        checks: [
          'e2e/receipts › asks a signed-out visitor to sign in before showing any receipts',
          'e2e/receipts › refuses the receipt endpoints without a signed-in user',
          'api/receipts › needs storage, a signed-in user and an organization',
        ],
      },
      {
        id: 'AC6',
        given: 'receipts filed in my organization',
        when: 'anyone in another organization looks for them',
        then: 'they see none of them, and a receipt’s file is always stored under my organization’s own path, whatever the app asks for',
        decided: { by: 'blueprint', source: 'arch AP6' },
        checks: [
          'db/receipts.int › keeps receipts inside their organization',
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
        ],
      },
      {
        id: 'AC7',
        given: 'I file a receipt',
        when: 'it is saved',
        then: 'the receipt, its expense and the event that has it read are saved together, and the audit trail records that it was captured',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
          'db/receipts.int › records each model once per request, then settles once',
        ],
      },
    ],
    note: 'The 10 MB limit is kept in three places in the code: storage, the API and the capture screen. The rule register checks only the first, so a change must be made in all three.',
  },
  {
    id: 'US-CAP-02',
    title: 'Never wait while a receipt is read',
    as: 'Alex, who travels for work and captures receipts between meetings',
    want: 'capture to be finished as soon as the file is up, with the reading done afterwards',
    soThat: 'I can put my phone away straight after the photo',
    feature: 'F-05',
    requirements: ['NFR-PERF-02', 'FR-CAP-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I add a receipt',
        when: 'the app files it',
        then: 'the answer comes straight back with the receipt shown as Reading…; no model is asked while I wait, and the reading happens in the background',
        decided: { by: 'blueprint', source: 'arch AP3' },
        checks: [
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
        ],
      },
      {
        id: 'AC2',
        given: 'a photo or file I add',
        when: 'it is uploaded',
        then: 'it goes from my device straight to private storage, with a one-time upload good for one path in my organization, and never passes through the app’s API',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'api/receipts › hands out a one-time upload for a path inside the organization',
          'storage/supabase › creates the private bucket once, then signs uploads with the secret key',
        ],
      },
      {
        id: 'AC3',
        given: 'the service that reads receipts can’t be reached when I file one',
        when: 'I file it',
        then: 'it is still filed, and the event that has it read stays saved with it, so the receipt is not lost',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'api/receipts › still files the receipt when the runner is unreachable; the relay sends it later',
          'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
        ],
      },
      {
        id: 'AC4',
        given: 'the file in storage is not the one described when the receipt was filed',
        when: 'the receipt is read',
        then: 'no model is sent it, and it shows as Not read',
        decided: { by: 'blueprint', source: 'ADR-0017' },
        checks: [
          'workflows/receipts › reads nothing when the stored file is not the one described',
        ],
      },
    ],
    note: 'No test times the “about a second”; the tests prove that filing asks no model and does no slow work. The relay that sends an event the first hand-off missed isn’t running in production until #11, so until then such a receipt waits to be read again.',
  },
  {
    id: 'US-CAP-03',
    title: 'Never file the same file twice',
    as: 'Sam, a finance admin',
    want: 'a file that is already filed to be refused, wherever it comes from',
    soThat: 'one receipt is never claimed twice',
    feature: 'F-05',
    requirements: ['FR-INT-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a file already filed in my organization',
        when: 'someone adds the same file again',
        then: 'it is refused by its fingerprint before it is uploaded again, naming the receipt already filed',
        decided: { by: 'blueprint', source: 'arch §6.5' },
        checks: ['api/receipts › refuses a file that is already filed, before and after upload'],
      },
      {
        id: 'AC2',
        given: 'that refusal',
        when: 'the app receives it',
        then: 'it opens the receipt already filed instead of filing a copy',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given:
          'a second copy of a file that got past that first check, for example because both were added at once',
        when: 'it is filed',
        then: 'it is refused as a copy, naming the receipt filed first',
        decided: { by: 'claude' },
        checks: [
          'api/receipts › refuses a file that is already filed, before and after upload',
          'db/receipts.int › treats a retried request as done, and a second copy of a file as a duplicate',
        ],
      },
      {
        id: 'AC4',
        given: 'an emailed attachment, or an email’s text, that is already filed as a receipt',
        when: 'the email is filed',
        then: 'that file is not filed again',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: ['workflows/email › does not file a file that is already a receipt'],
      },
      {
        id: 'AC5',
        given: 'a file filed in another organization',
        when: 'someone files the same file in mine',
        then: 'it is filed: copies are looked for only within one organization',
        decided: { by: 'blueprint', source: 'arch AP6' },
        checks: ['db/receipts.int › keeps receipts inside their organization'],
      },
    ],
    note: 'Only a byte-for-byte identical file counts here. A receipt photographed twice, or an email forwarded again, makes a different file; FR-INT-18 holds those as possible duplicates. Before upload the app opens the earlier receipt without saying it was a copy; when a copy is refused after upload, the app says “This file is already filed” but doesn’t open it, although the answer names it.',
  },
  {
    id: 'US-CAP-04',
    title: 'Nothing filed twice when something is retried',
    as: 'Alex, who travels for work and often captures receipts on a patchy connection',
    want: 'anything my phone, the email service or the app sends again to change nothing',
    soThat: 'a retry never leaves me a second receipt, a second reading or a lost email',
    feature: 'F-05',
    requirements: ['NFR-DAT-06'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given:
          'my phone files a receipt and, after a dropped connection, sends the same filing again',
        when: 'the second one arrives',
        then: 'it is answered as already filed, with one receipt and one event to read it',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
          'db/receipts.int › treats a retried request as done, and a second copy of a file as a duplicate',
        ],
      },
      {
        id: 'AC2',
        given: 'a step that reads a receipt is retried',
        when: 'a model’s reading for the same request is saved again, or the receipt is settled again',
        then: 'each model’s reading is kept once, and the receipt settles once, with one audit entry',
        decided: { by: 'blueprint', source: 'ADR-0017' },
        checks: ['db/receipts.int › records each model once per request, then settles once'],
      },
      {
        id: 'AC3',
        given: 'an event handed to the workflow runner straight away and again by the outbox relay',
        when: 'both arrive',
        then: 'both carry the same event id, the outbox’s, so the runner takes them as one',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'workflows/relay › uses the outbox id as the event id and the change time as the timestamp',
          'workflows/relay › sends an event just committed under its outbox id, as the relay would',
        ],
      },
      {
        id: 'AC4',
        given:
          'an emailed receipt the email service delivers again, or a step that kept it is retried',
        when: 'it is kept again',
        then: 'nothing is filed twice, not even the PDF made from its text, and receipts still waiting to be read are handed on again',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'db/inbound.int › files nothing twice when the same message is delivered again',
          'workflows/email › files a verified member’s attachments as receipts, under ids made from the message',
          'workflows/email-pdf › is a PDF, the same bytes every time for the same email',
        ],
      },
      {
        id: 'AC5',
        given: 'an email arrives but can’t be handed on to be read',
        when: 'the email service delivers it',
        then: 'it is told to try again later, so the email is not lost',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: ['api/inbound › answers 503 so Bird tries again when the hand-off fails'],
      },
      {
        id: 'AC6',
        given: 'the key that proves an email’s sender can’t be looked up for now',
        when: 'the email is checked',
        then: 'the check is tried again later, rather than the email being treated as unproved',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: ['workflows/email › asks to be tried again when a key can’t be looked up for now'],
      },
    ],
  },
  {
    id: 'US-CAP-05',
    title: 'Email or forward a receipt',
    as: 'Alex, who travels for work and gets most receipts by email',
    want: 'to email or forward a receipt or purchase summary to the receipts address and have it filed like a photo',
    soThat: 'ride, airline, hotel and shop receipts reach my expenses without a screenshot',
    feature: 'F-16',
    requirements: ['FR-CAP-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given:
          'I email or forward a receipt attached as a PDF or photo, from an address I sign in with',
        when: 'it arrives',
        then: 'each attachment is filed as my receipt from email, with its expense, and read exactly as an upload is',
        decided: OCT3,
        checks: [
          'workflows/email › files a verified member’s attachments as receipts, under ids made from the message',
          'db/inbound.int › files each attachment as a receipt with its expense, and keeps the email, together',
          'workflows/email › keeps the email, then hands its receipts to the receipt workflow',
        ],
      },
      {
        id: 'AC2',
        given: 'an email with several things attached',
        when: 'its attachments are chosen',
        then: 'PDFs and pictures count by what they contain, not what they are labelled; logos and pictures that lay out the email are left out; each file counts once, none over 10 MB, and at most ten',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › takes PDFs and photos by their bytes, whatever they are labelled',
          'workflows/email › leaves out logos and pictures that lay out the email',
          'workflows/email › takes each file once, none over 10 MB, and at most ten',
        ],
        rules: ['R-EMAIL-RECEIPTS', 'R-RECEIPT-SIZE'],
      },
      {
        id: 'AC3',
        given:
          'an email with nothing attached that can be a receipt, such as an Uber, airline or hotel email',
        when: 'it arrives',
        then: 'the email’s own text is filed as the receipt and read like an upload',
        decided: OCT3,
        checks: [
          'workflows/email › files the email itself as a PDF receipt when nothing is attached',
        ],
      },
      {
        id: 'AC4',
        given: 'an email whose text is filed as the receipt',
        when: 'the text is laid out',
        then: 'it becomes a PDF of the HTML version’s text, each amount beside its label, with no pictures, links, styles or scripts, and at most five pages long',
        decided: { by: 'claude', source: 'ADR-0027' },
        checks: [
          'workflows/email-pdf › keeps each amount beside its label, without pictures, links, styles or scripts',
          'workflows/email › prefers the HTML to a plain part that only links to it',
          'workflows/email-pdf › runs on to further pages, wrapping long lines, and stops at five',
        ],
        rules: ['R-EMAIL-PDF-PAGES'],
      },
      {
        id: 'AC5',
        given: 'an email with a receipt attached and text as well',
        when: 'it arrives',
        then: 'only the attachments are filed, so one purchase is not filed twice',
        decided: { by: 'claude', source: 'ADR-0027' },
        checks: [
          'workflows/email › files the attachments, not the text, when something is attached',
        ],
      },
      {
        id: 'AC6',
        given: 'an email from me with no text and nothing attached',
        when: 'it arrives',
        then: 'nothing is filed, and only that it came is kept',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › keeps a verified email with no text and nothing attached, filing nothing',
          'db/inbound.int › keeps an email with nothing attached, or an unverified one, without receipts',
        ],
      },
      {
        id: 'AC7',
        given: 'an emailed purchase summary, such as an order confirmation',
        when: 'it is read',
        then: 'it is marked as a purchase summary and waits for my review in Needs you, however well it reads; an emailed receipt follows the same rule as a photo',
        decided: { by: 'owner', source: 'Q10' },
        checks: [
          'extraction/checks › always flags a purchase summary, however well it reads',
          'extraction/checks › never makes a purchase summary Ready on its own (Q10)',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC8',
        given: 'an email from me is kept',
        when: 'its receipts are filed',
        then: 'the receipts, their expenses and a record of the email are saved together, and the audit trail records that it arrived',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/inbound.int › files each attachment as a receipt with its expense, and keeps the email, together',
        ],
      },
    ],
    note: 'Forwarding by hand works; an automatic forwarding rule keeps the merchant’s address as the sender, so it isn’t filed (ADR-0026). A PDF made from an email is written in a font that covers Latin script: signs such as ₹ become their currency codes, and other scripts, such as Japanese, become question marks (ADR-0027). A longer email is cut at five pages, ending with a line saying the rest is left out. Nothing in the app shows the receipts address yet, and an email that filed nothing is shown nowhere until #59.',
  },
  {
    id: 'US-CAP-06',
    title: 'Only email that is provably mine is filed',
    as: 'Alex, who forwards receipts by email',
    want: 'only email that provably comes from one of my sign-in addresses to be filed in my name',
    soThat: 'nobody can put receipts into my claims by pretending to be me',
    feature: 'F-16',
    requirements: ['FR-CAP-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given:
          'an email from an address that isn’t one I sign in with, even another address of mine',
        when: 'it arrives',
        then: 'it is not filed: only the addresses I sign in with send receipts in',
        decided: { by: 'owner', source: 'Q17' },
        checks: [
          'workflows/email › keeps nothing from someone who is not a member',
          'db/inbound.int › finds the member who signs in with the address, in any case, and no one else',
        ],
      },
      {
        id: 'AC2',
        given: 'an email from someone who isn’t a member',
        when: 'it arrives',
        then: 'nothing about it is kept, not even that it came',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: ['workflows/email › keeps nothing from someone who is not a member'],
      },
      {
        id: 'AC3',
        given:
          'an email from my sign-in address, digitally signed (DKIM) by my address’s own domain or a domain of the same organization',
        when: 'it is checked',
        then: 'it counts as proved to be from me',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › trusts the From address when its own domain signed the message',
          'workflows/email › trusts a signature from another domain of the same organization',
        ],
      },
      {
        id: 'AC4',
        given:
          'an email that names my address as its sender but is unsigned, signed by some other domain such as a mailing service, changed after it was signed, or signed over only part of its text',
        when: 'it is checked',
        then: 'it is not proved as mine',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › does not trust an unsigned message, whatever its From says',
          'workflows/email › does not trust a signature by some other domain, such as a mailing service',
          'workflows/email › does not trust a message changed after it was signed',
          'workflows/email › does not trust a signature that leaves part of the body unsigned',
        ],
      },
      {
        id: 'AC5',
        given: 'an email from my address that isn’t proved',
        when: 'it arrives',
        then: 'nothing in it is filed, and only that it came is kept, with its subject but never its text or files',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › files nothing from an email it can’t verify, and keeps no body, only that it came',
          'db/inbound.int › keeps an email with nothing attached, or an unverified one, without receipts',
        ],
      },
      {
        id: 'AC6',
        given:
          'a call to the email-in address that the email service didn’t sign, signed for another body, or sent more than five minutes off, or one naming a message in a way that could change where it is fetched from',
        when: 'it arrives',
        then: 'it is refused and no email is fetched',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'api/inbound › refuses a delivery whose signature does not match its body',
          'api/inbound › refuses a delivery more than five minutes off',
          'api/inbound › refuses a message id that could change where the email is fetched from',
        ],
      },
      {
        id: 'AC7',
        given: 'emails kept for members of my organization',
        when: 'anyone in another organization looks',
        then: 'they see none of them, and finding who sent an email reveals nothing but which member it is',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'db/inbound.int › keeps emails inside their organization',
          'db/inbound.int › answers with ids only: the runtime still cannot read sign-ins outside an organization',
        ],
      },
    ],
    note: 'Bird’s own allowlist, which you set (Q16), is a first gate in front of these checks. An email that waits more than 30 days to be read can no longer be fetched or checked, so it is dropped (ADR-0026). An email from your address that isn’t proved is kept but shown nowhere until #59.',
  },
];
