import type { Story } from '../model.ts';

const OCT3 = { by: 'owner', source: 'owner 2026-10-03' } as const;

/** Capture: camera, upload and PDF (F-05), and email-in (F-16). */
export const CAPTURE_STORIES: readonly Story[] = [
  {
    id: 'US-CAP-01',
    title: 'Capture a receipt with my camera or from a file',
    as: 'Alex, who travels for work',
    want: 'to take a photo of a receipt, or choose a picture or PDF of one, and have it filed',
    soThat: 'every receipt is kept the moment I have it, before it is lost or faded',
    feature: 'F-05',
    requirements: ['FR-CAP-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I am on Home',
        when: 'I tap Capture',
        then: 'the Receipts screen opens, where I can Take a photo or Upload a file',
        decided: { by: 'blueprint', source: 'capmap P1' },
        checks: ['e2e/receipts › opens from the Capture button on the home page', 'e2e/signed-in'],
      },
      {
        id: 'AC2',
        given: 'a photo I take, or a picture or PDF I choose, of 10 MB or less',
        when: 'I add it',
        then: 'it is filed as my receipt, marked as from the camera or an upload, and shows as Reading… until the models have read it',
        decided: { by: 'blueprint', source: 'capmap P1' },
        checks: [
          'api/receipts › hands out a one-time upload for a path inside the organization',
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
          'workflows/receipts › recognizes %s',
        ],
        rules: ['R-RECEIPT-SIZE'],
      },
      {
        id: 'AC3',
        given:
          'a file over 10 MB, or one that isn’t a JPEG, PNG, WebP, GIF or PDF, such as a web page',
        when: 'I add it',
        then: 'it is refused and nothing is filed',
        decided: { by: 'claude' },
        checks: ['api/receipts › rejects files over 10 MB and types it cannot read'],
        rules: ['R-RECEIPT-SIZE'],
      },
      {
        id: 'AC4',
        given: 'a photo my browser can open',
        when: 'I add it',
        then: 'before it leaves my device it is scaled to about 2,000 pixels on its long edge and saved as a JPEG, which drops the location saved in it; a PDF goes as it is',
        decided: { by: 'blueprint', source: 'ADR-0017' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'I am not signed in, or not yet in an organization',
        when: 'I open Receipts or try to file a receipt',
        then: 'I am asked to sign in, and nothing is shown or filed',
        decided: { by: 'claude' },
        checks: [
          'e2e/receipts › asks a signed-out visitor to sign in before showing any receipts',
          'e2e/receipts › refuses the receipt endpoints without a signed-in user',
          'api/receipts › needs storage, a signed-in user and an organization',
        ],
      },
      {
        id: 'AC6',
        given: 'receipts filed in my organization',
        when: 'anyone in another organization looks for them',
        then: 'they see none of them, and a receipt’s file is always stored under my organization’s own path, whatever the app asks for',
        decided: { by: 'blueprint', source: 'arch AP6' },
        checks: [
          'db/receipts.int › keeps receipts inside their organization',
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
        ],
      },
      {
        id: 'AC7',
        given: 'I file a receipt',
        when: 'it is saved',
        then: 'the receipt, its expense and the event that has it read are saved together, and the audit trail records that it was captured',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
          'db/receipts.int › records each model once per request, then settles once',
        ],
      },
    ],
    note: 'The 10 MB limit is kept in three places in the code: storage, the API and the capture screen. The rule register checks only the first, so a change must be made in all three.',
  },
  {
    id: 'US-CAP-02',
    title: 'Never wait while a receipt is read',
    as: 'Alex, who travels for work and captures receipts between meetings',
    want: 'capture to be finished as soon as the file is up, with the reading done afterwards',
    soThat: 'I can put my phone away straight after the photo',
    feature: 'F-05',
    requirements: ['NFR-PERF-02', 'FR-CAP-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I add a receipt',
        when: 'the app files it',
        then: 'the answer comes straight back with the receipt shown as Reading…; no model is asked while I wait, and the reading happens in the background',
        decided: { by: 'blueprint', source: 'arch AP3' },
        checks: [
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
        ],
      },
      {
        id: 'AC2',
        given: 'a photo or file I add',
        when: 'it is uploaded',
        then: 'it goes from my device straight to private storage, with a one-time upload good for one path in my organization, and never passes through the app’s API',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'api/receipts › hands out a one-time upload for a path inside the organization',
          'storage/supabase › creates the private bucket once, then signs uploads with the secret key',
        ],
      },
      {
        id: 'AC3',
        given: 'the service that reads receipts can’t be reached when I file one',
        when: 'I file it',
        then: 'it is still filed, and the event that has it read stays saved with it, so the receipt is not lost',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'api/receipts › still files the receipt when the runner is unreachable; the relay sends it later',
          'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
        ],
      },
      {
        id: 'AC4',
        given: 'the file in storage is not the one described when the receipt was filed',
        when: 'the receipt is read',
        then: 'no model is sent it, and it shows as Not read',
        decided: { by: 'blueprint', source: 'ADR-0017' },
        checks: [
          'workflows/receipts › reads nothing when the stored file is not the one described',
        ],
      },
    ],
    note: 'No test times the “about a second”; the tests prove that filing asks no model and does no slow work. The relay that sends an event the first hand-off missed isn’t running in production until #11, so until then such a receipt waits to be read again.',
  },
  {
    id: 'US-CAP-03',
    title: 'Never file the same file twice',
    as: 'Sam, a finance admin',
    want: 'a file that is already filed to be refused, wherever it comes from',
    soThat: 'one receipt is never claimed twice',
    feature: 'F-05',
    requirements: ['FR-INT-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a file already filed in my organization',
        when: 'someone adds the same file again',
        then: 'it is refused by its fingerprint before it is uploaded again, naming the receipt already filed',
        decided: { by: 'blueprint', source: 'arch §6.5' },
        checks: ['api/receipts › refuses a file that is already filed, before and after upload'],
      },
      {
        id: 'AC2',
        given: 'that refusal',
        when: 'the app receives it',
        then: 'it opens the receipt already filed instead of filing a copy',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given:
          'a second copy of a file that got past that first check, for example because both were added at once',
        when: 'it is filed',
        then: 'it is refused as a copy, naming the receipt filed first',
        decided: { by: 'claude' },
        checks: [
          'api/receipts › refuses a file that is already filed, before and after upload',
          'db/receipts.int › treats a retried request as done, and a second copy of a file as a duplicate',
        ],
      },
      {
        id: 'AC4',
        given: 'an emailed attachment, or an email’s text, that is already filed as a receipt',
        when: 'the email is filed',
        then: 'that file is not filed again',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: ['workflows/email › does not file a file that is already a receipt'],
      },
      {
        id: 'AC5',
        given: 'a file filed in another organization',
        when: 'someone files the same file in mine',
        then: 'it is filed: copies are looked for only within one organization',
        decided: { by: 'blueprint', source: 'arch AP6' },
        checks: ['db/receipts.int › keeps receipts inside their organization'],
      },
    ],
    note: 'Only a byte-for-byte identical file counts here. A receipt photographed twice, or an email forwarded again, makes a different file; FR-INT-18 holds those as possible duplicates. Before upload the app opens the earlier receipt without saying it was a copy; when a copy is refused after upload, the app says “This file is already filed” but doesn’t open it, although the answer names it.',
  },
  {
    id: 'US-CAP-04',
    title: 'Nothing filed twice when something is retried',
    as: 'Alex, who travels for work and often captures receipts on a patchy connection',
    want: 'anything my phone, the email service or the app sends again to change nothing',
    soThat: 'a retry never leaves me a second receipt, a second reading or a lost email',
    feature: 'F-05',
    requirements: ['NFR-DAT-06'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given:
          'my phone files a receipt and, after a dropped connection, sends the same filing again',
        when: 'the second one arrives',
        then: 'it is answered as already filed, with one receipt and one event to read it',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
          'db/receipts.int › treats a retried request as done, and a second copy of a file as a duplicate',
        ],
      },
      {
        id: 'AC2',
        given: 'a step that reads a receipt is retried',
        when: 'a model’s reading for the same request is saved again, or the receipt is settled again',
        then: 'each model’s reading is kept once, and the receipt settles once, with one audit entry',
        decided: { by: 'blueprint', source: 'ADR-0017' },
        checks: ['db/receipts.int › records each model once per request, then settles once'],
      },
      {
        id: 'AC3',
        given: 'an event handed to the workflow runner straight away and again by the outbox relay',
        when: 'both arrive',
        then: 'both carry the same event id, the outbox’s, so the runner takes them as one',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'workflows/relay › uses the outbox id as the event id and the change time as the timestamp',
          'workflows/relay › sends an event just committed under its outbox id, as the relay would',
        ],
      },
      {
        id: 'AC4',
        given:
          'an emailed receipt the email service delivers again, or a step that kept it is retried',
        when: 'it is kept again',
        then: 'nothing is filed twice, not even the PDF made from its text, and receipts still waiting to be read are handed on again',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'db/inbound.int › files nothing twice when the same message is delivered again',
          'workflows/email › files a verified member’s attachments as receipts, under ids made from the message',
          'workflows/email-pdf › is a PDF, the same bytes every time for the same email',
        ],
      },
      {
        id: 'AC5',
        given: 'an email arrives but can’t be handed on to be read',
        when: 'the email service delivers it',
        then: 'it is told to try again later, so the email is not lost',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: ['api/inbound › answers 503 so Bird tries again when the hand-off fails'],
      },
      {
        id: 'AC6',
        given: 'the key that proves an email’s sender can’t be looked up for now',
        when: 'the email is checked',
        then: 'the check is tried again later, rather than the email being treated as unproved',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: ['workflows/email › asks to be tried again when a key can’t be looked up for now'],
      },
    ],
  },
  {
    id: 'US-CAP-05',
    title: 'Email or forward a receipt',
    as: 'Alex, who travels for work and gets most receipts by email',
    want: 'to email or forward a receipt or purchase summary to the receipts address and have it filed like a photo',
    soThat: 'ride, airline, hotel and shop receipts reach my expenses without a screenshot',
    feature: 'F-16',
    requirements: ['FR-CAP-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given:
          'I email or forward a receipt attached as a PDF or photo, from an address I sign in with',
        when: 'it arrives',
        then: 'each attachment is filed as my receipt from email, with its expense, and read exactly as an upload is',
        decided: OCT3,
        checks: [
          'workflows/email › files a verified member’s attachments as receipts, under ids made from the message',
          'db/inbound.int › files each attachment as a receipt with its expense, and keeps the email, together',
          'workflows/email › keeps the email, then hands its receipts to the receipt workflow',
        ],
      },
      {
        id: 'AC2',
        given: 'an email with several things attached',
        when: 'its attachments are chosen',
        then: 'PDFs and pictures count by what they contain, not what they are labelled; logos and pictures that lay out the email are left out; each file counts once, none over 10 MB, and at most ten',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › takes PDFs and photos by their bytes, whatever they are labelled',
          'workflows/email › leaves out logos and pictures that lay out the email',
          'workflows/email › takes each file once, none over 10 MB, and at most ten',
        ],
        rules: ['R-EMAIL-RECEIPTS', 'R-RECEIPT-SIZE'],
      },
      {
        id: 'AC3',
        given:
          'an email with nothing attached that can be a receipt, such as an Uber, airline or hotel email',
        when: 'it arrives',
        then: 'the email’s own text is filed as the receipt and read like an upload',
        decided: OCT3,
        checks: [
          'workflows/email › files the email itself as a PDF receipt when nothing is attached',
        ],
      },
      {
        id: 'AC4',
        given: 'an email whose text is filed as the receipt',
        when: 'the text is laid out',
        then: 'it becomes a PDF of the HTML version’s text, each amount beside its label, with no pictures, links, styles or scripts, and at most five pages long',
        decided: { by: 'claude', source: 'ADR-0027' },
        checks: [
          'workflows/email-pdf › keeps each amount beside its label, without pictures, links, styles or scripts',
          'workflows/email › prefers the HTML to a plain part that only links to it',
          'workflows/email-pdf › runs on to further pages, wrapping long lines, and stops at five',
        ],
        rules: ['R-EMAIL-PDF-PAGES'],
      },
      {
        id: 'AC5',
        given: 'an email with a receipt attached and text as well',
        when: 'it arrives',
        then: 'only the attachments are filed, so one purchase is not filed twice',
        decided: { by: 'claude', source: 'ADR-0027' },
        checks: [
          'workflows/email › files the attachments, not the text, when something is attached',
        ],
      },
      {
        id: 'AC6',
        given: 'an email from me with no text and nothing attached',
        when: 'it arrives',
        then: 'nothing is filed, and only that it came is kept',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › keeps a verified email with no text and nothing attached, filing nothing',
          'db/inbound.int › keeps an email with nothing attached, or an unverified one, without receipts',
        ],
      },
      {
        id: 'AC7',
        given: 'an emailed purchase summary, such as an order confirmation',
        when: 'it is read',
        then: 'it is marked as a purchase summary and waits for my review in Needs you, however well it reads; an emailed receipt follows the same rule as a photo',
        decided: { by: 'owner', source: 'Q10' },
        checks: [
          'extraction/checks › always flags a purchase summary, however well it reads',
          'extraction/checks › never makes a purchase summary Ready on its own (Q10)',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC8',
        given: 'an email from me is kept',
        when: 'its receipts are filed',
        then: 'the receipts, their expenses and a record of the email are saved together, and the audit trail records that it arrived',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/inbound.int › files each attachment as a receipt with its expense, and keeps the email, together',
        ],
      },
    ],
    note: 'Forwarding by hand works; an automatic forwarding rule keeps the merchant’s address as the sender, so it isn’t filed (ADR-0026). A PDF made from an email is written in a font that covers Latin script: signs such as ₹ become their currency codes, and other scripts, such as Japanese, become question marks (ADR-0027). A longer email is cut at five pages, ending with a line saying the rest is left out. Nothing in the app shows the receipts address yet. Since PR #60 an email that filed nothing shows in Needs you, while Emails that filed nothing is on (US-INBOX-02).',
  },
  {
    id: 'US-CAP-06',
    title: 'Only email that is provably mine is filed',
    as: 'Alex, who forwards receipts by email',
    want: 'only email that provably comes from one of my sign-in addresses to be filed in my name',
    soThat: 'nobody can put receipts into my claims by pretending to be me',
    feature: 'F-16',
    requirements: ['FR-CAP-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given:
          'an email from an address that isn’t one I sign in with, even another address of mine',
        when: 'it arrives',
        then: 'it is not filed: only the addresses I sign in with send receipts in',
        decided: { by: 'owner', source: 'Q17' },
        checks: [
          'workflows/email › keeps nothing from someone who is not a member',
          'db/inbound.int › finds the member who signs in with the address, in any case, and no one else',
        ],
      },
      {
        id: 'AC2',
        given: 'an email from someone who isn’t a member',
        when: 'it arrives',
        then: 'nothing about it is kept, not even that it came',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: ['workflows/email › keeps nothing from someone who is not a member'],
      },
      {
        id: 'AC3',
        given:
          'an email from my sign-in address, digitally signed (DKIM) by my address’s own domain or a domain of the same organization',
        when: 'it is checked',
        then: 'it counts as proved to be from me',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › trusts the From address when its own domain signed the message',
          'workflows/email › trusts a signature from another domain of the same organization',
        ],
      },
      {
        id: 'AC4',
        given:
          'an email that names my address as its sender but is unsigned, signed by some other domain such as a mailing service, changed after it was signed, or signed over only part of its text',
        when: 'it is checked',
        then: 'it is not proved as mine',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › does not trust an unsigned message, whatever its From says',
          'workflows/email › does not trust a signature by some other domain, such as a mailing service',
          'workflows/email › does not trust a message changed after it was signed',
          'workflows/email › does not trust a signature that leaves part of the body unsigned',
        ],
      },
      {
        id: 'AC5',
        given: 'an email from my address that isn’t proved',
        when: 'it arrives',
        then: 'nothing in it is filed, and only that it came is kept, with its subject but never its text or files',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'workflows/email › files nothing from an email it can’t verify, and keeps no body, only that it came',
          'db/inbound.int › keeps an email with nothing attached, or an unverified one, without receipts',
        ],
      },
      {
        id: 'AC6',
        given:
          'a call to the email-in address that the email service didn’t sign, signed for another body, or sent more than five minutes off, or one naming a message in a way that could change where it is fetched from',
        when: 'it arrives',
        then: 'it is refused and no email is fetched',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'api/inbound › refuses a delivery whose signature does not match its body',
          'api/inbound › refuses a delivery more than five minutes off',
          'api/inbound › refuses a message id that could change where the email is fetched from',
        ],
      },
      {
        id: 'AC7',
        given: 'emails kept for members of my organization',
        when: 'anyone in another organization looks',
        then: 'they see none of them, and finding who sent an email reveals nothing but which member it is',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'db/inbound.int › keeps emails inside their organization',
          'db/inbound.int › answers with ids only: the runtime still cannot read sign-ins outside an organization',
        ],
      },
      {
        id: 'AC8',
        given: 'an email from my address that isn’t proved',
        when: 'it is kept',
        then: 'why it wasn’t proved is kept with it: unsigned, signed by another domain, changed after it was signed, or signed over only part of it, so Needs you can say so',
        decided: { by: 'claude' },
        checks: [
          'workflows/email › keeps why it couldn’t prove the sender, such as a message changed after it was signed',
          'db/inbound.int › keeps why a sender wasn’t proved only for an unproved email, and dismisses none filed',
        ],
      },
    ],
    note: 'Bird’s own allowlist, which you set (Q16), is a first gate in front of these checks. An email that waits more than 30 days to be read can no longer be fetched or checked, so it is dropped (ADR-0026). Since PR #60 an email from your address that isn’t proved shows in your Needs you with why, while Emails that filed nothing is on (US-INBOX-02).',
  },
  {
    id: 'US-MILE-01',
    title: 'Log a business drive',
    as: 'Riley, a solo professional who drives to clients',
    want: 'to log a business drive with its date, destination, purpose and miles',
    soThat:
      'it is claimed at the rate in force that day, with the evidence IRS Publication 463 asks for, and no log to rebuild at tax time',
    feature: 'F-13',
    requirements: ['FR-CAP-03'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'mileage switched on for my organization',
        when: 'I add a drive with its date, destination, business purpose and miles',
        then: 'it becomes a Ready expense of mine for miles × the rate in force on its date, rounded half-up to the cent, and the audit trail records it with that rate',
        decided: { by: 'blueprint', source: 'journeys §4.3' },
        checks: [
          'domain/mileage › claims miles times the rate on the day, rounded half-up to the cent',
          'db/mileage.int › logs a drive as a Ready expense of miles times the rate on the day, with the rate copied on',
          'api/mileage › logs a drive for the caller and answers with it as an expense, its rate copied on',
        ],
      },
      {
        id: 'AC2',
        given: 'the Add mileage form',
        when: 'I enter a date and miles',
        then: 'it shows what the drive pays and the rate it is paid at, before I save',
        decided: { by: 'claude', source: 'ADR-0038' },
        checks: [
          'api/mileage › quotes what a drive would pay before it is logged',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC3',
        given:
          'a field left empty, miles of zero, more than two decimal places or more than 1,000 miles, or a purpose of more than 500 characters',
        when: 'I add the drive',
        then: 'it is refused, naming the field, and nothing is logged',
        decided: { by: 'claude', source: 'ADR-0038' },
        rules: ['R-MILEAGE-MAX', 'R-JUSTIFICATION-MAX'],
        checks: [
          'domain/mileage › refuses %o, naming the field %s',
          'db/mileage.int › refuses a drive that is not valid, and records nothing',
          'api/mileage › names the field that is not valid, and logs nothing',
        ],
      },
      {
        id: 'AC4',
        given:
          'a date more than a day after today, before 1 Jan 2022, or after the last day ExpenseWise knows the rate for',
        when: 'I add the drive',
        then: 'it is refused, naming the date, rather than paid at a rate that wasn’t in force that day',
        decided: { by: 'claude', source: 'ADR-0038' },
        rules: ['R-MILEAGE-AHEAD', 'R-MILEAGE-RATE'],
        checks: [
          'domain/mileage › has no rate before the first it holds, or after the last day it knows',
          'domain/mileage › takes a date a day ahead, for a time zone ahead of UTC, and up to the most miles',
          'api/mileage › names the field that is not valid, and logs nothing',
        ],
      },
    ],
    note: 'Add mileage is on the Expenses page. Miles only: kilometres and routes come with route-based mileage (#20). It pays the IRS business rate by default, as your answer to Q28 confirms, or your organization’s own rate a mile, set in Settings › Mileage (US-MILE-11).',
  },
  {
    id: 'US-MILE-02',
    title: 'A drive keeps the rate it was paid at',
    as: 'Riley, a solo professional who self-attests',
    want: 'each drive to keep the rate it was paid at',
    soThat: 'a later rate never changes a claim already made',
    feature: 'F-13',
    requirements: ['NFR-DAT-04', 'FR-CAP-03'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a drive I logged',
        when: 'the rates change later',
        then: 'it keeps its rate, the rate’s currency, the day it took effect and where it came from, and its amount',
        decided: { by: 'blueprint', source: 'journeys §4.3' },
        checks: [
          'db/mileage.int › keeps the rate it was logged at when the rates change later',
          'domain/mileage › snapshots the rate it used',
        ],
      },
      {
        id: 'AC2',
        given: 'a drive’s date, with no rate of my organization’s own in force on it',
        when: 'its rate is chosen',
        then: 'it is the IRS business rate that took effect on or before that date: 70 cents a mile on 31 Dec 2025, 72.5 cents from 1 Jan 2026',
        decided: { by: 'claude', source: 'ADR-0038' },
        rules: ['R-MILEAGE-RATE'],
        checks: [
          'domain/mileage › pays the IRS business rate in force on the travel date',
          'domain/mileage › uses the rate in force on the travel date',
        ],
      },
    ],
    note: 'The rate is copied onto the drive’s mileage log with its currency, effective date and source (NFR-DAT-04).',
  },
  {
    id: 'US-MILE-03',
    title: 'A drive is claimed like any expense',
    as: 'Alex, who travels for work',
    want: 'a drive to list, file to its trip and join its report like any other expense',
    soThat: 'my trip’s report and its totals include my miles without a second list',
    feature: 'F-13',
    requirements: ['FR-CAP-03'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a drive dated inside one of my trips',
        when: 'I add it',
        then: 'it files to that trip, counts in the trip’s totals, and lists among my expenses marked as mileage',
        decided: { by: 'blueprint', source: 'ADR-0023' },
        checks: [
          'db/mileage.int › files a drive to the trip its date falls in, and counts it in the trip’s totals',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'a drive on a trip',
        when: 'the trip joins its report',
        then: 'the drive is on the report with it and counts in its totals',
        decided: { by: 'blueprint', source: 'ADR-0029' },
        checks: [
          'db/mileage.int › joins its trip’s report, and a local drive joins one with its purpose as its reason',
        ],
      },
      {
        id: 'AC3',
        given: 'a drive on no trip',
        when: 'it joins a report 24 hours after its day',
        then: 'its business purpose is its reason, so it never holds the report open for one',
        decided: { by: 'claude', source: 'ADR-0038' },
        checks: [
          'db/mileage.int › joins its trip’s report, and a local drive joins one with its purpose as its reason',
        ],
      },
    ],
  },
  {
    id: 'US-MILE-04',
    title: 'Correct a drive before it is submitted',
    as: 'Riley, a solo professional who self-attests',
    want: 'to correct a drive’s date, destination, purpose or miles until I submit it',
    soThat: 'a mistake is fixed before anyone approves it, and an approved claim never changes',
    feature: 'F-13',
    requirements: ['FR-CAP-03', 'NFR-DAT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a Ready drive',
        when: 'I change its miles or its date',
        then: 'its amount is worked out again at the rate in force on its date, that rate is copied on afresh, and the audit trail records the change with both amounts',
        decided: { by: 'claude', source: 'ADR-0038' },
        checks: [
          'domain/mileage › works the amount out again, at the rate on the new date, when the miles or date change',
          'db/mileage.int › prices it again at the rate on its new date or for its new miles, and files it again by date',
          'api/mileage › corrects a drive, pricing it again when its miles change',
        ],
      },
      {
        id: 'AC2',
        given: 'a Ready drive',
        when: 'I change only its destination or purpose',
        then: 'its rate and amount stay as they are',
        decided: { by: 'claude', source: 'ADR-0038' },
        checks: [
          'domain/mileage › keeps the rate it has when only where or why changes, and sees no change in the same miles',
          'db/mileage.int › keeps the rate it was logged at when the rates change later',
        ],
      },
      {
        id: 'AC3',
        given: 'a drive given a new date',
        when: 'I save it',
        then: 'it files again to the trip that date falls in, or to none',
        decided: { by: 'blueprint', source: 'ADR-0023' },
        checks: [
          'db/mileage.int › prices it again at the rate on its new date or for its new miles, and files it again by date',
        ],
      },
      {
        id: 'AC4',
        given: 'a drive that is submitted or approved',
        when: 'I try to change it',
        then: 'it is refused: an approved drive is corrected by a reversal',
        decided: { by: 'blueprint', source: 'journeys §4.5' },
        checks: [
          'db/mileage.int › refuses a change once it is submitted, and refuses editing it as an ordinary expense',
          'api/mileage › refuses a change once the drive is submitted',
        ],
      },
      {
        id: 'AC5',
        given: 'a drive',
        when: 'anyone edits its amount, merchant or date as an ordinary expense',
        then: 'it is refused, so its amount is always its miles × its rate',
        decided: { by: 'claude', source: 'ADR-0038' },
        checks: [
          'db/mileage.int › refuses a change once it is submitted, and refuses editing it as an ordinary expense',
          'api/mileage › refuses editing a drive as an ordinary expense',
        ],
      },
      {
        id: 'AC6',
        given: 'a drive on no trip',
        when: 'I change its reason on its expense or its report',
        then: 'its business purpose changes with it, and it can’t be cleared',
        decided: { by: 'claude', source: 'ADR-0038' },
        rules: ['R-JUSTIFICATION-MAX'],
        checks: [
          'db/mileage.int › changes its business purpose when its reason changes on its report, and never clears it',
        ],
      },
    ],
  },
  {
    id: 'US-MILE-05',
    title: 'Mileage shows only when switched on, and only my own drives',
    as: 'Riley, a solo professional who self-attests',
    want: 'mileage out of sight until I switch it on, and my drives mine alone',
    soThat:
      'I can check it on my phone before relying on it, and nobody else opens or changes my claims',
    feature: 'F-13',
    requirements: ['FR-CAP-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'mileage switched off for my organization, as it is until its owner switches it on',
        when: 'anyone calls the mileage operations',
        then: 'each answers as if it did not exist, and nothing is logged',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/mileage › answers 404 feature_off to every mileage operation when it is off (%s)',
        ],
      },
      {
        id: 'AC2',
        given: 'mileage switched off',
        when: 'I open Expenses, Add mileage or a drive’s expense',
        then: 'Add mileage and the drive’s details are not shown, and Add mileage says the feature is off',
        decided: { by: 'owner', source: 'Q5' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'another member’s drive',
        when: 'I open it or change it',
        then: 'it is not found',
        decided: { by: 'claude' },
        checks: [
          'db/mileage.int › finds no other member’s drive, to open or to change',
          'api/mileage › opens and changes only the caller’s own drives',
        ],
      },
      {
        id: 'AC4',
        given: 'drives in another organization',
        when: 'anyone in mine looks',
        then: 'they see none of them',
        decided: { by: 'blueprint', source: 'ADR-0001' },
        checks: ['db/mileage.int › keeps drives inside their organization'],
      },
      {
        id: 'AC5',
        given: 'I am signed out',
        when: 'I open Add mileage or call its operations',
        then: 'I am asked to sign in, and every operation is refused',
        decided: { by: 'claude' },
        checks: [
          'e2e/expenses › asks a signed-out visitor to sign in before adding mileage, and refuses its endpoints',
        ],
      },
    ],
    note: 'The end-to-end bench switches every feature on, so no test yet opens the screens with mileage off (#66). A drive logged while mileage was on stays an expense when it is switched off: it is money already claimed, so it still lists and counts, with its drive details hidden.',
  },
  {
    id: 'US-MILE-11',
    title: 'Pay drives at our own rate a mile',
    as: 'Sam, a finance admin',
    want: 'to pay drives at our organization’s own rate a mile from a day I choose, or at the IRS business rate',
    soThat:
      'what we reimburse for miles is our policy, in our currency, and a claim already made never changes',
    feature: 'F-13',
    requirements: ['FR-CAP-03', 'NFR-DAT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'mileage switched on, and no rate of our own set',
        when: 'a drive is logged or quoted',
        then: 'it is paid at the IRS business rate on its date',
        decided: { by: 'owner', source: 'Q28' },
        rules: ['R-MILEAGE-RATE'],
        checks: [
          'domain/mileage › pays its own rate from the day it takes effect, and the IRS rate before it',
          'api/mileage-rates › shows every member the rate in force today, where it comes from, and each change',
        ],
      },
      {
        id: 'AC2',
        given: 'I am an owner or a finance admin',
        when: 'I set our own rate a mile from a day',
        then: 'drives dated from that day on are paid at it, in our home currency, and each copies it on with its source, our organization; drives dated before it keep the rate before it',
        decided: { by: 'owner', source: 'Q28' },
        checks: [
          'domain/mileage › pays its own rate from the day it takes effect, and the IRS rate before it',
          'db/mileage-rates.int › sets its own rate a mile from a day, in its home currency, each change in the audit trail',
          'db/mileage-rates.int › logs and corrects a drive at its own rate, copied on with source organization',
          'api/mileage-rates › lets an owner or finance admin set their own rate from a day, or go back to the IRS rate',
        ],
      },
      {
        id: 'AC3',
        given: 'our own rate is set',
        when: 'I go back to the IRS rate from a day',
        then: 'drives dated from that day on are paid at the IRS business rate again',
        decided: { by: 'owner', source: 'Q28' },
        checks: [
          'domain/mileage › goes back to the IRS rate from the day it switches back',
          'db/mileage-rates.int › goes back to the IRS rate from a day, and refuses a rate that is not valid',
          'api/mileage-rates › lets an owner or finance admin set their own rate from a day, or go back to the IRS rate',
        ],
      },
      {
        id: 'AC4',
        given: 'our own rate is in force',
        when: 'a drive is dated after the last day ExpenseWise knows the IRS rate for, such as in 2027',
        then: 'it is paid at our own rate, which has no last day; at the IRS rate it would be refused until that year’s rate is added',
        decided: { by: 'claude' },
        rules: ['R-MILEAGE-RATE'],
        checks: [
          'domain/mileage › pays its own rate in 2027, which has no last day known, and the IRS rate there only once known',
          'api/mileage-rates › quotes a drive at the organization’s own rate, which has no last day known',
        ],
      },
      {
        id: 'AC5',
        given: 'a drive already logged',
        when: 'the rate changes later',
        then: 'it keeps the rate it was paid at and its amount, unless its date or miles change, when it is priced again at the rate then in force on its date',
        decided: { by: 'blueprint', source: 'journeys §4.3' },
        checks: [
          'db/mileage-rates.int › keeps a drive’s rate when the organization’s rate changes later',
          'db/mileage-rates.int › logs and corrects a drive at its own rate, copied on with source organization',
        ],
      },
      {
        id: 'AC6',
        given:
          'a rate of zero, a negative one, one of more than 4 decimal places, or a day that doesn’t exist',
        when: 'I save the change',
        then: 'it is refused, naming the rate or the day, and nothing changes',
        decided: { by: 'claude' },
        rules: ['R-MILEAGE-OWN-RATE'],
        checks: [
          'domain/mileage › refuses a change from %s at %s, naming the field %s',
          'db/mileage-rates.int › goes back to the IRS rate from a day, and refuses a rate that is not valid',
          'api/mileage-rates › names the field that is not valid, and sets nothing',
        ],
      },
      {
        id: 'AC7',
        given: 'I am neither an owner nor a finance admin',
        when: 'I try to change the rate',
        then: 'I am refused, and I can still see the rate in force and its changes',
        decided: { by: 'claude' },
        checks: [
          'api/mileage-rates › refuses %s, who is neither an owner nor a finance admin, and changes nothing',
          'api/mileage-rates › shows every member the rate in force today, where it comes from, and each change',
        ],
      },
      {
        id: 'AC8',
        given: 'a change to the rate',
        when: 'it is saved',
        then: 'the audit trail records who set what from which day, and what it replaced; setting a day to what it already has records nothing, and setting a day again replaces its change',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/mileage-rates.int › sets its own rate a mile from a day, in its home currency, each change in the audit trail',
        ],
      },
      {
        id: 'AC9',
        given: 'Settings › Mileage',
        when: 'I open it',
        then: 'it shows the rate in force today and where it comes from, each change with its day and who set it, and, for an owner or finance admin, a form to set our own rate from a day or go back to the IRS rate',
        decided: { by: 'claude' },
        checks: [
          'e2e/signed-in › mileage settings, with the rate a mile and its changes',
          'e2e/signed-in › setting your own rate a mile',
          'e2e/signed-in › going back to the IRS rate a mile',
        ],
      },
      {
        id: 'AC10',
        given: 'mileage switched off for my organization',
        when: 'anyone reads or sets the rate',
        then: 'each answers as if it did not exist, and nothing is set',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/mileage-rates › answers 404 feature_off when mileage is off (%s), and sets nothing',
        ],
      },
      {
        id: 'AC11',
        given: 'another organization’s rates',
        when: 'anyone in mine prices a drive or looks',
        then: 'they see none of them, and every member of mine reads our own',
        decided: { by: 'blueprint', source: 'ADR-0001' },
        checks: [
          'db/mileage-rates.int › keeps rates inside their organization, and every member reads them',
        ],
      },
    ],
    note: 'Your answer to Q28: the IRS business rate by default, and your own rate a mile in Settings whenever you want it. That owners and finance admins set it, as they keep the categories, that a change applies from a day you choose, and AC4, AC6 and AC9 are Claude’s, yours to overturn. A rate is set in the organization’s home currency as it is that day and keeps that currency.',
  },
  {
    id: 'US-MILE-06',
    title: 'Log a drive by its route',
    as: 'Riley, a solo professional who drives to clients',
    want: 'to log a drive by where it started, where it stopped and where it ended, and have its distance measured',
    soThat:
      'the miles come from a map rather than my memory, and the claim says where they came from',
    feature: 'F-14',
    requirements: ['FR-CAP-04', 'NFR-DAT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'route mileage switched on for my organization',
        when: 'I add a drive by route with its date, business purpose, a start, stops in order and an end',
        then: 'it is saved at once with its stops as typed and shows Measuring…, and measuring it is asked for through the outbox and done by a workflow, never in my request',
        decided: { by: 'blueprint', source: 'arch AP3' },
        checks: [
          'db/mileage-routes.int › logs a route drive as processing, with its stops as typed, the rate copied on and a request to measure it',
          'api/route-mileage › logs a drive by its stops for the caller, Measuring…, and hands on the request to measure it',
          'workflows/route-mileage › records the measurement for the request it was asked for',
        ],
      },
      {
        id: 'AC2',
        given: 'a drive waiting to be measured',
        when: 'the workflow measures it',
        then: 'each stop is found on the map with OpenRouteService and the route is measured by car through them in order, and the drive keeps each stop as typed, the place it was found at and its coordinates, each leg and the total in whole metres, the provider, the profile and when',
        decided: { by: 'owner', source: 'owner 2026-10-04' },
        checks: [
          'workflows/route-mileage › finds each stop and measures the route, in whole metres, with the source and when',
          'workflows/route-mileage › measures every leg through the points in order, by car',
          'db/mileage-routes.int › records each stop’s place and leg, the metres, the miles and the source, and claims those miles at the rate on the day',
        ],
      },
      {
        id: 'AC3',
        given: 'the round-trip box ticked',
        when: 'the drive is measured',
        then: 'the route returns from the end to the start, and the way back is in its distance',
        decided: { by: 'blueprint', source: 'journeys §4.3' },
        checks: [
          'workflows/route-mileage › measures a round trip back to its start',
          'db/mileage-routes.int › measures a round trip back to its start, and looks addresses up in the organization’s country',
        ],
      },
      {
        id: 'AC4',
        given: 'a measured distance in metres',
        when: 'it is claimed',
        then: 'its miles are hundredths of a mile, rounded half up with integer arithmetic from 1,609.344 metres a mile, paid at the rate in force on the drive’s date as a drive logged by hand is',
        decided: { by: 'claude', source: 'ADR-0039' },
        rules: ['R-MILEAGE-RATE'],
        checks: [
          'domain/route-mileage › turns whole metres into hundredths of a mile, exactly, rounding half up',
          'domain/route-mileage › reads a distance in metres to the whole metre, half up, through its digits',
          'domain/route-mileage › pays the measured miles at the rate on the drive’s date, with no reason needed',
          'db/mileage-routes.int › records each stop’s place and leg, the metres, the miles and the source, and claims those miles at the rate on the day',
        ],
      },
      {
        id: 'AC5',
        given:
          'fewer than a start and an end, more than 25 places, an empty address or one of more than 200 characters',
        when: 'I add the drive',
        then: 'it is refused, naming the stop, and nothing is logged',
        decided: { by: 'claude', source: 'ADR-0039' },
        rules: ['R-ROUTE-STOPS'],
        checks: [
          'domain/route-mileage › needs a start and an end, at most the most stops, and an address for each',
          'api/route-mileage › names the stop that is not valid, and logs nothing',
          'db/mileage-routes.int › refuses a route drive that is not valid, and records nothing',
        ],
      },
      {
        id: 'AC6',
        given: 'a drive being measured',
        when: 'its stops are sent to OpenRouteService',
        then: 'each address is sent as typed, every time it is measured, and never a place’s name, a note or the purpose; the form says so in one line',
        decided: { by: 'owner', source: 'Q32' },
        checks: [
          'workflows/route-mileage › sends each address as typed, with the key in a header and never in the address, narrowed to the country',
          'workflows/route-mileage › finds each stop and measures the route, in whole metres, with the source and when',
        ],
      },
      {
        id: 'AC7',
        given: 'my organization keeps its country',
        when: 'a drive’s addresses are looked up',
        then: 'the search is kept to that country',
        decided: { by: 'claude', source: 'ADR-0039' },
        checks: [
          'workflows/route-mileage › sends each address as typed, with the key in a header and never in the address, narrowed to the country',
          'db/mileage-routes.int › measures a round trip back to its start, and looks addresses up in the organization’s country',
        ],
      },
    ],
    note: 'By route sits beside By miles on Add mileage while route mileage is on. Measuring takes a few seconds; the drive’s page looks again until it is done.',
  },
  {
    id: 'US-MILE-07',
    title: 'A drive that can’t be measured says why',
    as: 'Riley, a solo professional who drives to clients',
    want: 'to be told plainly why a drive wasn’t measured, and to fix it or enter the miles myself',
    soThat: 'a typo or a used-up allowance never leaves a drive I can’t claim',
    feature: 'F-14',
    requirements: ['FR-CAP-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a stop OpenRouteService can’t find, or with no road near it',
        when: 'the drive is measured',
        then: 'it needs a look, naming the stop and its address, and claims nothing until it is fixed',
        decided: { by: 'claude', source: 'ADR-0039' },
        checks: [
          'workflows/route-mileage › asks for a look, naming the stop, when a stop can’t be found or has no road near it',
          'db/mileage-routes.int › asks for a look, with the reason, when a stop can’t be found, the route is too long or measures nothing',
        ],
      },
      {
        id: 'AC2',
        given:
          'no key, a key that can no longer be read, a key OpenRouteService refuses, or route mileage switched off before it was measured',
        when: 'the drive is measured',
        then: 'it needs a look saying what to do, such as having an owner or finance admin save the key in Settings › Mileage, and OpenRouteService is not asked again',
        decided: { by: 'claude', source: 'ADR-0039' },
        checks: [
          'workflows/route-mileage › asks for a look without trying again when the key is refused, missing or unreadable, or route mileage is off',
          'workflows/route-mileage › records why when the key is refused, in one run',
        ],
      },
      {
        id: 'AC3',
        given: 'OpenRouteService’s allowance used up for now (429) or failing on its side (5xx)',
        when: 'the drive is measured',
        then: 'the workflow asks again 3 more times, then the drive needs a look saying to measure it again later or enter its miles',
        decided: { by: 'claude', source: 'ADR-0039' },
        rules: ['R-ROUTE-RETRIES'],
        checks: [
          'workflows/route-mileage › tries again when OpenRouteService’s allowance is used up or it is failing, then asks for a look',
          'workflows/route-mileage › fails the run for the runner to try again when the allowance is used up',
          'workflows/route-mileage › runs on each request to measure, one organization at a time, trying a busy service again',
        ],
      },
      {
        id: 'AC4',
        given: 'a drive that needs a look',
        when: 'I fix a stop, or ask for it to be measured again',
        then: 'it is measured again, and an answer to the request before is never recorded',
        decided: { by: 'claude', source: 'ADR-0039' },
        checks: [
          'db/mileage-routes.int › prices the miles claimed again at the rate on its new date, and measures a drive that couldn’t be measured again on request',
          'db/mileage-routes.int › measures it again when its stops change, and never records the measurement asked for before',
          'workflows/route-mileage › measures nothing for a request the drive no longer waits for',
        ],
      },
      {
        id: 'AC5',
        given: 'a drive that couldn’t be measured',
        when: 'I enter its miles by hand with a reason',
        then: 'it is Ready for those miles at the rate on its date, keeping why it wasn’t measured and my reason; without a reason it is refused',
        decided: { by: 'claude', source: 'ADR-0039' },
        rules: ['R-MILEAGE-MAX'],
        checks: [
          'db/mileage-routes.int › takes miles entered by hand, with a reason, for a drive that couldn’t be measured',
          'domain/route-mileage › needs a reason for other miles, or for miles entered by hand, and keeps it short',
          'domain/route-mileage › refuses miles a drive logged by hand would refuse',
        ],
      },
      {
        id: 'AC6',
        given: 'a route that measures more than 1,000 miles, or nothing at all',
        when: 'it is measured',
        then: 'it needs a look saying so, with the places each stop was found at kept',
        decided: { by: 'claude', source: 'ADR-0039' },
        rules: ['R-MILEAGE-MAX'],
        checks: [
          'db/mileage-routes.int › asks for a look, with the reason, when a stop can’t be found, the route is too long or measures nothing',
        ],
      },
    ],
  },
  {
    id: 'US-MILE-08',
    title: 'Claim the miles I drove, with a reason, beside those measured',
    as: 'Riley, a solo professional who self-attests',
    want: 'to change a route drive’s measured miles to the miles I actually drove, saying why',
    soThat: 'the claim matches my odometer and a reviewer sees both figures and the reason',
    feature: 'F-14',
    requirements: ['FR-CAP-04', 'NFR-DAT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a measured drive',
        when: 'I claim other miles with a reason',
        then: 'it is paid for those miles at the rate on its date, the miles, metres and source measured stay beside them, and the audit trail records the miles before and after, the reason and the miles measured',
        decided: { by: 'owner', source: 'Q33' },
        checks: [
          'db/mileage-routes.int › claims other miles only with a reason, keeps the miles measured, and claims those again with none',
          'api/route-mileage › changes the measured miles only with a reason, and shows both with the reason',
        ],
      },
      {
        id: 'AC2',
        given: 'a measured drive',
        when: 'I claim other miles with no reason, or a reason of more than 500 characters',
        then: 'it is refused, naming the reason; claiming the measured miles again needs none, and drops the one given',
        decided: { by: 'owner', source: 'Q33' },
        rules: ['R-MILES-REASON-MAX'],
        checks: [
          'domain/route-mileage › needs a reason for other miles, or for miles entered by hand, and keeps it short',
          'domain/route-mileage › pays the measured miles at the rate on the drive’s date, with no reason needed',
          'api/route-mileage › changes the measured miles only with a reason, and shows both with the reason',
        ],
      },
      {
        id: 'AC3',
        given: 'a drive whose claimed miles differ from those measured',
        when: 'I open it, or its closed report is exported as CSV or PDF',
        then: 'the drive and the export show the miles measured, the miles claimed and the reason',
        decided: { by: 'owner', source: 'Q33' },
        checks: [
          'api/route-mileage › shows a measured drive with each stop’s place and leg, the metres, the miles and its source',
          'domain/report-export › shows the miles measured, the miles claimed and why they differ, with where the route came from',
          'api/route-mileage › exports the measured and claimed miles with the reason, and where the route came from',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC4',
        given: 'a measured drive',
        when: 'the rates change, or I change only its date or purpose',
        then: 'it keeps the distance it was measured at, its source and when, and is never measured again on its own; only new stops or a round trip switched, before it is submitted, measure it again',
        decided: { by: 'owner', source: 'Q33' },
        checks: [
          'db/mileage-routes.int › keeps the distance it was measured at and its source when the rates change later, and never measures it again on its own',
          'domain/route-mileage › measures again only when the stops or the round trip change',
          'api/route-mileage › measures it again only when its stops or round trip change',
        ],
      },
      {
        id: 'AC5',
        given: 'a route drive that is submitted or approved',
        when: 'I try to change its stops or its miles, or change it as a drive logged by hand',
        then: 'it is refused: an approved drive is corrected by a reversal',
        decided: { by: 'blueprint', source: 'journeys §4.5' },
        checks: [
          'db/mileage-routes.int › refuses a change once it is submitted, and a change as a drive logged by hand',
          'api/route-mileage › refuses a change once the drive is submitted, and a change to it as a drive logged by hand',
        ],
      },
      {
        id: 'AC6',
        given: 'a measured route',
        when: 'it is shown on the drive’s page or in a report’s export',
        then: 'it says “Route © openrouteservice.org by HeiGIT · Map data © OpenStreetMap contributors”',
        decided: { by: 'claude', source: 'ADR-0039' },
        checks: [
          'api/route-mileage › shows a measured drive with each stop’s place and leg, the metres, the miles and its source',
          'domain/report-export › shows the miles measured, the miles claimed and why they differ, with where the route came from',
        ],
      },
    ],
    note: 'Your answer to Q33. A report with no measured drive is exported as it always was.',
  },
  {
    id: 'US-MILE-09',
    title: 'Pick a stop from my saved places',
    as: 'Riley, a solo professional who drives to clients',
    want: 'to keep named addresses, such as Home and Office, and pick one for a stop',
    soThat: 'I don’t type the same addresses on my phone for every drive',
    feature: 'F-14',
    requirements: ['FR-CAP-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'route mileage switched on',
        when: 'I save a place with a name and an address in Settings › Mileage, and pick it for a stop',
        then: 'its address is copied onto the stop; my places are mine alone, each name once, and I can rename, change or remove them',
        decided: { by: 'blueprint', source: 'journeys §4.3' },
        checks: [
          'api/route-mileage › keeps the caller’s places, each name once, and changes or removes only their own',
          'db/mileage-routes.int › keeps each member’s saved places to them, by name once, and the trail without their addresses',
          'domain/route-mileage › keeps a name and an address, each trimmed, and changes either',
        ],
      },
      {
        id: 'AC2',
        given: 'a saved place',
        when: 'it is used for a drive, or changed',
        then: 'its name is never sent to OpenRouteService, and the audit trail records its name and that its address changed, never the address',
        decided: { by: 'owner', source: 'Q32' },
        checks: [
          'db/mileage-routes.int › keeps each member’s saved places to them, by name once, and the trail without their addresses',
          'workflows/route-mileage › finds each stop and measures the route, in whole metres, with the source and when',
        ],
      },
      {
        id: 'AC3',
        given:
          'a place with no name or address, a name of more than 40 characters or an address of more than 200',
        when: 'I save it',
        then: 'it is refused, naming the field',
        decided: { by: 'claude', source: 'ADR-0039' },
        checks: [
          'domain/route-mileage › refuses a place with no name or address, or one too long',
          'api/route-mileage › keeps the caller’s places, each name once, and changes or removes only their own',
        ],
      },
    ],
  },
  {
    id: 'US-MILE-10',
    title: 'Our OpenRouteService key, in Settings, and route mileage only when switched on',
    as: 'Riley, the organization’s owner',
    want: 'to paste our OpenRouteService key in Settings, see it checked, and keep route mileage out of sight until I switch it on',
    soThat:
      'measuring works on our own free key, the key is safe, and I check the feature on my phone first',
    feature: 'F-14',
    requirements: ['FR-CAP-04', 'NFR-SEC-04'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'route mileage switched on and I am an owner or finance admin',
        when: 'I paste the key in Settings › Mileage',
        then: 'it is checked with one short route on OpenRouteService, and only when that works is it stored, encrypted and bound to my organization and the provider, shown by its last four characters only, and audited',
        decided: { by: 'owner', source: 'Q31' },
        checks: [
          'api/route-mileage › checks a key with OpenRouteService as it is saved, stores it encrypted, and shows only its last four characters',
          'workflows/route-mileage › checks a key with one short route, and says how OpenRouteService answered',
          'db/mileage-routes.int › keeps one key per provider as ciphertext and its last four characters, replaced or removed with its audit event',
        ],
      },
      {
        id: 'AC2',
        given: 'a key OpenRouteService refuses, a used-up allowance, or no answer',
        when: 'I save it',
        then: 'nothing is stored, and the page says what OpenRouteService answered',
        decided: { by: 'blueprint', source: 'ADR-0015' },
        checks: [
          'api/route-mileage › stores nothing when OpenRouteService refuses the key or can’t say',
        ],
      },
      {
        id: 'AC3',
        given: 'a member who is not an owner or finance admin',
        when: 'they open, set or remove the key',
        then: 'it is refused; the key is never returned or logged, and an owner or finance admin can remove it',
        decided: { by: 'blueprint', source: 'ADR-0015' },
        checks: [
          'api/route-mileage › lets only an owner or finance admin see, set or remove it',
          'api/route-mileage › checks a key with OpenRouteService as it is saved, stores it encrypted, and shows only its last four characters',
        ],
      },
      {
        id: 'AC4',
        given: 'route mileage switched off, as it is until the owner switches it on',
        when: 'anyone calls its operations or exports a report',
        then: 'each answers as if it did not exist, nothing is measured, and the export is as it always was',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/route-mileage › answers 404 feature_off to %s %s, and does nothing',
          'api/route-mileage › exports a report as it always was, without the miles columns',
          'domain/report-export › is exported as it always was when no drive on it was measured',
        ],
      },
      {
        id: 'AC5',
        given: 'route mileage switched off',
        when: 'I open Add mileage, a drive or Settings › Mileage',
        then: 'By route, the drive’s route and the route measuring and saved places sections are not shown',
        decided: { by: 'owner', source: 'Q5' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given: 'another member’s route drive or saved place',
        when: 'I open it or change it',
        then: 'it is not found, and the database refuses a change to it even from an owner',
        decided: { by: 'claude', source: 'ADR-0035' },
        checks: [
          'db/mileage-routes.int › shows a member only their own route drives and stops, and refuses a change to anyone else’s',
          'api/route-mileage › opens and changes only the caller’s own route drives',
        ],
      },
      {
        id: 'AC7',
        given: 'route drives, places and a key in another organization',
        when: 'anyone in mine looks',
        then: 'they see none of them',
        decided: { by: 'blueprint', source: 'ADR-0001' },
        checks: [
          'db/mileage-routes.int › keeps route drives, places and keys inside their organization',
        ],
      },
    ],
    note: 'Your answers to Q31 and Q5. The end-to-end bench switches every feature on, so no test yet opens these screens with route mileage off (#66).',
  },
];
