import type { Story } from '../model.ts';

const AP4 = { by: 'blueprint', source: 'arch AP4' } as const;
const AP5 = { by: 'blueprint', source: 'arch AP5' } as const;
const DOMAIN_MODEL = { by: 'blueprint', source: 'arch §6.6' } as const;
const CONVENTIONS = { by: 'blueprint', source: 'arch §6.7' } as const;
const CLAUDE = { by: 'claude' } as const;

/**
 * Money, FX, dates, ids and the audit log (F-24, F-28; FR-GOV-05, NFR-DAT-01, NFR-DAT-02,
 * NFR-DAT-03, NFR-DAT-05). ADR-0008 was recommended with no objection, so the rules it
 * adds beyond the blueprint's are Claude's to confirm.
 */
export const DOMAIN_STORIES: readonly Story[] = [
  {
    id: 'US-DOM-01',
    title: 'Keep every amount exact, in its own currency',
    as: 'Sam, a finance admin',
    want: 'every amount kept as a whole number of its currency’s smallest unit, with its currency code',
    soThat: 'every total adds up to the cent, and nothing is lost or gained in rounding',
    feature: 'F-24',
    requirements: ['NFR-DAT-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt for 58.43 US dollars or 1,200 yen',
        when: 'it is read',
        then: 'its total is kept as 5843 cents or 1200 yen with the currency code, each currency with its own number of decimal places: two for dollars, none for yen, three for Kuwaiti dinars',
        decided: AP5,
        checks: [
          'extraction/normalize › turns decimal strings into integer minor units in the stated currency',
          'extraction/normalize › handles currencies with other minor units',
          'domain/money › knows minor units',
        ],
      },
      {
        id: 'AC2',
        given:
          'a total read with more decimal places than its currency has, such as 6.505 dollars, or one that isn’t a plain number',
        when: 'the receipt is read',
        then: 'that amount is left blank and the receipt needs a look; nothing is rounded or guessed',
        decided: CLAUDE,
        checks: [
          'extraction/normalize › flags values it cannot read instead of rounding or guessing',
          'extraction/review › never files a reading with an unreadable value',
          'domain/money › refuses extra precision unless a rounding mode is given',
        ],
      },
      {
        id: 'AC3',
        given: 'an expense in US dollars',
        when: 'its amount is corrected to 6.505, or its currency changed to yen while the amount has cents',
        then: 'the edit is refused with a message to enter the amount again, and nothing is rounded',
        decided: CLAUDE,
        checks: [
          'domain/expense-values › refuses %o as a value for %s',
          'domain/expense-values › refuses an amount the corrected currency cannot hold, rather than rounding',
        ],
      },
      {
        id: 'AC4',
        given: 'amounts in one currency',
        when: 'the app adds them up, or splits one into shares',
        then: 'the sum is exact, and the shares always add back to the whole, each within one smallest unit of its exact share, with a leftover cent going to the first',
        decided: { by: 'claude', source: 'ADR-0008' },
        checks: [
          'domain/money › adds, subtracts, negates and sums within one currency',
          'domain/money › always sums to the total, with each share within one minor unit of its exact value',
          'domain/money › gives the leftover cent to the earliest share',
        ],
      },
      {
        id: 'AC5',
        given: 'amounts in different currencies, such as euros and dollars on one trip',
        when: 'Home, a trip or a report adds them up',
        then: 'each currency is totalled on its own and shown side by side, never converted or added together',
        decided: CLAUDE,
        checks: [
          'domain/money › refuses to mix currencies',
          'api/home › adds up the month per currency, never converted, and what is on no trip',
          'api/trips › lists trips with their progress and a total per currency, never converted',
          'api/reports › lists the person’s reports with their trips, totals per currency and what holds them',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt whose currency is one the app doesn’t support, such as one read as ZZZ',
        when: 'it is read',
        then: 'its currency and its amounts are left blank and flagged as not read; no currency is guessed',
        decided: CLAUDE,
        checks: [
          'extraction/normalize › flags an unknown currency, and its amounts, unless a fallback applies',
          'domain/money › rejects unsupported codes',
        ],
      },
      {
        id: 'AC7',
        given: 'an amount on a receipt, an expense or a total',
        when: 'the app sends it to a screen',
        then: 'it goes as the whole number of smallest units, the currency and the exact decimal, such as 650, USD and 6.50, and that decimal reads back as the same amount in every supported currency',
        decided: CLAUDE,
        checks: [
          'api/receipts › shows both readings, where they differ, and money as minor units',
          'domain/money › writes plain decimals',
          'domain/money › round-trips through the decimal form for every supported currency',
        ],
      },
      {
        id: 'AC8',
        given: 'a change to the code that reads, checks or scores amounts',
        when: 'it parses an amount as a floating-point number, or rounds one by hand',
        then: 'the static checks fail in CI',
        decided: AP5,
        checks: ['ci:static'],
      },
    ],
    note: 'The lint rule covers the domain rules, receipt reading and the eval set, where amounts are parsed and rounded; the API and the web app only pass on and format amounts the domain rules made. No screen splits an amount yet.',
  },
  {
    id: 'US-DOM-02',
    title: 'See the rate behind a converted amount',
    as: 'an auditor',
    want: 'every converted amount to carry the rate used, where the rate came from and the date it is for',
    soThat: 'I can check any conversion against its published rate and get the same figure',
    feature: 'F-24',
    requirements: ['NFR-DAT-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an amount and a rate, such as 100.00 euros at 1.0845 dollars to the euro',
        when: 'it is converted',
        then: 'the result is worked out exactly, in whole cents, as 108.45 dollars, whatever the decimal places of the two currencies',
        decided: AP5,
        checks: [
          'domain/fx › %s → %s at %s: %d → %d',
          'domain/fx › is monotonic and nearly additive',
        ],
      },
      {
        id: 'AC2',
        given: 'a conversion that lands exactly halfway between two cents',
        when: 'it is rounded',
        then: 'it goes to the even cent, so many conversions carry no bias up or down, unless a rule asks for half up',
        decided: CLAUDE,
        checks: [
          'domain/fx › rounds half-even by default and half-up on request',
          'domain/decimal › is never more than half a unit away from the exact quotient',
        ],
      },
      {
        id: 'AC3',
        given:
          'a rate without its source, or dated on a day that doesn’t exist, such as 30 February',
        when: 'it is recorded',
        then: 'it is refused',
        decided: AP5,
        checks: ['domain/fx › validates rates'],
      },
      {
        id: 'AC4',
        given: 'a rate of zero or less',
        when: 'it is recorded',
        then: 'it is refused',
        decided: CLAUDE,
        checks: ['domain/fx › validates rates'],
      },
      {
        id: 'AC5',
        given: 'an amount in pounds and a rate that converts euros',
        when: 'it is converted',
        then: 'it is refused, never converted at the wrong rate',
        decided: CLAUDE,
        checks: ['domain/fx › refuses an amount in the wrong currency'],
      },
      {
        id: 'AC6',
        given: 'an expense with a converted amount',
        when: 'it is saved with its rate but without the rate’s date or source',
        then: 'the database refuses it: a rate is stored only with its date, its source and the converted amount',
        decided: AP5,
        checks: ['db/tenancy.int › refuses a converted amount without its rate provenance'],
      },
    ],
    note: 'Reports convert to your reimbursement currency at the purchase date’s reference rate (FR-EXP-13, F-49, ADR-0034, US-RPT-11), each conversion kept with its rate, the rate’s date and its source in its own record, whose check refuses a converted amount without all three; an amount that needed no rate has no conversion. The expense columns AC6 checks were built in Phase 0 for one home currency and stay unused. Trips still total each currency apart.',
  },
  {
    id: 'US-DOM-03',
    title: 'Keep a purchase on the day it was made',
    as: 'Alex, who travels for work',
    want: 'each expense dated by the calendar day on its receipt, with no time zone to shift it',
    soThat: 'an 11 pm dinner in Tokyo stays on the day I ate it',
    feature: 'F-24',
    requirements: ['NFR-DAT-03'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt dated 24 September 2026',
        when: 'it is read and its expense filed',
        then: 'the expense is dated 2026-09-24, a calendar date with no time attached, so no time zone can move it to another day',
        decided: CONVENTIONS,
        checks: [
          'db/expenses.int › is Ready with the reading when the receipt is Ready, together with its audit event',
          'domain/dates › rejects %j',
        ],
      },
      {
        id: 'AC2',
        given:
          'a date that doesn’t exist, such as 30 February, or one not written as year, month and day',
        when: 'it is read from a receipt, typed on an expense or asked for',
        then: 'it is refused, or left blank for a look, never rolled over into another day',
        decided: CLAUDE,
        checks: [
          'domain/dates › assertIsoDate throws a domain error',
          'extraction/normalize › flags values it cannot read instead of rounding or guessing',
          'api/expenses › names the field that is not valid',
          'api/home › refuses a day that does not exist, and needs a signed-in member and a database',
        ],
      },
      {
        id: 'AC3',
        given: 'two dates, such as a trip’s first day and today',
        when: 'the days between them are counted',
        then: 'whole calendar days are counted, across month ends, leap days and the change to summer time alike',
        decided: CLAUDE,
        checks: [
          'domain/dates › counts %s to %s as %i',
          'api/home › shows the trip under way as which day of it, with its totals',
        ],
      },
      {
        id: 'AC4',
        given:
          'a moment something happened, such as when an expense was edited, a trip made or an audit event written',
        when: 'it is stored and read back',
        then: 'it is the same instant, kept and given out in UTC',
        decided: CONVENTIONS,
        checks: [
          'db/audit.int › chains events so the stored history verifies',
          'api/expenses › edits when and where it was bought, working out the time zone from the place',
          'api/trips › lists trips with their progress and a total per currency, never converted',
        ],
      },
    ],
    note: 'The time of a purchase is kept as printed, with the time zone of its place (ADR-0030), not as a UTC instant: a receipt prints a local time.',
  },
  {
    id: 'US-DOM-04',
    title: 'Give every record an id that never clashes',
    as: 'the product owner',
    want: 'every record to get a unique id, in the order records were made, that can be made anywhere without asking the database',
    soThat:
      'records made in different places can be joined without clashing, and a retried step never makes a second record',
    feature: 'F-24',
    requirements: ['NFR-DAT-03'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a new receipt, expense, trip, report, organization or audit event',
        when: 'it is made',
        then: 'it gets a version 7 UUID: unique, and sorting in the order the records were made',
        decided: CONVENTIONS,
        checks: ['domain/ids › creates time-ordered version 7 UUIDs'],
      },
      {
        id: 'AC2',
        given: 'an emailed receipt, or the email it came in',
        when: 'the step that files it runs again',
        then: 'it gets the same id as the first time, a version 5 UUID made from the message and the file, so nothing is filed twice',
        decided: { by: 'claude', source: 'ADR-0026' },
        checks: [
          'domain/ids › derives the same version 5 UUID from the same name, and another from another',
          'workflows/email › files a verified member’s attachments as receipts, under ids made from the message',
        ],
      },
    ],
    note: 'NFR-DAT-03 says every id is a UUIDv7. Ids made from an email are UUIDv5 by design (ADR-0026), so that a retried step makes them again exactly.',
  },
  {
    id: 'US-DOM-05',
    title: 'Record every change in the audit trail',
    as: 'an auditor',
    want: 'every change to a record to leave an audit event saying who made it, to what, and what changed, saved with the change itself',
    soThat: 'the history of any claim is complete, and no change is saved without its trace',
    feature: 'F-28',
    requirements: ['FR-GOV-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt filed, a reading confirmed, an expense filed or a trip made',
        when: 'the change is saved',
        then: 'an audit event naming who did it, the record and the action is written in the same transaction as the change',
        decided: AP4,
        checks: [
          'db/receipts.int › makes it Ready with the values, the corrections and an audit event, together',
          'db/expenses.int › is Ready with the reading when the receipt is Ready, together with its audit event',
          'db/trips.int › files the member’s expenses dated in a new trip, start and end days included',
        ],
      },
      {
        id: 'AC2',
        given:
          'a change the app makes on its own, such as filing a newly read receipt’s expense to its trip',
        when: 'it is saved',
        then: 'its audit event names the app’s workflow as the one who made it, never a person',
        decided: CLAUDE,
        checks: [
          'db/trips.int › files a receipt read after the trip exists to it, with no human touch',
        ],
      },
      {
        id: 'AC3',
        given: 'an edit to a trip',
        when: 'it is saved',
        then: 'its audit event records each field changed, from what to what, and a save that changes nothing records nothing',
        decided: CLAUDE,
        checks: ['db/trips.int › files again when a trip’s dates change, and records each change'],
      },
      {
        id: 'AC4',
        given: 'several changes in one organization at the same moment',
        when: 'they are saved',
        then: 'their events are numbered one after another, with no number missed or used twice',
        decided: CLAUDE,
        checks: ['db/audit.int › keeps sequences gapless under concurrent writers'],
      },
      {
        id: 'AC5',
        given: 'two organizations',
        when: 'each records changes',
        then: 'each has a trail of its own, and neither sees the other’s events',
        decided: CLAUDE,
        checks: [
          'db/audit.int › chains events so the stored history verifies',
          'db/tenancy.int › puts a forced tenant policy on every table that holds org data',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt deleted as a duplicate',
        when: 'anyone later reads the trail',
        then: 'the receipt’s events are still there, with one saying it was deleted',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › deletes a copy with its readings and expense, keeps a record of it, and returns its file',
        ],
      },
    ],
    note: 'No screen shows the trail yet: finance admins and auditors reading it is FR-GOV-06 (#26). Each model’s reading of a receipt is stored as it arrives; the audit event comes when the reading settles the receipt.',
  },
  {
    id: 'US-DOM-06',
    title: 'Show if the history has been rewritten',
    as: 'an auditor',
    want: 'each audit event sealed with a hash of its content and of the event before it',
    soThat: 'editing, removing or reordering a past event shows when the trail is checked',
    feature: 'F-28',
    requirements: ['FR-GOV-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an organization’s trail as it was written',
        when: 'it is checked',
        then: 'each event’s hash matches its content and the event before it, back to a fixed start, and the trail verifies',
        decided: DOMAIN_MODEL,
        checks: [
          'domain/audit › verifies an untouched chain',
          'db/audit.int › chains events so the stored history verifies',
        ],
      },
      {
        id: 'AC2',
        given: 'an event whose details were changed afterwards, such as its amount',
        when: 'the trail is checked',
        then: 'it fails at that event',
        decided: DOMAIN_MODEL,
        checks: ['domain/audit › detects an edited payload'],
      },
      {
        id: 'AC3',
        given: 'an event removed, or two events swapped',
        when: 'the trail is checked',
        then: 'it fails at the first event out of place',
        decided: DOMAIN_MODEL,
        checks: ['domain/audit › detects removed and reordered events'],
      },
      {
        id: 'AC4',
        given: 'an event whose stored hash was replaced',
        when: 'the trail is checked',
        then: 'it fails at that event',
        decided: CLAUDE,
        checks: ['domain/audit › detects a recomputed hash that no longer matches its content'],
      },
      {
        id: 'AC5',
        given: 'an event',
        when: 'it is hashed',
        then: 'the same details give the same hash in whatever order they are written, and details that can’t be written down exactly, such as a number that isn’t finite, are refused',
        decided: CLAUDE,
        checks: [
          'domain/audit › ignores key order at every level and drops undefined',
          'domain/audit › refuses values that do not round-trip through JSON',
        ],
      },
    ],
    note: 'Nothing in the app checks the trail yet; the tests do, and #26 (FR-GOV-06) checks it on screen. The chain shows an edit to a stored event. An edit made with every later hash recomputed as well would take a copy kept elsewhere, such as a backup, to show.',
  },
  {
    id: 'US-DOM-07',
    title: 'Nobody can change or delete the audit trail',
    as: 'an auditor',
    want: 'the audit trail to refuse every change and deletion, from the app and from the account that owns the table alike',
    soThat: 'what was recorded stays as it was recorded',
    feature: 'F-28',
    requirements: ['NFR-DAT-05', 'FR-GOV-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'the app',
        when: 'it tries to change or delete an audit event',
        then: 'the database refuses it: the app can only add events',
        decided: DOMAIN_MODEL,
        checks: ['db/audit.int › denies UPDATE and DELETE to the application role'],
      },
      {
        id: 'AC2',
        given: 'the account that owns the audit table, which the app never connects as',
        when: 'it tries to change, delete or empty the trail',
        then: 'each is refused: the trail is append-only',
        decided: AP4,
        checks: ['db/audit.int › blocks even the table owner from rewriting history'],
      },
    ],
    note: 'The account that owns the table could switch the guard off before an edit; the hash chain (US-DOM-06) would then show the edited event.',
  },
  {
    id: 'US-DOM-08',
    title: 'Keep receipts and expenses once they count',
    as: 'Sam, a finance admin',
    want: 'receipts, their readings and their expenses never deleted, but for a duplicate a member chose to delete before submitting it',
    soThat: 'everything that was claimed is still there to reconcile and audit',
    feature: 'F-28',
    requirements: ['NFR-DAT-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'the app',
        when: 'it tries to delete a receipt, a reading, a confirmation or an expense directly',
        then: 'the database refuses: the one way to delete a receipt is as a duplicate',
        decided: CONVENTIONS,
        checks: [
          'db/duplicates.int › deletes nothing in another organization, and the app cannot delete receipts any other way',
        ],
      },
      {
        id: 'AC2',
        given: 'a receipt whose expense is submitted, approved or paid',
        when: 'anyone tries to delete it, even as a duplicate',
        then: 'it is refused, by the app and by the database alike',
        decided: CONVENTIONS,
        checks: [
          'db/duplicates.int › never deletes a submitted expense, and acts only on a pair that is open',
          'api/receipts › refuses a receipt outside the pair, a pair already decided, and a locked expense',
        ],
      },
      {
        id: 'AC3',
        given: 'a duplicate receipt a member chose to delete before its expense was submitted',
        when: 'it is deleted',
        then: 'it goes with its readings and its expense, as the one exception',
        decided: { by: 'owner', source: 'owner 2026-10-03' },
        checks: [
          'db/duplicates.int › deletes a copy with its readings and expense, keeps a record of it, and returns its file',
        ],
      },
      {
        id: 'AC4',
        given: 'a receipt in another organization',
        when: 'the deleting function is asked to delete it',
        then: 'nothing is deleted',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › deletes nothing in another organization, and the app cannot delete receipts any other way',
        ],
      },
    ],
    note: 'GAP-10 is still partly open: the app can delete reports, approval steps and mileage logs (#33). It does drop an open report with nothing on it, with an audit event. Your decision of Oct 3 to delete a duplicate outright is the one exception for receipts and expenses, and only before submission.',
  },
];
