import type { Story } from '../model.ts';

const OCT3 = { by: 'owner', source: 'owner 2026-10-03' } as const;
const OCT4 = { by: 'owner', source: 'owner 2026-10-04' } as const;

/** Possible duplicates (FR-INT-18, FR-INT-19; ADR-0028, ADR-0031). */
export const DUPLICATE_STORIES: readonly Story[] = [
  {
    id: 'US-DUP-01',
    title: 'Catch a receipt I have filed twice',
    as: 'Alex, who travels for work and forwards most receipts by email',
    want: 'a receipt I have already filed to be held before it counts',
    soThat: 'one purchase is never reimbursed twice, and I never have to spot copies myself',
    feature: 'F-48',
    requirements: ['FR-INT-18'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'two of my receipts from a similar merchant, at the same place, on the same day, at the same minute and for the same total',
        when: 'the later one is read',
        then: 'it is held as an exact copy: it needs a look and counts in no total until I decide',
        decided: OCT4,
        checks: [
          'domain/duplicates › is exact when the time, place and total are all the same',
          'db/duplicates.int › holds an exact copy: the same time, place and total',
        ],
      },
      {
        id: 'AC2',
        given: 'two such receipts where the later one is a few minutes on and for another total, as with a card slip with the tip added, or an amended receipt',
        when: 'the later one is read',
        then: 'it is held as a possible duplicate',
        decided: OCT4,
        checks: [
          'domain/duplicates › is possible when the total differs at the same time and place, as with a tip added',
          'db/duplicates.int › holds the slip with a tip, minutes later and with another total, as possible',
        ],
        rules: ['R-DUPLICATE-WINDOW'],
      },
      {
        id: 'AC3',
        given: 'two receipts from one merchant at one place on one day, hours apart, even for the same total',
        when: 'the later one is read',
        then: 'neither is held: they are two purchases',
        decided: OCT4,
        checks: [
          'domain/duplicates › is two purchases when they say different times, places or days, whatever the total',
          'db/duplicates.int › keeps apart two purchases at the same place hours apart, even with the same total',
        ],
        rules: ['R-DUPLICATE-WINDOW'],
      },
      {
        id: 'AC4',
        given: 'two receipts that don’t both show a time and a place, such as receipts read before time and place were',
        when: 'the later one is read',
        then: 'it is held as possible only if the merchant is similar, the currency and total match, and the dates are a day apart at most',
        decided: { by: 'owner', source: 'Q18' },
        checks: [
          'domain/duplicates › falls back to the total and a day either way without a time on both (Q18)',
          'domain/duplicates › needs the total to match when only the time is known on both',
          'db/duplicates.int › holds a later copy of a purchase for a look, and leaves it out of Home’s totals',
        ],
        rules: ['R-DUPLICATE-DAYS'],
      },
      {
        id: 'AC5',
        given: 'a merchant written differently on two receipts, such as “Uber” and “Uber Technologies Inc.”, or a place written as “1200 McKinney St” and “1200 MCKINNEY STREET”',
        when: 'they are compared',
        then: 'they count as the same merchant and the same place; different businesses, cities or countries never do',
        decided: { by: 'claude', source: 'ADR-0031' },
        checks: [
          'domain/duplicates › treats a shorter name inside a longer one, or the same words run together, as one business',
          'domain/duplicates › tells different businesses apart',
          'domain/duplicates › is the same city, or addresses with the same words, street words spelled either way',
          'domain/duplicates › is somewhere else in another city or country, and unknown when either doesn’t say',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt whose merchant or date nothing could read, another member’s receipt, or one that failed to read',
        when: 'receipts are compared',
        then: 'it is never matched: a guess is no evidence',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'domain/duplicates › never matches on a guess: the merchant and the date must be known on both',
          'db/duplicates.int › leaves alone a different total, merchant, another member’s receipt, or one nothing could read',
        ],
      },
      {
        id: 'AC7',
        given: 'a held copy',
        when: 'it is read again, or I try Looks right on it',
        then: 'it stays held, and confirming it is refused until I decide about the pair',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › keeps a copy held when it is read again, and refuses to confirm it until the person decides',
          'api/receipts › shows the pair on both receipts, and refuses Looks right while the copy is held',
        ],
      },
      {
        id: 'AC8',
        given: 'receipts filed before duplicates were looked for',
        when: 'the release that brought the check ran',
        then: 'each was compared once, oldest first, and only the later copies were held',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: ['db/duplicates.int › holds the later copies, once, and leaves the rest'],
      },
    ],
  },
  {
    id: 'US-DUP-02',
    title: 'See a held copy and what it matches',
    as: 'Alex, who travels for work',
    want: 'a held copy to tell me which receipt it matches, how sure the match is, and where they differ',
    soThat: 'I can decide in seconds without opening both',
    feature: 'F-48',
    requirements: ['FR-INT-18', 'FR-EXP-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a held copy',
        when: 'I open Needs you',
        then: 'it is listed with the earlier receipt’s merchant, total and date, called a copy when exact and a possible duplicate otherwise',
        decided: { by: 'claude', source: 'ADR-0031' },
        checks: [
          'api/receipts › puts the later copy in Needs you, naming the receipt it looks like',
          'api/receipts › says whether a pair is exact or possible, from the time, place and total (ADR-0031)',
        ],
      },
      {
        id: 'AC2',
        given: 'a pair',
        when: 'I open either receipt',
        then: 'the two show side by side: merchant, date, amount, notes, trip, time, place and when each was added, with every difference marked',
        decided: OCT3,
        checks: [
          'api/receipts › shows the pair on both receipts, and refuses Looks right while the copy is held',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC3',
        given: 'a pair whose expenses I have since edited apart',
        when: 'I open it',
        then: 'it still shows, as possible, until I decide',
        decided: { by: 'claude', source: 'ADR-0031' },
        checks: [
          'api/receipts › says whether a pair is exact or possible, from the time, place and total (ADR-0031)',
        ],
      },
    ],
  },
  {
    id: 'US-DUP-03',
    title: 'Decide what happens to a duplicate',
    as: 'Alex, who travels for work',
    want: 'to keep both, delete one, merge one into the other, or replace the earlier one',
    soThat: 'my claim holds each purchase once, as the receipt I trust',
    feature: 'F-48',
    requirements: ['FR-INT-18'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a held pair',
        when: 'I choose Keep both',
        then: 'nothing is deleted, the copy goes back to what it was read as, and the pair is never flagged again',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › keeps both: the copy goes back to what it was read as, and the pair is never flagged again',
          'api/receipts › keeps both: nothing is deleted',
        ],
      },
      {
        id: 'AC2',
        given: 'a held pair',
        when: 'I choose Delete one and pick which',
        then: 'that receipt, its readings, its expense and its file are deleted, and no copy is kept',
        decided: OCT3,
        checks: [
          'db/duplicates.int › deletes a copy with its readings and expense, keeps a record of it, and returns its file',
          'api/receipts › deletes the one not kept, then its file',
          'api/receipts › still deletes when the file can’t be removed, and needs a signed-in member',
        ],
      },
      {
        id: 'AC3',
        given: 'a held pair',
        when: 'I choose Merge, pick the receipt to keep and tick fields to take',
        then: 'the kept one takes every field it lacks and each field I ticked, an amount with its currency, and the other is deleted as in AC2',
        decided: OCT3,
        checks: [
          'domain/duplicates › fills what the primary lacks and keeps what it has',
          'domain/duplicates › takes the fields the person chose, an amount with its currency',
          'domain/duplicates › never takes a blank: a chosen field the duplicate lacks stays as it was',
          'db/duplicates.int › merges a copy into the primary chosen, taking what it lacks and what was picked',
          'api/receipts › merges into the primary chosen, from either receipt’s page',
        ],
      },
      {
        id: 'AC4',
        given: 'an exact copy is held',
        when: 'I tap Delete the copy',
        then: 'in that one tap the copy is deleted and the earlier receipt kept, taking any note or trip only the copy had',
        decided: { by: 'owner', source: 'Q19' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'a possible duplicate is held',
        when: 'I tap Replace the earlier one',
        then: 'the later receipt is kept, as for an amended one, and the earlier is deleted, passing on any note or trip the later lacks',
        decided: { by: 'owner', source: 'Q19' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given: 'either receipt’s expense is submitted, approved or paid',
        when: 'I try to delete or merge',
        then: 'it is refused: a submitted expense is never deleted',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › never deletes a submitted expense, and acts only on a pair that is open',
          'api/receipts › refuses a receipt outside the pair, a pair already decided, and a locked expense',
        ],
      },
      {
        id: 'AC7',
        given: 'a receipt is deleted or merged away',
        when: 'anyone later looks at the audit trail',
        then: 'it says what the receipt was, and a third copy that pointed at it is paired with the receipt kept',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › deletes a copy with its readings and expense, keeps a record of it, and returns its file',
          'db/duplicates.int › re-pairs a third copy with the receipt kept when the one it pointed at is deleted',
        ],
      },
      {
        id: 'AC8',
        given: 'someone in another organization, or the app outside the one deleting function',
        when: 'they try to delete a receipt',
        then: 'nothing is deleted',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › deletes nothing in another organization, and the app cannot delete receipts any other way',
        ],
      },
    ],
  },
  {
    id: 'US-DUP-04',
    title: 'Set how close in time a duplicate must be',
    as: 'the organization’s owner',
    want: 'to set the window within which two receipts at one place count as one purchase',
    soThat: 'the control fits how my people buy, and nobody can loosen it for their own receipts',
    feature: 'F-52',
    requirements: ['FR-INT-19'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'I am the organization’s owner',
        when: 'I open Settings',
        then: 'I can set the window from 0 to 120 minutes; it starts at 30, and 0 means the same minute only',
        decided: OCT4,
        checks: [],
        rules: ['R-DUPLICATE-WINDOW'],
      },
      {
        id: 'AC2',
        given: 'I am a member who is not the owner',
        when: 'I open Settings',
        then: 'I see the window but can’t change it',
        decided: { by: 'owner', source: 'Q24' },
        checks: [],
      },
      {
        id: 'AC3',
        given: 'the owner changes the window',
        when: 'receipts are read afterwards',
        then: 'they are judged by the new window; pairs already decided stay decided, and the audit trail records the change',
        decided: OCT4,
        checks: [],
      },
      {
        id: 'AC4',
        given: 'I sign in with any of my addresses',
        when: 'I open Settings',
        then: 'it shows my role, so I can confirm each address is the owner',
        decided: { by: 'owner', source: 'Q24' },
        checks: [],
      },
    ],
  },
];
