import type { Story } from '../model.ts';

const OCT3 = { by: 'owner', source: 'owner 2026-10-03' } as const;
const ADR22 = { by: 'claude', source: 'ADR-0022' } as const;
const ADR23 = { by: 'claude', source: 'ADR-0023' } as const;
const AUDIT = { by: 'blueprint', source: 'arch AP4' } as const;
const TENANCY = { by: 'blueprint', source: 'arch AP6' } as const;
const SEARCH = { by: 'blueprint', source: 'capmap P1' } as const;

/**
 * Expenses, trips, the Needs you inbox and the Home dashboard (FR-EXP-01, FR-EXP-02, FR-EXP-04,
 * FR-EXP-08, FR-EXP-09, FR-INS-01, FR-INS-02; ADR-0022, ADR-0023).
 */
export const EXPENSE_STORIES: readonly Story[] = [
  // Expenses
  {
    id: 'US-EXP-01',
    title: 'Have each receipt become an expense on its own',
    as: 'Alex, a road warrior who travels for work',
    want: 'every receipt I capture to become an expense by itself, filled in from what was read',
    soThat:
      'a receipt read with confidence needs nothing more from me, and an unsure one is ready to fix',
    feature: 'F-09',
    requirements: ['FR-EXP-01', 'FR-EXP-08'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I capture a receipt',
        when: 'it is filed',
        then: 'an expense exists at once, shown as Reading…, linked to the receipt as its proof, and the audit trail records both',
        decided: ADR22,
        checks: [
          'db/expenses.int › exists from capture, processing and linked to its receipt as proof',
        ],
      },
      {
        id: 'AC2',
        given:
          'both models read my receipt with confidence, they agree and its checks pass, so the receipt is Ready',
        when: 'the reading is filed',
        then: 'the expense is Ready, with the merchant, date, currency and amount read, and no touch from me',
        decided: { by: 'blueprint', source: 'journeys §4.6' },
        checks: [
          'workflows/receipts › files it as Ready when both read it with confidence and agree',
          'db/expenses.int › is Ready with the reading when the receipt is Ready, together with its audit event',
        ],
      },
      {
        id: 'AC3',
        given: 'a Ready receipt from which the merchant, date, currency or amount is missing',
        when: 'it is filed',
        then: 'its expense Needs a look until every one of the four is filled in',
        decided: ADR22,
        checks: [
          'domain/expense-values › is Ready only when the receipt is Ready and the claim is complete',
          'domain/expense-values › needs merchant, date, currency and amount',
        ],
      },
      {
        id: 'AC4',
        given: 'my receipt Needs a look, or no model could read it',
        when: 'it is filed',
        then: 'its expense Needs a look: filled in as read, or empty when nothing was read',
        decided: { by: 'blueprint', source: 'journeys §4.5' },
        checks: [
          'db/expenses.int › needs review, filled in as read, while its receipt needs a look; failed leaves it empty',
        ],
      },
      {
        id: 'AC5',
        given: 'a receipt that Needs a look',
        when: 'I confirm or correct it on the receipt',
        then: 'its expense becomes Ready with what I confirmed',
        decided: { by: 'blueprint', source: 'journeys §4.5' },
        checks: [
          'db/expenses.int › becomes Ready with the confirmed values when its receipt is confirmed',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt no model could read',
        when: 'I fill in every field on the receipt',
        then: 'its expense becomes Ready, so no receipt is a dead end',
        decided: ADR22,
        checks: [
          'db/expenses.int › is Ready once a receipt no model could read is filled in by hand',
        ],
      },
      {
        id: 'AC7',
        given: 'receipts filed before expenses existed',
        when: 'the release that brought expenses ran',
        then: 'each got exactly one expense, one not yet confirmed getting an expense that needs a look, and running it again added none',
        decided: ADR22,
        checks: [
          'db/expenses.int › each get an expense once, confirmed ones Ready with what was confirmed',
        ],
      },
    ],
    note: 'Increment 1’s exit test, a receipt filed as an expense within 30 seconds, is measured in use, not by a test. Filing to a trip by date is US-TRIP-01.',
  },
  {
    id: 'US-EXP-02',
    title: 'Keep the receipt as proof and see where my claim differs',
    as: 'Alex, a road warrior who travels for work',
    want: 'my expense to keep its receipt as proof, and to show me wherever what I claim differs from it',
    soThat: 'editing never rewrites the evidence, and I see a difference before anyone reviews it',
    feature: 'F-09',
    requirements: ['FR-EXP-08'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense made from a receipt',
        when: 'I open it',
        then: 'Its receipt shows what the receipt says: what was confirmed on it, or else the reading, marked as read and not yet confirmed, with Open the receipt',
        decided: ADR22,
        checks: ['api/expenses › shows what its receipt shows, as its proof'],
      },
      {
        id: 'AC2',
        given: 'I have edited an expense',
        when: 'I look at its receipt',
        then: 'the receipt, its readings and what was confirmed on it are as they were',
        decided: OCT3,
        checks: ['api/expenses › edits an expense and shows where it now differs from its receipt'],
      },
      {
        id: 'AC3',
        given:
          'I edit an expense so that its merchant, date, currency or amount no longer matches its receipt',
        when: 'I save',
        then: 'each such field is marked “differs from its receipt”, and the Expenses list says so too',
        decided: { by: 'owner', source: 'Q6' },
        checks: [
          'api/expenses › edits an expense and shows where it now differs from its receipt',
          'api/expenses › lists each expense with whether it matches its receipt',
          'extraction/proof › names each field that differs',
        ],
      },
      {
        id: 'AC4',
        given:
          'a merchant written another way than on the receipt, such as “BLUE BOTTLE COFFEE INC” for “Blue Bottle Coffee”, or a field the receipt doesn’t show',
        when: 'the expense is compared with its receipt',
        then: 'neither counts as a difference; the date, currency and amount must be exactly the same',
        decided: ADR22,
        checks: [
          'extraction/proof › finds nothing when the expense matches its receipt, allowing loose merchant names',
          'extraction/proof › cannot differ where the receipt shows nothing, and an empty claim differs',
        ],
      },
      {
        id: 'AC5',
        given: 'I change the time or place of an expense from what its receipt prints',
        when: 'I open it',
        then: 'Time or Place is marked “differs from its receipt”',
        decided: { by: 'claude', source: 'ADR-0030' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given: 'an expense in my organization',
        when: 'someone in another organization asks for it or lists expenses',
        then: 'they find nothing of it',
        decided: TENANCY,
        checks: ['db/expenses.int › stays inside its organization'],
      },
      {
        id: 'AC7',
        given: 'I am not signed in',
        when: 'I open Expenses or an expense, or ask the API for one',
        then: 'I am asked to sign in and no expense is shown',
        decided: { by: 'claude' },
        checks: [
          'e2e/expenses › asks a signed-out visitor to sign in before showing any expense',
          'e2e/expenses › refuses the expense endpoints without a signed-in user',
          'api/expenses › answers 404 for an expense it does not have, and needs a signed-in member',
        ],
      },
    ],
    note: 'Refusing to submit a report while a difference has no reason, and rejecting one at review, are FR-GOV-13 and FR-GOV-10, which come with approval (#24). Inside an organization a member opens only their own expenses (US-SEC-14).',
  },
  {
    id: 'US-EXP-03',
    title: 'Correct an expense',
    as: 'Alex, a road warrior who travels for work',
    want: 'to correct an expense’s merchant, date, amount, currency, time and place while it needs a look or is Ready',
    soThat: 'what I claim is right even when the reading wasn’t, and every change is on record',
    feature: 'F-09',
    requirements: ['FR-EXP-09', 'FR-INT-17'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense that Needs a look or is Ready',
        when: 'I tap Edit, change its merchant, date, amount or currency, and tap Save',
        then: 'it shows the new values, and the audit trail records who changed each field, from what to what',
        decided: OCT3,
        checks: [
          'domain/expense-values › applies each field and lists what changed, amounts as decimals',
          'db/expenses.int › keeps a person’s edit over any later reading, and is Ready once the receipt is',
        ],
      },
      {
        id: 'AC2',
        given: 'an expense I have edited',
        when: 'its receipt is read again or confirmed',
        then: 'my values stay; only its status follows the receipt, and it is Ready once the receipt is',
        decided: ADR22,
        checks: [
          'db/expenses.int › keeps a person’s edit over any later reading, and is Ready once the receipt is',
        ],
      },
      {
        id: 'AC3',
        given: 'an expense',
        when: 'I edit when and where it was bought: the time, address, city, state or region, and country',
        then: 'they are saved, with the time zone worked out from the place, or the one I choose',
        decided: { by: 'owner', source: 'Q9' },
        checks: [
          'api/expenses › edits when and where it was bought, working out the time zone from the place',
        ],
      },
      {
        id: 'AC4',
        given: 'an expense whose receipt is being read',
        when: 'I try to edit it',
        then: 'it is refused until the reading is done, so a reading and an edit never cross',
        decided: ADR22,
        checks: [
          'api/expenses › refuses an edit while the receipt is read, or once submitted',
          'db/expenses.int › keeps a person’s edit over any later reading, and is Ready once the receipt is',
        ],
      },
      {
        id: 'AC5',
        given: 'an expense that is submitted, approved or paid',
        when: 'I try to edit it',
        then: 'it is refused and shown as not editable: an approved expense is locked',
        decided: { by: 'blueprint', source: 'journeys §4.5' },
        checks: [
          'api/expenses › refuses an edit while the receipt is read, or once submitted',
          'domain/lifecycle/expense › allows edits only before submission and locks approved records',
        ],
      },
      {
        id: 'AC6',
        given:
          'I enter an empty merchant, a date that doesn’t exist, a currency ExpenseWise doesn’t support, a negative amount, or more decimals than the currency has',
        when: 'I tap Save',
        then: 'it is refused, naming the field, and nothing is rounded or saved',
        decided: ADR22,
        checks: [
          'domain/expense-values › refuses %o as a value for %s',
          'api/expenses › names the field that is not valid',
          'db/expenses.int › refuses a value that is not valid, and records nothing for no change',
        ],
      },
      {
        id: 'AC7',
        given: 'I correct only the currency',
        when: 'I tap Save',
        then: 'the amount stays as written, never converted; one the new currency can’t hold, such as 6.50 in yen, is refused until I enter it again',
        decided: ADR22,
        checks: [
          'domain/expense-values › keeps the amount as written when the currency is corrected',
          'domain/expense-values › refuses an amount the corrected currency cannot hold, rather than rounding',
        ],
      },
      {
        id: 'AC8',
        given: 'I save values that are the ones already there',
        when: 'the edit is applied',
        then: 'nothing changes and nothing is recorded',
        decided: ADR22,
        checks: [
          'domain/expense-values › does not count a value entered unchanged as a change',
          'db/expenses.int › refuses a value that is not valid, and records nothing for no change',
        ],
      },
    ],
    note: 'Editing again when a report comes back follows the expense lifecycle, where a returned expense is Ready again, but nothing returns a report until approval is built (#24). Inside an organization a member changes only their own expenses (US-SEC-14).',
  },
  {
    id: 'US-EXP-04',
    title: 'Find a past expense',
    as: 'Riley, a solo professional who self-attests',
    want: 'to find past expenses by part of the merchant’s name, a range of dates, an amount, or a trip',
    soThat: 'I can answer any question about a purchase in seconds, at tax time or any time',
    feature: 'F-12',
    requirements: ['FR-INS-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'expenses from many merchants',
        when: 'I type part of a merchant’s name in Merchant on Expenses and tap Search',
        then: 'only expenses whose merchant contains it, in any case, are listed; a % matches only itself',
        decided: SEARCH,
        checks: [
          'db/trips.int › finds expenses by merchant, dates, amount in any currency, trip, or on no trip',
          'api/expenses › searches by merchant, dates, amount in any currency, and trip (FR-INS-02)',
        ],
      },
      {
        id: 'AC2',
        given: 'expenses over many months',
        when: 'I enter From and To and tap Search',
        then: 'only expenses dated on or between those days are listed',
        decided: SEARCH,
        checks: [
          'db/trips.int › finds expenses by merchant, dates, amount in any currency, trip, or on no trip',
          'api/expenses › searches by merchant, dates, amount in any currency, and trip (FR-INS-02)',
        ],
      },
      {
        id: 'AC3',
        given: 'expenses in several currencies',
        when: 'I search for an Amount such as 18.92',
        then: 'it finds 18.92 in every currency with cents and 18.920 in those with three decimals, never 1,892 yen, and nothing is rounded',
        decided: ADR23,
        checks: [
          'domain/trips › reads an amount with cents in every currency that has cents or more',
          'domain/trips › reads three decimals only in currencies that have them',
          'db/trips.int › finds expenses by merchant, dates, amount in any currency, trip, or on no trip',
        ],
      },
      {
        id: 'AC4',
        given:
          'a search narrowed to one trip, or to expenses on no trip as Home’s Not on a trip figure opens it',
        when: 'it runs with any of merchant, dates and amount',
        then: 'only expenses matching every part are listed',
        decided: SEARCH,
        checks: [
          'db/trips.int › finds expenses by merchant, dates, amount in any currency, trip, or on no trip',
          'api/expenses › finds the expenses on no trip, or on some trip (Home’s figures open them)',
        ],
      },
      {
        id: 'AC5',
        given:
          'a search with an amount written 1,000 or with too many decimals, or a date that doesn’t exist',
        when: 'it is sent',
        then: 'it is refused, and nothing is guessed',
        decided: { by: 'claude' },
        checks: ['api/expenses › refuses the search %s'],
      },
      {
        id: 'AC6',
        given: 'expenses in another organization',
        when: 'I search',
        then: 'none of them is ever found',
        decided: TENANCY,
        checks: ['db/expenses.int › stays inside its organization'],
      },
    ],
    note: 'Expenses has no trip field of its own: a trip’s page lists its expenses (US-TRIP-04), and Home’s figures open Expenses already narrowed. Search finds only the person’s own expenses, whatever their role (US-SEC-15).',
  },

  // Trips
  {
    id: 'US-TRIP-01',
    title: 'Make a trip and have my expenses file to it',
    as: 'Alex, a road warrior who travels for work',
    want: 'to make a trip with its dates and purpose, and have every expense dated in it file to it by itself',
    soThat: 'my spend is organized by trip without my sorting a single receipt',
    feature: 'F-12',
    requirements: ['FR-EXP-04', 'FR-EXP-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I am on Trips',
        when: 'I tap New trip, enter a Name, First day and Last day, and tap Make the trip',
        then: 'the trip is made and opens, and the audit trail records it',
        decided: { by: 'blueprint', source: 'journeys §4.2' },
        checks: [
          'api/trips › makes a trip for the caller and answers with it',
          'db/trips.int › files the member’s expenses dated in a new trip, start and end days included',
        ],
      },
      {
        id: 'AC2',
        given:
          'expenses of mine dated from the first to the last day of a new trip, both days included',
        when: 'the trip is made',
        then: 'each files to it and each move is recorded; expenses dated outside it, not yet dated, or another member’s stay where they are',
        decided: { by: 'blueprint', source: 'journeys §4.2' },
        checks: [
          'domain/trips › files a date to the trip that covers it, start and end days included',
          'domain/trips › files nothing outside every trip, or with no date yet',
          'db/trips.int › files the member’s expenses dated in a new trip, start and end days included',
        ],
      },
      {
        id: 'AC3',
        given: 'a trip of mine exists',
        when: 'a receipt dated in it is read, even while the trip is still being made',
        then: 'its expense files to the trip with no touch from me',
        decided: { by: 'blueprint', source: 'journeys §4.6' },
        checks: [
          'db/trips.int › files a receipt read after the trip exists to it, with no human touch',
          'db/trips.int › files an expense whose date arrives while the trip is being made',
        ],
      },
      {
        id: 'AC4',
        given: 'I make a trip ahead, before I know its purpose or city',
        when: 'I leave Purpose and Where empty',
        then: 'the trip is made, and either can be added or cleared later',
        decided: { by: 'claude' },
        checks: [
          'api/trips › makes a trip for the caller and answers with it',
          'domain/trips › changes only the fields sent, and clears a purpose or city sent empty',
        ],
      },
      {
        id: 'AC5',
        given:
          'a trip with no name, a missing day, a last day before its first, or longer than 366 days',
        when: 'I make or save it',
        then: 'it is refused, naming the field; a one-day trip and one a year long are fine',
        decided: { by: 'claude' },
        checks: [
          'domain/trips › needs a name and both dates for a new trip',
          'domain/trips › allows a one-day trip and one a year long, and nothing longer',
          'api/trips › names the field that is not valid',
        ],
        rules: ['R-TRIP-LENGTH'],
      },
    ],
    note: 'Making a trip from a forwarded itinerary is Phase 2 (journeys §4.2).',
  },
  {
    id: 'US-TRIP-02',
    title: 'Keep expenses on the right trip as things change',
    as: 'Alex, a road warrior who travels for work',
    want: 'my expenses to move to the right trip whenever an expense’s date or a trip’s dates change, or a trip is deleted',
    soThat: 'a trip always holds what was spent on it, without my moving anything',
    feature: 'F-12',
    requirements: ['FR-EXP-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense filed by its date',
        when: 'I change its date',
        then: 'it moves onto the trip the new date falls in, or off the one it leaves; an edit that keeps the date doesn’t move it',
        decided: ADR23,
        checks: ['db/trips.int › moves an expense when its date is edited, onto a trip or off one'],
      },
      {
        id: 'AC2',
        given: 'a trip',
        when: 'I tap Edit, change its dates, and tap Save',
        then: 'expenses now dated in it join it and those outside leave, unless someone put them there by hand, and the audit trail records each field’s old and new value',
        decided: ADR23,
        checks: [
          'db/trips.int › files again when a trip’s dates change, and records each change',
          'api/trips › edits a trip and answers with it as it is now',
        ],
      },
      {
        id: 'AC3',
        given: 'two of my trips share a day, as when I fly from one straight to the next',
        when: 'an expense is dated that day',
        then: 'it files to the trip that ends first, so a hotel checkout stays with its stay, and a short trip inside a longer one keeps its own days',
        decided: ADR23,
        checks: [
          'domain/trips › gives a day two trips share to the trip that ends first, where the hotel bill belongs',
          'domain/trips › keeps a short trip’s days inside a longer one',
          'domain/trips › does not depend on the order the trips are listed in',
          'db/trips.int › gives a day two trips share to the trip that ends first',
        ],
      },
      {
        id: 'AC4',
        given: 'a trip',
        when: 'I tap Delete, then Delete the trip',
        then: 'it is gone; its expenses stay and file by date to any other trip that covers them, those I put on it included, and the audit trail records the trip and its expenses',
        decided: ADR23,
        checks: [
          'db/trips.int › files its expenses by date again, a person’s choice of it included',
          'api/trips › deletes a trip, unless something submitted rests on it',
        ],
      },
      {
        id: 'AC5',
        given: 'an expense that is submitted or later',
        when: 'a trip is made, redated or deleted',
        then: 'it stays on its trip, as its report does, and a trip it rests on can’t be deleted',
        decided: ADR23,
        checks: [
          'db/trips.int › never moves a submitted expense by date',
          'db/trips.int › refuses while a submitted expense rests on it, and reopens a closed report it was on',
          'api/trips › deletes a trip, unless something submitted rests on it',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt is read, or an expense edited, at the moment a trip is being made',
        when: 'both finish',
        then: 'the expense ends up on the trip, and neither waits on the other for ever',
        decided: ADR23,
        checks: [
          'db/trips.int › files an expense whose date arrives while the trip is being made',
          'db/trips.int › never deadlocks an edit to an expense against a trip filing it',
        ],
      },
    ],
  },
  {
    id: 'US-TRIP-03',
    title: 'Choose an expense’s trip, or none',
    as: 'Alex, a road warrior who travels for work',
    want: 'to put an expense on another trip, such as a flight booked weeks ahead, or on no trip, and have that choice stick',
    soThat: 'dates never undo a decision I made',
    feature: 'F-12',
    requirements: ['FR-EXP-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense filed by its date',
        when: 'I tap Change trip, choose a trip in Put it on, and tap Move it',
        then: 'it moves there, shows as put there by hand, and stays whatever its date or the trip’s dates later say',
        decided: ADR23,
        checks: [
          'db/trips.int › keeps an expense on the trip a person chose, whatever its date',
          'api/expenses › puts an expense on a trip a person chose, on none, or back to filing by date',
        ],
      },
      {
        id: 'AC2',
        given: 'an expense on a trip',
        when: 'I choose No trip and tap Move it',
        then: 'it leaves the trip, and dates never file it to one again',
        decided: ADR23,
        checks: [
          'db/trips.int › keeps an expense a person took off a trip off it',
          'api/expenses › puts an expense on a trip a person chose, on none, or back to filing by date',
        ],
      },
      {
        id: 'AC3',
        given: 'an expense I put somewhere by hand',
        when: 'I choose The trip its date falls in',
        then: 'it goes back to filing by date',
        decided: ADR23,
        checks: [
          'db/trips.int › keeps an expense on the trip a person chose, whatever its date',
          'api/expenses › puts an expense on a trip a person chose, on none, or back to filing by date',
        ],
      },
      {
        id: 'AC4',
        given: 'another member’s trip, or a trip that doesn’t exist',
        when: 'someone tries to put my expense on it',
        then: 'it is refused: an expense goes only on its owner’s trips',
        decided: ADR23,
        checks: [
          'db/trips.int › refuses a trip that is someone else’s or doesn’t exist, and a submitted expense',
          'api/expenses › refuses another member’s trip, a trip that doesn’t exist, and a submitted expense',
        ],
      },
      {
        id: 'AC5',
        given: 'an expense that is submitted or later',
        when: 'I try to move it',
        then: 'it is refused: it stays with its report',
        decided: ADR23,
        checks: [
          'db/trips.int › refuses a trip that is someone else’s or doesn’t exist, and a submitted expense',
          'api/expenses › refuses another member’s trip, a trip that doesn’t exist, and a submitted expense',
        ],
      },
      {
        id: 'AC6',
        given: 'I choose a trip, no trip, or filing by date',
        when: 'it is saved',
        then: 'the audit trail records who moved it, the trip it left and the one it joined',
        decided: AUDIT,
        checks: ['db/trips.int › keeps an expense on the trip a person chose, whatever its date'],
      },
    ],
  },
  {
    id: 'US-TRIP-04',
    title: 'Browse my trips and see what is on each',
    as: 'Alex, a road warrior who travels for work',
    want: 'to see my trips under way, upcoming and past, and open any one to its expenses day by day',
    soThat: 'I know which trips are done and what is left on the rest',
    feature: 'F-12',
    requirements: ['FR-EXP-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'trips before, around and after today',
        when: 'I open Trips',
        then: 'they are grouped as Under way, Upcoming and Past trips by my own date, the latest to start first',
        decided: ADR23,
        checks: [
          'domain/trips › on %s it is %s',
          'db/trips.int › finds trips by name, purpose, city or a merchant on them, and by dates',
        ],
      },
      {
        id: 'AC2',
        given: 'a trip in the list',
        when: 'I look at it',
        then: 'it shows its dates and city, how many of its expenses are ready and how many need a look, and its total in each currency, never converted',
        decided: { by: 'claude' },
        checks: [
          'api/trips › lists trips with their progress and a total per currency, never converted',
          'db/trips.int › lists a trip’s expenses by date and tallies them by currency and status',
        ],
      },
      {
        id: 'AC3',
        given: 'a trip',
        when: 'I open it',
        then: 'its timeline lists its expenses by day, undated ones last, each with its status and whether it was filed by date or put there by hand',
        decided: { by: 'blueprint', source: 'design §5.3' },
        checks: [
          'db/trips.int › lists a trip’s expenses by date and tallies them by currency and status',
          'api/trips › shows a trip with its expenses, each with the trip it is filed to',
        ],
      },
      {
        id: 'AC4',
        given: 'trips in another organization',
        when: 'I browse or open trips',
        then: 'none of them, nor what is on them, is ever shown',
        decided: TENANCY,
        checks: ['db/trips.int › keeps trips inside their organization'],
      },
      {
        id: 'AC5',
        given: 'I am not signed in',
        when: 'I open Trips or a trip, or ask the API for one',
        then: 'I am asked to sign in and no trip is shown',
        decided: { by: 'claude' },
        checks: [
          'e2e/trips › asks a signed-out visitor to sign in before showing any trip',
          'e2e/trips › refuses the trip endpoints without a signed-in user',
          'api/trips › answers 404 for a trip it does not have, and needs a signed-in member',
        ],
      },
    ],
    note: 'Trips lists only the person’s own trips, whatever their role (US-SEC-15); a trip is marked done when its report closes (#23).',
  },
  {
    id: 'US-TRIP-05',
    title: 'Find a past trip',
    as: 'Riley, a solo professional who self-attests',
    want: 'to find a trip by part of its name, purpose or city, a merchant I paid on it, or its dates',
    soThat: 'I can pull up any trip months later without remembering when it was',
    feature: 'F-12',
    requirements: ['FR-INS-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'my trips',
        when: 'I type in Name, purpose, city or merchant on Trips and tap Search',
        then: 'trips whose name, purpose or city contains it, in any case, or with an expense from a merchant that does, are listed',
        decided: SEARCH,
        checks: [
          'db/trips.int › finds trips by name, purpose, city or a merchant on them, and by dates',
          'api/trips › searches by text and dates, and refuses a date that does not exist',
        ],
      },
      {
        id: 'AC2',
        given: 'my trips',
        when: 'I enter From and To and tap Search',
        then: 'trips that share at least one day with that range are listed',
        decided: SEARCH,
        checks: [
          'db/trips.int › finds trips by name, purpose, city or a merchant on them, and by dates',
          'api/trips › searches by text and dates, and refuses a date that does not exist',
        ],
      },
      {
        id: 'AC3',
        given: 'a search with a % in it, or a date that doesn’t exist',
        when: 'I search',
        then: 'a % matches only itself, and a date that doesn’t exist is refused',
        decided: { by: 'claude' },
        checks: [
          'db/trips.int › finds trips by name, purpose, city or a merchant on them, and by dates',
          'api/trips › searches by text and dates, and refuses a date that does not exist',
        ],
      },
    ],
  },

  // Needs you
  {
    id: 'US-INBOX-01',
    title: 'See only what needs me, and why',
    as: 'Alex, a road warrior who travels for work',
    want: 'Home to open on a short list of only the things that need me, each saying why and what to do',
    soThat: 'I deal with the few exceptions and trust that everything else is done',
    feature: 'F-10',
    requirements: ['FR-EXP-02'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given:
          'receipts of mine, some Ready, some being read, some needing a look and some Not read',
        when: 'I open Home',
        then: 'Needs you lists only those that need a look or that nothing could read, newest first',
        decided: { by: 'blueprint', source: 'design DP2' },
        checks: [
          'api/receipts › lists what needs a look or could not be read, newest first, each with why',
          'db/receipts.int › lists only the receipts in the statuses asked for, newest first',
        ],
      },
      {
        id: 'AC2',
        given: 'a receipt in Needs you',
        when: 'I look at it',
        then: 'it says why: nothing could read it, the models read a field differently, only the fallback model read it, a check on its sums or date failed, or a model wasn’t sure',
        decided: { by: 'blueprint', source: 'design §5.3' },
        checks: [
          'api/receipts › lists what needs a look or could not be read, newest first, each with why',
          'api/receipts › says which check failed when the models agree',
        ],
      },
      {
        id: 'AC3',
        given: 'a receipt in Needs you',
        when: 'I look at it',
        then: 'it offers one thing to do: Check it, Fill it in when nothing could read it, Open it when the models were unavailable, or Open settings when a key is the problem',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'more than three things need me',
        when: 'I open Home',
        then: 'Needs you shows the first three and the count of all of them, and Show all opens the rest in place',
        decided: { by: 'claude' },
        checks: [
          'api/home › counts everything that needs the person, and shows the newest three',
          'e2e/signed-in',
        ],
        rules: ['R-HOME-NEEDS'],
      },
      {
        id: 'AC5',
        given: 'nothing needs me',
        when: 'I open Home',
        then: 'Needs you is empty and says nothing needs me right now',
        decided: { by: 'blueprint', source: 'design DP2' },
        checks: [
          'api/receipts › is empty when nothing needs the person, and needs a signed-in member',
        ],
      },
      {
        id: 'AC6',
        given: 'another member of my organization has receipts that need a look',
        when: 'I open Home',
        then: 'none of theirs is in my Needs you',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC7',
        given: 'receipts in another organization',
        when: 'I open Home',
        then: 'none of them is ever listed',
        decided: TENANCY,
        checks: ['db/receipts.int › keeps receipts inside their organization'],
      },
      {
        id: 'AC8',
        given: 'I am not signed in, or not yet in an organization',
        when: 'Needs you is asked for',
        then: 'it is refused, and nothing is listed',
        decided: { by: 'claude' },
        checks: [
          'api/receipts › is empty when nothing needs the person, and needs a signed-in member',
        ],
      },
    ],
    note: 'A held duplicate is in Needs you too, naming the receipt it looks like (US-DUP-02). Since PR #52 so are a report overdue or in its last week, a local expense needing a reason, and a report ready to close; their stories are with reports (FR-EXP-12, FR-EXP-14). Returned reports join with approval (#24), and missing receipts with card transactions (FR-CAP-06).',
  },

  // Home
  {
    id: 'US-HOME-01',
    title: 'See the trip I am on, or the next one, and my recent trips',
    as: 'Alex, a road warrior who travels for work',
    want: 'Home to show the trip I am on, or the one coming up, and whether my recent trips are done',
    soThat: 'I see where I stand on each trip without opening Trips',
    feature: 'F-22',
    requirements: ['FR-INS-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a trip of mine is under way today, by my own date',
        when: 'I open Home',
        then: 'beneath Needs you, On a trip shows it as day N of its days, with its spend so far in each currency, its expenses and how many are still to check',
        decided: OCT3,
        checks: [
          'api/home › shows the trip under way as which day of it, with its totals',
          'db/home.int › finds the trip under way, or else the next within two weeks',
        ],
      },
      {
        id: 'AC2',
        given: 'no trip under way, and one of mine starting within 14 days',
        when: 'I open Home',
        then: 'Coming up shows it with how many days until it starts; with none that soon, there is no trip card',
        decided: { by: 'claude' },
        checks: [
          'api/home › shows the next trip as days until it starts, or no trip at all',
          'db/home.int › finds the trip under way, or else the next within two weeks',
        ],
      },
      {
        id: 'AC3',
        given: 'trips of mine that ended before today',
        when: 'I open Home',
        then: 'Recent trips lists the last three to end, latest first, each with its total and whether all its expenses are Ready or how many need a look',
        decided: { by: 'claude' },
        checks: [
          'db/home.int › lists the last three trips to end before the day, with what is on them',
          'api/home › adds up the month per currency, never converted, and what is on no trip',
        ],
      },
      {
        id: 'AC4',
        given: 'my day is not the same as the day in UTC',
        when: 'I open Home',
        then: 'the trip under way, the next trip and the month are worked out from my own date',
        decided: ADR23,
        checks: [
          'api/home › builds Home for the person’s own day, scoped to them',
          'api/home › defaults to today in UTC when no day is given',
        ],
      },
    ],
  },
  {
    id: 'US-HOME-02',
    title: 'See this month at a glance',
    as: 'Riley, a solo professional who self-attests',
    want: 'Home to show this month’s spend, expenses and trips, what is on no trip, and what is still being read',
    soThat: 'I know where the month stands without adding anything up',
    feature: 'F-22',
    requirements: ['FR-INS-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'expenses of mine dated this month',
        when: 'I open Home',
        then: 'this month so far shows what I spent in each currency, never converted, how many expenses, how many trips, and how many of the expenses are Ready or further on',
        decided: { by: 'blueprint', source: 'design §5.3' },
        checks: [
          'api/home › adds up the month per currency, never converted, and what is on no trip',
          'db/home.int › tallies this month’s expenses by status, currency and whether on a trip',
        ],
      },
      {
        id: 'AC2',
        given: 'expenses of mine this month that are on no trip',
        when: 'I open Home',
        then: 'Not on a trip shows how many and their total, and opens Expenses for this month on no trip',
        decided: { by: 'owner', source: 'Q14' },
        checks: [
          'api/home › adds up the month per currency, never converted, and what is on no trip',
          'api/expenses › finds the expenses on no trip, or on some trip (Home’s figures open them)',
        ],
      },
      {
        id: 'AC3',
        given: 'receipts of mine still being read',
        when: 'I open Home',
        then: 'one line says how many are being read',
        decided: OCT3,
        checks: [
          'db/home.int › counts the member’s receipts still being read',
          'api/home › adds up the month per currency, never converted, and what is on no trip',
        ],
      },
      {
        id: 'AC4',
        given: 'a receipt held as a possible duplicate',
        when: 'I open Home',
        then: 'its expense counts in none of this month’s figures until I decide',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › holds a later copy of a purchase for a look, and leaves it out of Home’s totals',
        ],
      },
    ],
    note: 'Q14 made expenses on no trip a figure, not items in Needs you. Since your answer to Q21, one that is Ready and still needs a reason is in Needs you as a local expense (FR-EXP-14).',
  },
  {
    id: 'US-HOME-03',
    title: 'Trust every figure on Home and act on it',
    as: 'Alex, a road warrior who travels for work',
    want: 'every figure on Home to be my own and to open the list behind it, with empty sections left out',
    soThat: 'Home is short, and one tap takes me from a number to the expenses in it',
    feature: 'F-22',
    requirements: ['FR-INS-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I open Home',
        when: 'it loads',
        then: 'Needs you comes first, and the dashboard sits beneath it',
        decided: OCT3,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC2',
        given: 'another member of my organization has trips and expenses',
        when: 'I open Home',
        then: 'none of theirs is in my trip, my month or my recent trips',
        decided: { by: 'claude' },
        checks: [
          'db/home.int › shows each member only their own trips, expenses and receipts',
          'api/home › builds Home for the person’s own day, scoped to them',
        ],
      },
      {
        id: 'AC3',
        given: 'another member of my organization has receipts still being read',
        when: 'I open Home',
        then: 'they are not counted in my receipts being read',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'a figure on Home',
        when: 'I tap it',
        then: 'it opens the list behind it: Spent and Ready to file open this month’s expenses, Not on a trip those on no trip, Trips the trip list, a trip its timeline, and receipts being read the Receipts page',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given:
          'a section with nothing to say: no trip under way or coming up, nothing this month, no receipt being read, or no recent trip',
        when: 'I open Home',
        then: 'that section is left out',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given:
          'Home with a trip under way, with one coming up, and with everything in Needs you open',
        when: 'it is shown on a phone or a desktop, in light or dark',
        then: 'it fits the screen and passes WCAG 2.2 AA',
        decided: { by: 'blueprint', source: 'design DP5' },
        checks: ['e2e/signed-in'],
      },
    ],
    note: 'Reports to finish are on Home since PR #52; their story is with reports (FR-EXP-05). The Trips figure counts this month’s trips but opens every trip.',
  },
  {
    id: 'US-HOME-04',
    title: 'See my business miles and what awaits reimbursement',
    as: 'Riley, a solo professional who self-attests',
    want: 'Home to show this month’s business miles and the money I am still owed, once each exists',
    soThat: 'the month’s figures are whole without a separate log or a spreadsheet',
    feature: 'F-22',
    requirements: ['FR-INS-01'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'business miles I logged this month',
        when: 'I open Home',
        then: 'this month so far shows my business miles',
        decided: { by: 'blueprint', source: 'design §5.3' },
        checks: [],
      },
      {
        id: 'AC2',
        given: 'approved expenses not yet paid to me',
        when: 'I open Home',
        then: 'it shows what awaits reimbursement',
        decided: { by: 'blueprint', source: 'design §5.3' },
        checks: [],
      },
    ],
    note: 'Mileage is built (#17), and business miles join Home with #73; what awaits reimbursement once payouts exist.',
  },
  // Category suggestions (FR-INT-10, ADR-0036)
  {
    id: 'US-EXP-05',
    title: 'A category and type suggested for each expense',
    as: 'Alex, who travels for work',
    want: 'each expense to come with a category and type already suggested, for me to confirm with a tap',
    soThat: 'coding my expenses takes no thought and no typing',
    feature: 'F-15',
    requirements: ['FR-INT-10'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense with no category and type chosen',
        when: 'I open it, or the expense list',
        then: 'a type and its category are suggested, shown as a suggestion until I confirm it',
        decided: { by: 'blueprint', source: 'design §5.3' },
        checks: [
          'api/categories › suggests one from what the expense shows, marked as a suggestion, or says it has none',
          'e2e/signed-in › an expense with a suggested category',
        ],
      },
      {
        id: 'AC2',
        given: 'a suggestion',
        when: 'I tap Use this, or choose another',
        then: 'what I chose is the expense’s, recorded as mine; until then nothing is stored',
        decided: { by: 'blueprint', source: 'arch §6.5' },
        checks: [
          'api/categories › takes a type its category allows, confirmed from then on',
          'db/categories.int › takes a type its category allows, once, and records who chose it',
        ],
      },
      {
        id: 'AC3',
        given: 'a receipt read as an airline ticket, a hotel folio or a ride receipt',
        when: 'a suggestion is worked out',
        then: 'what the reading says the document is decides it, before any word of the merchant’s name',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'domain/categories › goes by what the reading says the document is before any word',
        ],
      },
      {
        id: 'AC4',
        given: 'nothing I chose before fits',
        when: 'a suggestion is worked out',
        then: 'words in the merchant’s name, such as hotel, airlines, taxi or restaurant, suggest a ready-made type, still found once renamed and never once retired; a mileage expense is suggested Mileage',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'domain/categories › suggests %s as %s from the words of its name',
          'domain/categories › suggests a ready-made type under another category that allows it, and never a retired one',
          'domain/categories › suggests Mileage for a mileage expense, whatever its words',
        ],
      },
      {
        id: 'AC5',
        given: 'nothing fits',
        when: 'a suggestion is worked out',
        then: 'nothing is suggested, and the expense says it has no category',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: ['domain/categories › suggests nothing when no rule fits'],
      },
      {
        id: 'AC6',
        given: 'any expense',
        when: 'a suggestion is worked out',
        then: 'no AI model is asked and nothing is spent: it is worked out by rules from what ExpenseWise already holds',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: ['domain/categories'],
      },
    ],
    note: 'Suggestions are rule-based by Claude’s decision to spend nothing on them, as the blueprint’s enrich stage is ordinary code (arch §6.5, ADR-0036). They come with categories: switching `expenses.categories` on brings both.',
  },
  {
    id: 'US-EXP-06',
    title: 'Suggestions learn from what I chose',
    as: 'Alex, who travels for work',
    want: 'the type I chose for a merchant last time to be suggested for it again',
    soThat: 'my regular merchants are coded my way without my choosing each time',
    feature: 'F-15',
    requirements: ['FR-INT-10'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I chose a category and type for an expense at a merchant',
        when: 'another expense of mine at that merchant needs one',
        then: 'what I chose last is suggested first, the merchant matched as duplicates are, so Uber and Uber Technologies Inc. are one',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'domain/categories › suggests what the person last chose for the same merchant, matched loosely',
          'db/categories.int › learns from each member’s own choices, newest first, for expenses that name a merchant',
        ],
      },
      {
        id: 'AC2',
        given: 'a colleague chose differently for the same merchant',
        when: 'my expense is suggested a type',
        then: 'only my own choices count',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: ['api/categories › suggests what its owner last chose for the same merchant first'],
      },
      {
        id: 'AC3',
        given: 'what I chose last can no longer be chosen, retired or no longer allowed',
        when: 'a suggestion is worked out',
        then: 'it is passed over for the next that can, or a keyword rule',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: ['domain/categories › passes over a past choice that can no longer be made'],
      },
      {
        id: 'AC4',
        given: 'an expense whose merchant is blank or edited',
        when: 'my history is matched',
        then: 'the merchant as its receipt was read is matched too',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'domain/categories › matches history on the merchant as read when the expense has none',
        ],
      },
    ],
  },
];
