import type { Story } from '../model.ts';

const OCT3 = { by: 'owner', source: 'owner 2026-10-03' } as const;
const Q12 = { by: 'owner', source: 'Q12' } as const;
const Q13 = { by: 'owner', source: 'Q13' } as const;
const Q26 = { by: 'owner', source: 'Q26' } as const;
const Q5 = { by: 'owner', source: 'Q5' } as const;
const CLAUDE = { by: 'claude' } as const;
const ADR13 = { by: 'blueprint', source: 'ADR-0013' } as const;
const ADR14 = { by: 'claude', source: 'ADR-0014' } as const;
const ADR17 = { by: 'blueprint', source: 'ADR-0017' } as const;
const ADR18 = { by: 'blueprint', source: 'ADR-0018' } as const;
const ADR19 = { by: 'blueprint', source: 'ADR-0019' } as const;
const DP4 = { by: 'blueprint', source: 'design DP4' } as const;
const DP5 = { by: 'blueprint', source: 'design DP5' } as const;
const DP6 = { by: 'blueprint', source: 'design DP6' } as const;
const AP7 = { by: 'blueprint', source: 'arch AP7' } as const;
const GATES = { by: 'blueprint', source: 'delivery §7.4' } as const;
const TESTING = { by: 'blueprint', source: 'delivery §7.5' } as const;
const RELEASES = { by: 'blueprint', source: 'delivery §7.7' } as const;

/**
 * Running the service (US-OPS), releases and quality gates (US-REL), these records and their
 * pages (US-DOC), and the app shell, layout and accessibility checks (US-UX).
 */
export const OPERATIONS_STORIES: readonly Story[] = [
  {
    id: 'US-OPS-01',
    title: 'See what is live and whether it is safe',
    as: 'the product owner, who runs the service',
    want: 'to ask production which build it runs and whether it can safely serve anyone’s data',
    soThat:
      'a release can be confirmed live, and a fault that could show one organization another’s data shows up as not ready',
    feature: 'F-30',
    requirements: ['NFR-OPS-02', 'NFR-REL-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'production is up',
        when: 'anyone asks its health check',
        then: 'it answers that it is up and names the commit it runs, without touching the database',
        decided: ADR18,
        checks: [
          'api/api › reports health and the deployed version',
          'e2e/shell › serves health and the OpenAPI contract under /api',
        ],
      },
      {
        id: 'AC2',
        given:
          'the app connects to the database as its own role, which can’t bypass row-level security',
        when: 'the readiness check runs',
        then: 'the role check passes; connected as Supabase’s administrator role, or as the relay’s role, it fails and names the role',
        decided: ADR13,
        checks: [
          'db/readiness.int › is ready as expensewise_app on a migrated database',
          'db/readiness.int › is not ready as a role that bypasses row-level security',
          'db/readiness.int › is not ready as the relay role',
        ],
      },
      {
        id: 'AC3',
        given:
          'the database answers, the role is right, the connection is verified against Supabase’s root certificate, and every tenant table forces row-level security',
        when: 'anyone asks the readiness check',
        then: 'it answers ready with a report of each check, never kept by a browser or proxy; when any check fails it answers not ready with the same report',
        decided: CLAUDE,
        checks: [
          'api/ready › answers 200 with the report when every check passes, never cached',
          'api/ready › answers 503 with the report when a check fails',
          'db/readiness › passes for Supabase, which is verified against its root certificate',
        ],
      },
      {
        id: 'AC4',
        given:
          'a tenant table that doesn’t force row-level security, the outbox the relay reads aside, or a database whose migrations have not run',
        when: 'the readiness check runs',
        then: 'it answers not ready and names the tables',
        decided: CLAUDE,
        checks: [
          'db/readiness › passes when every tenant table forces RLS, outbox aside',
          'db/readiness › names tables without enforced RLS',
          'db/readiness › fails when migrations have not run',
        ],
      },
      {
        id: 'AC5',
        given:
          'a wrong database password, a database that can’t be reached, or a connection setting that can’t be read',
        when: 'the readiness check runs',
        then: 'it answers not ready within seconds with a plain reason, and never shows the connection setting or the password',
        decided: CLAUDE,
        checks: [
          'db/readiness.int › reports a wrong password without echoing the connection string',
          'db/readiness.int › reports an unreachable database quickly',
          'db/readiness › reports an unusable connection string without echoing it',
          'api/ready › answers 503, not 500, when the probe throws, without echoing the error',
        ],
      },
      {
        id: 'AC6',
        given: 'the readiness check was answered moments ago',
        when: 'it is asked again',
        then: 'the same report is reused for a short while, 15 seconds in production, so polling it can’t load the database',
        decided: CLAUDE,
        checks: ['db/readiness › reuses a report within the cache window and refreshes after it'],
      },
      {
        id: 'AC7',
        given: 'production can’t safely serve',
        when: 'a check from outside the app asks the readiness check',
        then: 'it gets a not-ready answer it can alert on, matching the report',
        decided: RELEASES,
        checks: [
          'e2e/shell › reports readiness with a status that matches the report',
          'api/ready › answers 503 when no probe is configured',
        ],
      },
    ],
    note: 'Nothing outside the app calls the readiness check yet, so availability isn’t measured and nobody is told when production is down (GAP-08, #14).',
  },
  {
    id: 'US-OPS-02',
    title: 'Hear about errors without ever seeing a secret in them',
    as: 'the product owner, who runs the service',
    want: 'every unexpected error, on the server or in the browser, to reach one place that alerts me, with request contents and secrets left out',
    soThat:
      'I learn of a fault before it costs a receipt, and an error report never leaks a password or anyone’s data',
    feature: 'F-32',
    requirements: ['NFR-OPS-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'the API meets an error nobody planned for',
        when: 'it answers the request',
        then: 'the caller gets a plain error that hides the error’s own text, and the error is reported to error tracking',
        decided: { by: 'blueprint', source: 'arch §6.3' },
        checks: ['api/api › maps broken business rules to 422 and hides internal errors'],
      },
      {
        id: 'AC2',
        given: 'a request breaks a business rule, such as adding dollars to euros',
        when: 'the API refuses it',
        then: 'the caller is told which rule, and it is not reported as an error, since it is no fault',
        decided: CLAUDE,
        checks: ['api/api › maps broken business rules to 422 and hides internal errors'],
      },
      {
        id: 'AC3',
        given:
          'an error’s text holds a database connection string, a bearer token, a sign-in token or a vendor key',
        when: 'it is reported',
        then: 'each is replaced by a redaction mark in the message, the exception and the console trail, and the host and everything else are kept',
        decided: CLAUDE,
        checks: [
          'api/redact › removes credentials from connection strings but keeps the host',
          'api/redact › removes bearer tokens, JWTs and vendor keys',
          'api/redact › redacts the message, exception values and breadcrumbs, and keeps the rest',
        ],
      },
      {
        id: 'AC4',
        given: 'error tracking is on',
        when: 'it collects an event',
        then: 'it takes no request or response bodies, cookies, query strings, database parameters, local variables or user details',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'an error in the browser, or while a page is drawn on the server',
        when: 'it happens',
        then: 'it is reported to the same place as the API’s errors, with the same redaction',
        decided: { by: 'blueprint', source: 'arch §6.3' },
        checks: [],
        untested: 66,
      },
    ],
    note: 'Error tracking is built but has no destination: no Sentry project is connected in production, so errors reach only Vercel’s short-lived logs and nothing alerts (GAP-07, #13).',
  },
  {
    id: 'US-OPS-03',
    title: 'Never lose a receipt between filing and reading',
    as: 'Alex, who travels for work and files receipts from an iPhone',
    want: 'every receipt I file to be read and settled, even when the service that reads it is down for a while',
    soThat: 'no receipt is lost, or left saying Reading for ever',
    feature: 'F-33',
    requirements: ['NFR-DAT-07'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I file a receipt',
        when: 'it is saved',
        then: 'the receipt and the event that has it read are stored in one step, so a receipt never exists without that event',
        decided: { by: 'blueprint', source: 'arch §6.4' },
        checks: [
          'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
        ],
      },
      {
        id: 'AC2',
        given: 'the receipt is saved',
        when: 'my request finishes',
        then: 'its event goes to the workflow runner at once, and filing the same receipt again sends nothing more',
        decided: ADR17,
        checks: [
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
        ],
      },
      {
        id: 'AC3',
        given: 'the workflow runner can’t be reached',
        when: 'I file a receipt',
        then: 'it is still filed, and its event waits in the outbox for the relay',
        decided: ADR17,
        checks: [
          'api/receipts › still files the receipt when the runner is unreachable; the relay sends it later',
        ],
      },
      {
        id: 'AC4',
        given: 'events wait in the outbox',
        when: 'the relay runs, every 5 minutes or when nudged, one run at a time',
        then: 'it claims them across organizations and marks each batch sent only after sending it',
        decided: { by: 'claude', source: 'ADR-0017' },
        checks: [
          'workflows/functions › runs on the sweep schedule and on a nudge, one run at a time',
          'workflows/relay › sends each batch before marking it published',
          'db/outbox.int › lets the relay claim events across organizations, once, then mark them published',
        ],
      },
      {
        id: 'AC5',
        given: 'sending fails, or the relay stops after claiming events',
        when: 'their 5-minute claim runs out',
        then: 'they are claimed and sent again under the same event id, so the runner can drop a copy it already has',
        decided: { by: 'claude', source: 'ADR-0017' },
        checks: [
          'workflows/relay › marks nothing published when sending fails, so the lease expires and it is retried',
          'db/outbox.int › claims an unpublished event again once its claim has expired',
          'workflows/relay › uses the outbox id as the event id and the change time as the timestamp',
        ],
      },
      {
        id: 'AC6',
        given: 'the relay’s own database role',
        when: 'it works',
        then: 'it can only claim events and mark them sent, never read the app’s tables, and the app can’t claim events',
        decided: CLAUDE,
        checks: [
          'db/outbox.int › keeps the relay away from table data and the app away from the relay functions',
        ],
      },
      {
        id: 'AC7',
        given: 'no model can read a receipt, the fallback included',
        when: 'every reading has failed',
        then: 'it settles as Not read, never left Reading',
        decided: ADR17,
        checks: ['workflows/receipts › settles as failed when the fallback has no credit either'],
      },
      {
        id: 'AC8',
        given: 'the reading workflow itself fails and runs out of retries',
        when: 'it gives up',
        then: 'the receipt is settled from whatever readings were stored, so it never stays Reading',
        decided: ADR17,
        checks: [],
        untested: 66,
      },
    ],
    note: 'In production the relay isn’t running, because its database setting isn’t set in Vercel, so a receipt whose first send fails waits until someone presses Read again (GAP-05, #11). Nothing yet finds a receipt stuck in Reading, as the hourly check the service level objective names would (GAP-06, #12).',
  },
  {
    id: 'US-OPS-04',
    title: 'Keep an encrypted copy of everything at a second vendor',
    as: 'the product owner, whose receipts are tax evidence',
    want: 'the database, sign-in accounts included, and every receipt image copied every night, encrypted, to a second vendor',
    soThat: 'a bad migration, a bug or a lost Supabase project never loses a record',
    feature: 'F-37',
    requirements: ['NFR-REL-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'it is night, at about 2 a.m. in California',
        when: 'the nightly backup runs',
        then: 'it dumps the whole database, sign-in accounts included, as Supabase documents, encrypts the dump on the runner and uploads it to a private Backblaze B2 bucket',
        decided: ADR14,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC2',
        given: 'the dump is uploaded',
        when: 'the job goes on',
        then: 'it downloads that copy again and checks it decrypts to the same bytes, or the run fails',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'receipt images added since the last run',
        when: 'the backup runs',
        then: 'each is copied, encrypted, and no image is ever deleted from the copy',
        decided: ADR14,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'the dumps in the bucket',
        when: 'they age',
        then: 'the last 30 daily dumps and one for each of the last 12 months are kept, and nobody can delete a file in its first 30 days, not even the owner',
        decided: ADR14,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'the repository and its logs are public',
        when: 'the backup runs',
        then: 'its log shows steps, counts, sizes and timings only, never data, file names or credentials, and it keeps nothing to download',
        decided: ADR14,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given: 'a scheduled run fails',
        when: 'it ends',
        then: 'GitHub emails the owner',
        decided: ADR14,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Runs every night since Oct 3. That day you decrypted the first copy with the passphrase from your password manager, and the failure email of the first run reached you. The restore drill (US-OPS-05) proves each month that the copy restores. After a file’s 30-day lock, the job’s own key could still delete it (GAP-18, #48).',
  },
  {
    id: 'US-OPS-05',
    title: 'Prove every month that the backup restores',
    as: 'the product owner, whose receipts are tax evidence',
    want: 'the newest backup restored and checked every month, the way a real recovery would use it',
    soThat:
      'I know the backup works before the day I need it, losing a day at most and back within four hours',
    feature: 'F-41',
    requirements: ['NFR-REL-02', 'NFR-REL-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'it is the 2nd of the month',
        when: 'the restore drill runs',
        then: 'it restores the newest backup into a throwaway Supabase stack, with its database, auth and storage, and brings this commit’s newer migrations forward',
        decided: ADR14,
        checks: [
          'db/restore-drill.int › finds the restored migrations are this commit’s first ones, then brings them forward',
        ],
      },
      {
        id: 'AC2',
        given: 'the restored database',
        when: 'it is checked',
        then: 'each table has the rows the backup counted, the tables Supabase keeps for itself aside; a table short of rows, or missing, fails the drill',
        decided: ADR14,
        checks: [
          'db/restore-drill.int › matches row counts, leaving out the tables Supabase keeps for itself',
        ],
      },
      {
        id: 'AC3',
        given: 'two organizations restored',
        when: 'each is read signed in as the app',
        then: 'each sees only its own rows; a policy that lets rows leak, or row-level security off on any table, fails the drill',
        decided: ADR14,
        checks: [
          'db/restore-drill.int › finds each organization sees only its own rows',
          'db/restore-drill.int › fails when a policy lets rows leak',
          'db/restore-drill.int › fails when row-level security is off for a table',
        ],
      },
      {
        id: 'AC4',
        given:
          'a migration edited after production applied it, or a restored schema that differs from the committed one',
        when: 'the drill checks the restore',
        then: 'it fails, naming the migration or the table',
        decided: CLAUDE,
        checks: [
          'db/restore-drill.int › fails when a migration was edited after production applied it',
          'db/restore-drill.int › fails when a policy lets rows leak',
        ],
      },
      {
        id: 'AC5',
        given: 'the newest dump',
        when: 'it is downloaded',
        then: 'it must decrypt with the passphrase and each of its files match the checksum the backup recorded, or the drill stops',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given: 'a sample of up to 100 receipts',
        when: 'their images are fetched from the copy and decrypted',
        then: 'each must match the checksum its receipt recorded; one missing or different fails the drill',
        decided: { by: 'blueprint', source: 'roadmap inc 4' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC7',
        given:
          'the newest dump is more than 24 hours old, or the whole drill takes more than 4 hours',
        when: 'the drill runs',
        then: 'it fails: the recovery point or the recovery time is missed',
        decided: ADR14,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC8',
        given: 'a scheduled drill fails',
        when: 'it ends',
        then: 'GitHub emails the owner',
        decided: ADR14,
        checks: [],
        untested: 66,
      },
    ],
    note: 'On Oct 3 it restored production’s backup with every check passing: the dump 22 minutes old, all 6 receipt images matching, in 1 min 11 s. The image, checksum and recovery-time checks run in the drill’s script, rehearsed by hand, not in CI. A whole recovery, into a new Supabase project with Vercel pointed at it, has not been rehearsed or timed against the 4 hours (#56).',
  },
  {
    id: 'US-OPS-06',
    title: 'Keep the Free plan from pausing or filling up unnoticed',
    as: 'the product owner, who runs production on Supabase’s Free plan',
    want: 'the project kept active while I’m away, and a warning well before the database or file storage is full',
    soThat: 'sign-in and capture never stop because the project paused or ran out of room',
    feature: 'F-42',
    requirements: ['NFR-REL-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'the nightly job writes the heartbeat',
        when: 'it runs again, however often',
        then: 'the heartbeat stays one row, with the latest time',
        decided: ADR14,
        checks: ['db/heartbeat.int › takes the nightly write as one row, however often it runs'],
      },
      {
        id: 'AC2',
        given: 'the app, the relay or Supabase’s Data API roles',
        when: 'they try to read or write the heartbeat',
        then: 'they are refused',
        decided: CLAUDE,
        checks: ['db/heartbeat.int › is out of reach of the app, the relay and the Data API roles'],
      },
      {
        id: 'AC3',
        given: 'a later step fails, such as Backblaze being down',
        when: 'the nightly job runs',
        then: 'the heartbeat has already been written, since it comes first',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'the database has passed 70% of its 500 MB limit, or file storage 70% of its 1 GB',
        when: 'the nightly job measures them',
        then: 'the run fails and GitHub emails the owner',
        decided: ADR14,
        checks: [],
        untested: 66,
      },
    ],
    note: 'The quota alert was rehearsed by hand, not in CI.',
  },
  {
    id: 'US-OPS-07',
    title: 'Be able to leave any vendor',
    as: 'the product owner',
    want: 'every vendor the app depends on kept behind the app’s own interface, and every decision about a vendor recording how to leave it',
    soThat: 'a price rise, an outage or a better model never traps the product',
    requirements: ['NFR-ARC-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an AI model reads a receipt',
        when: 'the reading pipeline asks for a reading',
        then: 'it talks only to the app’s own reader, with each Claude and OpenAI model behind it, so a model or provider can change without touching the pipeline',
        decided: AP7,
        checks: [
          'extraction/claude › sends the image, the schema and the tier effort, and prices the call',
          'extraction/openai › sends the image, the strict schema and the effort, stores nothing, and prices the call',
        ],
      },
      {
        id: 'AC2',
        given: 'a receipt’s file',
        when: 'it is stored, fetched or removed',
        then: 'it goes through the app’s own file store, with Supabase Storage behind it',
        decided: AP7,
        checks: [
          'storage/supabase › creates the private bucket once, then signs uploads with the secret key',
          'storage/supabase › downloads bytes, and reports a missing object as null',
          'storage/supabase › removes an object by its path',
        ],
      },
      {
        id: 'AC3',
        given: 'a feature flag',
        when: 'it is read',
        then: 'it goes through the app’s own flags, with PostHog as one source behind them',
        decided: AP7,
        checks: [
          'flags/flags › follows the source, and reads a flag the source omits as off',
          'flags/posthog › evaluates for the server when there is no user, and keeps only flags PostHog returned',
        ],
      },
      {
        id: 'AC4',
        given: 'a decision about a vendor',
        when: 'it is recorded as an ADR',
        then: 'the ADR says how to leave that vendor or reverse the decision',
        decided: { by: 'blueprint', source: 'risks R5' },
        checks: [],
        untested: 66,
      },
    ],
    note: 'The database, sign-in and files are all on Supabase. Leaving it uses standard Postgres and the same dumps and image copies the restore drill (US-OPS-05) restores each month (ADR-0013, ADR-0014).',
  },
  {
    id: 'US-REL-01',
    title: 'Merge nothing until every gate passes',
    as: 'the product owner, who approves each merge',
    want: 'every pull request checked automatically, end to end, before I am asked to merge it',
    soThat:
      'a change that breaks a rule, a test, the contract, security or a screen never reaches production',
    feature: 'F-35',
    requirements: ['NFR-DEL-01', 'NFR-DEL-02', 'NFR-DEL-06'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a pull request',
        when: 'gate G1 runs',
        then: 'formatting, lint and strict type checks must pass before it is merged',
        decided: GATES,
        checks: ['ci:static'],
      },
      {
        id: 'AC2',
        given: 'a pull request',
        when: 'gate G2 runs',
        then: 'every unit test, these records’ checks among them, must pass before it is merged, and the domain package must keep at least 90% of its lines, branches, functions and statements covered',
        decided: TESTING,
        checks: ['ci:unit'],
      },
      {
        id: 'AC3',
        given: 'a pull request',
        when: 'gate G3 runs',
        then: 'before it is merged, the integration tests must pass against a real Postgres, and the committed API contract and database migrations must match the code',
        decided: GATES,
        checks: ['ci:integration'],
      },
      {
        id: 'AC4',
        given: 'a pull request',
        when: 'gate G4 runs',
        then: 'the secret scan, a dependency audit that fails on any high or critical advisory, and static analysis must pass before it is merged',
        decided: GATES,
        checks: ['ci:security', 'ci:codeql'],
      },
      {
        id: 'AC5',
        given: 'a pull request',
        when: 'gate G5 runs',
        then: 'before it is merged, the app must build, and the end-to-end journeys and the layout and accessibility checks of every screen, signed out and in, must pass in desktop Chromium and iPhone WebKit',
        decided: GATES,
        checks: ['ci:e2e'],
      },
      {
        id: 'AC6',
        given: 'an end-to-end test fails',
        when: 'gate G5 runs',
        then: 'the test is not run again to look for a pass: the failure fails the gate',
        decided: TESTING,
        checks: ['ci:e2e'],
      },
      {
        id: 'AC7',
        given: 'a test that fails only sometimes',
        when: 'it is found',
        then: 'it is fixed as a bug, never skipped, quarantined or retried to get to green',
        decided: TESTING,
        checks: [],
        untested: 66,
      },
    ],
    note: 'The gates run again on main after each merge. G3 has no breaking-change diff of the contract and doesn’t rehearse migrations on a copy (GAP-11, #34). G4 audits dependencies with pnpm rather than OSV-Scanner, and has no license check. Gate G6 needs a staging environment, which Phase 1 doesn’t have (ADR-0025). That a flaky test is fixed, not hidden, is a rule Claude follows (CLAUDE.md); nothing checks it.',
  },
  {
    id: 'US-REL-02',
    title: 'Release a change on my word, in a safe order',
    as: 'the product owner, who approves each release',
    want: 'my word to merge a pull request to release it: the database migrated first, then that commit’s build made live and checked',
    soThat:
      'one decision releases a change, code never goes live before its migration, and an older run never rolls production back',
    feature: 'F-36',
    requirements: ['NFR-DEL-03', 'NFR-DEL-04', 'NFR-REL-07'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a pull request with every gate green',
        when: 'I say merge for that pull request',
        then: 'Claude merges it, and never merges one I haven’t named',
        decided: ADR19,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC2',
        given: 'a merge to main',
        when: 'CI passes on the merged commit',
        then: 'the Release run starts at once, with no second approval',
        decided: { by: 'owner', source: 'owner 2026-10-09' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'the Release run',
        when: 'it starts',
        then: 'it applies the database migrations before anything goes live',
        decided: ADR18,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'the migrations are applied',
        when: 'the run sets the passwords of the app’s and the relay’s database roles',
        then: 'it leaves a role alone when it already signs in, and sets its password again only when it can’t',
        decided: ADR18,
        checks: [
          'db/role-passwords.int › leaves a role alone when it already signs in, so a pooler cache stays valid',
          'db/role-passwords.int › sets the password again when the role cannot sign in, and it still works',
        ],
      },
      {
        id: 'AC5',
        given: 'Vercel has built this commit for production',
        when: 'the run promotes that build',
        then: 'it checks production’s health check reports this commit, and fails if it doesn’t within 5 minutes',
        decided: ADR18,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given: 'main has moved on to a newer commit',
        when: 'an older run reaches promotion',
        then: 'it migrates but doesn’t promote, so production is never rolled back',
        decided: ADR18,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC7',
        given: 'a commit Vercel doesn’t build, such as a change to docs alone',
        when: 'the run finds no build of it',
        then: 'it finishes with production unchanged',
        decided: ADR18,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC8',
        given: 'a migration',
        when: 'it is written',
        then: 'it keeps the build already live working: expand, migrate, then contract in a later release',
        decided: RELEASES,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC9',
        given: 'a merge to main whose gates fail there',
        when: 'CI completes on it',
        then: 'nothing is released, and production stays on the last commit that passed, until a fix is merged and passes',
        decided: { by: 'owner', source: 'owner 2026-10-09' },
        checks: [],
        untested: 66,
      },
    ],
    note: 'The release script has no test; it was exercised by hand before PR #17 (GAP-09, #15). Backward compatibility of a migration is a review rule with no check. Merging only on your word is a rule Claude follows (CLAUDE.md, ADR-0019), which no test can prove. Since Oct 9 the release waits for CI on the merged commit (ADR-0048, AC2, AC9).',
  },
  {
    id: 'US-REL-03',
    title: 'Ship code dark, and switch off a bad change',
    as: 'the product owner',
    want: 'changes to reach production switched off until they are turned on, and a bad release undone in seconds',
    soThat:
      'deploying is not releasing, and a fault in production is a switch or a click away from gone',
    feature: 'F-31',
    requirements: ['NFR-DEL-05', 'NFR-REL-06'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a change shipped behind a flag',
        when: 'it reaches production',
        then: 'it stays dark: every flag is off unless something turns it on',
        decided: { by: 'blueprint', source: 'arch AP8' },
        checks: [
          'flags/flags › is off by default, with no source and no overrides',
          'e2e/shell › ships the build-version change dark: its flag is off by default',
        ],
      },
      {
        id: 'AC2',
        given: 'PostHog is connected',
        when: 'a flag is read',
        then: 'PostHog decides, and a flag it doesn’t return reads as off',
        decided: CLAUDE,
        checks: [
          'flags/flags › follows the source, and reads a flag the source omits as off',
          'flags/posthog › evaluates for the server when there is no user, and keeps only flags PostHog returned',
        ],
      },
      {
        id: 'AC3',
        given: 'a change misbehaves',
        when: 'its flag is turned off in the override setting',
        then: 'the override beats PostHog, so it works as a kill switch',
        decided: RELEASES,
        checks: ['flags/flags › lets an override beat the source in both directions'],
      },
      {
        id: 'AC4',
        given: 'PostHog fails, or takes more than half a second to answer',
        when: 'a flag is read',
        then: 'it reads as off, so new code stays dark rather than half released, and the request carries on',
        decided: CLAUDE,
        checks: [
          'flags/flags › reads a flag as off when the source fails',
          'flags/flags › reads a flag as off when the source is too slow',
        ],
      },
      {
        id: 'AC5',
        given: 'the override setting names an unknown flag, or a value other than on or off',
        when: 'it is read',
        then: 'that entry is reported and ignored',
        decided: CLAUDE,
        checks: ['flags/flags › reports and ignores unknown flags and unreadable values'],
      },
      {
        id: 'AC6',
        given: 'a bad release',
        when: 'the previous build is promoted again in Vercel',
        then: 'production serves it within seconds; its migrations stay, which is why they are kept backward compatible',
        decided: RELEASES,
        checks: [],
        untested: 66,
      },
    ],
    note: 'The receipt screens shipped without a flag while you were the only user (ADR-0017), and every screen until Oct 4 did too. Your answer to Q5 ends that: every feature since ships behind a flag, switched per organization (US-REL-05). The build version on Home is turned on in production by the override setting (#22). A rollback has never been rehearsed.',
  },
  {
    id: 'US-REL-05',
    title: 'Switch each new feature on for my organization',
    as: 'the owner of an organization',
    want: 'each new feature to arrive switched off, and to switch it on, or off again, myself',
    soThat:
      'I check a feature on my phone before anyone relies on it, and hide one that misbehaves without waiting for a release',
    feature: 'F-31',
    requirements: ['NFR-DEL-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a feature that has just been released',
        when: 'anyone in the organization opens the app',
        then: 'it is off: its screens and actions are hidden, and its API answers 404 feature_off',
        decided: Q5,
        checks: [
          'api/workspace › lists every feature switched off, and lets only the owner switch one',
          'api/features › answers 404 feature_off for a feature that is off, so it looks absent',
          'db/features.int › is off until switched on, records each switch, and ignores a switch to what it is',
        ],
      },
      {
        id: 'AC2',
        given: 'I am the owner',
        when: 'I switch a feature on or off in Settings › Features',
        then: 'it changes for everyone in my organization at once, without a release, and the audit trail records who switched it and when',
        decided: Q5,
        checks: [
          'api/workspace › switches a feature on and off for the organization, with an audit event each time',
          'db/features.int › is off until switched on, records each switch, and ignores a switch to what it is',
        ],
      },
      {
        id: 'AC3',
        given: 'I am not the owner',
        when: 'I open Settings › Features',
        then: 'I see which features are on, and can switch none',
        decided: CLAUDE,
        checks: [
          'api/workspace › lists every feature switched off, and lets only the owner switch one',
        ],
      },
      {
        id: 'AC4',
        given: 'the server’s override setting turns a feature on or off',
        when: 'the owner’s switch says otherwise',
        then: 'the override wins, the page says it is set on the server, and a switch that would have no effect is refused',
        decided: RELEASES,
        checks: [
          'api/workspace › lets the server override beat the switch, and refuses a switch it would ignore',
          'api/features › is off by default, on when the organization switches it, and the override beats both',
        ],
      },
      {
        id: 'AC5',
        given: 'one organization switches a feature on',
        when: 'another organization uses the app',
        then: 'it stays off there',
        decided: CLAUDE,
        checks: [
          'db/features.int › keeps one organization’s switches from another, and refuses a malformed flag',
        ],
      },
      {
        id: 'AC6',
        given: 'a flag that belongs to the server, such as the build version',
        when: 'the owner looks for it',
        then: 'it is not offered: only the override setting turns it on',
        decided: CLAUDE,
        checks: [
          'api/features › never offers the server’s own flags to an organization',
          'api/workspace › refuses a feature that does not exist, or one that is the server’s own',
        ],
      },
    ],
  },
  {
    id: 'US-REL-04',
    title: 'Serve every app from one versioned, described API',
    as: 'the product owner, who will add an iPhone app',
    want: 'one API, described by a published contract and versioned in its path, to serve the web app now and the iPhone app later',
    soThat:
      'a second app needs no rules of its own, and an older app keeps working when the API changes',
    requirements: ['NFR-ARC-01', 'NFR-ARC-04'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'any app or developer',
        when: 'they ask the API for its contract',
        then: 'they get the OpenAPI 3.1 description of its operations, served by the API itself',
        decided: { by: 'blueprint', source: 'arch AP1' },
        checks: [
          'api/api › serves its own OpenAPI 3.1 contract',
          'api/api › registers named schemas as reusable components',
          'e2e/shell › serves health and the OpenAPI contract under /api',
        ],
      },
      {
        id: 'AC2',
        given: 'a change to the API',
        when: 'gate G3 runs',
        then: 'it fails unless the committed contract is the one the code generates',
        decided: CLAUDE,
        checks: ['ci:integration'],
      },
      {
        id: 'AC3',
        given: 'any app calls the API',
        when: 'it sends a request',
        then: 'every operation answers under its version in the path, /api/v1, and a path with no operation gets a plain problem document',
        decided: RELEASES,
        checks: [
          'api/api › keeps problem documents when mounted under /api',
          'e2e/shell › answers unknown API routes with a problem document',
        ],
      },
      {
        id: 'AC4',
        given: 'a business rule, such as when a receipt is Ready or what a total is',
        when: 'a screen shows its outcome',
        then: 'the API decided it, and the screen only shows what the API says',
        decided: { by: 'blueprint', source: 'arch AP1' },
        checks: [],
        untested: 66,
      },
    ],
    note: 'CI doesn’t yet block a breaking change that lacks a new version (GAP-11, #34), and no operation has been retired, so the six-month deprecation window is untried.',
  },
  {
    id: 'US-DOC-01',
    title: 'Trust that the records match the code',
    as: 'the product owner, a director of business architecture',
    want: 'the requirements, traceability and backlog checked against the code on every change, and republished after each release',
    soThat: 'what I read about the product is what the product does, never a document that drifted',
    feature: 'F-39',
    requirements: ['NFR-DEL-07'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an API operation, a screen, a background workflow or a feature flag in the code',
        when: 'gate G2 runs',
        then: 'it fails unless exactly one feature claims it, and fails for a claim on something that doesn’t exist',
        decided: CLAUDE,
        checks: ['records/integrity › agree with themselves and with the repository', 'ci:unit'],
      },
      {
        id: 'AC2',
        given: 'an ADR, a test file, or a capability on the blueprint’s capability map',
        when: 'gate G2 runs',
        then: 'it fails if no requirement or feature cites the ADR, no record names the test file, or no requirement delivers the capability',
        decided: CLAUDE,
        checks: ['records/integrity › agree with themselves and with the repository', 'ci:unit'],
      },
      {
        id: 'AC3',
        given: 'a record names a test, a source or another record',
        when: 'gate G2 runs',
        then: 'the test must exist by its exact title, the source must hold the section cited, and the record must exist',
        decided: CLAUDE,
        checks: [
          'records/integrity › resolve a named test, and refuse one that does not exist',
          'records/integrity › resolve sources to the doc that holds them, and refuse what is not there',
          'records/integrity › agree with themselves and with the repository',
        ],
      },
      {
        id: 'AC4',
        given: 'a requirement’s or a feature’s status',
        when: 'gate G2 runs',
        then: 'it must agree with its checks and its open shortfalls, and each gap must be open or closed with its backlog item',
        decided: CLAUDE,
        checks: ['records/integrity › agree with themselves and with the repository'],
      },
      {
        id: 'AC5',
        given:
          'the records disagree with the code, or production serves a commit this checkout doesn’t have',
        when: 'the pages are built',
        then: 'the build refuses, listing what disagrees',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC6',
        given: 'a pull request is merged',
        when: 'its Release run succeeds and production’s health check reports the merged commit, or the run reports no build was needed',
        then: 'Claude builds the pages from the latest main, republishes them to the same addresses and then reports with the links; never after the merge alone',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC7',
        given: 'the traceability page',
        when: 'it is published',
        then: 'it names the commit production serves and the records’ commit, has a row for every requirement and feature, and links each backlog item to the backlog page',
        decided: CLAUDE,
        checks: [
          'records/render › names itself, the live commit and the records commit',
          'records/render › has a row for every requirement and every feature, by id',
          'records/render › links backlog items to the published backlog page',
        ],
      },
      {
        id: 'AC8',
        given: 'the backlog page',
        when: 'it is published',
        then: 'it has every item, open and done, and lists the commits the release brought',
        decided: CLAUDE,
        checks: [
          'records/render › has a row for every item, open and done',
          'records/render › lists this release’s commits, escaped',
        ],
      },
    ],
    note: 'Pages built from a branch are published only as drafts, which say so. Updating the records in the same pull request as a change in behaviour is in the Definition of Done; the checks catch what the code shows, such as a new operation, screen or test, but not a changed rule nobody wrote down.',
  },
  {
    id: 'US-DOC-02',
    title: 'Read a living architecture and data model',
    as: 'the product owner, a director of business architecture',
    want: 'the technical architecture and the data model read from the repository and the migrated database, revised with every change and republished after every release',
    soThat: 'I review the system as it is, and see what each release changed',
    feature: 'F-44',
    requirements: ['NFR-DEL-08'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a pull request changes the system',
        when: 'it is opened',
        then: 'it revises the architecture and the data model in the same pull request, or says why neither needed revising',
        decided: OCT3,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC2',
        given:
          'a workspace package, a setting the code reads, a GitHub workflow, a background function, a table or a database function with no written description',
        when: 'gate G2 runs',
        then: 'it fails',
        decided: CLAUDE,
        checks: ['records/integrity › agree with themselves and with the repository', 'ci:unit'],
      },
      {
        id: 'AC3',
        given: 'a migration changes the schema',
        when: 'gate G3 runs',
        then: 'it fails until the schema snapshot is taken again from the migrated database and committed',
        decided: CLAUDE,
        checks: ['db/schema-snapshot.int', 'ci:integration'],
      },
      {
        id: 'AC4',
        given: 'the architecture page',
        when: 'it is published',
        then: 'it shows each component’s written description beside what was read from the repository, every API operation in the contract, and its diagrams',
        decided: OCT3,
        checks: [
          'records/render › names itself and shows the written half beside what it read',
          'records/render › lists every API operation in the contract',
          'records/render › draws its diagrams for the viewer to render',
        ],
      },
      {
        id: 'AC5',
        given: 'the data model page',
        when: 'it is published',
        then: 'it has a block for every table, in its domain, each rule with the database objects that enforce it, and the lifecycles drawn from the domain’s own rules',
        decided: OCT3,
        checks: [
          'records/render › has a block for every table, in its domain',
          'records/render › shows each rule with the objects that enforce it',
          'records/render › draws the lifecycles from the domain’s own rules',
        ],
      },
      {
        id: 'AC6',
        given: 'a successful release',
        when: 'the architecture page is republished',
        then: 'it says what changed since the last release',
        decided: OCT3,
        checks: ['records/render › says what changed since the last release'],
      },
      {
        id: 'AC7',
        given: 'a successful release',
        when: 'the data model page is republished',
        then: 'it lists the tables, columns, constraints, policies and functions the release added, changed or removed',
        decided: OCT3,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC8',
        given: 'a change, enhancement or fix',
        when: 'Claude reports it to the product owner',
        then: 'the report confirms what was revised on each page, or that nothing needed to be',
        decided: OCT3,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Your requirement of Oct 3, with the WayPoint pages as the pattern.',
  },
  {
    id: 'US-DOC-03',
    title: 'Sign off the detailed requirements as user stories',
    as: 'the product owner, a director of business architecture',
    want: 'every requirement of the entire build written as user stories with numbered Given/When/Then acceptance criteria, each traced to the test that proves it',
    soThat:
      'I can accept or reject exactly what the product does, and see which rules are mine and which are Claude’s to confirm',
    feature: 'F-53',
    requirements: ['NFR-DEL-09'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'any requirement that is built, or planned from my own words',
        when: 'the records are checked',
        then: 'a story details it, and the checks refuse a built requirement or feature that no delivered story covers',
        decided: Q26,
        checks: [
          'records/integrity › refuses a built requirement or feature that no delivered story covers',
          'records/integrity › agree with themselves and with the repository',
        ],
      },
      {
        id: 'AC2',
        given: 'an acceptance criterion',
        when: 'I read it on the stories page',
        then: 'it says who decided it: me, the blueprint, or Claude as an assumption for me to confirm',
        decided: Q26,
        checks: [
          'records/render › says who decided each criterion, and points an untested one at the item that adds its test',
          'records/integrity › refuses a test that doesn’t exist, and a decision credited to a question that doesn’t',
        ],
      },
      {
        id: 'AC3',
        given: 'an acceptance criterion of a built story',
        when: 'the records are checked',
        then: 'it names the test that proves it, or the open item that adds one, and a test it names must exist',
        decided: Q26,
        checks: [
          'records/integrity › refuses a built criterion no test proves, unless it names the open item that adds one',
          'records/integrity › refuses a test that doesn’t exist, and a decision credited to a question that doesn’t',
        ],
      },
      {
        id: 'AC4',
        given: 'a number several rules share, such as 28 days or 30 minutes',
        when: 'a criterion depends on it',
        then: 'it is named once, in the rule register, and the checks refuse a value that differs from the code',
        decided: Q26,
        checks: [
          'records/integrity › refuses a rule whose value differs from the code',
          'records/render › lists every rule in the register with the criteria that use it',
        ],
      },
      {
        id: 'AC5',
        given: 'the records',
        when: 'the pages are built',
        then: 'a fifth page, User stories & acceptance criteria, shows every story and criterion, and the traceability page lists each requirement’s stories',
        decided: Q26,
        checks: [
          'records/render › shows every story and every acceptance criterion, by id',
          'records/render › lists each requirement’s user stories, linked to the stories page',
        ],
      },
    ],
    note: 'Your request of Oct 4 (GAP-24) and your answer to Q26: as proposed, for the entire build (#65). Criteria of built stories that no test proves yet are listed against #66. The page is republished with the other four after each successful release (US-DOC-01).',
  },
  {
    id: 'US-UX-01',
    title: 'Reach every part of the app with my thumb',
    as: 'Alex, who travels for work and uses the app on an iPhone',
    want: 'one tab bar at the bottom of the screen, with capture in the middle',
    soThat: 'I can get anywhere, and capture a receipt, in one tap',
    feature: 'F-29',
    requirements: ['NFR-UX-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I open the app',
        when: 'Home loads',
        then: 'the tab bar shows Home, Expenses, Capture as the + in the middle, Trips and Reports, with Home marked as where I am',
        decided: DP4,
        checks: ['e2e/shell › opens on the inbox with the five-destination tab bar'],
      },
      {
        id: 'AC2',
        given: 'I am on Expenses, Trips, Capture or Settings',
        when: 'the screen opens',
        then: 'the tab bar is there, marking the section I am in; Settings, opened from Home’s header, marks none',
        decided: DP4,
        checks: [
          'e2e/shell › shows the tab bar on every screen but sign-in, marking where you are',
        ],
      },
      {
        id: 'AC3',
        given: 'the sign-in screen',
        when: 'it opens',
        then: 'it stands alone, without the tab bar',
        decided: CLAUDE,
        checks: [
          'e2e/shell › shows the tab bar on every screen but sign-in, marking where you are',
        ],
      },
    ],
    note: 'The tab bar was on Home only until PR #36; it is now on every screen but sign-in, as the design has it.',
  },
  {
    id: 'US-UX-02',
    title: 'Every screen fits my phone and passes WCAG 2.2 AA',
    as: 'Alex, who travels for work and uses the app on an iPhone',
    want: 'every screen, in every state, to fit my phone and meet WCAG 2.2 AA, in light and in dark, before it ships',
    soThat:
      'nothing overlaps, runs off the screen or is hard to read, whatever phone, eyes or tools I use',
    feature: 'F-47',
    requirements: ['NFR-UX-01', 'NFR-UX-02'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'every signed-in screen, in each state it can be in',
        when: 'gate G5 opens it on the desktop and on the iPhone, in light and in dark',
        then: 'it has no WCAG 2.2 AA violation, or the gate fails',
        decided: DP5,
        checks: ['e2e/signed-in', 'ci:e2e'],
      },
      {
        id: 'AC2',
        given:
          'the screens a signed-out visitor sees: Home, sign-in, and the sign-in prompts of receipts, expenses, trips and settings',
        when: 'gate G5 opens them in light and in dark',
        then: 'none has a WCAG 2.2 AA violation',
        decided: DP5,
        checks: [
          'e2e/shell › has no WCAG 2.2 AA violations',
          'e2e/receipts › has no WCAG 2.2 AA violations',
          'e2e/trips › has no WCAG 2.2 AA violations',
          'e2e/settings › has no WCAG 2.2 AA violations',
        ],
      },
      {
        id: 'AC3',
        given: 'every signed-in screen, in each state',
        when: 'gate G5 opens it in iPhone WebKit at 393 points wide in light and dark, and at 375 and 440 in light',
        then: 'nothing runs off the screen or out of its card, no controls overlap, no date or number is cut off in its field, and nothing is too small to tap',
        decided: DP4,
        checks: ['e2e/signed-in'],
      },
      {
        id: 'AC4',
        given: 'the same screens on a computer',
        when: 'gate G5 opens them in Chromium at 1280 wide, in light and dark',
        then: 'they pass the same layout checks',
        decided: DP4,
        checks: ['e2e/signed-in'],
      },
      {
        id: 'AC5',
        given: 'two date fields side by side in a narrow card, as From and To are',
        when: 'they are shown on an iPhone',
        then: 'each stays inside its column, because no date field is drawn in iOS Safari’s native style, which widens it past its column',
        decided: DP4,
        checks: [
          'e2e/shell › keeps two date fields side by side inside a narrow card',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC6',
        given: 'any signed-in screen',
        when: 'gate G5 loads it',
        then: 'nothing is logged as an error in the browser’s console',
        decided: CLAUDE,
        checks: ['e2e/signed-in'],
      },
      {
        id: 'AC7',
        given: 'a release that changes a screen',
        when: 'it is live',
        then: 'the product owner opens that screen on an iPhone in production, since CI’s iPhone engine is not iOS Safari',
        decided: Q13,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC8',
        given: 'whatever day gate G5 runs on',
        when: 'the bench seeds its receipts, trips, drives and reports',
        then: 'each is in the state its screen is checked in, its dates counted from that day, or the bench stops and the gate fails, naming what drifted',
        decided: CLAUDE,
        checks: ['e2e/signed-in'],
      },
    ],
    note: 'The bench seeds its data through the real API and reading workflow, with drawn receipt images, never real ones. Its dates count from the day it runs (AC8), so a receipt never turns a year older than its upload and a trip to come never becomes a past one. CI’s iPhone engine is WebKit on Linux, not iOS Safari (GAP-22); paying for a device cloud is #57. Put back on Oct 3, the overlapping date fields you found on your iPhone and the contrast failure on differing readings both fail these checks.',
  },
  {
    id: 'US-UX-03',
    title: 'Read money and status at a glance',
    as: 'Alex, who travels for work and spends in more than one currency',
    want: 'every amount shown with its currency, in figures that line up, and every status in words',
    soThat: 'I never mistake euros for dollars, or misread a status',
    feature: 'F-29',
    requirements: ['NFR-UX-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an amount anywhere in the app',
        when: 'it is shown',
        then: 'it shows its currency and exactly as many decimal places as the currency has, from the exact figure, never a rounded one',
        decided: DP5,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC2',
        given: 'figures in a list or a table',
        when: 'they are shown',
        then: 'they use figures of equal width, so they line up digit for digit',
        decided: DP5,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'expenses in more than one currency',
        when: 'a trip’s total or the month on Home is shown',
        then: 'each currency is totalled apart and shown side by side, never converted',
        decided: { by: 'claude', source: 'ADR-0008' },
        checks: [
          'api/trips › lists trips with their progress and a total per currency, never converted',
          'api/home › adds up the month per currency, never converted, and what is on no trip',
        ],
      },
      {
        id: 'AC4',
        given: 'a status, such as Ready, Needs a look or Not read',
        when: 'it is shown',
        then: 'it is written in words; colour only adds to them',
        decided: DP5,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Converting amounts into your preferred currency is planned (Q23, Q25).',
  },
  {
    id: 'US-UX-04',
    title: 'Know what the app did on its own, and why',
    as: 'Alex, who travels for work',
    want: 'every automatic decision to say what it did and why, and to let me change it',
    soThat: 'nothing the app does surprises me, and I only look at what needs me',
    requirements: ['NFR-UX-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'receipts the app could not settle on its own',
        when: 'I open Needs you',
        then: 'each is listed, newest first, with why: the fields the models read differently, the check that failed, that only the fallback could read it, or why it could not be read at all',
        decided: DP6,
        checks: [
          'api/receipts › lists what needs a look or could not be read, newest first, each with why',
          'api/receipts › says which check failed when the models agree',
        ],
      },
      {
        id: 'AC2',
        given: 'a reading fails a check',
        when: 'I open the receipt',
        then: 'each reading names the checks it fails, such as parts that don’t make the total or a date after the upload',
        decided: DP6,
        checks: [
          'api/receipts › names the checks each reading fails: its sums, and a date after the upload',
        ],
      },
      {
        id: 'AC3',
        given: 'an expense the app filed to a trip by its date',
        when: 'I open it',
        then: 'it says it is on that trip by its date, and I can choose another trip, no trip, or hand it back to filing by date, until it is submitted',
        decided: DP6,
        checks: [
          'api/expenses › puts an expense on a trip a person chose, on none, or back to filing by date',
          'api/expenses › refuses another member’s trip, a trip that doesn’t exist, and a submitted expense',
          'db/trips.int › keeps an expense on the trip a person chose, whatever its date',
          'db/trips.int › keeps an expense a person took off a trip off it',
        ],
      },
      {
        id: 'AC4',
        given: 'I make a trip',
        when: 'the app files my expenses dated in it, first and last days included',
        then: 'only my own expenses move, never a colleague’s, and the audit trail records each filing, with the trip it was on before, if any',
        decided: { by: 'claude', source: 'ADR-0023' },
        checks: [
          'db/trips.int › files the member’s expenses dated in a new trip, start and end days included',
        ],
      },
    ],
    note: 'Since PR #58 a reading the app made Ready can be corrected in place with a tap, with Where each field was read switched on (US-READ-21), until its expense is submitted.',
  },
  {
    id: 'US-UX-05',
    title: 'Read every date one way',
    as: 'Alex, who travels for work and reads dates on receipts, expenses and trips',
    want: 'every date shown the same way, as Sep 30, 2026, with the time as 1:12 PM where it matters',
    soThat: 'I never wonder whether 10/3 means October 3 or 10 March',
    requirements: ['NFR-UX-06'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a date shown anywhere in the app',
        when: 'I read it',
        then: 'it reads like Sep 30, 2026',
        decided: Q12,
        checks: [
          'domain/display › shows a calendar date as Sep 30, 2026, never moved a day by a time zone',
          'domain/display › shows two dates as one range, naming the month and year once where they repeat',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'a time that matters, such as when something was added or checked',
        when: 'it is shown',
        then: 'it follows the date as 1:12 PM',
        decided: Q12,
        checks: ['domain/display › shows the time as 1:12 PM where it matters, after the date'],
      },
      {
        id: 'AC3',
        given: 'a form that asks for a date',
        when: 'I fill it in on my phone',
        then: 'it keeps the phone’s own date picker',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'a model’s reading table on a receipt',
        when: 'it shows a date',
        then: 'the date stays exactly as the model read it, so a difference between readings stays visible',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Your answer to Q12 (#55). The date picker and the reading table were the exceptions the question set out; your answer chose the format.',
  },
];
