import type { Story } from '../model.ts';

const OCT2 = { by: 'owner', source: 'owner 2026-10-02' } as const;
const OCT3 = { by: 'owner', source: 'owner 2026-10-03' } as const;
const TWO_MODELS = { by: 'blueprint', source: 'ADR-0017' } as const;
const FALLBACK = { by: 'blueprint', source: 'ADR-0020' } as const;
const PIPELINE = { by: 'blueprint', source: 'arch §6.5' } as const;
const EVAL_SET = { by: 'blueprint', source: 'delivery §7.5' } as const;
const RUNS = { by: 'claude', source: 'ADR-0017' } as const;
const FALLBACK_RULES = { by: 'claude', source: 'ADR-0020' } as const;
const REVIEWS = { by: 'claude', source: 'ADR-0021' } as const;
const TIME_PLACE = { by: 'claude', source: 'ADR-0030' } as const;

/**
 * Reading receipts: the fields, the Ready rule and its checks, confirming and correcting, the
 * fallback reader, time and place, the model comparison, and the eval harness (FR-INT-01 to
 * FR-INT-17; ADR-0006, ADR-0017, ADR-0020, ADR-0021, ADR-0030).
 */
export const READING_STORIES: readonly Story[] = [
  {
    id: 'US-READ-01',
    title: 'Have each receipt read into its fields',
    as: 'Alex, who travels for work',
    want: 'each receipt I file read into its merchant, date, currency, total and the rest, with how sure the reading is of each',
    soThat: 'I never type a receipt in, and the app knows which fields it can trust',
    feature: 'F-06',
    requirements: ['FR-INT-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a photo or PDF of a receipt I have filed',
        when: 'it is read',
        then: 'each model is sent the file and a fixed structure, and returns the merchant, date, currency, total, subtotal, tax lines, tip, card last four, line items and document type in it, with a confidence of high, medium or low on each field but the line items and type',
        decided: PIPELINE,
        checks: [
          'extraction/claude › sends the image, the schema and the tier effort, and prices the call',
          'extraction/claude › sends PDFs as documents and omits effort for Haiku',
          'extraction/openai › sends the image, the strict schema and the effort, stores nothing, and prices the call',
          'extraction/openai › sends PDFs as files',
        ],
      },
      {
        id: 'AC2',
        given: 'a reading with amounts in it',
        when: 'it is stored',
        then: 'each amount becomes a whole number of its currency’s minor units, such as 5843 cents for $58.43 or 1200 for ¥1,200, never a rounded decimal',
        decided: { by: 'claude', source: 'ADR-0008' },
        checks: [
          'extraction/normalize › turns decimal strings into integer minor units in the stated currency',
          'extraction/normalize › handles currencies with other minor units',
        ],
      },
      {
        id: 'AC3',
        given: 'a value that isn’t valid, such as an amount with more decimals than its currency has or with a thousands separator, an unknown currency, a date in another format, or a card number that isn’t four digits',
        when: 'the reading is stored',
        then: 'that field is left blank and named as a problem, never rounded or guessed, and the reading can’t make the receipt Ready',
        decided: { by: 'claude' },
        checks: [
          'extraction/normalize › flags values it cannot read instead of rounding or guessing',
          'extraction/normalize › flags an unknown currency, and its amounts, unless a fallback applies',
          'extraction/review › never files a reading with an unreadable value',
        ],
      },
      {
        id: 'AC4',
        given: 'a model that refuses, runs out of room, or answers outside the structure',
        when: 'its answer comes back',
        then: 'that reading is stored as failed with nothing taken from it; free text is never parsed',
        decided: PIPELINE,
        checks: [
          'extraction/claude › reports %o as %s with no extraction',
          'extraction/openai › reports %s as %s with no extraction',
        ],
      },
      {
        id: 'AC5',
        given: 'a receipt with text on it that reads like an instruction',
        when: 'it is read',
        then: 'the text is treated as data: the model is given no tools and is told to ignore instructions on the document',
        decided: PIPELINE,
        checks: [],
        untested: 66,
      },
    ],
    note: 'The time and the merchant’s address are read too (US-READ-10). Fees that are neither tax nor tip, such as a ride’s booking fee, are read as their own lines (ADR-0027).',
  },
  {
    id: 'US-READ-02',
    title: 'Ready only when I needn’t look',
    as: 'Alex, who travels for work',
    want: 'a receipt marked Ready only when two models read its merchant, date, currency and total with confidence and agree, and anything less held for my look',
    soThat: 'I can trust Ready without checking, and see exactly what needs me',
    feature: 'F-06',
    requirements: ['FR-INT-02', 'FR-INT-08'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I file a receipt',
        when: 'it is read',
        then: 'Haiku 4.5 and Sonnet 5.5 each read it, on my organization’s own Anthropic key',
        decided: TWO_MODELS,
        checks: [
          'workflows/receipts › files it as Ready when both read it with confidence and agree',
          'api/receipts › shows each model pending while the receipt is read',
          'workflows/receipts › records a missing key as a failed reading, and calls no model',
        ],
      },
      {
        id: 'AC2',
        given: 'both models read the merchant, date, currency and total with high confidence and agree on them, and the reading’s sums and date pass their checks',
        when: 'the receipt settles',
        then: 'it is Ready, and its expense is filed with what was read',
        decided: TWO_MODELS,
        checks: [
          'workflows/receipts › files it as Ready when both read it with confidence and agree',
          'extraction/checks › needs the sums and the date to pass as well as confidence',
        ],
      },
      {
        id: 'AC3',
        given: 'the two models read the merchant, date, currency or total differently',
        when: 'the receipt settles',
        then: 'it Needs a look, and the receipt marks each field that differs',
        decided: TWO_MODELS,
        checks: [
          'workflows/receipts › asks for a look when the models disagree',
          'extraction/review › names each field that differs',
          'api/receipts › shows both readings, where they differ, and money as minor units',
        ],
      },
      {
        id: 'AC4',
        given: 'two readings of a merchant’s name that differ only in case, punctuation, “&” for “and”, a word such as “Inc”, or one being a shorter form of the other',
        when: 'they are compared',
        then: 'they agree, while different businesses never do; a field both models left blank agrees, and one only one of them left blank differs',
        decided: { by: 'claude' },
        checks: [
          'extraction/review › agrees when the filing fields match, allowing loose merchant names',
          'extraction/review › matches %s and %s',
          'extraction/review › does not match different businesses',
          'extraction/review › treats one empty field as a difference and two as agreement',
        ],
      },
      {
        id: 'AC5',
        given: 'either model read the merchant, date, currency or total with medium or low confidence, or not at all',
        when: 'the receipt settles',
        then: 'it Needs a look',
        decided: TWO_MODELS,
        checks: [
          'extraction/review › needs merchant, date, currency and total read with high confidence',
        ],
      },
      {
        id: 'AC6',
        given: 'only one of the two models could read it',
        when: 'the receipt settles',
        then: 'it Needs a look, however sure that model was',
        decided: TWO_MODELS,
        checks: [
          'workflows/receipts › keeps the other reading when the provider rejects one request for good',
          'workflows/receipts › is not called when a Claude model read the receipt',
        ],
      },
      {
        id: 'AC7',
        given: 'no model could read it',
        when: 'the receipt settles',
        then: 'it is Not read, and says why for each model',
        decided: TWO_MODELS,
        checks: [
          'workflows/receipts › records a missing key as a failed reading, and calls no model',
          'workflows/receipts › settles as failed when the fallback has no credit either',
          'api/receipts › lists what needs a look or could not be read, newest first, each with why',
        ],
      },
    ],
    note: 'Until the model tier is chosen (#21). With #52 a receipt will be read once, by the primary model (Q11), so Ready will rest on that one reading; that replaces ADR-0017 and gets its own decision record. While the Anthropic account has no credit (#4), the fallback reads every receipt and each one Needs a look (US-READ-09).',
  },
  {
    id: 'US-READ-03',
    title: 'Catch a reading whose sums or date don’t hold',
    as: 'Alex, who travels for work',
    want: 'a reading whose parts don’t make its total, or whose date can’t be right, held for my look even when both models agree',
    soThat: 'a confident misreading never files itself, and I see at once what is wrong',
    feature: 'F-06',
    requirements: ['FR-INT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a reading whose subtotal, taxes, fees and tip don’t come to its total',
        when: 'the receipt settles',
        then: 'it Needs a look, even when both models agree on every figure',
        decided: { by: 'blueprint', source: 'journeys §4.6' },
        checks: [
          'workflows/receipts › asks for a look when both agree on parts that don’t make the total',
          'extraction/checks › names the sums when the parts do not make the total',
          'extraction/checks › needs the sums and the date to pass as well as confidence',
        ],
      },
      {
        id: 'AC2',
        given: 'a receipt whose tax, fee and tip lines are each rounded on their own',
        when: 'its parts are added up',
        then: 'they may miss the total by one minor unit, a cent, per tax, fee or tip line, and no more; in yen the unit is one yen',
        decided: OCT3,
        checks: [
          'extraction/checks › allows a minor unit for each tax or tip line, and no more',
          'extraction/checks › counts minor units in the currency, so a yen is the unit for JPY',
        ],
        rules: ['R-SUMS-TOLERANCE'],
      },
      {
        id: 'AC3',
        given: 'a ride receipt that prints a booking fee or an airport surcharge',
        when: 'its parts are added up',
        then: 'each fee counts towards the total, as neither tax nor tip',
        decided: { by: 'claude', source: 'ADR-0027' },
        checks: [
          'extraction/checks › counts fees that are neither tax nor tip, as a ride receipt prints them',
        ],
      },
      {
        id: 'AC4',
        given: 'a receipt whose prices include their tax, as VAT receipts print them',
        when: 'its parts are added up',
        then: 'the subtotal, fees and tip alone may make the total, and it passes',
        decided: { by: 'claude' },
        checks: [
          'extraction/checks › accepts prices that include their tax, as VAT receipts print them',
        ],
      },
      {
        id: 'AC5',
        given: 'a receipt that prints no subtotal',
        when: 'it is checked',
        then: 'there is nothing to add up, so the sums never hold it',
        decided: { by: 'claude' },
        checks: ['extraction/checks › has nothing to add up without a subtotal or a total'],
      },
      {
        id: 'AC6',
        given: 'a reading dated after the day its receipt was uploaded',
        when: 'it is checked',
        then: 'it Needs a look if the date is more than one day after the upload’s day in UTC; one day ahead is allowed, for a merchant whose day runs ahead of UTC',
        decided: OCT3,
        checks: [
          'extraction/checks › allows the merchant’s day to run one ahead of the upload’s, and no more',
          'workflows/receipts › asks for a look when both read a date after the upload',
        ],
        rules: ['R-DATE-AHEAD'],
      },
      {
        id: 'AC7',
        given: 'a reading dated more than a year before its upload',
        when: 'it is checked',
        then: 'it Needs a look; a date exactly a year before still passes',
        decided: OCT3,
        checks: [
          'extraction/checks › flags a date more than a year before the upload',
          'extraction/checks › needs the sums and the date to pass as well as confidence',
        ],
        rules: ['R-DATE-BEHIND'],
      },
      {
        id: 'AC8',
        given: 'a reading that fails one or more checks',
        when: 'I open the receipt or Needs you',
        then: 'it names every check that failed: the sums, a date after the upload, or a date more than a year before it, even when the models agree',
        decided: { by: 'claude' },
        checks: [
          'api/receipts › names the checks each reading fails: its sums, and a date after the upload',
          'api/receipts › says which check failed when the models agree',
          'extraction/checks › reports every check that fails',
        ],
      },
    ],
    note: 'You confirmed the three limits on Oct 3. Receipts read before then keep the status they were given.',
  },
  {
    id: 'US-READ-04',
    title: 'Count a tax or tip the receipt doesn’t print as zero',
    as: 'Alex, who travels for work',
    want: 'a tax or tip my receipt doesn’t print to count as zero, marked as not on the receipt',
    soThat: 'a receipt with only a total is complete, without hiding a line the reading missed',
    feature: 'F-06',
    requirements: ['FR-INT-14'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt that prints no tax line, no tip line, or neither',
        when: 'it is read',
        then: 'each one missing counts as zero in the receipt’s currency, and shows as “not on receipt”',
        decided: OCT2,
        checks: [
          'extraction/normalize › counts tax and tip a receipt does not print as zero',
          'extraction/normalize › agrees with a subtotal that already equals the total',
          "api/receipts › shows tax and tip the receipt doesn't print as zero, marked as assumed",
        ],
      },
      {
        id: 'AC2',
        given: 'a receipt whose printed subtotal and the lines that were read don’t reach the total',
        when: 'it is read',
        then: 'nothing is counted as zero, since a line was most likely missed; where the rest add up, only the missing one is',
        decided: OCT2,
        checks: [
          'extraction/normalize › assumes nothing when the printed figures leave an amount unaccounted for',
          'extraction/normalize › assumes only the missing one when the rest add up',
        ],
      },
      {
        id: 'AC3',
        given: 'a tax or tip line that is printed but couldn’t be read, or a reading with no total',
        when: 'it is read',
        then: 'that line is never counted as zero',
        decided: OCT2,
        checks: [
          'extraction/normalize › never assumes a line that is printed but unreadable, or anything without a total',
        ],
      },
      {
        id: 'AC4',
        given: 'a tax or tip counted as zero',
        when: 'the reading is stored',
        then: 'the reading keeps it absent, as read; the zero is only how it is shown and filed',
        decided: OCT2,
        checks: ['extraction/normalize › leaves the reading itself as read'],
      },
      {
        id: 'AC5',
        given: 'a reading I confirm',
        when: 'it is filed',
        then: 'a tax or tip the receipt doesn’t print is filed as zero, and one it prints keeps its amount',
        decided: REVIEWS,
        checks: [
          'extraction/confirm › files a tax or tip the receipt does not print as zero, and keeps one it does',
          'api/receipts › makes the fallback reading Ready with Looks right, and says who confirmed it',
        ],
      },
    ],
    note: 'Refined from your request of Oct 2: no tax line means none was itemized, not necessarily that none was paid, so the reading keeps the difference.',
  },
  {
    id: 'US-READ-05',
    title: 'Confirm a reading that needs a look',
    as: 'Alex, who travels for work',
    want: 'a receipt that needs a look to offer Looks right, which files it as it was read',
    soThat: 'checking a receipt takes one tap, and no receipt is a dead end',
    feature: 'F-40',
    requirements: ['FR-INT-15'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt that Needs a look and isn’t held as a duplicate',
        when: 'I open it',
        then: 'it asks “Is this right?” and offers Looks right and Edit a field',
        decided: OCT2,
        checks: ['e2e/signed-in'],
      },
      {
        id: 'AC2',
        given: 'a receipt read by more than one model',
        when: 'I confirm it',
        then: 'I choose which reading to start from, and a reading the receipt doesn’t have is refused',
        decided: REVIEWS,
        checks: [
          'api/receipts › files corrected fields with Edit a field, keeping what the model read',
          'api/receipts › names the field that is not valid, or the filing fields still missing',
        ],
      },
      {
        id: 'AC3',
        given: 'a reading that has the merchant, date, currency and total',
        when: 'I tap Looks right',
        then: 'the receipt is Ready with that reading, whatever its confidence, and the page says who confirmed which model’s reading',
        decided: OCT2,
        checks: [
          'api/receipts › makes the fallback reading Ready with Looks right, and says who confirmed it',
          'extraction/confirm › confirms a reading as it is, with no corrections, whatever its confidence',
        ],
      },
      {
        id: 'AC4',
        given: 'a reading that lacks the merchant, date, currency or total',
        when: 'I try Looks right',
        then: 'it can’t be filed as it is, and the receipt names what is missing for me to enter with Edit a field',
        decided: REVIEWS,
        checks: [
          'extraction/confirm › needs every filing field, entered when the reading lacks it',
          'api/receipts › names the field that is not valid, or the filing fields still missing',
        ],
      },
      {
        id: 'AC5',
        given: 'I confirm a receipt',
        when: 'it is saved',
        then: 'the confirmed values, the Ready status and an audit event naming me, the reading and the request are saved together, and its expense is filed with the confirmed values',
        decided: REVIEWS,
        checks: [
          'db/receipts.int › makes it Ready with the values, the corrections and an audit event, together',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt that is Ready, still being read, or already confirmed',
        when: 'anyone tries to confirm it',
        then: 'it is refused and nothing changes',
        decided: REVIEWS,
        checks: [
          'api/receipts › refuses a receipt that is not waiting for a look',
          'db/receipts.int › refuses a receipt that is no longer waiting, or was read again since',
        ],
      },
      {
        id: 'AC7',
        given: 'a confirmation that has been saved',
        when: 'anyone tries to change or delete it, or looks for it from another organization',
        then: 'it can’t be changed or deleted, and another organization sees nothing',
        decided: REVIEWS,
        checks: [
          'db/receipts.int › keeps reviews inside their organization, and never edits or deletes one',
        ],
      },
      {
        id: 'AC8',
        given: 'someone who isn’t signed in, or is signed in but in no organization',
        when: 'they try to confirm a receipt',
        then: 'it is refused',
        decided: { by: 'claude' },
        checks: ['api/receipts › needs a signed-in member'],
      },
    ],
    note: 'A held duplicate is decided first (US-DUP-03). Confirming makes a fallback reading Ready, which the fallback alone never can (ADR-0021 amends ADR-0020).',
  },
  {
    id: 'US-READ-06',
    title: 'Correct a field before the receipt is filed',
    as: 'Alex, who travels for work',
    want: 'to correct the merchant, date, currency, total, tax or tip of a reading that needs a look, then file it',
    soThat: 'a reading that is nearly right becomes Ready in seconds, and what the model got wrong is kept',
    feature: 'F-40',
    requirements: ['FR-INT-15'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt that Needs a look',
        when: 'I tap Edit a field, change any of the merchant, date, currency, total, tax and tip, and tap Save and file',
        then: 'it is Ready with my values',
        decided: OCT2,
        checks: [
          'api/receipts › files corrected fields with Edit a field, keeping what the model read',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'a field I changed',
        when: 'the receipt is filed',
        then: 'the correction keeps what the model read beside what I entered, and the reading itself stays as the model read it',
        decided: OCT2,
        checks: [
          'api/receipts › files corrected fields with Edit a field, keeping what the model read',
          'extraction/confirm › applies corrections and keeps what was read beside each one',
        ],
      },
      {
        id: 'AC3',
        given: 'a value I enter as it was read, such as 6.5 for 6.50',
        when: 'the receipt is filed',
        then: 'it isn’t counted as a correction',
        decided: REVIEWS,
        checks: ['extraction/confirm › does not count a value entered unchanged as a correction'],
      },
      {
        id: 'AC4',
        given: 'a value that isn’t valid: an empty merchant, a date that doesn’t exist, a currency ExpenseWise doesn’t support, an amount with too many decimals or a thousands separator, or a negative amount',
        when: 'I tap Save and file',
        then: 'nothing is filed, and the field is named',
        decided: REVIEWS,
        checks: [
          'extraction/confirm › refuses %o as a value for %s',
          'api/receipts › names the field that is not valid, or the filing fields still missing',
        ],
      },
      {
        id: 'AC5',
        given: 'I correct the currency',
        when: 'the receipt is filed',
        then: 'the printed amounts stay as printed in the new currency, never converted; an amount the new currency can’t hold, such as cents in yen, must be entered again',
        decided: REVIEWS,
        checks: [
          'extraction/confirm › keeps the printed amounts when the currency is corrected',
          'extraction/confirm › refuses a read amount that the corrected currency cannot hold, rather than rounding',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt no model could read',
        when: 'I open it',
        then: 'I can enter its merchant, date, currency and total myself, and file it as Ready',
        decided: REVIEWS,
        checks: [
          'api/receipts › lets a receipt no model could read be filled in by hand',
          'extraction/confirm › can be filled in entirely by hand when no reading has fields',
          'e2e/signed-in',
        ],
      },
    ],
  },
  {
    id: 'US-READ-07',
    title: 'See how sure each field is, beside the original',
    as: 'Alex, who travels for work',
    want: 'each model’s reading shown field by field beside the original receipt, with how sure it is of each field',
    soThat: 'I can check a reading against the receipt in seconds',
    feature: 'F-06',
    requirements: ['FR-INT-11', 'FR-INT-08'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt that has been read',
        when: 'I open it',
        then: 'each model’s reading shows side by side, field by field, with the original image or a link to the PDF',
        decided: TWO_MODELS,
        checks: [
          'api/receipts › shows both readings, where they differ, and money as minor units',
          'api/receipts › shows each model pending while the receipt is read',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'a field a model read with medium or low confidence',
        when: 'I open the receipt',
        then: 'that confidence shows beside the value',
        decided: { by: 'blueprint', source: 'design DP3' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'I correct a field of a reading that needs a look',
        when: 'the receipt is filed',
        then: 'the correction is kept with what the model read beside it, as a candidate for the eval set',
        decided: EVAL_SET,
        checks: [
          'extraction/confirm › applies corrections and keeps what was read beside each one',
          'db/receipts.int › makes it Ready with the values, the corrections and an audit event, together',
        ],
      },
    ],
    note: 'Not built: a field doesn’t show the receipt text it came from, and a Ready reading can’t be corrected (GAP-14, #37). Corrections wait in the database until the real-world eval layer is built (#39).',
  },
  {
    id: 'US-READ-08',
    title: 'Have a receipt read again',
    as: 'Alex, who travels for work',
    want: 'to have a receipt read again when its reading failed or looks wrong',
    soThat: 'an outage or a bad reading never leaves me typing a receipt in',
    feature: 'F-06',
    requirements: ['FR-INT-07'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt in my organization',
        when: 'I tap Read again',
        then: 'it goes back to Reading and is read again under a new request, and the receipt then shows the new readings',
        decided: TWO_MODELS,
        checks: [
          'api/receipts › reads a receipt again on request',
          'db/receipts.int › reads again on request, with a new request id',
        ],
      },
      {
        id: 'AC2',
        given: 'the earlier readings and any confirmation of them',
        when: 'the receipt is read again',
        then: 'they stay on record beside the new ones; the app can’t delete a reading',
        decided: TWO_MODELS,
        checks: [
          'db/receipts.int › refuses a receipt that is no longer waiting, or was read again since',
          'db/duplicates.int › deletes nothing in another organization, and the app cannot delete receipts any other way',
        ],
      },
      {
        id: 'AC3',
        given: 'a receipt I confirmed or corrected',
        when: 'it is read again',
        then: 'it starts over: the new readings decide its status, and my confirmation no longer applies',
        decided: REVIEWS,
        checks: [
          'api/receipts › starts over when the receipt is read again',
          'db/receipts.int › refuses a receipt that is no longer waiting, or was read again since',
        ],
      },
      {
        id: 'AC4',
        given: 'a receipt I confirmed',
        when: 'I tap Read again',
        then: 'it first warns that reading it again replaces the confirmed values, and reads it only if I agree',
        decided: REVIEWS,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC5',
        given: 'a receipt read again since I opened it',
        when: 'I confirm the readings I was shown',
        then: 'it is refused, and the new readings can be confirmed instead',
        decided: REVIEWS,
        checks: [
          'db/receipts.int › refuses a receipt that is no longer waiting, or was read again since',
        ],
      },
      {
        id: 'AC6',
        given: 'I ask for a receipt to be read again',
        when: 'the request is saved',
        then: 'the audit trail records who asked',
        decided: RUNS,
        checks: [],
        untested: 66,
      },
    ],
  },
  {
    id: 'US-READ-09',
    title: 'Have a receipt read even when Claude can’t',
    as: 'Alex, who travels for work',
    want: 'a receipt read by a fallback model when neither Claude model can read it',
    soThat: 'I check a reading instead of typing the receipt in, even during an outage or with no credit',
    feature: 'F-08',
    requirements: ['FR-INT-09'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'neither Claude model produced a reading, because there is no Anthropic key or credit, the key was rejected, or Anthropic didn’t answer after several tries',
        when: 'the receipt is read',
        then: 'a fallback model reads it once, on the organization’s own OpenAI key',
        decided: FALLBACK,
        checks: [
          'workflows/receipts › reads the receipt when Anthropic has no credit, and asks for a look',
          'workflows/receipts › reads the receipt when there is no Anthropic key',
          'workflows/receipts › reads the receipt when the Claude steps run out of retries',
        ],
      },
      {
        id: 'AC2',
        given: 'a Claude model read the receipt',
        when: 'it settles',
        then: 'the fallback isn’t asked',
        decided: FALLBACK,
        checks: ['workflows/receipts › is not called when a Claude model read the receipt'],
      },
      {
        id: 'AC3',
        given: 'only the fallback read the receipt',
        when: 'it settles',
        then: 'it Needs a look, however sure the fallback was, and its expense starts from that reading',
        decided: FALLBACK_RULES,
        checks: [
          'workflows/receipts › reads the receipt when Anthropic has no credit, and asks for a look',
        ],
      },
      {
        id: 'AC4',
        given: 'the organization has no OpenAI key',
        when: 'neither Claude model could read a receipt',
        then: 'the fallback is skipped, nothing is stored for it, and the receipt is Not read',
        decided: FALLBACK_RULES,
        checks: ['workflows/receipts › records a missing key as a failed reading, and calls no model'],
      },
      {
        id: 'AC5',
        given: 'the fallback can’t read it either, such as when the OpenAI account has no credit',
        when: 'the receipt settles',
        then: 'it is Not read, with OpenAI’s own message, and that isn’t retried',
        decided: FALLBACK_RULES,
        checks: [
          'workflows/receipts › settles as failed when the fallback has no credit either',
          'workflows/receipts › reads %o as %s',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt only the fallback read',
        when: 'I open it, or the model comparison',
        then: 'its reading shows in its own column marked fallback, beside why each Claude model couldn’t read it, and the comparison gives it its own row with its spend, never counting it as compared or agreed',
        decided: FALLBACK_RULES,
        checks: [
          'api/receipts › shows the fallback reading when no Claude model could read the receipt',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC7',
        given: 'the fallback reads a receipt',
        when: 'the request is sent',
        then: 'it gets the same instructions and structure as Claude, OpenAI is told to keep no copy, and no error it raises carries the key',
        decided: FALLBACK_RULES,
        checks: [
          'extraction/openai › sends the image, the strict schema and the effort, stores nothing, and prices the call',
          'extraction/openai › closes every object, requires every property and drops $schema',
          "extraction/openai › throws the provider's status, message and code, without the key",
        ],
      },
    ],
    note: 'The fallback model, GPT-5.6 Luna, and the rule that its reading alone is never Ready are Claude’s recommendations (ADR-0020); a person can make it Ready with Looks right (US-READ-05). Since Oct 3 it reads every receipt, while the Anthropic account has no credit (#4). FR-INT-16 replaces it once #52 is built.',
  },
  {
    id: 'US-READ-10',
    title: 'Capture when and where I bought it',
    as: 'Alex, who travels for work',
    want: 'the time of the purchase and the merchant’s address read from the receipt, with the time zone worked out from the place',
    soThat: 'each expense says when and where it happened without my typing it',
    feature: 'F-46',
    requirements: ['FR-INT-17'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt that prints a time and an address',
        when: 'it is read',
        then: 'the reading captures the time as printed, as hours and minutes, and the address as printed with its city and country picked out, each with its confidence',
        decided: OCT3,
        checks: [
          'extraction/normalize › reads the time as HH:MM and the address with its city, region and country',
        ],
      },
      {
        id: 'AC2',
        given: 'a receipt that prints no time or address, or one that can’t be read as a time of day or a two-letter country',
        when: 'it is read',
        then: 'that part is blank, and a blank never makes the receipt Need a look',
        decided: OCT3,
        checks: [
          'extraction/normalize › leaves one it can’t read blank, never a reason for review',
          'extraction/place › is blank for no reading, or one that printed neither',
        ],
      },
      {
        id: 'AC3',
        given: 'a receipt whose address pins a time zone',
        when: 'it is read',
        then: 'the time carries the zone worked out from the address; where the address can’t pin one, the zone is left blank',
        decided: { by: 'owner', source: 'Q9' },
        checks: [
          'extraction/place › carries the time, the address and the zone worked out from it',
          'extraction/place › says nothing when it can’t know',
        ],
      },
      {
        id: 'AC4',
        given: 'an address with a city, a region and a country',
        when: 'its time zone is worked out',
        then: 'it is the city’s zone, matched without case or accents, else the zone of the region’s largest city, else the country’s if the country has only one',
        decided: TIME_PLACE,
        checks: [
          'extraction/place › finds a city’s, in any case and without its accents',
          'extraction/place › falls back to its region, then to a country with one time zone',
        ],
      },
      {
        id: 'AC5',
        given: 'a receipt with a time or place',
        when: 'its expense is filed',
        then: 'the expense carries the time, time zone, address, city, region and country',
        decided: OCT3,
        checks: ['db/expense-details.int › files them with the expense, and a later reading refreshes them'],
      },
      {
        id: 'AC6',
        given: 'an expense I haven’t edited',
        when: 'its receipt is read again',
        then: 'a new time or place replaces the old, and a reading that offers neither leaves them as they are',
        decided: TIME_PLACE,
        checks: ['db/expense-details.int › files them with the expense, and a later reading refreshes them'],
      },
      {
        id: 'AC7',
        given: 'a reading stored before time and place were read',
        when: 'it is shown or used',
        then: 'it has neither, and is otherwise read as before',
        decided: TIME_PLACE,
        checks: ['extraction/schema › reads a reading made before fees were read as having none'],
      },
    ],
    note: 'Your requirement of Oct 3 and your answer to Q9. The time zone is looked up offline from about 7,300 world cities, so no address leaves ExpenseWise; a small town falls back to its region’s largest city, which can be wrong where a zone line splits the region (ADR-0030).',
  },
  {
    id: 'US-READ-11',
    title: 'Correct when and where on the expense',
    as: 'Alex, who travels for work',
    want: 'to edit the time and place on an expense, and set its time zone where the place doesn’t pin one',
    soThat: 'an expense says when and where it really happened, even when its receipt is wrong or silent',
    feature: 'F-46',
    requirements: ['FR-INT-17'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense',
        when: 'I open it and tap Edit',
        then: 'it shows when and where it was bought, and I can change the time, address, city, region, country and time zone like its other fields',
        decided: OCT3,
        checks: [
          'api/expenses › edits when and where it was bought, working out the time zone from the place',
          'domain/expense-details › sets, tidies and clears fields, and says what changed',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'I change the city, region or country',
        when: 'I save',
        then: 'the time zone is worked out again from the place unless the same edit sets one, and is blank where the place pins none; clearing the zone asks for it from the place again',
        decided: TIME_PLACE,
        checks: [
          'api/expenses › edits when and where it was bought, working out the time zone from the place',
        ],
      },
      {
        id: 'AC3',
        given: 'a place that can’t pin a time zone',
        when: 'I edit the expense',
        then: 'I can set any real time zone myself',
        decided: { by: 'owner', source: 'Q9' },
        checks: [
          'api/expenses › edits when and where it was bought, working out the time zone from the place',
          'domain/expense-details › knows a country code’s shape and a real time zone',
        ],
      },
      {
        id: 'AC4',
        given: 'I have edited the expense',
        when: 'its receipt is read again',
        then: 'my time and place stay as I set them',
        decided: TIME_PLACE,
        checks: [
          'db/expense-details.int › keeps a person’s edit over any later reading, and refuses a malformed one',
        ],
      },
      {
        id: 'AC5',
        given: 'a time that isn’t a time of day, a country that isn’t two letters, a time zone that doesn’t exist, or an address over 300 characters',
        when: 'I save',
        then: 'nothing is saved and the field is named; the database refuses such a time or country too',
        decided: TIME_PLACE,
        checks: [
          'domain/expense-details › refuses %j',
          'db/expense-details.int › stores a time of day and a two-letter country, and nothing else',
          'db/expense-details.int › keeps a person’s edit over any later reading, and refuses a malformed one',
        ],
      },
      {
        id: 'AC6',
        given: 'I change the time or place',
        when: 'it is saved',
        then: 'the audit trail records what changed',
        decided: TIME_PLACE,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Claude’s assumption, yours to overturn: a time or place on the expense that differs from its receipt shows against the receipt, but doesn’t by itself make review reject it, which checks what is claimed (FR-GOV-10).',
  },
  {
    id: 'US-READ-12',
    title: 'Compare the two models on our own receipts',
    as: 'the product owner',
    want: 'a running comparison of how Haiku 4.5 and Sonnet 5.5 read our real receipts: how often they agree, how sure each is, how long each takes and what each costs',
    soThat: 'the model tier is chosen on evidence from our own receipts, not impressions',
    feature: 'F-07',
    requirements: ['FR-INT-08', 'NFR-AI-04', 'NFR-AI-03'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'receipts read by both models',
        when: 'I open Receipts',
        then: 'How the models compare says how many receipts both read the same way on merchant, date, currency and total, and for each model how many readings were sure, the average time and the spend',
        decided: TWO_MODELS,
        checks: ['api/receipts › keeps a running comparison of the two models', 'e2e/signed-in'],
      },
      {
        id: 'AC2',
        given: 'a reading that wouldn’t be Ready on its own, its sums and date included',
        when: 'the comparison counts it',
        then: 'it counts as unsure, even when both models agree on it',
        decided: { by: 'claude' },
        checks: [
          'workflows/receipts › asks for a look when both agree on parts that don’t make the total',
        ],
      },
      {
        id: 'AC3',
        given: 'the fallback model has read some receipts',
        when: 'I open Receipts',
        then: 'it has its own row with its spend, and its readings never count towards the receipts compared or agreed',
        decided: FALLBACK_RULES,
        checks: [
          'api/receipts › shows the fallback reading when no Claude model could read the receipt',
        ],
      },
      {
        id: 'AC4',
        given: 'each reading in the comparison',
        when: 'its spend is added up',
        then: 'it counts the exact cost of that call, summed per model',
        decided: { by: 'blueprint', source: 'ADR-0006' },
        checks: [
          'api/receipts › keeps a running comparison of the two models',
          'extraction/models › prices a call exactly in nano-dollars',
        ],
      },
    ],
    note: 'It collects nothing while the Anthropic account has no credit (#4). The tier decision (#21) needs about 20 receipts read by both, then your decision, and takes effect by turning the other model off (#52); re-confirming it after about 100 real receipts waits on that.',
  },
  {
    id: 'US-READ-13',
    title: 'Trace any figure to what read it',
    as: 'an auditor',
    want: 'every reading kept with the model that made it, how it went, what it cost and the request that asked for it',
    soThat: 'any figure on a receipt can be traced to what read it',
    feature: 'F-06',
    requirements: ['FR-INT-06', 'NFR-AI-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt is read',
        when: 'each model answers',
        then: 'its reading is stored once for that request, with the model, its outcome and its cost; a retried step never stores it twice',
        decided: TWO_MODELS,
        checks: [
          'db/receipts.int › records each model once per request, then settles once',
          'workflows/receipts › files it as Ready when both read it with confidence and agree',
        ],
      },
      {
        id: 'AC2',
        given: 'a stored reading',
        when: 'it is kept',
        then: 'it also records the prompt version, the schema version, how long it took and the tokens it used',
        decided: TWO_MODELS,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC3',
        given: 'a reading that failed',
        when: 'it is stored',
        then: 'it keeps why: no key, a refused request with the provider’s own message, or no answer after several tries',
        decided: RUNS,
        checks: [
          'workflows/receipts › records a missing key as a failed reading, and calls no model',
          'workflows/receipts › keeps the other reading when the provider rejects one request for good',
          'workflows/receipts › reads the receipt when the Claude steps run out of retries',
        ],
      },
      {
        id: 'AC4',
        given: 'a model’s answer',
        when: 'its cost is worked out',
        then: 'it is exact: the model’s list price per token in whole nano-dollars, cache reads and writes included, with no floating point, kept on the reading in whole micro-dollars',
        decided: { by: 'claude' },
        checks: [
          'extraction/models › prices a call exactly in nano-dollars',
          'extraction/models › includes cache reads and writes',
          'extraction/openai › sends the image, the strict schema and the effort, stores nothing, and prices the call',
          'workflows/receipts › files it as Ready when both read it with confidence and agree',
        ],
      },
      {
        id: 'AC5',
        given: 'a receipt’s readings are in',
        when: 'its status is settled',
        then: 'the audit trail records that it was read, once per request',
        decided: RUNS,
        checks: ['db/receipts.int › records each model once per request, then settles once'],
      },
      {
        id: 'AC6',
        given: 'someone in another organization',
        when: 'they look for a receipt or its readings',
        then: 'they find nothing',
        decided: { by: 'claude' },
        checks: [
          'db/receipts.int › keeps receipts inside their organization',
          'db/tenancy.int › puts a forced tenant policy on every table that holds org data',
        ],
      },
      {
        id: 'AC7',
        given: 'a stored reading',
        when: 'anything in the app tries to delete it',
        then: 'it is refused; a reading goes only with its receipt, when a person deletes a duplicate',
        decided: { by: 'claude', source: 'ADR-0028' },
        checks: [
          'db/duplicates.int › deletes nothing in another organization, and the app cannot delete receipts any other way',
          'db/duplicates.int › deletes a copy with its readings and expense, keeps a record of it, and returns its file',
        ],
      },
    ],
  },
  {
    id: 'US-READ-14',
    title: 'Only the file I filed is read',
    as: 'an auditor',
    want: 'the stored file checked against what was filed before any model reads it',
    soThat: 'a reading always belongs to the file it claims to',
    feature: 'F-06',
    requirements: ['FR-INT-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a stored file whose size or SHA-256 isn’t what was described when it was filed',
        when: 'reading starts',
        then: 'no model sees it, and the receipt is Not read, recorded as a changed file',
        decided: TWO_MODELS,
        checks: ['workflows/receipts › reads nothing when the stored file is not the one described'],
      },
      {
        id: 'AC2',
        given: 'a stored file whose first bytes aren’t those of an image or PDF the app reads',
        when: 'reading starts',
        then: 'no model sees it',
        decided: TWO_MODELS,
        checks: ['workflows/receipts › recognizes %s', 'workflows/receipts › rejects anything else'],
      },
      {
        id: 'AC3',
        given: 'a stored file whose first bytes show another type than the one it was filed as',
        when: 'reading starts',
        then: 'no model sees it',
        decided: TWO_MODELS,
        checks: [],
        untested: 66,
      },
    ],
  },
  {
    id: 'US-READ-15',
    title: 'Never wait on a reading, and never lose one',
    as: 'Alex, who travels for work',
    want: 'filing a receipt to answer at once, with the reading done in the background and carried through a provider’s failures',
    soThat: 'I never wait on AI, and no receipt is left half-read',
    feature: 'F-06',
    requirements: ['NFR-ARC-02'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I file a receipt',
        when: 'filing is saved',
        then: 'the app answers with the receipt Reading, without waiting for it to be read, and hands the reading to the workflow runner; filing the same receipt again is safe',
        decided: { by: 'blueprint', source: 'arch AP3' },
        checks: ['api/receipts › files the receipt, hands its event to the runner, and is safe to retry'],
      },
      {
        id: 'AC2',
        given: 'the workflow runner can’t be reached',
        when: 'I file a receipt',
        then: 'it is still filed, and the request to read it waits in the outbox, saved with the receipt',
        decided: RUNS,
        checks: [
          'api/receipts › still files the receipt when the runner is unreachable; the relay sends it later',
          'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
        ],
      },
      {
        id: 'AC3',
        given: 'a model call that fails in a way trying again may fix, such as an overloaded or rate-limited provider',
        when: 'the step fails',
        then: 'it is retried, and nothing is stored for it until it succeeds or runs out of tries',
        decided: RUNS,
        checks: [
          'workflows/receipts › throws errors a retry may fix, so the step is retried',
          'workflows/receipts › reads %o as %s',
        ],
      },
      {
        id: 'AC4',
        given: 'a failure that trying again won’t fix, such as a rejected key or no credit',
        when: 'the provider answers',
        then: 'the reading is stored as failed with the provider’s own message, and isn’t retried',
        decided: RUNS,
        checks: [
          'workflows/receipts › keeps the other reading when the provider rejects one request for good',
          'workflows/receipts › reads %o as %s',
        ],
      },
      {
        id: 'AC5',
        given: 'a model’s step runs out of tries',
        when: 'it gives up',
        then: 'that reading is stored as unavailable, and the receipt still settles from the readings there are',
        decided: RUNS,
        checks: ['workflows/receipts › reads the receipt when the Claude steps run out of retries'],
      },
      {
        id: 'AC6',
        given: 'the whole reading run fails',
        when: 'the runner gives up on it',
        then: 'the receipt is settled from whatever readings were stored, so it never stays Reading',
        decided: RUNS,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC7',
        given: 'a server with no workflow runner connected',
        when: 'I open Receipts',
        then: 'it says receipts are stored but can’t be read yet',
        decided: RUNS,
        checks: ['api/receipts › says when this server cannot have receipts read'],
      },
    ],
    note: 'In production the outbox relay isn’t running yet, so a receipt whose hand-off fails waits for Read again (GAP-05, #11).',
  },
  {
    id: 'US-READ-16',
    title: 'Have a receipt Ready within 30 seconds',
    as: 'Alex, who travels for work',
    want: 'a receipt I capture to be Ready within 30 seconds',
    soThat: 'capturing feels instant, and I can put my phone away',
    feature: 'F-06',
    requirements: ['NFR-PERF-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I file a receipt',
        when: 'filing is saved',
        then: 'its reading starts at once, without waiting for the outbox relay',
        decided: RUNS,
        checks: ['api/receipts › files the receipt, hands its event to the runner, and is safe to retry'],
      },
      {
        id: 'AC2',
        given: 'a receipt being read',
        when: 'I open it',
        then: 'each model shows as pending until it answers',
        decided: RUNS,
        checks: ['api/receipts › shows each model pending while the receipt is read', 'e2e/signed-in'],
      },
      {
        id: 'AC3',
        given: 'each reading',
        when: 'it is stored',
        then: 'its time is kept, and the model comparison shows each model’s average',
        decided: RUNS,
        checks: ['api/receipts › keeps a running comparison of the two models'],
      },
      {
        id: 'AC4',
        given: 'receipts captured in everyday use',
        when: 'each one settles',
        then: 'the time from capture to Ready is under 30 seconds for 95 of every 100',
        decided: { by: 'blueprint', source: 'journeys §4.2' },
        checks: [],
        untested: 32,
      },
    ],
    note: 'Nothing yet measures capture to Ready end to end; each reading stores only its own time (GAP-16). #32 records it at settlement and shows the 95th percentile beside the comparison, which is what proves AC4.',
  },
  {
    id: 'US-READ-17',
    title: 'Turn each AI model on or off for my organization',
    as: 'the organization’s owner',
    want: 'to turn each AI model on or off for my organization, and choose the one that reads our receipts first',
    soThat: 'we pay only for the models we choose, and receipts keep moving when one can’t read',
    feature: 'F-45',
    requirements: ['FR-INT-16'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'I am an owner or a finance admin',
        when: 'I open Settings',
        then: 'I can turn each AI model on or off for my organization',
        decided: { by: 'owner', source: 'Q8' },
        checks: [],
      },
      {
        id: 'AC2',
        given: 'models that are on',
        when: 'I choose the primary',
        then: 'exactly one is primary; any model that is on can be made primary at any time, OpenAI’s included, whatever the eval set says of it',
        decided: OCT3,
        checks: [],
      },
      {
        id: 'AC3',
        given: 'a primary and back-ups',
        when: 'a receipt is read',
        then: 'the primary reads it; a model that is on but not primary is a back-up, and reads only when the primary can’t, in the order I set',
        decided: { by: 'owner', source: 'Q11' },
        checks: [],
      },
      {
        id: 'AC4',
        given: 'a model that is off',
        when: 'any of our receipts is read',
        then: 'that model doesn’t read it',
        decided: OCT3,
        checks: [],
      },
      {
        id: 'AC5',
        given: 'every model is off',
        when: 'a receipt is filed',
        then: 'it is filed but not read, for a person to fill in',
        decided: { by: 'owner', source: 'Q8' },
        checks: [],
      },
      {
        id: 'AC6',
        given: 'anyone changes a switch, the primary or the order',
        when: 'it is saved',
        then: 'the change records who made it',
        decided: OCT3,
        checks: [],
      },
    ],
    note: 'Your requirement of Oct 3, with your answers to Q8 and Q11 (#52). It is how the tier decision (#21) takes effect, and it replaces the fallback rule (FR-INT-09). A receipt will then be read once, by the primary, so Ready will rest on that one reading; that needs a decision record replacing ADR-0017.',
  },
  {
    id: 'US-READ-18',
    title: 'Switch a model off for every organization at once',
    as: 'the product owner',
    want: 'an operator switch for each AI model that turns it off for every organization at once',
    soThat: 'I can stop a model during an outage or a bad release, whatever each organization has chosen',
    feature: 'F-45',
    requirements: ['FR-INT-16'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'I turn a model off with its operator switch',
        when: 'any organization’s receipt is read',
        then: 'that model doesn’t read it, whatever the organization’s own setting',
        decided: { by: 'owner', source: 'Q8' },
        checks: [],
      },
      {
        id: 'AC2',
        given: 'I change an operator switch',
        when: 'it is saved',
        then: 'the change records who made it',
        decided: OCT3,
        checks: [],
      },
    ],
  },
  {
    id: 'US-EVAL-01',
    title: 'Know how accurately each model reads, by layer',
    as: 'the product owner',
    want: 'each model’s readings scored against documents whose answers are known, field by field and for each layer of the eval set',
    soThat: 'the model tier, and every change of prompt or model, rests on measured accuracy',
    feature: 'F-38',
    requirements: ['NFR-AI-01', 'FR-INT-17'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a document with known answers and a model’s reading of it',
        when: 'the reading is scored',
        then: 'each field the document prints is scored: document type, merchant, date, currency, total, subtotal, tax, tip and card; a field it doesn’t print is skipped',
        decided: EVAL_SET,
        checks: [
          'evals/score › scores every printed field and files a fully confident read as Ready',
          'evals/score › skips fields the document does not print',
        ],
      },
      {
        id: 'AC2',
        given: 'a merchant read differently from the known answer',
        when: 'it is scored',
        then: 'case, punctuation, “&” for “and”, a branch number or an “Inc.” don’t count against it, but another business does',
        decided: { by: 'claude' },
        checks: ['evals/score › matches %s and %s', 'evals/score › does not match %s and %s'],
      },
      {
        id: 'AC3',
        given: 'a document that prints a time or a city',
        when: 'it is scored',
        then: 'the time, city and country are scored too',
        decided: TIME_PLACE,
        checks: ['evals/score › scores the time and place a document prints (FR-INT-17)'],
      },
      {
        id: 'AC4',
        given: 'a reading that would be filed as Ready with a wrong field',
        when: 'it is scored',
        then: 'it counts as a silent error; one that low confidence or the sums and date checks send for a look doesn’t',
        decided: { by: 'claude' },
        checks: [
          'evals/score › flags a confidently wrong total as a silent error when nothing checks it',
          'evals/score › sends a total its parts do not make to review, so it is no silent error',
          'evals/score › sends a doubtful read to review rather than counting a silent error',
          'evals/score › judges the date as if the receipt was captured on the day it is dated',
        ],
      },
      {
        id: 'AC5',
        given: 'a model that refuses a document',
        when: 'it is scored',
        then: 'every field it should have read counts as wrong',
        decided: { by: 'claude' },
        checks: ['evals/score › counts a refusal as every scored field wrong'],
      },
      {
        id: 'AC6',
        given: 'a run of the harness',
        when: 'its report is written',
        then: 'it gives each model’s fields correct, documents that would skip review, silent errors, confidently wrong fields and cost, with percentages worked out without floating point',
        decided: { by: 'claude', source: 'ADR-0006' },
        checks: [
          'evals/score › summarizes accuracy, review routing and cost per model',
          'evals/score › formats percentages and percentiles without floats',
        ],
      },
      {
        id: 'AC7',
        given: 'a run of the harness',
        when: 'its report is written',
        then: 'accuracy is reported for each layer of the eval set apart, today the public and the synthetic',
        decided: EVAL_SET,
        checks: [],
        untested: 66,
      },
    ],
    note: 'The harness has never run against a model: the key never reached the build environment, so your real receipts are compared on the page instead (ADR-0017). The layers from your past emails and from real captures wait on your decision on D-12 (#39).',
  },
  {
    id: 'US-EVAL-02',
    title: 'Build an eval set whose answers are known',
    as: 'the product owner',
    want: 'an eval set of public receipts and generated documents whose answers are known',
    soThat: 'accuracy can be measured before any of our own receipts are labelled',
    feature: 'F-38',
    requirements: ['NFR-AI-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'the public CORD v2 receipts',
        when: 'the eval set is built',
        then: 'each one’s total, subtotal and tax are taken from its labels as Indonesian rupiah, and one without a usable total is left out',
        decided: EVAL_SET,
        checks: [
          'evals/datasets/cord › reads total, subtotal and tax as rupiah',
          'evals/datasets/cord › skips receipts without a usable total',
          'evals/datasets/cord › reads %j as %s',
          'evals/datasets/cord › ignores %j',
        ],
      },
      {
        id: 'AC2',
        given: 'no public dataset of hotel folios exists',
        when: 'the eval set is built',
        then: 'hotel folios and airline e-tickets with known answers are generated for it',
        decided: EVAL_SET,
        checks: ['evals/synthetic/synthetic › prints totals that reconcile (seed %i)'],
      },
      {
        id: 'AC3',
        given: 'a seed',
        when: 'a folio, e-ticket or restaurant receipt is generated from it',
        then: 'the same seed always makes the same document',
        decided: { by: 'claude' },
        checks: [
          'evals/synthetic/synthetic › is reproducible from its seed',
          'evals/synthetic/synthetic › repeats exactly for the same seed',
        ],
      },
      {
        id: 'AC4',
        given: 'a generated document',
        when: 'it is printed',
        then: 'its subtotal, tax and tip make its total, with tax worked out in whole cents, and its total, card number and any time or city in its answers appear on it',
        decided: { by: 'claude' },
        checks: [
          'evals/synthetic/synthetic › prints totals that reconcile (seed %i)',
          'evals/synthetic/synthetic › computes tax half up in cents and moves dates by whole days',
        ],
      },
      {
        id: 'AC5',
        given: 'eval documents and results',
        when: 'changes are committed',
        then: 'they are never in git',
        decided: { by: 'claude', source: 'ADR-0012' },
        checks: [],
        untested: 66,
      },
    ],
    note: 'SROIE was planned for the public layer, but its usual mirrors carry code rather than receipts, so generated US restaurant card slips cover the merchant, date, tip and card instead: Claude’s substitution.',
  },
];
