import type { Story } from '../model.ts';

const OCT3 = { by: 'owner', source: 'owner 2026-10-03' } as const;
const OCT4 = { by: 'owner', source: 'owner 2026-10-04' } as const;
const Q6 = { by: 'owner', source: 'Q6' } as const;
const Q7 = { by: 'owner', source: 'Q7' } as const;
const ADR29 = { by: 'claude', source: 'ADR-0029' } as const;

/**
 * Expense reports, local expenses, and what comes with submitting and approving them
 * (FR-EXP-05, FR-EXP-10 to FR-EXP-14, FR-GOV-10 to FR-GOV-13; ADR-0029).
 */
export const REPORT_STORIES: readonly Story[] = [
  {
    id: 'US-RPT-01',
    title: 'My trips go on a report once I’m back',
    as: 'Alex, who travels for work',
    want: 'each trip to go on an expense report by itself, a day after I’m back',
    soThat: 'every trip is claimed without my having to remember it',
    feature: 'F-17',
    requirements: ['FR-EXP-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a trip with expenses on it, and no report of mine open',
        when: '24 hours have passed after its return date',
        then: 'it goes on a new report, opened for it',
        decided: OCT4,
        checks: [
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
        rules: ['R-REPORT-JOIN'],
      },
      {
        id: 'AC2',
        given: 'a trip’s return date',
        when: 'the 24 hours are counted',
        then: 'they run from the end of that day where it ends last (UTC−12), so the trip joins at noon UTC two days after its return date, and never earlier for anyone',
        decided: ADR29,
        checks: [
          'domain/reports › waits until 24 hours after its day has ended everywhere: noon UTC two days on',
          'domain/reports › is never early, even where the day ends last (UTC−12)',
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
        rules: ['R-REPORT-JOIN'],
      },
      {
        id: 'AC3',
        given: 'a report of mine already open',
        when: 'a later trip’s time comes',
        then: 'it joins that report rather than a new one',
        decided: OCT4,
        checks: ['db/reports.int › puts later trips and local expenses on the report already open'],
      },
      {
        id: 'AC4',
        given: 'a trip with no expenses on it',
        when: 'its time comes',
        then: 'it joins no report until something is on it',
        decided: ADR29,
        checks: [
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
      },
      {
        id: 'AC5',
        given: 'a trip on a report, including one with expenses still needing a look',
        when: 'I look at what the report holds',
        then: 'the trip’s expenses are on it through the trip, and never on the report by themselves',
        decided: ADR29,
        checks: [
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
          'db/reports.int › closes with what is ready and moves what still needs review to the next report',
          'db/reports.int › holds only its member’s trips and expenses, and a closed time only when closed',
        ],
      },
      {
        id: 'AC6',
        given: 'it is 7 minutes past an hour',
        when: 'the schedule runs',
        then: 'it does each organization’s due work as of that one moment, joining what is due and closing reports whose day 28 has come; one organization failing doesn’t hold up the rest, the run is retried, and nothing joins twice',
        decided: ADR29,
        checks: [
          'workflows/reports › does each organization’s due work at one moment, and logs counts only',
          'workflows/reports › carries on past an organization that fails, then fails the run so it is retried',
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
        rules: ['R-REPORT-SCHEDULE'],
      },
      {
        id: 'AC7',
        given: 'reports in many organizations',
        when: 'the schedule asks what is due',
        then: 'it learns only which organizations have work, by id, and does each one’s work inside that organization; a report holds only its own member’s trips and expenses',
        decided: ADR29,
        checks: [
          'db/reports.int › tells the schedule which organizations have work due, and no more than their ids',
          'db/reports.int › holds only its member’s trips and expenses, and a closed time only when closed',
        ],
      },
      {
        id: 'AC8',
        given: 'a report opens and a trip joins it',
        when: 'anyone later looks at the audit trail',
        then: 'it records the report opening and the trip being added',
        decided: ADR29,
        checks: [
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
      },
    ],
    note: 'Counting from where the return day ends last means a trip joins between 24 and 50 hours after its return day ends where the traveler is (about 31 hours in US Central time), and within the hour after that, since the schedule runs hourly. Your organization’s time zone (#63) could tighten it. That a trip with no expenses waits, and that its expenses go with it, are Claude’s assumptions (FR-EXP-05), yours to overturn.',
  },
  {
    id: 'US-RPT-02',
    title: 'Claim spend on no trip, saying why it was for business',
    as: 'Riley, a solo professional who self-attests',
    want: 'an expense on no trip to go on my report as a local expense, once I have said why it was for business',
    soThat:
      'everyday business spend is reimbursed too, with the reason an approver or auditor will ask for',
    feature: 'F-50',
    requirements: ['FR-EXP-14', 'FR-EXP-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense dated on a day no trip of mine covers',
        when: 'it is filed',
        then: 'it is a local expense, on no trip, and needs a justification',
        decided: { by: 'owner', source: 'Q21' },
        checks: [
          'db/reports.int › puts later trips and local expenses on the report already open',
          'db/reports.int › refuses a justification on a trip’s expense, or one too long',
          'domain/reports › is a local expense needing review, or with no justification',
        ],
      },
      {
        id: 'AC2',
        given: 'a local expense',
        when: '24 hours have passed after its date',
        then: 'it joins my open report as a local expense; one with no date yet joins none',
        decided: ADR29,
        checks: [
          'db/reports.int › puts later trips and local expenses on the report already open',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
        rules: ['R-REPORT-JOIN'],
      },
      {
        id: 'AC3',
        given: 'a local expense',
        when: 'I open it',
        then: 'its section Why it was for business asks for a reason, and Save the reason keeps what I write, trimmed',
        decided: { by: 'owner', source: 'Q21' },
        checks: [
          'api/reports › refuses to close while anything needs a justification, then closes and reopens',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC4',
        given: 'a reason',
        when: 'I save it',
        then: 'it can be up to 500 characters; a longer one is refused, and a blank one counts as no reason',
        decided: ADR29,
        checks: [
          'domain/reports › keeps a justification trimmed, blank as none, and refuses one too long',
          'db/reports.int › refuses a justification on a trip’s expense, or one too long',
          'api/reports › refuses to reopen an open report, and a justification on a trip’s expense or too long',
        ],
        rules: ['R-JUSTIFICATION-MAX'],
      },
      {
        id: 'AC5',
        given: 'an expense on a trip',
        when: 'I try to give it a justification',
        then: 'it is refused: the trip says why it was spent',
        decided: ADR29,
        checks: [
          'db/reports.int › refuses a justification on a trip’s expense, or one too long',
          'api/reports › refuses to reopen an open report, and a justification on a trip’s expense or too long',
        ],
      },
      {
        id: 'AC6',
        given: 'a local expense on my report with no reason',
        when: 'I try to close the report',
        then: 'it is refused, naming that expense, until I give one',
        decided: ADR29,
        checks: [
          'domain/reports › is a local expense needing review, or with no justification',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
          'api/reports › refuses to close while anything needs a justification, then closes and reopens',
        ],
      },
      {
        id: 'AC7',
        given: 'a local expense that is Ready and has no reason, even before it joins a report',
        when: 'I open Needs you',
        then: 'it is listed as Local, asking me to add a reason',
        decided: ADR29,
        checks: [
          'api/reports › asks for a justification, and says when a report is ready to close',
        ],
      },
      {
        id: 'AC8',
        given: 'a local expense still being read, or one submitted',
        when: 'I try to give or change its reason',
        then: 'it is refused',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC9',
        given: 'I give or change a reason',
        when: 'anyone later looks at the audit trail',
        then: 'it records the reason before and after',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Your answer to Q21 makes these expenses local and needing a justification. That one without a reason holds its report open is Claude’s assumption (FR-EXP-12), though FR-EXP-14 states it as yours; please confirm. That a local expense joins 24 hours after its own date, and that a report may hold only local expenses in a month with no travel, are Claude’s assumptions too (FR-EXP-05). Whether a trip covers an expense goes by the expense’s date (ADR-0023).',
  },
  {
    id: 'US-RPT-03',
    title: 'Close my report when it is done, and reopen it',
    as: 'Alex, who travels for work',
    want: 'to close a report once nothing on it needs me, and to reopen it if I need to, until I submit it',
    soThat: 'what I claim is settled before I submit it, and a late change is never stranded',
    feature: 'F-17',
    requirements: ['FR-EXP-12'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an open report where nothing needs a look and every local expense has a reason',
        when: 'I press Close the report',
        then: 'it closes, and is not submitted: submitting is mine to do',
        decided: OCT4,
        checks: [
          'domain/lifecycle/report › closes only with nothing left to review, and reopens until submitted',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
          'api/reports › refuses to close while anything needs a justification, then closes and reopens',
        ],
      },
      {
        id: 'AC2',
        given: 'a trip on my report with an expense that needs a look',
        when: 'I try to close the report',
        then: 'it is refused, naming what still needs me',
        decided: OCT4,
        checks: [
          'domain/lifecycle/report › closes only with nothing left to review, and reopens until submitted',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
      },
      {
        id: 'AC3',
        given: 'something on my report still being read, or held as a possible duplicate',
        when: 'I try to close the report',
        then: 'it is refused, as for something needing a look',
        decided: ADR29,
        checks: [
          'domain/reports › is a trip with an expense being read or needing review',
          'api/reports › shows each trip and local expense, and leaves a possible duplicate out of the totals',
        ],
      },
      {
        id: 'AC4',
        given: 'a report that is still open',
        when: 'anyone tries to submit it',
        then: 'it is refused: only a closed report can be submitted',
        decided: OCT4,
        checks: ['domain/lifecycle/report › from %s rejects %j with %s'],
      },
      {
        id: 'AC5',
        given: 'a closed report',
        when: 'I press Reopen',
        then: 'it is open again; reopening one already open, or one submitted, is refused, since a submitted report is locked',
        decided: OCT4,
        checks: [
          'domain/lifecycle/report › closes only with nothing left to review, and reopens until submitted',
          'api/reports › refuses to close while anything needs a justification, then closes and reopens',
          'api/reports › refuses to reopen an open report, and a justification on a trip’s expense or too long',
        ],
      },
      {
        id: 'AC6',
        given: 'I reopen a closed report',
        when: 'its new closing day is set',
        then: 'it keeps its day 28, or gets 7 days from reopening if that is later',
        decided: ADR29,
        checks: [
          'domain/reports › gives a reopened report a week, or keeps its own day 28 if later',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
        rules: ['R-REOPEN-GRACE'],
      },
      {
        id: 'AC7',
        given: 'a closed report',
        when: 'an expense on it is edited, or a trip on it is deleted',
        then: 'it reopens by itself',
        decided: ADR29,
        checks: [
          'db/reports.int › reopens a closed report when something on it changes',
          'db/trips.int › refuses while a submitted expense rests on it, and reopens a closed report it was on',
        ],
      },
      {
        id: 'AC8',
        given: 'a closed report',
        when: 'a receipt on it is read again, a trip on it is edited, an expense moves onto or off it, a reason on it changes, or a duplicate on it is deleted or merged',
        then: 'it reopens by itself too, with the audit trail saying why; a submitted report never reopens this way',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC9',
        given: 'my report has been closed and reopened',
        when: 'anyone looks at the audit trail',
        then: 'it shows each step in order: opened, each trip and local expense added, closed, reopened',
        decided: ADR29,
        checks: [
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
      },
    ],
    note: 'Submitting arrives with approval (#24); until then the report’s lifecycle refuses it from any state but closed (AC4). That an expense still being read or a possible duplicate holds a report open, the 7 days a reopened report gets, and reopening on any change are Claude’s (ADR-0029), yours to overturn.',
  },
  {
    id: 'US-RPT-04',
    title: 'My report closes itself on day 28',
    as: 'Alex, who travels for work',
    want: 'a report to close itself 28 days after it opens, with whatever is ready, and to be warned before then if something still needs me',
    soThat:
      'finished trips are reimbursed on time, and one unfinished receipt never holds up the rest',
    feature: 'F-17',
    requirements: ['FR-EXP-12'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a report that has just opened',
        when: 'I look at when it closes',
        then: 'it is 28 days from opening',
        decided: OCT4,
        checks: [
          'domain/reports › closes itself 28 days after it opens, and warns in its last week',
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
        rules: ['R-REPORT-WINDOW'],
      },
      {
        id: 'AC2',
        given:
          'day 28 has come, with one trip on my report still needing a look and the rest ready',
        when: 'the schedule reaches it',
        then: 'the report closes with what is ready, without being submitted, and the trip still needing a look moves to the next report, opened for it if need be, with its own 28 days',
        decided: { by: 'owner', source: 'Q20' },
        checks: [
          'domain/reports › closes with what is ready and moves the rest on',
          'db/reports.int › closes with what is ready and moves what still needs review to the next report',
        ],
        rules: ['R-REPORT-WINDOW'],
      },
      {
        id: 'AC3',
        given: 'day 28 has come and nothing on my report is ready',
        when: 'the schedule reaches it',
        then: 'it stays open, overdue, rather than moving everything on, and Needs you puts it first',
        decided: ADR29,
        checks: [
          'domain/reports › waits, overdue, when nothing is ready, and drops a report holding nothing',
          'db/reports.int › leaves a report with nothing ready open, overdue, and drops one holding nothing',
          'api/reports › puts a report first in its last week with something left, and when overdue',
        ],
      },
      {
        id: 'AC4',
        given: 'an open report left holding nothing, as when its only expense moves off its trip',
        when: 'the schedule runs',
        then: 'the report is dropped, whatever its day, and the empty trip comes off it',
        decided: ADR29,
        checks: [
          'domain/reports › waits, overdue, when nothing is ready, and drops a report holding nothing',
          'db/reports.int › leaves a report with nothing ready open, overdue, and drops one holding nothing',
        ],
      },
      {
        id: 'AC5',
        given: 'day 28 is near and something on my report still needs me',
        when: 'I open Needs you',
        then: 'the report comes first, warning that reimbursement will be delayed unless I close it by its date',
        decided: OCT4,
        checks: [
          'api/reports › puts a report first in its last week with something left, and when overdue',
        ],
      },
      {
        id: 'AC6',
        given: 'an open report with something still needing me',
        when: 'it reaches its last 7 days',
        then: 'the warning starts, and stays while the report is open',
        decided: ADR29,
        checks: [
          'domain/reports › closes itself 28 days after it opens, and warns in its last week',
          'api/reports › puts a report first in its last week with something left, and when overdue',
        ],
        rules: ['R-REPORT-WARNING'],
      },
      {
        id: 'AC7',
        given: 'day 28 closes a report, or a report is dropped',
        when: 'anyone later looks at the audit trail',
        then: 'it records the close by day 28 with what moved, or the drop',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
    ],
    note: 'You asked for the warning as day 28 nears; that it starts 7 days before is Claude’s. Waiting, overdue, when nothing is ready, and dropping an empty report, are Claude’s too (ADR-0029), yours to overturn.',
  },
  {
    id: 'US-RPT-05',
    title: 'Move a trip to another report',
    as: 'Alex, who travels for work',
    want: 'to move a trip, or a local expense, to another open report or a new one',
    soThat:
      'a trip still needing a look doesn’t hold up the others, and each report holds what I want claimed together',
    feature: 'F-17',
    requirements: ['FR-EXP-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a trip on my open report',
        when: 'I choose Move to another report and pick another open report, or A new report',
        then: 'the trip moves there, with its expenses',
        decided: OCT4,
        checks: [
          'db/reports.int › moves a trip to a new report, dropping the one it leaves empty',
          'api/reports › moves a trip or a local expense to a new report, and refuses a closed one',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'a local expense on my open report',
        when: 'I move it',
        then: 'it moves on its own; an expense on a trip can’t, since it goes with its trip',
        decided: ADR29,
        checks: [
          'db/reports.int › moves a local expense, and refuses a closed report, a trip’s expense or another member’s',
          'api/reports › moves a trip or a local expense to a new report, and refuses a closed one',
        ],
      },
      {
        id: 'AC3',
        given: 'the report it is on, or the one I pick, is closed',
        when: 'I try to move it',
        then: 'it is refused: reopen it first',
        decided: ADR29,
        checks: [
          'db/reports.int › moves a local expense, and refuses a closed report, a trip’s expense or another member’s',
          'api/reports › moves a trip or a local expense to a new report, and refuses a closed one',
        ],
      },
      {
        id: 'AC4',
        given: 'a move that leaves a report holding nothing',
        when: 'it is done',
        then: 'that report is dropped',
        decided: ADR29,
        checks: [
          'db/reports.int › moves a trip to a new report, dropping the one it leaves empty',
          'api/reports › moves a trip or a local expense to a new report, and refuses a closed one',
        ],
      },
      {
        id: 'AC5',
        given: 'a trip or expense of one member, and a report of another',
        when: 'anyone tries to put one on the other',
        then: 'it is refused: a report holds only its own member’s trips and expenses',
        decided: ADR29,
        checks: [
          'db/reports.int › moves a local expense, and refuses a closed report, a trip’s expense or another member’s',
          'db/reports.int › holds only its member’s trips and expenses, and a closed time only when closed',
        ],
      },
      {
        id: 'AC6',
        given: 'I move a trip or local expense',
        when: 'anyone later looks at the audit trail',
        then: 'it records what moved, from which report to which',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Your answer to Q20 lets a trip still needing review be moved by hand: moving doesn’t depend on whether the trip is ready. Moving local expenses, and refusing a move to or from a closed report, are Claude’s (ADR-0029).',
  },
  {
    id: 'US-RPT-06',
    title: 'See my reports and what each still needs',
    as: 'Alex, who travels for work',
    want: 'to see my reports, what is on each, when each closes and what still needs me, on Reports, Home and Needs you',
    soThat: 'I know what to finish without opening each one',
    feature: 'F-17',
    requirements: ['FR-EXP-05', 'FR-EXP-12'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I have open and closed reports',
        when: 'I open Reports',
        then: 'they are listed under Open and Closed, each with its trips and local expenses, its totals, when it closes or closed, and how many things need me',
        decided: ADR29,
        checks: [
          'api/reports › lists the person’s reports with their trips, totals per currency and what holds them',
          'db/reports.int › lists a member’s reports newest first',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given:
          'a report with amounts in more than one currency, or a local expense held as a possible duplicate',
        when: 'its totals are shown',
        then: 'there is one total per currency as spent, never converted, and the possible duplicate counts in none; with conversion on, a total in my reimbursement currency comes first (US-RPT-11)',
        decided: ADR29,
        checks: [
          'api/reports › lists the person’s reports with their trips, totals per currency and what holds them',
          'api/reports › shows each trip and local expense, and leaves a possible duplicate out of the totals',
        ],
      },
      {
        id: 'AC3',
        given: 'a report',
        when: 'I open it',
        then: 'each trip shows Ready or how many of its expenses need a look, and each local expense shows Ready, its status, or that it needs a reason',
        decided: ADR29,
        checks: [
          'api/reports › shows each trip and local expense, and leaves a possible duplicate out of the totals',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC4',
        given:
          'a report overdue or in its last week with something left, a local expense needing a reason, and a report ready to close',
        when: 'I open Needs you',
        then: 'the overdue or closing report comes first, and the report ready to close comes after the local expense',
        decided: ADR29,
        checks: [
          'api/reports › puts a report first in its last week with something left, and when overdue',
          'api/reports › asks for a justification, and says when a report is ready to close',
        ],
      },
      {
        id: 'AC5',
        given: 'a report still filling up, or one closed',
        when: 'I open Needs you',
        then: 'it isn’t there: what holds it open is listed already',
        decided: ADR29,
        checks: ['api/reports › leaves out a report still filling up, or closed'],
      },
      {
        id: 'AC6',
        given: 'I have open or closed reports',
        when: 'I open Home',
        then: 'Reports lists them, each with what it holds, when it closes and what it still needs',
        decided: { by: 'owner', source: 'Q15' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC7',
        given: 'reports in another organization',
        when: 'I ask for reports, or someone not signed in or in no organization does',
        then: 'none of theirs is ever shown, and without a signed-in member nothing is',
        decided: ADR29,
        checks: [
          'db/reports.int › tells the schedule which organizations have work due, and no more than their ids',
          'db/tenancy.int › puts a forced tenant policy on every table that holds org data',
          'api/reports › needs a signed-in member',
        ],
      },
      {
        id: 'AC8',
        given: 'another member of my organization has reports',
        when: 'I open Reports or Home',
        then: 'only my own are listed',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
    ],
    note: 'You asked to be told in the app, on Home and in Needs you (FR-EXP-05). Which reports Needs you shows, and in what order, is Claude’s reading of that (ADR-0029). Within an organization, any member can still open, close or reopen another member’s report by its link, as with receipts, expenses and trips (GAP-20, #50); harmless while every organization has one person.',
  },
  {
    id: 'US-RPT-07',
    title: 'Claim only part of a receipt',
    as: 'Alex, who travels for work',
    want: 'to claim less than a receipt shows, saying why, but never more',
    soThat: 'I can leave out a personal charge or split a receipt honestly, and never over-claim',
    feature: 'F-18',
    requirements: ['FR-EXP-10'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'a hotel bill with a personal minibar charge on it',
        when: 'I set the expense below the receipt’s total and give a reason',
        then: 'it claims the lower amount, with my reason',
        decided: Q6,
        checks: [],
      },
      {
        id: 'AC2',
        given: 'an expense with a receipt',
        when: 'I set it above the receipt’s total',
        then: 'it is refused: an expense never claims more than its receipt',
        decided: Q6,
        checks: [],
      },
      {
        id: 'AC3',
        given: 'one receipt split across several expenses',
        when: 'their amounts would add up to more than the receipt',
        then: 'it is refused',
        decided: Q6,
        checks: [],
      },
    ],
  },
  {
    id: 'US-RPT-08',
    title: 'Fix a difference before I submit',
    as: 'Alex, who travels for work',
    want: 'to be stopped from submitting a report while an expense on it differs from its receipt without a reason',
    soThat: 'I put it right before it reaches review, instead of getting the whole report back',
    feature: 'F-18',
    requirements: ['FR-GOV-13'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense on my closed report that differs from its receipt and gives no reason',
        when: 'I submit the report',
        then: 'it is refused, naming that expense',
        decided: Q6,
        checks: [],
      },
      {
        id: 'AC2',
        given: 'each expense that differs from its receipt gives its reason',
        when: 'I submit the report',
        then: 'the differences don’t stop it; review still checks each one',
        decided: Q6,
        checks: [],
      },
    ],
    note: 'The difference already shows as soon as an expense is edited (F-09); what is planned is refusing the submission, which arrives with approval (#24).',
  },
  {
    id: 'US-RPT-09',
    title: 'Reject an expense that doesn’t match its receipt',
    as: 'Jordan, an approver',
    want: 'an expense whose merchant, date, currency or amount doesn’t match its receipt to be rejected when its report is reviewed',
    soThat: 'only what the evidence supports is reimbursed',
    feature: 'F-18',
    requirements: ['FR-GOV-10'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense whose date or currency isn’t its receipt’s',
        when: 'its report is reviewed',
        then: 'the expense is rejected',
        decided: Q6,
        checks: [],
      },
      {
        id: 'AC2',
        given: 'an expense whose merchant is written differently from its receipt’s',
        when: 'its report is reviewed',
        then: 'it matches if it is the same business, and is rejected if it is another',
        decided: Q6,
        checks: [],
      },
      {
        id: 'AC3',
        given: 'an expense claiming more than its receipt, or less without a reason',
        when: 'its report is reviewed',
        then: 'it is rejected; one claiming less with a reason matches',
        decided: Q6,
        checks: [],
      },
      {
        id: 'AC4',
        given: 'an expense is rejected',
        when: 'anyone later looks at the audit trail',
        then: 'it records the rejection and why',
        decided: { by: 'blueprint', source: 'journeys §4.4' },
        checks: [],
      },
    ],
  },
  {
    id: 'US-RPT-10',
    title: 'Get my report back with each rejected expense and why',
    as: 'Alex, who travels for work',
    want: 'a report with a rejected expense to come back to me whole, each rejected expense marked with why, and listed in Needs you',
    soThat: 'I can put it right and submit it again without hunting for the problem',
    feature: 'F-18',
    requirements: ['FR-GOV-11', 'FR-GOV-12'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'one expense on a report I submitted is rejected',
        when: 'the review finishes',
        then: 'the whole report comes back to me, not only that expense',
        decided: OCT3,
        checks: [],
      },
      {
        id: 'AC2',
        given: 'my report comes back',
        when: 'I open it',
        then: 'it is open again, so I can correct it and submit it again',
        decided: { by: 'blueprint', source: 'journeys §4.5' },
        checks: [],
      },
      {
        id: 'AC3',
        given: 'a returned report',
        when: 'I open it',
        then: 'each rejected expense is marked, with why it was rejected',
        decided: OCT3,
        checks: [],
      },
      {
        id: 'AC4',
        given: 'a rejected expense',
        when: 'I open Needs you',
        then: 'it is listed with why it was rejected',
        decided: OCT3,
        checks: [],
      },
    ],
    note: 'The Needs you inbox exists (F-10); rejected expenses join it when approval does (#24).',
  },
  {
    id: 'US-RPT-11',
    title: 'See every report in the currency I’m reimbursed in',
    as: 'Alex, who travels for work, abroad too',
    want: 'every amount on a report converted to the currency I’m reimbursed in, beside what I spent',
    soThat: 'a report shows one total, the one I will get back',
    feature: 'F-49',
    requirements: ['FR-EXP-13', 'NFR-DAT-02', 'NFR-DAT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a report with amounts in more than one currency',
        when: 'I open it',
        then: 'each amount shows in my reimbursement currency beside the amount as spent, and the report totals in that one currency',
        decided: OCT4,
        checks: [
          'api/reimbursement › totals in one currency: amounts already in it as they are, the rest at their rate, and says what is left out',
          'api/reimbursement › shows each amount beside its conversion, with the rate, its date and its source',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'an expense in another currency',
        when: 'it is converted',
        then: 'it is at the reference rate for its purchase date',
        decided: { by: 'owner', source: 'Q25' },
        checks: [
          'domain/reference-rates › takes the purchase date’s own rate, against the euro as published',
          'db/conversions.int › converts at the purchase date’s reference rate, or the last one before it, and copies the rate on',
        ],
      },
      {
        id: 'AC3',
        given:
          'an expense already in my reimbursement currency, as when my card converted it at purchase',
        when: 'the report is totalled',
        then: 'it counts as it is, with no rate applied',
        decided: { by: 'owner', source: 'Q22' },
        checks: [
          'domain/reimbursement › counts an amount already in it as it is, with no rate',
          'api/reimbursement › totals in one currency: amounts already in it as they are, the rest at their rate, and says what is left out',
        ],
      },
      {
        id: 'AC4',
        given: 'I open Settings',
        when: 'I choose my reimbursement currency',
        then: 'my reports convert to it',
        decided: { by: 'owner', source: 'Q23' },
        checks: [
          'db/conversions.int › moves open and closed reports to a new choice, and leaves a submitted one as it was',
          'api/reimbursement › sets the person’s choice and hands the request to convert to the workflows at once',
        ],
      },
      {
        id: 'AC5',
        given: 'I have never chosen one',
        when: 'my reports convert',
        then: 'they use my organization’s home currency',
        decided: OCT4,
        checks: [
          'db/conversions.int › starts as the organization’s home currency, and is the person’s own once chosen',
          'api/reimbursement › is the organization’s home currency until the person chooses, with every currency to choose from',
        ],
      },
      {
        id: 'AC6',
        given: 'an amount was converted',
        when: 'anyone looks at it later, after rates have moved',
        then: 'it keeps the rate it was converted at, that rate’s date and its source, unchanged',
        decided: { by: 'blueprint', source: 'arch §6.7' },
        checks: [
          'db/conversions.int › keeps the rate it converted at when rates move, and applies it again to an edited amount',
          'db/conversions.int › refuses a converted amount without its rate, the rate’s date or its source',
        ],
      },
      {
        id: 'AC7',
        given: 'a purchase on a weekend or a holiday, when the ECB publishes no rate',
        when: 'it is converted',
        then: 'the last rate published before it applies, at most 10 days back, and the rate’s date recorded is the day it was published',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'domain/reference-rates › uses the last rate published before a weekend, and records that rate’s own date',
          'domain/reference-rates › has no rate past the lookback, or for a day both currencies weren’t published',
        ],
        rules: ['R-RATE-LOOKBACK'],
      },
      {
        id: 'AC8',
        given: 'an amount in one currency reimbursed in another, neither of them the euro',
        when: 'it is converted',
        then: 'the rate is crossed through the euro, kept to 10 significant digits, and that stored rate alone gives the converted amount, within a cent of the exact cross',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'domain/reference-rates › crosses two currencies through the euro, to ten significant digits',
          'domain/reference-rates › converts up to 100,000.00 within a cent of the exact cross rate',
        ],
      },
      {
        id: 'AC9',
        given: 'a report I open, or one on Home or in Needs you',
        when: 'it is totalled',
        then: 'the total I see first is in my reimbursement currency, with what was spent beside it, and the report lists each rate used with its date and source',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'api/reimbursement › totals in the reimbursement currency on Home and in Needs you too',
          'api/reimbursement › shows each amount beside its conversion, with the rate, its date and its source',
        ],
      },
      {
        id: 'AC10',
        given: 'currency conversion is switched off',
        when: 'I open my reports, Home or Needs you',
        then: 'they read exactly as before: one total per currency, nothing converted',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/reimbursement › reads exactly as before while the feature is off',
          'db/conversions.int › does nothing while the feature is off',
        ],
      },
    ],
    note: 'Replacing the reference rate with the amount on a card statement was not part of your answer to Q25, so it isn’t planned. AC7 to AC9 are Claude’s (ADR-0034), yours to overturn.',
  },
  {
    id: 'US-RPT-12',
    title: 'Keep our own expense categories and types',
    as: 'Sam, a finance admin',
    want: 'to define our organization’s own categories and types, as two lists that can each nest, and which types each category allows',
    soThat: 'spend is coded the way we book it, and people pick only types that fit',
    feature: 'F-43',
    requirements: ['FR-EXP-11'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'my organization',
        when: 'its categories and types are set up',
        then: 'they are two separate lists, and each can nest',
        decided: Q7,
        checks: [],
      },
      {
        id: 'AC2',
        given: 'a category',
        when: 'I edit it',
        then: 'I choose which types it allows',
        decided: Q7,
        checks: [],
      },
      {
        id: 'AC3',
        given: 'a type',
        when: 'I allow it in several categories',
        then: 'it is offered under each of them',
        decided: { by: 'claude' },
        checks: [],
      },
      {
        id: 'AC4',
        given: 'a category and a type',
        when: 'they are set up',
        then: 'the general ledger and tax codes go on the category, and the rules, such as attendees, a mileage rate or a receipt being needed, go on the type',
        decided: { by: 'claude' },
        checks: [],
      },
      {
        id: 'AC5',
        given: 'a new organization',
        when: 'it starts',
        then: 'it has a ready-made set that owners and finance admins rename, add to or retire; one in use is retired, never deleted, so old claims keep it',
        decided: { by: 'claude' },
        checks: [],
      },
    ],
    note: 'Your answer to Q7 chose two trees, the category narrowing the types. AC3 to AC5 are Claude’s assumptions (FR-EXP-11, #51), yours to overturn.',
  },
  {
    id: 'US-RPT-13',
    title: 'Give each expense a category and a type',
    as: 'Alex, who travels for work',
    want: 'to give each expense a category and a type, choosing the type from those its category allows',
    soThat: 'every expense is coded correctly without my knowing finance’s codes',
    feature: 'F-43',
    requirements: ['FR-EXP-11'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'any expense',
        when: 'it is filed or edited',
        then: 'it carries a category and a type',
        decided: OCT3,
        checks: [],
      },
      {
        id: 'AC2',
        given: 'I have chosen a category for an expense',
        when: 'I pick its type',
        then: 'only the types that category allows are offered',
        decided: Q7,
        checks: [],
      },
    ],
  },
  {
    id: 'US-RPT-14',
    title: 'Know when an amount isn’t converted yet, or can’t be',
    as: 'Alex, who travels for work, abroad too',
    want: 'to see plainly which amounts are still being converted, and which can’t be',
    soThat: 'I never take a partial total for the one I will get back',
    feature: 'F-49',
    requirements: ['FR-EXP-13'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an amount on a report whose rate isn’t recorded yet',
        when: 'I open the report',
        then: 'it says it is converting, the total says how many amounts it leaves out, and the rate is fetched in the background, never while I wait',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'domain/reimbursement › is converting while no recorded rate applies: none yet, or another currency, date or target',
          'api/reimbursement › totals in one currency: amounts already in it as they are, the rest at their rate, and says what is left out',
          'workflows/conversions › converts what it can, fetches the rates still needed, then converts with them',
        ],
      },
      {
        id: 'AC2',
        given: 'an amount in a currency the ECB doesn’t publish, such as dirhams',
        when: 'the report is converted',
        then: 'it stays as spent, marked not converted, and is listed apart from the total',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › records a currency the source has no rate for, or a day with none in reach, as unconverted',
          'domain/reimbursement › stays as spent, said plainly, when the source has no rate for it',
          'api/reimbursement › shows each amount beside its conversion, with the rate, its date and its source',
        ],
      },
      {
        id: 'AC3',
        given: 'a trip joins a report, or an amount on one changes',
        when: 'the change is saved',
        then: 'conversion is asked for at once, and an hourly sweep tries again whatever is still converting, such as after the ECB was down',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › asks when something on a report changes, and the sweep finds the organization until it is converted',
          'workflows/conversions › takes no series as no rate, tries a busy source again, and gives up on a bad request',
          'workflows/conversions › carries on past an organization that fails, then fails the sweep so it is retried',
        ],
        rules: ['R-CONVERSION-SWEEP'],
      },
      {
        id: 'AC4',
        given: 'a purchase dated today',
        when: 'it would be converted',
        then: 'it waits until tomorrow, when today’s rate is published, rather than taking yesterday’s',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'domain/reference-rates › waits for the day after a purchase, when that day’s rate is published',
          'db/conversions.int › waits for the day after a purchase before asking for its rate',
        ],
      },
      {
        id: 'AC5',
        given: 'the owner switches currency conversion on',
        when: 'it is switched',
        then: 'what is already on reports is converted without waiting for a change',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › announces a feature switched on or off',
          'workflows/conversions › run when asked, or when the owner switches the feature on, one at a time per organization',
        ],
      },
    ],
    note: 'All Claude’s (ADR-0034), yours to overturn. The ECB publishes about 30 currencies; dirhams, dinars, riyals and the pesos of Chile, Colombia and Argentina are among those it doesn’t.',
  },
  {
    id: 'US-RPT-15',
    title: 'Choose the currency I’m reimbursed in',
    as: 'Alex, who travels for work, abroad too',
    want: 'to choose in Settings the currency I’m reimbursed in',
    soThat: 'my reports total in the money I am actually paid back in',
    feature: 'F-49',
    requirements: ['FR-EXP-13'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I have never chosen one',
        when: 'I open Settings › Currency',
        then: 'it shows my organization’s home currency, and every currency I could choose, marking those the ECB has no rate for',
        decided: { by: 'owner', source: 'Q23' },
        checks: [
          'api/reimbursement › is the organization’s home currency until the person chooses, with every currency to choose from',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'I choose another currency',
        when: 'I save it',
        then: 'my open and closed reports move to it and convert again, and a report opened from then on opens in it',
        decided: { by: 'owner', source: 'Q23' },
        checks: [
          'db/conversions.int › moves open and closed reports to a new choice, and leaves a submitted one as it was',
          'db/conversions.int › opens a new report in the person’s currency while the feature is on, and the home currency while off',
          'api/reimbursement › sets the person’s choice and hands the request to convert to the workflows at once',
        ],
      },
      {
        id: 'AC3',
        given: 'a report already submitted',
        when: 'I choose another currency',
        then: 'it keeps the currency it was submitted in',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › moves open and closed reports to a new choice, and leaves a submitted one as it was',
        ],
      },
      {
        id: 'AC4',
        given: 'I chose a currency',
        when: 'I choose my organization’s again',
        then: 'my reports follow its home currency, whatever it becomes',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › starts as the organization’s home currency, and is the person’s own once chosen',
          'api/reimbursement › sets the person’s choice and hands the request to convert to the workflows at once',
        ],
      },
      {
        id: 'AC5',
        given: 'any choice of currency',
        when: 'it is saved',
        then: 'it is in the audit trail, with what it was before',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/conversions.int › starts as the organization’s home currency, and is the person’s own once chosen',
        ],
      },
      {
        id: 'AC6',
        given: 'currency conversion is switched off',
        when: 'I look in Settings',
        then: 'there is no Currency page, and asking for my currency answers that the feature is off',
        decided: { by: 'owner', source: 'Q5' },
        checks: ['api/reimbursement › looks absent while the feature is off'],
      },
      {
        id: 'AC7',
        given: 'a currency the app doesn’t support',
        when: 'it is asked for',
        then: 'it is refused, and nothing changes',
        decided: { by: 'claude' },
        checks: ['api/reimbursement › refuses a currency the app doesn’t support, and a stranger'],
      },
    ],
    note: 'Your answer to Q23: your preferred currency, set in the app. Keeping a submitted report’s currency, and following the organization’s home currency until you choose, are Claude’s (ADR-0034).',
  },
];
