import type { Story } from '../model.ts';

const OCT3 = { by: 'owner', source: 'owner 2026-10-03' } as const;
const OCT4 = { by: 'owner', source: 'owner 2026-10-04' } as const;
const Q6 = { by: 'owner', source: 'Q6' } as const;
const Q7 = { by: 'owner', source: 'Q7' } as const;
const ADR29 = { by: 'claude', source: 'ADR-0029' } as const;

/**
 * Expense reports, local expenses, and what comes with submitting and approving them
 * (FR-EXP-05, FR-EXP-10 to FR-EXP-14, FR-GOV-10 to FR-GOV-13; ADR-0029).
 */
export const REPORT_STORIES: readonly Story[] = [
  {
    id: 'US-RPT-01',
    title: 'My trips go on a report once I’m back',
    as: 'Alex, who travels for work',
    want: 'each trip to go on an expense report by itself, a day after I’m back',
    soThat: 'every trip is claimed without my having to remember it',
    feature: 'F-17',
    requirements: ['FR-EXP-05'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a trip with expenses on it, and no report of mine open',
        when: '24 hours have passed after its return date',
        then: 'it goes on a new report, opened for it',
        decided: OCT4,
        checks: [
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
        rules: ['R-REPORT-JOIN'],
      },
      {
        id: 'AC2',
        given: 'a trip’s return date, in an organization that keeps no time zone of its own',
        when: 'the 24 hours are counted',
        then: 'they run from the end of that day where it ends last (UTC−12), so the trip joins at noon UTC two days after its return date, and never earlier for anyone',
        decided: ADR29,
        checks: [
          'domain/reports › waits until 24 hours after its day has ended everywhere: noon UTC two days on',
          'domain/reports › is never early, even where the day ends last (UTC−12)',
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
        rules: ['R-REPORT-JOIN'],
      },
      {
        id: 'AC3',
        given: 'a report of mine already open',
        when: 'a later trip’s time comes',
        then: 'it joins that report rather than a new one',
        decided: OCT4,
        checks: ['db/reports.int › puts later trips and local expenses on the report already open'],
      },
      {
        id: 'AC4',
        given: 'a trip with no expenses on it',
        when: 'its time comes',
        then: 'it joins no report until something is on it',
        decided: ADR29,
        checks: [
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
      },
      {
        id: 'AC5',
        given: 'a trip on a report, including one with expenses still needing a look',
        when: 'I look at what the report holds',
        then: 'the trip’s expenses are on it through the trip, and never on the report by themselves',
        decided: ADR29,
        checks: [
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
          'db/reports.int › closes with what is ready and moves what still needs review to the next report',
          'db/reports.int › holds only its member’s trips and expenses, and a closed time only when closed',
        ],
      },
      {
        id: 'AC6',
        given: 'it is 7 minutes past an hour',
        when: 'the schedule runs',
        then: 'it does each organization’s due work as of that one moment, joining what is due and closing reports whose day 28 has come; one organization failing doesn’t hold up the rest, the run is retried, and nothing joins twice',
        decided: ADR29,
        checks: [
          'workflows/reports › does each organization’s due work at one moment, and logs counts only',
          'workflows/reports › carries on past an organization that fails, then fails the run so it is retried',
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
        rules: ['R-REPORT-SCHEDULE'],
      },
      {
        id: 'AC7',
        given: 'reports in many organizations',
        when: 'the schedule asks what is due',
        then: 'it learns only which organizations have work, by id, and does each one’s work inside that organization; a report holds only its own member’s trips and expenses',
        decided: ADR29,
        checks: [
          'db/reports.int › tells the schedule which organizations have work due, and no more than their ids',
          'db/reports.int › holds only its member’s trips and expenses, and a closed time only when closed',
        ],
      },
      {
        id: 'AC8',
        given: 'a report opens and a trip joins it',
        when: 'anyone later looks at the audit trail',
        then: 'it records the report opening and the trip being added',
        decided: ADR29,
        checks: [
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
      },
    ],
    note: 'Counting from where the return day ends last means a trip joins between 24 and 50 hours after its return day ends where the traveler is (about 31 hours in US Central time), and within the hour after that, since the schedule runs hourly. Your organization’s time zone (#63) could tighten it. That a trip with no expenses waits, and that its expenses go with it, are Claude’s assumptions (FR-EXP-05), yours to overturn.',
  },
  {
    id: 'US-RPT-02',
    title: 'Claim spend on no trip, saying why it was for business',
    as: 'Riley, a solo professional who self-attests',
    want: 'an expense on no trip to go on my report as a local expense, once I have said why it was for business',
    soThat:
      'everyday business spend is reimbursed too, with the reason an approver or auditor will ask for',
    feature: 'F-50',
    requirements: ['FR-EXP-14', 'FR-EXP-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense dated on a day no trip of mine covers',
        when: 'it is filed',
        then: 'it is a local expense, on no trip, and needs a justification',
        decided: { by: 'owner', source: 'Q21' },
        checks: [
          'db/reports.int › puts later trips and local expenses on the report already open',
          'db/reports.int › refuses a justification on a trip’s expense, or one too long',
          'domain/reports › is a local expense needing review, or with no justification',
        ],
      },
      {
        id: 'AC2',
        given: 'a local expense',
        when: '24 hours have passed after its date',
        then: 'it joins my open report as a local expense; one with no date yet joins none',
        decided: ADR29,
        checks: [
          'db/reports.int › puts later trips and local expenses on the report already open',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
        rules: ['R-REPORT-JOIN'],
      },
      {
        id: 'AC3',
        given: 'a local expense',
        when: 'I open it',
        then: 'its section Why it was for business asks for a reason, and Save the reason keeps what I write, trimmed',
        decided: { by: 'owner', source: 'Q21' },
        checks: [
          'api/reports › refuses to close while anything needs a justification, then closes and reopens',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC4',
        given: 'a reason',
        when: 'I save it',
        then: 'it can be up to 500 characters; a longer one is refused, and a blank one counts as no reason',
        decided: ADR29,
        checks: [
          'domain/reports › keeps a justification trimmed, blank as none, and refuses one too long',
          'db/reports.int › refuses a justification on a trip’s expense, or one too long',
          'api/reports › refuses to reopen an open report, and a justification on a trip’s expense or too long',
        ],
        rules: ['R-JUSTIFICATION-MAX'],
      },
      {
        id: 'AC5',
        given: 'an expense on a trip',
        when: 'I try to give it a justification',
        then: 'it is refused: the trip says why it was spent',
        decided: ADR29,
        checks: [
          'db/reports.int › refuses a justification on a trip’s expense, or one too long',
          'api/reports › refuses to reopen an open report, and a justification on a trip’s expense or too long',
        ],
      },
      {
        id: 'AC6',
        given: 'a local expense on my report with no reason',
        when: 'I try to close the report',
        then: 'it is refused, naming that expense, until I give one',
        decided: ADR29,
        checks: [
          'domain/reports › is a local expense needing review, or with no justification',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
          'api/reports › refuses to close while anything needs a justification, then closes and reopens',
        ],
      },
      {
        id: 'AC7',
        given: 'a local expense that is Ready and has no reason, even before it joins a report',
        when: 'I open Needs you',
        then: 'it is listed as Local, asking me to add a reason',
        decided: ADR29,
        checks: [
          'api/reports › asks for a justification, and says when a report is ready to close',
        ],
      },
      {
        id: 'AC8',
        given: 'a local expense still being read, or one submitted',
        when: 'I try to give or change its reason',
        then: 'it is refused',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC9',
        given: 'I give or change a reason',
        when: 'anyone later looks at the audit trail',
        then: 'it records the reason before and after',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Your answer to Q21 makes these expenses local and needing a justification. That one without a reason holds its report open is Claude’s assumption (FR-EXP-12), though FR-EXP-14 states it as yours; please confirm. That a local expense joins 24 hours after its own date, and that a report may hold only local expenses in a month with no travel, are Claude’s assumptions too (FR-EXP-05). Whether a trip covers an expense goes by the expense’s date (ADR-0023).',
  },
  {
    id: 'US-RPT-03',
    title: 'Close my report when it is done, and reopen it',
    as: 'Alex, who travels for work',
    want: 'to close a report once nothing on it needs me, and to reopen it if I need to, until I submit it',
    soThat: 'what I claim is settled before I submit it, and a late change is never stranded',
    feature: 'F-17',
    requirements: ['FR-EXP-12'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'an open report where nothing needs a look and every local expense has a reason',
        when: 'I press Close the report',
        then: 'it closes, and is not submitted: submitting is mine to do',
        decided: OCT4,
        checks: [
          'domain/lifecycle/report › closes only with nothing left to review, and reopens until submitted',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
          'api/reports › refuses to close while anything needs a justification, then closes and reopens',
        ],
      },
      {
        id: 'AC2',
        given: 'a trip on my report with an expense that needs a look',
        when: 'I try to close the report',
        then: 'it is refused, naming what still needs me',
        decided: OCT4,
        checks: [
          'domain/lifecycle/report › closes only with nothing left to review, and reopens until submitted',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
      },
      {
        id: 'AC3',
        given: 'something on my report still being read, or held as a possible duplicate',
        when: 'I try to close the report',
        then: 'it is refused, as for something needing a look',
        decided: ADR29,
        checks: [
          'domain/reports › is a trip with an expense being read or needing review',
          'api/reports › shows each trip and local expense, and leaves a possible duplicate out of the totals',
        ],
      },
      {
        id: 'AC4',
        given: 'a report that is still open',
        when: 'anyone tries to submit it',
        then: 'it is refused: only a closed report can be submitted',
        decided: OCT4,
        checks: ['domain/lifecycle/report › from %s rejects %j with %s'],
      },
      {
        id: 'AC5',
        given: 'a closed report',
        when: 'I press Reopen',
        then: 'it is open again; reopening one already open, or one submitted, is refused, since a submitted report is locked',
        decided: OCT4,
        checks: [
          'domain/lifecycle/report › closes only with nothing left to review, and reopens until submitted',
          'api/reports › refuses to close while anything needs a justification, then closes and reopens',
          'api/reports › refuses to reopen an open report, and a justification on a trip’s expense or too long',
        ],
      },
      {
        id: 'AC6',
        given: 'I reopen a closed report',
        when: 'its new closing day is set',
        then: 'it keeps its day 28, or gets 7 days from reopening if that is later',
        decided: ADR29,
        checks: [
          'domain/reports › gives a reopened report a week, or keeps its own day 28 if later',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
        rules: ['R-REOPEN-GRACE'],
      },
      {
        id: 'AC7',
        given: 'a closed report',
        when: 'an expense on it is edited, or a trip on it is deleted',
        then: 'it reopens by itself',
        decided: ADR29,
        checks: [
          'db/reports.int › reopens a closed report when something on it changes',
          'db/trips.int › refuses while a submitted expense rests on it, and reopens a closed report it was on',
        ],
      },
      {
        id: 'AC8',
        given: 'a closed report',
        when: 'a receipt on it is read again, a trip on it is edited, an expense moves onto or off it, a reason on it changes, or a duplicate on it is deleted or merged',
        then: 'it reopens by itself too, with the audit trail saying why; a submitted report never reopens this way',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC9',
        given: 'my report has been closed and reopened',
        when: 'anyone looks at the audit trail',
        then: 'it shows each step in order: opened, each trip and local expense added, closed, reopened',
        decided: ADR29,
        checks: [
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
      },
    ],
    note: 'Since PR #60, with approval on, a closed report is submitted (#24, US-RPT-19); the report’s lifecycle refuses it from any state but closed (AC4). That an expense still being read or a possible duplicate holds a report open, the 7 days a reopened report gets, and reopening on any change are Claude’s (ADR-0029), yours to overturn.',
  },
  {
    id: 'US-RPT-04',
    title: 'My report closes itself on day 28',
    as: 'Alex, who travels for work',
    want: 'a report to close itself 28 days after it opens, with whatever is ready, and to be warned before then if something still needs me',
    soThat:
      'finished trips are reimbursed on time, and one unfinished receipt never holds up the rest',
    feature: 'F-17',
    requirements: ['FR-EXP-12'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a report that has just opened',
        when: 'I look at when it closes',
        then: 'it is 28 days from opening',
        decided: OCT4,
        checks: [
          'domain/reports › closes itself 28 days after it opens, and warns in its last week',
          'db/reports.int › puts a trip on a new report 24 hours after its return day, not before',
        ],
        rules: ['R-REPORT-WINDOW'],
      },
      {
        id: 'AC2',
        given:
          'day 28 has come, with one trip on my report still needing a look and the rest ready',
        when: 'the schedule reaches it',
        then: 'the report closes with what is ready, without being submitted, and the trip still needing a look moves to the next report, opened for it if need be, with its own 28 days',
        decided: { by: 'owner', source: 'Q20' },
        checks: [
          'domain/reports › closes with what is ready and moves the rest on',
          'db/reports.int › closes with what is ready and moves what still needs review to the next report',
        ],
        rules: ['R-REPORT-WINDOW'],
      },
      {
        id: 'AC3',
        given: 'day 28 has come and nothing on my report is ready',
        when: 'the schedule reaches it',
        then: 'it stays open, overdue, rather than moving everything on, and Needs you puts it first',
        decided: ADR29,
        checks: [
          'domain/reports › waits, overdue, when nothing is ready, and drops a report holding nothing',
          'db/reports.int › leaves a report with nothing ready open, overdue, and drops one holding nothing',
          'api/reports › puts a report first in its last week with something left, and when overdue',
        ],
      },
      {
        id: 'AC4',
        given: 'an open report left holding nothing, as when its only expense moves off its trip',
        when: 'the schedule runs',
        then: 'the report is dropped, whatever its day, and the empty trip comes off it',
        decided: ADR29,
        checks: [
          'domain/reports › waits, overdue, when nothing is ready, and drops a report holding nothing',
          'db/reports.int › leaves a report with nothing ready open, overdue, and drops one holding nothing',
        ],
      },
      {
        id: 'AC5',
        given: 'day 28 is near and something on my report still needs me',
        when: 'I open Needs you',
        then: 'the report comes first, warning that reimbursement will be delayed unless I close it by its date',
        decided: OCT4,
        checks: [
          'api/reports › puts a report first in its last week with something left, and when overdue',
        ],
      },
      {
        id: 'AC6',
        given: 'an open report with something still needing me',
        when: 'it reaches its last 7 days',
        then: 'the warning starts, and stays while the report is open',
        decided: ADR29,
        checks: [
          'domain/reports › closes itself 28 days after it opens, and warns in its last week',
          'api/reports › puts a report first in its last week with something left, and when overdue',
        ],
        rules: ['R-REPORT-WARNING'],
      },
      {
        id: 'AC7',
        given: 'day 28 closes a report, or a report is dropped',
        when: 'anyone later looks at the audit trail',
        then: 'it records the close by day 28 with what moved, or the drop',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
    ],
    note: 'You asked for the warning as day 28 nears; that it starts 7 days before is Claude’s. Waiting, overdue, when nothing is ready, and dropping an empty report, are Claude’s too (ADR-0029), yours to overturn.',
  },
  {
    id: 'US-RPT-05',
    title: 'Move a trip to another report',
    as: 'Alex, who travels for work',
    want: 'to move a trip, or a local expense, to another open report or a new one',
    soThat:
      'a trip still needing a look doesn’t hold up the others, and each report holds what I want claimed together',
    feature: 'F-17',
    requirements: ['FR-EXP-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a trip on my open report',
        when: 'I choose Move to another report and pick another open report, or A new report',
        then: 'the trip moves there, with its expenses',
        decided: OCT4,
        checks: [
          'db/reports.int › moves a trip to a new report, dropping the one it leaves empty',
          'api/reports › moves a trip or a local expense to a new report, and refuses a closed one',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'a local expense on my open report',
        when: 'I move it',
        then: 'it moves on its own; an expense on a trip can’t, since it goes with its trip',
        decided: ADR29,
        checks: [
          'db/reports.int › moves a local expense, and refuses a closed report, a trip’s expense or another member’s',
          'api/reports › moves a trip or a local expense to a new report, and refuses a closed one',
        ],
      },
      {
        id: 'AC3',
        given: 'the report it is on, or the one I pick, is closed',
        when: 'I try to move it',
        then: 'it is refused: reopen it first',
        decided: ADR29,
        checks: [
          'db/reports.int › moves a local expense, and refuses a closed report, a trip’s expense or another member’s',
          'api/reports › moves a trip or a local expense to a new report, and refuses a closed one',
        ],
      },
      {
        id: 'AC4',
        given: 'a move that leaves a report holding nothing',
        when: 'it is done',
        then: 'that report is dropped',
        decided: ADR29,
        checks: [
          'db/reports.int › moves a trip to a new report, dropping the one it leaves empty',
          'api/reports › moves a trip or a local expense to a new report, and refuses a closed one',
        ],
      },
      {
        id: 'AC5',
        given: 'a trip or expense of one member, and a report of another',
        when: 'anyone tries to put one on the other',
        then: 'it is refused: a report holds only its own member’s trips and expenses',
        decided: ADR29,
        checks: [
          'db/reports.int › moves a local expense, and refuses a closed report, a trip’s expense or another member’s',
          'db/reports.int › holds only its member’s trips and expenses, and a closed time only when closed',
        ],
      },
      {
        id: 'AC6',
        given: 'I move a trip or local expense',
        when: 'anyone later looks at the audit trail',
        then: 'it records what moved, from which report to which',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Your answer to Q20 lets a trip still needing review be moved by hand: moving doesn’t depend on whether the trip is ready. Moving local expenses, and refusing a move to or from a closed report, are Claude’s (ADR-0029).',
  },
  {
    id: 'US-RPT-06',
    title: 'See my reports and what each still needs',
    as: 'Alex, who travels for work',
    want: 'to see my reports, what is on each, when each closes and what still needs me, on Reports, Home and Needs you',
    soThat: 'I know what to finish without opening each one',
    feature: 'F-17',
    requirements: ['FR-EXP-05', 'FR-EXP-12'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'I have open and closed reports',
        when: 'I open Reports',
        then: 'they are listed under Open and Closed, each with its trips and local expenses, its totals, when it closes or closed, and how many things need me',
        decided: ADR29,
        checks: [
          'api/reports › lists the person’s reports with their trips, totals per currency and what holds them',
          'db/reports.int › lists a member’s reports newest first',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given:
          'a report with amounts in more than one currency, or a local expense held as a possible duplicate',
        when: 'its totals are shown',
        then: 'there is one total per currency as spent, never converted, and the possible duplicate counts in none; with conversion on, a total in my reimbursement currency comes first (US-RPT-11)',
        decided: ADR29,
        checks: [
          'api/reports › lists the person’s reports with their trips, totals per currency and what holds them',
          'api/reports › shows each trip and local expense, and leaves a possible duplicate out of the totals',
        ],
      },
      {
        id: 'AC3',
        given: 'a report',
        when: 'I open it',
        then: 'each trip shows Ready or how many of its expenses need a look, and each local expense shows Ready, its status, or that it needs a reason',
        decided: ADR29,
        checks: [
          'api/reports › shows each trip and local expense, and leaves a possible duplicate out of the totals',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC4',
        given:
          'a report overdue or in its last week with something left, a local expense needing a reason, and a report ready to close',
        when: 'I open Needs you',
        then: 'the overdue or closing report comes first, and the report ready to close comes after the local expense',
        decided: ADR29,
        checks: [
          'api/reports › puts a report first in its last week with something left, and when overdue',
          'api/reports › asks for a justification, and says when a report is ready to close',
        ],
      },
      {
        id: 'AC5',
        given: 'a report still filling up, or one closed',
        when: 'I open Needs you',
        then: 'it isn’t there: what holds it open is listed already',
        decided: ADR29,
        checks: ['api/reports › leaves out a report still filling up, or closed'],
      },
      {
        id: 'AC6',
        given: 'I have open or closed reports',
        when: 'I open Home',
        then: 'Reports lists them, each with what it holds, when it closes and what it still needs',
        decided: { by: 'owner', source: 'Q15' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC7',
        given: 'reports in another organization',
        when: 'I ask for reports, or someone not signed in or in no organization does',
        then: 'none of theirs is ever shown, and without a signed-in member nothing is',
        decided: ADR29,
        checks: [
          'db/reports.int › tells the schedule which organizations have work due, and no more than their ids',
          'db/tenancy.int › puts a forced tenant policy on every table that holds org data',
          'api/reports › needs a signed-in member',
        ],
      },
      {
        id: 'AC8',
        given: 'another member of my organization has reports',
        when: 'I open Reports or Home',
        then: 'only my own are listed',
        decided: ADR29,
        checks: [],
        untested: 66,
      },
    ],
    note: 'You asked to be told in the app, on Home and in Needs you (FR-EXP-05). Which reports Needs you shows, and in what order, is Claude’s reading of that (ADR-0029). Within an organization, a member opens, closes and reopens only their own reports, as with receipts, expenses and trips (US-SEC-14).',
  },
  {
    id: 'US-RPT-07',
    title: 'Claim only part of a receipt',
    as: 'Alex, who travels for work',
    want: 'to claim less than a receipt shows, saying why, but never more',
    soThat: 'I can leave out a personal charge or split a receipt honestly, and never over-claim',
    feature: 'F-18',
    requirements: ['FR-EXP-10'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a hotel bill with a personal minibar charge on it',
        when: 'I set the expense below the receipt’s total and give a reason',
        then: 'it claims the lower amount, with my reason, up to 500 characters, and its report can be submitted',
        decided: Q6,
        checks: [
          'domain/receipt-check › takes a lower claim with the person’s reason, or with lines left out, each with its own',
          'db/approval.int › keeps the reason for claiming less, reopening a closed report, and refuses one too long',
          'api/approval.int › submits once the lower claim says why, keeping its category’s name as it went in',
        ],
        rules: ['R-APPROVAL-NOTE-MAX'],
      },
      {
        id: 'AC2',
        given: 'an expense with a receipt',
        when: 'I set it above the receipt’s total',
        then: 'it is refused: an expense never claims more than its receipt',
        decided: Q6,
        checks: [
          'api/approval.int › refuses an amount above the receipt, and a submission while a lower one says nothing of why',
          'domain/receipt-check › never takes more than the receipt, whatever the reason',
        ],
      },
      {
        id: 'AC3',
        given: 'one receipt split across several parts',
        when: 'their amounts would add up to more than the receipt',
        then: 'it is refused: a split is one expense with one receipt, its parts always add up to its claim, and its claim is never more than the receipt',
        decided: { by: 'owner', source: 'Q35' },
        checks: [
          'db/itemized.int › splits by amount, refusing parts that don’t add up to the claim, and refuses an exclusion while so split',
          'domain/receipt-check › never takes more than the receipt, whatever the reason',
        ],
      },
      {
        id: 'AC4',
        given: 'lines of the receipt left out of the claim, each with its reason',
        when: 'the expense is checked against its receipt',
        then: 'the lines are its reason for claiming less, and nothing more is asked',
        decided: { by: 'owner', source: 'Q38' },
        checks: [
          'domain/receipt-check › takes a lower claim with the person’s reason, or with lines left out, each with its own',
        ],
      },
      {
        id: 'AC5',
        given: 'approval is switched off for my organization',
        when: 'I edit an expense’s amount',
        then: 'it is saved as before, and nothing asks why it claims less',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/approval.int › answers 404 feature_off on every route, and leaves reports, export and Needs you as they were',
        ],
      },
    ],
    note: 'Your answer to Q35 made a split one expense with one receipt, so “expenses split from one receipt” are its parts, which always add up to its claim. Built in PR #60 behind Approval (#24, ADR-0043).',
  },
  {
    id: 'US-RPT-08',
    title: 'Fix a difference before I submit',
    as: 'Alex, who travels for work',
    want: 'to be stopped from submitting a report while an expense on it differs from its receipt without a reason',
    soThat: 'I put it right before it reaches review, instead of getting the whole report back',
    feature: 'F-18',
    requirements: ['FR-GOV-13'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense on my closed report that differs from its receipt and gives no reason',
        when: 'I submit the report',
        then: 'it is refused, naming that expense and why',
        decided: Q6,
        checks: [
          'db/approval.int › refuses one not closed, another member’s, one differing from its receipt without a reason, and one no one else can approve',
          'api/approval.int › refuses an amount above the receipt, and a submission while a lower one says nothing of why',
        ],
      },
      {
        id: 'AC2',
        given: 'each expense that differs from its receipt gives its reason',
        when: 'I submit the report',
        then: 'the differences don’t stop it; review still checks each one',
        decided: Q6,
        checks: [
          'db/approval.int › refuses one not closed, another member’s, one differing from its receipt without a reason, and one no one else can approve',
          'api/approval.int › submits once the lower claim says why, keeping its category’s name as it went in',
        ],
      },
      {
        id: 'AC3',
        given: 'I edit an expense so it differs from its receipt',
        when: 'it is saved',
        then: 'the expense shows at once how it holds up against its receipt, and asks why it claims less',
        decided: Q6,
        checks: [
          'api/approval.int › refuses an amount above the receipt, and a submission while a lower one says nothing of why',
        ],
      },
    ],
    note: 'The difference showed as soon as an expense was edited before (F-09); since PR #60, with approval on, the expense also says whether it holds up, and asks why it claims less (#24).',
  },
  {
    id: 'US-RPT-09',
    title: 'Reject an expense that doesn’t match its receipt',
    as: 'Jordan, an approver',
    want: 'an expense whose merchant, date, currency or amount doesn’t match its receipt to be rejected when its report is reviewed',
    soThat: 'only what the evidence supports is reimbursed',
    feature: 'F-18',
    requirements: ['FR-GOV-10'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an expense whose date or currency isn’t its receipt’s',
        when: 'its report is reviewed',
        then: 'the expense is rejected on its own, with why, so the report can only be returned',
        decided: Q6,
        checks: [
          'domain/receipt-check › never takes another merchant, date or currency, whatever the reason',
          'db/approval.int › returns the whole report for one rejected expense, each rejection kept with why, and opens it again',
        ],
      },
      {
        id: 'AC2',
        given: 'an expense whose merchant is written differently from its receipt’s',
        when: 'its report is reviewed',
        then: 'it matches if it is the same business, and is rejected if it is another',
        decided: Q6,
        checks: [
          'extraction/proof › finds nothing when the expense matches its receipt, allowing loose merchant names',
          'extraction/proof › names each field that differs',
        ],
      },
      {
        id: 'AC3',
        given: 'an expense claiming more than its receipt, or less without a reason',
        when: 'its report is reviewed',
        then: 'it is rejected; one claiming less with a reason matches',
        decided: Q6,
        checks: [
          'domain/receipt-check › holds a lower claim without a reason, and says a reason would settle it',
          'domain/receipt-check › never takes more than the receipt, whatever the reason',
          'domain/receipt-check › takes a lower claim with the person’s reason, or with lines left out, each with its own',
        ],
      },
      {
        id: 'AC4',
        given: 'an expense is rejected',
        when: 'anyone later looks at the audit trail',
        then: 'it records the rejection and why',
        decided: { by: 'blueprint', source: 'journeys §4.4' },
        checks: [
          'db/approval.int › returns the whole report for one rejected expense, each rejection kept with why, and opens it again',
        ],
      },
      {
        id: 'AC5',
        given: 'a drive, or an expense typed in with no receipt',
        when: 'its report is reviewed',
        then: 'it has nothing to differ from, so nothing rejects it on its own',
        decided: { by: 'claude', source: 'ADR-0043' },
        checks: [
          'domain/receipt-check › has nothing to differ from without a receipt, as for a drive',
        ],
      },
    ],
  },
  {
    id: 'US-RPT-10',
    title: 'Get my report back with each rejected expense and why',
    as: 'Alex, who travels for work',
    want: 'a report with a rejected expense to come back to me whole, each rejected expense marked with why, and listed in Needs you',
    soThat: 'I can put it right and submit it again without hunting for the problem',
    feature: 'F-18',
    requirements: ['FR-GOV-11', 'FR-GOV-12'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'one expense on a report I submitted is rejected',
        when: 'the review finishes',
        then: 'the whole report comes back to me, not only that expense',
        decided: OCT3,
        checks: [
          'db/approval.int › returns the whole report for one rejected expense, each rejection kept with why, and opens it again',
          'api/approval.int › returns the whole report with a rejected expense, shown with why on it and in Needs you',
        ],
      },
      {
        id: 'AC2',
        given: 'my report comes back',
        when: 'I open it',
        then: 'it is open again, its expenses changeable, with its day 28 or a week from the return if that is later, so I can correct it, close it and submit it again',
        decided: { by: 'blueprint', source: 'journeys §4.5' },
        checks: [
          'db/approval.int › returns the whole report for one rejected expense, each rejection kept with why, and opens it again',
          'api/approval.int › returns the whole report with a rejected expense, shown with why on it and in Needs you',
        ],
        rules: ['R-REOPEN-GRACE'],
      },
      {
        id: 'AC3',
        given: 'a returned report',
        when: 'I open it',
        then: 'it shows the approver’s comment, and each rejected expense is marked, with why it was rejected',
        decided: OCT3,
        checks: [
          'api/approval.int › returns the whole report with a rejected expense, shown with why on it and in Needs you',
          'e2e/signed-in › a report returned with a rejected expense',
        ],
      },
      {
        id: 'AC4',
        given: 'a rejected expense',
        when: 'I open Needs you',
        then: 'it is listed with why it was rejected, beside the returned report and its comment, until I submit the report again',
        decided: OCT3,
        checks: [
          'api/approval.int › returns the whole report with a rejected expense, shown with why on it and in Needs you',
          'db/approval.int › returns the whole report for one rejected expense, each rejection kept with why, and opens it again',
          'e2e/signed-in › a rejected expense in Needs you',
        ],
      },
      {
        id: 'AC5',
        given: 'a returned report I empty by moving everything off it',
        when: 'the schedule next runs',
        then: 'it stays, with its approval history, rather than being dropped',
        decided: { by: 'claude', source: 'ADR-0043' },
        checks: [
          'db/approval.int › keeps a returned report that is emptied, and lets its member delete a rejected expense',
        ],
      },
    ],
    note: 'Built in PR #60 behind Approval (#24). That a returned report gets a week to close as a reopened one does, and that a rejection stays in Needs you until the report goes again, are Claude’s (ADR-0043), yours to overturn.',
  },
  {
    id: 'US-RPT-11',
    title: 'See every report in the currency I’m reimbursed in',
    as: 'Alex, who travels for work, abroad too',
    want: 'every amount on a report converted to the currency I’m reimbursed in, beside what I spent',
    soThat: 'a report shows one total, the one I will get back',
    feature: 'F-49',
    requirements: ['FR-EXP-13', 'NFR-DAT-02', 'NFR-DAT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a report with amounts in more than one currency',
        when: 'I open it',
        then: 'each amount shows in my reimbursement currency beside the amount as spent, and the report totals in that one currency',
        decided: OCT4,
        checks: [
          'api/reimbursement › totals in one currency: amounts already in it as they are, the rest at their rate, and says what is left out',
          'api/reimbursement › shows each amount beside its conversion, with the rate, its date and its source',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'an expense in another currency',
        when: 'it is converted',
        then: 'it is at the reference rate for its purchase date',
        decided: { by: 'owner', source: 'Q25' },
        checks: [
          'domain/reference-rates › takes the purchase date’s own rate, against the euro as published',
          'db/conversions.int › converts at the purchase date’s reference rate, or the last one before it, and copies the rate on',
        ],
      },
      {
        id: 'AC3',
        given:
          'an expense already in my reimbursement currency, as when my card converted it at purchase',
        when: 'the report is totalled',
        then: 'it counts as it is, with no rate applied',
        decided: { by: 'owner', source: 'Q22' },
        checks: [
          'domain/reimbursement › counts an amount already in it as it is, with no rate',
          'api/reimbursement › totals in one currency: amounts already in it as they are, the rest at their rate, and says what is left out',
        ],
      },
      {
        id: 'AC4',
        given: 'I open Settings',
        when: 'I choose my reimbursement currency',
        then: 'my reports convert to it',
        decided: { by: 'owner', source: 'Q23' },
        checks: [
          'db/conversions.int › moves open and closed reports to a new choice, and leaves a submitted one as it was',
          'api/reimbursement › sets the person’s choice and hands the request to convert to the workflows at once',
        ],
      },
      {
        id: 'AC5',
        given: 'I have never chosen one',
        when: 'my reports convert',
        then: 'they use my organization’s home currency',
        decided: OCT4,
        checks: [
          'db/conversions.int › starts as the organization’s home currency, and is the person’s own once chosen',
          'api/reimbursement › is the organization’s home currency until the person chooses, with every currency to choose from',
        ],
      },
      {
        id: 'AC6',
        given: 'an amount was converted',
        when: 'anyone looks at it later, after rates have moved',
        then: 'it keeps the rate it was converted at, that rate’s date and its source, unchanged',
        decided: { by: 'blueprint', source: 'arch §6.7' },
        checks: [
          'db/conversions.int › keeps the rate it converted at when rates move, and applies it again to an edited amount',
          'db/conversions.int › refuses a converted amount without its rate, the rate’s date or its source',
        ],
      },
      {
        id: 'AC7',
        given: 'a purchase on a weekend or a holiday, when the ECB publishes no rate',
        when: 'it is converted',
        then: 'the last rate published before it applies, at most 10 days back, and the rate’s date recorded is the day it was published',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'domain/reference-rates › uses the last rate published before a weekend, and records that rate’s own date',
          'domain/reference-rates › has no rate past the lookback, or for a day both currencies weren’t published',
        ],
        rules: ['R-RATE-LOOKBACK'],
      },
      {
        id: 'AC8',
        given: 'an amount in one currency reimbursed in another, neither of them the euro',
        when: 'it is converted',
        then: 'the rate is crossed through the euro, kept to 10 significant digits, and that stored rate alone gives the converted amount, within a cent of the exact cross',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'domain/reference-rates › crosses two currencies through the euro, to ten significant digits',
          'domain/reference-rates › converts up to 100,000.00 within a cent of the exact cross rate',
        ],
      },
      {
        id: 'AC9',
        given: 'a report I open, or one on Home or in Needs you',
        when: 'it is totalled',
        then: 'the total I see first is in my reimbursement currency, with what was spent beside it, and the report lists each rate used with its date and source',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'api/reimbursement › totals in the reimbursement currency on Home and in Needs you too',
          'api/reimbursement › shows each amount beside its conversion, with the rate, its date and its source',
        ],
      },
      {
        id: 'AC10',
        given: 'currency conversion is switched off',
        when: 'I open my reports, Home or Needs you',
        then: 'they read exactly as before: one total per currency, nothing converted',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/reimbursement › reads exactly as before while the feature is off',
          'db/conversions.int › does nothing while the feature is off',
        ],
      },
    ],
    note: 'Replacing the reference rate with the amount on a card statement was not part of your answer to Q25, so it isn’t planned. AC7 to AC9 are Claude’s (ADR-0034), yours to overturn.',
  },
  {
    id: 'US-RPT-12',
    title: 'Keep our own expense categories and types',
    as: 'Sam, a finance admin',
    want: 'to define our organization’s own categories and types, as two lists that can each nest, and which types each category allows',
    soThat: 'spend is coded the way we book it, and people pick only types that fit',
    feature: 'F-43',
    requirements: ['FR-EXP-11'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'my organization',
        when: 'its categories and types are set up',
        then: 'they are two separate lists, and each can nest',
        decided: Q7,
        checks: [
          'db/categories.int › adds, renames, nests, codes and retires categories and types, each in the audit trail',
          'domain/categories › reads a list as a tree: each after its parent, siblings by name, with its depth',
          'api/categories › lists both trees in order, with the types each category allows, for everyone',
          'e2e/signed-in › category settings',
        ],
      },
      {
        id: 'AC2',
        given: 'a category',
        when: 'I edit it',
        then: 'I choose which types it allows',
        decided: Q7,
        checks: [
          'db/categories.int › adds, renames, nests, codes and retires categories and types, each in the audit trail',
          'e2e/signed-in › editing a category',
        ],
      },
      {
        id: 'AC3',
        given: 'a type',
        when: 'I allow it in several categories',
        then: 'it is offered under each of them',
        decided: { by: 'claude' },
        checks: [
          'db/categories.int › adds, renames, nests, codes and retires categories and types, each in the audit trail',
          'domain/categories › suggests a ready-made type under another category that allows it, and never a retired one',
        ],
      },
      {
        id: 'AC4',
        given: 'a category and a type',
        when: 'they are set up',
        then: 'the general ledger and tax codes go on the category, and the rules, such as attendees or a receipt being needed, go on the type',
        decided: { by: 'claude' },
        checks: [],
        untested: 78,
      },
      {
        id: 'AC5',
        given: 'a new organization',
        when: 'it starts',
        then: 'it has a ready-made set that owners and finance admins rename, add to or retire; one in use is retired, never deleted, so old claims keep it',
        decided: { by: 'claude' },
        checks: [
          'db/categories.int › gives a new organization the ready-made categories and types, once',
          'db/categories.int › deletes only what no expense has and nothing sits under; one in use is retired and kept',
          'api/categories › says what is wrong with a change, and refuses to delete one in use',
        ],
      },
      {
        id: 'AC6',
        given: 'a category',
        when: 'I set it up',
        then: 'it carries its general ledger code and its tax code, each optional',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'db/categories.int › adds, renames, nests, codes and retires categories and types, each in the audit trail',
          'domain/categories › keeps a code trimmed, a blank one as none, and refuses a long one',
        ],
      },
      {
        id: 'AC7',
        given: 'I am neither an owner nor a finance admin',
        when: 'I try to change the categories or types',
        then: 'I am refused, and I can still read them to choose from',
        decided: { by: 'blueprint', source: 'design §5.2' },
        checks: [
          'api/categories › lets only owners and finance admins add, change, retire or delete them',
          'api/categories › lists both trees in order, with the types each category allows, for everyone',
        ],
      },
      {
        id: 'AC8',
        given: 'a category or type',
        when: 'anyone adds, changes, retires or deletes it',
        then: 'the audit trail says who did what',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/categories.int › adds, renames, nests, codes and retires categories and types, each in the audit trail',
          'db/categories.int › deletes only what no expense has and nothing sits under; one in use is retired and kept',
        ],
      },
      {
        id: 'AC9',
        given: 'a category or type',
        when: 'I put it under another',
        then: 'it can’t go under itself or anything under it, and a name is used once in its list, case aside',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'domain/categories › refuses a parent that is the node itself or one of its descendants',
          'db/categories.int › adds, renames, nests, codes and retires categories and types, each in the audit trail',
        ],
      },
      {
        id: 'AC10',
        given: 'an organization that existed before categories arrived',
        when: 'they arrive',
        then: 'it starts from the same ready-made set as a new one, and an untouched set is no one’s work, so a sign-in can still move out of an empty organization',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'db/categories.int › gives a new organization the ready-made categories and types, once',
          'db/categories.int › seeds only the organization it runs in',
          'db/categories.int › is no one’s work until a person changes it, so a sign-in can still move out',
        ],
      },
      {
        id: 'AC11',
        given: 'categories are switched off for my organization',
        when: 'anyone uses the app',
        then: 'nothing changes: Settings has no Categories page, expenses show none and need none, and the API answers 404 feature_off',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/categories › answers 404 feature_off on every route, and shows expenses as before',
        ],
      },
    ],
    note: 'Your answer to Q7 chose two trees, the category narrowing the types. AC3 to AC6, AC9 and AC10 are Claude’s assumptions (FR-EXP-11, ADR-0036), yours to overturn. The ready-made set: Travel (Airfare, Lodging, Ground transport, Mileage), Meals (Business meal, Per-diem meal), Office (Office supplies), Software (Software) and Other (Other). Rules on types wait until the rules themselves are built (#78); the mileage rate is the organization’s, by your answer to Q28, not the type’s.',
  },
  {
    id: 'US-RPT-13',
    title: 'Give each expense a category and a type',
    as: 'Alex, who travels for work',
    want: 'to give each expense a category and a type, choosing the type from those its category allows',
    soThat: 'every expense is coded correctly without my knowing finance’s codes',
    feature: 'F-43',
    requirements: ['FR-EXP-11'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'any expense filed or edited without a category and a type',
        when: 'I look at it, at my expense list or at Needs you',
        then: 'each says it still needs them, until I give it them',
        decided: { by: 'owner', source: 'Q27' },
        checks: [
          'api/categories › suggests one from what the expense shows, marked as a suggestion, or says it has none',
          'api/categories › asks for each of the member’s own, with its suggestion, after reasons and before reports to close',
        ],
      },
      {
        id: 'AC2',
        given: 'I have chosen a category for an expense',
        when: 'I pick its type',
        then: 'only the types that category allows are offered',
        decided: Q7,
        checks: [
          'domain/categories › refuses a type the category does not allow, and anything missing or retired',
          'db/categories.int › takes a type its category allows, once, and records who chose it',
          'api/categories › takes a type its category allows, confirmed from then on',
          'e2e/signed-in › choosing a category and type',
        ],
      },
      {
        id: 'AC3',
        given: 'an expense with no category and type, and none to suggest',
        when: 'I see it, on its page or in the expense list',
        then: 'it says it has none',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'api/categories › suggests one from what the expense shows, marked as a suggestion, or says it has none',
          'e2e/signed-in › an expense with no category',
        ],
      },
      {
        id: 'AC4',
        given: 'an expense with no category and type',
        when: 'I look at Needs you, or close its report',
        then: 'it is in Needs you as well, and holds nothing up',
        decided: { by: 'owner', source: 'Q27' },
        checks: [
          'api/categories › asks for each of the member’s own, with its suggestion, after reasons and before reports to close',
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
      },
      {
        id: 'AC5',
        given: 'a category or type that is retired',
        when: 'I choose for an expense',
        then: 'it is not offered, but an expense that already has it keeps it, marked retired',
        decided: { by: 'claude', source: 'ADR-0036' },
        checks: [
          'domain/categories › refuses a type the category does not allow, and anything missing or retired',
          'api/categories › keeps a retired type on the expense that has it, marked retired',
          'db/categories.int › deletes only what no expense has and nothing sits under; one in use is retired and kept',
        ],
      },
      {
        id: 'AC6',
        given: 'my expense is submitted or later',
        when: 'I try to change its category or type',
        then: 'it stays as it went in',
        decided: ADR29,
        checks: [
          'api/categories › leaves a submitted expense as it went in',
          'db/categories.int › takes a type its category allows, once, and records who chose it',
        ],
      },
      {
        id: 'AC7',
        given: 'an expense on a report I have closed',
        when: 'I give it a category and type',
        then: 'the report opens again, as for any change to it',
        decided: ADR29,
        checks: [
          'db/categories.int › opens a closed report again when an expense on it is given a category',
        ],
      },
      {
        id: 'AC8',
        given: 'I choose or confirm a category and type',
        when: 'it is saved',
        then: 'the audit trail records who chose what, and what it had before',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/categories.int › takes a type its category allows, once, and records who chose it',
        ],
      },
    ],
    note: 'An expense without a category and type says so on its page and in the list, and holds nothing up. Your answer to Q27 adds it to Needs you as well, built in PR #59 (#71, US-RPT-18). Submitting a report will not need them (ADR-0036, Q27).',
  },
  {
    id: 'US-RPT-16',
    title: 'Export a closed report as a spreadsheet',
    as: 'Riley, a solo professional who self-attests',
    want: 'to download a closed report as a CSV file',
    soThat: 'I can hand my claim to whoever reimburses me, or load it into my own books',
    feature: 'F-19',
    requirements: ['FR-SET-01'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a closed report of mine',
        when: 'I export it as CSV',
        then: 'it has a row per expense on it, its trips’ and its local expenses alike, in date order: the date, merchant, category, type, trip, purpose (the trip’s, or the local expense’s justification), note, and the amount and currency as spent',
        decided: { by: 'claude' },
        checks: [
          'domain/report-export › has a row per expense, in the order given, and a total per currency, never converted',
          'db/report-export.int › lists every expense on a report, through its trips and as local expenses, in date order',
          'api/report-export › answers a closed report as CSV: a row per expense, then each currency’s total',
        ],
      },
      {
        id: 'AC2',
        given: 'a report with amounts in more than one currency',
        when: 'I export it',
        then: 'after the expenses comes a total for each currency, never converted, each amount in its currency’s own decimals; a possible duplicate is in neither the rows nor the totals, as on the report itself',
        decided: ADR29,
        checks: [
          'domain/report-export › has a row per expense, in the order given, and a total per currency, never converted',
          'domain/report-export › writes each amount in its currency’s own minor units, and leaves out one with no amount',
          'db/report-export.int › leaves out a possible duplicate, as the report’s totals do',
        ],
      },
      {
        id: 'AC3',
        given: 'the CSV',
        when: 'I open it in Excel, Numbers or Google Sheets',
        then: 'accented names and currency signs show as written (UTF-8 with a byte order mark), a comma, quote or line break stays inside its cell, and text that starts like a formula (=, +, -, @) is written as text, never run',
        decided: { by: 'claude' },
        checks: [
          'domain/report-export › starts with a byte order mark and ends each line with CRLF, so Excel reads it as UTF-8',
          'domain/report-export › quotes a value with a comma, a quote or a line break, doubling its quotes',
          'domain/report-export › writes text that starts like a formula as plain text, but never a negative amount',
        ],
      },
      {
        id: 'AC4',
        given: 'an expense with a category or a type',
        when: 'its report is exported',
        then: 'they are in its columns; until my organization has its own categories and types (#51), the columns are there and empty',
        decided: { by: 'claude' },
        checks: [
          'domain/report-export › carries a category and type once the expense has them',
          'db/report-export.int › lists every expense on a report, through its trips and as local expenses, in date order',
        ],
      },
      {
        id: 'AC5',
        given: 'a report of mine',
        when: 'I ask to export it',
        then: 'it is refused while the report is open, and exported once it has closed, and at every state after that, while approval is off; with approval on, only once it is submitted, and after',
        decided: { by: 'owner', source: 'Q29' },
        checks: [
          'domain/report-export › exports a report once it has closed, and never one still open',
          'api/report-export › refuses a report still open with 409 not_closed, in either format',
          'domain/report-export › exports only a submitted or approved report once approval exists (Q29)',
          'api/approval.int › refuses an amount above the receipt, and a submission while a lower one says nothing of why',
        ],
      },
      {
        id: 'AC6',
        given: 'another member’s report in my organization',
        when: 'I ask to export it, being neither its member nor the owner, a finance admin or an auditor',
        then: 'it is as if there were no such report, open or closed',
        decided: { by: 'claude' },
        checks: [
          'domain/report-export › lets the member whose report it is export it, and the owner, finance admins and auditors any',
          'api/report-export › lets only the member whose report it is, or the owner, finance admins and auditors, export it',
        ],
      },
      {
        id: 'AC7',
        given: 'report export is switched off for my organization',
        when: 'anything asks for a report’s CSV or PDF',
        then: 'it is answered as if there were no such thing (feature_off), and the report is not read',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/report-export › looks absent while report export is switched off: 404 feature_off, nothing read',
        ],
      },
      {
        id: 'AC8',
        given: 'a closed report’s page, with report export switched on',
        when: 'I tap Export CSV',
        then: 'the file downloads, named for me and the day the report opened, such as expense-report-riley-2026-09-04.csv; with report export switched off, or the report open, there is no Export CSV or Export PDF',
        decided: { by: 'claude' },
        checks: [],
        untested: 66,
      },
    ],
    note: 'FR-SET-01 asks for approved reports. You asked for export before approval (#24), so while approval is off a closed report is exported; your answer to Q29 narrows export to submitted and approved reports once approval exists, built in PR #60 (AC5). The columns, who may export and the CSV’s form are Claude’s too. A converted amount joins as a column with your reimbursement currency (#62). The file’s name is checked through the API; tapping the buttons is not yet checked end to end.',
  },
  {
    id: 'US-RPT-17',
    title: 'Export a closed report as a PDF summary',
    as: 'Riley, a solo professional who self-attests',
    want: 'a closed report as one PDF document, with its totals',
    soThat: 'I can send or print my claim as it stands',
    feature: 'F-19',
    requirements: ['FR-SET-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a closed report of mine',
        when: 'I export it as PDF',
        then: 'it is one document: a heading with my name, my organization, the report’s status, the days it opened and closed, the dates its expenses span and when it was exported; then the CSV’s table and each currency’s total',
        decided: { by: 'claude' },
        checks: [
          'api/report-export › heads it with the person, organization, status and dates, then the CSV’s table and totals',
          'api/report-export › answers a closed report as a one-page PDF with no images, named for its person and the day it opened',
        ],
      },
      {
        id: 'AC2',
        given: 'the PDF',
        when: 'I open it',
        then: 'it holds no receipt images, nor any other picture',
        decided: { by: 'claude' },
        checks: [
          'api/report-export › answers a closed report as a one-page PDF with no images, named for its person and the day it opened',
        ],
      },
      {
        id: 'AC3',
        given: 'a report too long for one page',
        when: 'it is exported as PDF',
        then: 'it runs on to further pages with the table’s headings on each, and an expense is never split across two pages',
        decided: { by: 'claude' },
        checks: [
          'api/report-export › runs on to further pages with the table’s headings on each, never splitting a row',
        ],
      },
      {
        id: 'AC4',
        given: 'a merchant written in a script the PDF’s font lacks, or a very long note',
        when: 'it is exported as PDF',
        then: 'the PDF is still made: signs such as ₹ become their currency codes and other characters question marks, and a cell longer than twelve lines ends in “…”, the CSV keeping all of it',
        decided: { by: 'claude' },
        checks: [
          'api/report-export › wraps a long cell, ends one too long for twelve lines in "…", and never fails on a character',
        ],
        rules: ['R-PDF-CELL-LINES'],
      },
      {
        id: 'AC5',
        given: 'a report still open, another member’s, or report export switched off',
        when: 'I ask for its PDF',
        then: 'it is refused as the CSV is',
        decided: { by: 'claude' },
        checks: [
          'api/report-export › refuses a report still open with 409 not_closed, in either format',
          'api/report-export › lets only the member whose report it is, or the owner, finance admins and auditors, export it',
          'api/report-export › looks absent while report export is switched off: 404 feature_off, nothing read',
        ],
      },
    ],
    note: 'Like the PDF made from an email (ADR-0027), it is written in a standard font that covers Latin script. It is laid out in the request: a report holds a month of one person’s spending, which takes milliseconds of computing and no other service.',
  },
  {
    id: 'US-RPT-14',
    title: 'Know when an amount isn’t converted yet, or can’t be',
    as: 'Alex, who travels for work, abroad too',
    want: 'to see plainly which amounts are still being converted, and which can’t be',
    soThat: 'I never take a partial total for the one I will get back',
    feature: 'F-49',
    requirements: ['FR-EXP-13'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an amount on a report whose rate isn’t recorded yet',
        when: 'I open the report',
        then: 'it says it is converting, the total says how many amounts it leaves out, and the rate is fetched in the background, never while I wait',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'domain/reimbursement › is converting while no recorded rate applies: none yet, or another currency, date or target',
          'api/reimbursement › totals in one currency: amounts already in it as they are, the rest at their rate, and says what is left out',
          'workflows/conversions › converts what it can, fetches the rates still needed, then converts with them',
        ],
      },
      {
        id: 'AC2',
        given: 'an amount in a currency the ECB doesn’t publish, such as dirhams',
        when: 'the report is converted',
        then: 'it stays as spent, marked not converted, and is listed apart from the total',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › records a currency the source has no rate for, or a day with none in reach, as unconverted',
          'domain/reimbursement › stays as spent, said plainly, when the source has no rate for it',
          'api/reimbursement › shows each amount beside its conversion, with the rate, its date and its source',
        ],
      },
      {
        id: 'AC3',
        given: 'a trip joins a report, or an amount on one changes',
        when: 'the change is saved',
        then: 'conversion is asked for at once, and an hourly sweep tries again whatever is still converting, such as after the ECB was down',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › asks when something on a report changes, and the sweep finds the organization until it is converted',
          'workflows/conversions › takes no series as no rate, tries a busy source again, and gives up on a bad request',
          'workflows/conversions › carries on past an organization that fails, then fails the sweep so it is retried',
        ],
        rules: ['R-CONVERSION-SWEEP'],
      },
      {
        id: 'AC4',
        given: 'a purchase dated today',
        when: 'it would be converted',
        then: 'it waits until tomorrow, when today’s rate is published, rather than taking yesterday’s',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'domain/reference-rates › waits for the day after a purchase, when that day’s rate is published',
          'db/conversions.int › waits for the day after a purchase before asking for its rate',
        ],
      },
      {
        id: 'AC5',
        given: 'the owner switches currency conversion on',
        when: 'it is switched',
        then: 'what is already on reports is converted without waiting for a change',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › announces a feature switched on or off',
          'workflows/conversions › run when asked, or when the owner switches the feature on, one at a time per organization',
        ],
      },
    ],
    note: 'All Claude’s (ADR-0034), yours to overturn. The ECB publishes about 30 currencies; dirhams, dinars, riyals and the pesos of Chile, Colombia and Argentina are among those it doesn’t.',
  },
  {
    id: 'US-RPT-15',
    title: 'Choose the currency I’m reimbursed in',
    as: 'Alex, who travels for work, abroad too',
    want: 'to choose in Settings the currency I’m reimbursed in',
    soThat: 'my reports total in the money I am actually paid back in',
    feature: 'F-49',
    requirements: ['FR-EXP-13'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I have never chosen one',
        when: 'I open Settings › Currency',
        then: 'it shows my organization’s home currency, and every currency I could choose, marking those the ECB has no rate for',
        decided: { by: 'owner', source: 'Q23' },
        checks: [
          'api/reimbursement › is the organization’s home currency until the person chooses, with every currency to choose from',
          'e2e/signed-in',
        ],
      },
      {
        id: 'AC2',
        given: 'I choose another currency',
        when: 'I save it',
        then: 'my open and closed reports move to it and convert again, and a report opened from then on opens in it',
        decided: { by: 'owner', source: 'Q23' },
        checks: [
          'db/conversions.int › moves open and closed reports to a new choice, and leaves a submitted one as it was',
          'db/conversions.int › opens a new report in the person’s currency while the feature is on, and the home currency while off',
          'api/reimbursement › sets the person’s choice and hands the request to convert to the workflows at once',
        ],
      },
      {
        id: 'AC3',
        given: 'a report already submitted',
        when: 'I choose another currency',
        then: 'it keeps the currency it was submitted in',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › moves open and closed reports to a new choice, and leaves a submitted one as it was',
        ],
      },
      {
        id: 'AC4',
        given: 'I chose a currency',
        when: 'I choose my organization’s again',
        then: 'my reports follow its home currency, whatever it becomes',
        decided: { by: 'claude', source: 'ADR-0034' },
        checks: [
          'db/conversions.int › starts as the organization’s home currency, and is the person’s own once chosen',
          'api/reimbursement › sets the person’s choice and hands the request to convert to the workflows at once',
        ],
      },
      {
        id: 'AC5',
        given: 'any choice of currency',
        when: 'it is saved',
        then: 'it is in the audit trail, with what it was before',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/conversions.int › starts as the organization’s home currency, and is the person’s own once chosen',
        ],
      },
      {
        id: 'AC6',
        given: 'currency conversion is switched off',
        when: 'I look in Settings',
        then: 'there is no Currency page, and asking for my currency answers that the feature is off',
        decided: { by: 'owner', source: 'Q5' },
        checks: ['api/reimbursement › looks absent while the feature is off'],
      },
      {
        id: 'AC7',
        given: 'a currency the app doesn’t support',
        when: 'it is asked for',
        then: 'it is refused, and nothing changes',
        decided: { by: 'claude' },
        checks: ['api/reimbursement › refuses a currency the app doesn’t support, and a stranger'],
      },
    ],
    note: 'Your answer to Q23: your preferred currency, set in the app. Keeping a submitted report’s currency, and following the organization’s home currency until you choose, are Claude’s (ADR-0034).',
  },
  {
    id: 'US-RPT-18',
    title: 'See in Needs you each expense that needs a category and type',
    as: 'Riley, a solo professional who self-attests',
    want: 'each of my expenses without a category and type to be in Needs you, with what is suggested for it',
    soThat: 'I code them as I go, most with a tap, and nothing waits on them',
    feature: 'F-43',
    requirements: ['FR-EXP-11'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'categories switched on, and a Ready expense of mine with no category and type',
        when: 'I look at Needs you',
        then: 'it is there, saying it needs a category and type and what is suggested for it, if anything, and opens the expense, where a suggestion is confirmed with a tap',
        decided: { by: 'owner', source: 'Q27' },
        checks: [
          'api/categories › asks for each of the member’s own, with its suggestion, after reasons and before reports to close',
          'e2e/signed-in › an expense with no category and type, in Needs you',
        ],
      },
      {
        id: 'AC2',
        given: 'several such expenses',
        when: 'Needs you lists them',
        then: 'they come oldest first, after local expenses needing a reason and before reports ready to close',
        decided: { by: 'claude' },
        checks: [
          'api/categories › asks for each of the member’s own, with its suggestion, after reasons and before reports to close',
          'db/categories.int › lists a member’s own Ready ones, oldest first, but not one submitted or held as a duplicate',
        ],
      },
      {
        id: 'AC3',
        given:
          'an expense submitted or later, held as a possible duplicate, still being read or needing a look, or a colleague’s',
        when: 'Needs you is built for me',
        then: 'it is not listed for its category: one being read or needing a look is there for that already, and a held one waits on my decision about the pair',
        decided: { by: 'claude' },
        checks: [
          'db/categories.int › lists a member’s own Ready ones, oldest first, but not one submitted or held as a duplicate',
        ],
      },
      {
        id: 'AC4',
        given: 'an expense I give a category and type, or whose suggestion I confirm',
        when: 'I look at Needs you again',
        then: 'it is gone from it',
        decided: { by: 'owner', source: 'Q27' },
        checks: [
          'db/categories.int › lists a member’s own Ready ones, oldest first, but not one submitted or held as a duplicate',
        ],
      },
      {
        id: 'AC5',
        given: 'such an expense on a report',
        when: 'I close the report',
        then: 'it holds nothing up',
        decided: { by: 'owner', source: 'Q27' },
        checks: [
          'db/reports.int › refuses while anything needs review or a justification, then closes',
        ],
      },
      {
        id: 'AC6',
        given: 'Home',
        when: 'it counts what needs me',
        then: 'it counts these too, as Needs you lists them',
        decided: { by: 'claude' },
        checks: ['api/categories › counts them on Home, as the inbox lists them'],
      },
      {
        id: 'AC7',
        given: 'categories switched off for my organization',
        when: 'I look at Needs you or Home',
        then: 'they are exactly as they were, and nothing is asked of my expenses’ categories',
        decided: { by: 'owner', source: 'Q5' },
        checks: ['api/categories › leaves Needs you as it was when categories are off (%s)'],
      },
    ],
    note: 'Your answer to Q27. Switched on for the first time, Needs you lists every Ready expense you already have until each is coded; most carry a suggestion you confirm with a tap on the expense’s page. Only Ready ones, the order, and leaving out a held duplicate are Claude’s, yours to overturn.',
  },
  {
    id: 'US-RPT-19',
    title: 'Submit my closed report for approval',
    as: 'Alex, who travels for work',
    want: 'to submit a closed report and have it go to the one person who approves it',
    soThat: 'my claim reaches whoever pays it without my chasing anyone',
    feature: 'F-18',
    requirements: ['FR-GOV-02', 'FR-GOV-13', 'FR-EXP-12'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'my closed report, every expense on it holding up against its receipt',
        when: 'I submit it',
        then: 'it goes to its approver in one step and waits for them, each expense on it submitted and unchangeable while it waits',
        decided: { by: 'blueprint', source: 'journeys §4.4' },
        checks: [
          'db/approval.int › submits a closed report to its approver in one step, each expense submitted with its names copied',
          'api/approval.int › submits once the lower claim says why, keeping its category’s name as it went in',
        ],
      },
      {
        id: 'AC2',
        given: 'a team',
        when: 'my report is submitted',
        then: 'it goes to the approver an owner chose for me in People when they can approve it (US-TEAM-06); otherwise to the longest-standing approver, then finance admin, then owner, never to me',
        decided: { by: 'owner', source: 'Q42' },
        checks: [
          'domain/approvals › sends a report to an approver first, then a finance admin, then the owner, never its own member',
          'domain/approvals › sends it to the member’s manager when they can approve it',
          'domain/approvals › takes the longest-standing among equals',
          'domain/approvals › sends a report to the approver an owner chose, over the routing as built',
        ],
      },
      {
        id: 'AC3',
        given: 'a report still open, or another member’s',
        when: 'I submit it',
        then: 'it is refused: only a closed report is submitted, and each person submits only their own',
        decided: OCT4,
        checks: [
          'domain/lifecycle/report › closes only with nothing left to review, and reopens until submitted',
          'db/approval.int › refuses one not closed, another member’s, one differing from its receipt without a reason, and one no one else can approve',
        ],
      },
      {
        id: 'AC4',
        given: 'a team in which no one else can approve my report',
        when: 'I submit it',
        then: 'it is refused, saying an owner can give someone the approver or finance admin role, and it stays closed',
        decided: { by: 'blueprint', source: 'ADR-0001' },
        checks: [
          'domain/approvals › finds no one when nobody else in the team can approve it',
          'api/approval.int › refuses a team member’s own report with no one else able to approve it',
        ],
      },
      {
        id: 'AC5',
        given: 'my closed report',
        when: 'I open it',
        then: 'it says who it would go to before I submit it, and each expense says how it holds up against its receipt',
        decided: { by: 'claude', source: 'ADR-0043' },
        checks: [
          'api/approval.int › refuses an amount above the receipt, and a submission while a lower one says nothing of why',
          'e2e/signed-in › submitting a report for approval',
        ],
      },
      {
        id: 'AC6',
        given: 'a submitted report',
        when: 'anyone later looks at the audit trail',
        then: 'it records who submitted it, who it went to and its expenses',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/approval.int › submits a closed report to its approver in one step, each expense submitted with its names copied',
        ],
      },
      {
        id: 'AC7',
        given: 'approval is on',
        when: 'I export a report',
        then: 'only a submitted or approved one exports; a closed one is checked, and sent, by submitting it',
        decided: { by: 'owner', source: 'Q29' },
        checks: [
          'domain/report-export › exports only a submitted or approved report once approval exists (Q29)',
          'api/approval.int › refuses an amount above the receipt, and a submission while a lower one says nothing of why',
        ],
      },
      {
        id: 'AC8',
        given: 'approval is switched off for my organization',
        when: 'I use my reports',
        then: 'nothing is submitted, a closed report exports as before, and every approval route answers as if it weren’t there (feature_off)',
        decided: { by: 'owner', source: 'Q5' },
        checks: [
          'api/approval.int › answers 404 feature_off on every route, and leaves reports, export and Needs you as they were',
        ],
      },
      {
        id: 'AC9',
        given: 'a trip on a submitted report',
        when: 'a late receipt dated in it arrives, or I try to put an expense on it',
        then: 'the expense files as local and goes on my next report; the submitted trip takes no more',
        decided: { by: 'claude', source: 'ADR-0043' },
        checks: [
          'db/approval.int › files an expense dated in a submitted trip as local, and refuses to put one on it',
        ],
      },
    ],
    note: 'Built in PR #60 behind Approval (#24, ADR-0043). Submitting relates to closing as ADR-0029 has it: only a closed report is submitted, closing never submits, and day 28 closes but never submits. Who a report goes to is your answer to Q42, with the approver an owner chooses (#86); AC5 and AC9 are Claude’s, yours to overturn.',
  },
  {
    id: 'US-RPT-20',
    title: 'Approve a report, or return it with a comment',
    as: 'Jordan, an approver',
    want: 'to see each report sent to me, check every expense against its receipt, and approve it or send it back with a comment',
    soThat:
      'only claims the evidence supports are paid, and a claim that needs fixing goes back to its person',
    feature: 'F-18',
    requirements: ['FR-GOV-02', 'FR-GOV-03', 'FR-GOV-11', 'FR-EXP-03'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a report sent to me',
        when: 'I open Needs you or Reports',
        then: 'it is there, waiting for my decision',
        decided: { by: 'claude', source: 'ADR-0043' },
        checks: [
          'api/approval.int › shows the approver what is routed to them, and asks for the second factor to approve it',
        ],
      },
      {
        id: 'AC2',
        given: 'a report sent to me',
        when: 'I open it',
        then: 'every expense on it shows how it holds up against its receipt: matching, less with a reason, or differing and why',
        decided: Q6,
        checks: [
          'api/approval.int › submits once the lower claim says why, keeping its category’s name as it went in',
          'e2e/signed-in › a report waiting for your approval',
        ],
      },
      {
        id: 'AC3',
        given: 'someone else’s report, every expense holding up',
        when: 'I approve it in a session that passed the second factor',
        then: 'it is approved, and its expenses are approved and locked',
        decided: { by: 'blueprint', source: 'arch §6.9' },
        checks: [
          'db/approval.int › lets the approver decide it, changing only its status and its expenses’, and nothing else of its member’s',
          'api/approval.int › shows the approver what is routed to them, and asks for the second factor to approve it',
        ],
      },
      {
        id: 'AC4',
        given: 'someone else’s report',
        when: 'I approve it in a session that didn’t pass the second factor',
        then: 'it is refused, asking for my second factor, and nothing changes',
        decided: { by: 'blueprint', source: 'arch §6.9' },
        checks: [
          'db/approval.int › asks for the second factor to approve someone else’s, and never to self-attest alone',
          'api/approval.int › shows the approver what is routed to them, and asks for the second factor to approve it',
        ],
      },
      {
        id: 'AC5',
        given: 'a report sent to me',
        when: 'I return it',
        then: 'I must say why, up to 500 characters, and may reject expenses, each with why; it goes back to its member, and the second factor isn’t asked for',
        decided: { by: 'blueprint', source: 'journeys §4.4' },
        checks: [
          'db/approval.int › returns the whole report for one rejected expense, each rejection kept with why, and opens it again',
          'api/approval.int › returns the whole report with a rejected expense, shown with why on it and in Needs you',
          'e2e/signed-in › returning a report with an expense rejected',
        ],
        rules: ['R-APPROVAL-NOTE-MAX'],
      },
      {
        id: 'AC6',
        given: 'my own report, in a team',
        when: 'I try to approve or return it',
        then: 'it is refused, by the app and by the database: no one decides their own spend',
        decided: { by: 'blueprint', source: 'ADR-0001' },
        checks: [
          'db/approval.int › never lets anyone decide their own in a team, and lets an owner or finance admin decide in the approver’s place',
          'domain/approvals › refuses another approver, a member, and anyone deciding their own in a team',
        ],
      },
      {
        id: 'AC7',
        given: 'a report sent to another approver',
        when: 'an owner or finance admin decides it',
        then: 'they may, in that approver’s place, and the step records who decided; another approver may not',
        decided: { by: 'claude', source: 'ADR-0043' },
        checks: [
          'db/approval.int › never lets anyone decide their own in a team, and lets an owner or finance admin decide in the approver’s place',
          'domain/approvals › lets the approver it went to decide, and an owner or finance admin in their place',
        ],
      },
      {
        id: 'AC8',
        given: 'an approved expense',
        when: 'anyone tries to change it',
        then: 'it is refused, by the app and by the database; correcting it is a reversal and a new version, still to come',
        decided: { by: 'blueprint', source: 'ADR-0008' },
        checks: [
          'db/approval.int › locks an approved expense: an edit, a reason or a move to another trip is refused, by the database too',
          'api/approval.int › shows the approver what is routed to them, and asks for the second factor to approve it',
        ],
      },
      {
        id: 'AC9',
        given: 'I approve or return a report',
        when: 'anyone later looks at the audit trail',
        then: 'it records who decided, on what basis, the comment and each rejection',
        decided: { by: 'blueprint', source: 'arch AP4' },
        checks: [
          'db/approval.int › asks for the second factor to approve someone else’s, and never to self-attest alone',
          'db/approval.int › returns the whole report for one rejected expense, each rejection kept with why, and opens it again',
        ],
      },
    ],
    note: 'Built in PR #60 behind Approval (#24, ADR-0043). The second factor itself is enrolled and asked for at sign-in by #8, behind its own switch; until a person has one, they can return a report but not approve someone else’s. Not asking for it to return a report, and owners and finance admins deciding in an approver’s place, are Claude’s, yours to overturn. Correcting an approved expense is #87.',
  },
  {
    id: 'US-RPT-21',
    title: 'A submitted claim keeps its category and type names',
    as: 'Sam, a finance admin',
    want: 'a submitted claim and its export to keep the category and type names it went in with',
    soThat: 'renaming a category never changes a claim already sent, or what we booked from it',
    feature: 'F-18',
    requirements: ['NFR-DAT-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a submitted report',
        when: 'a category or type on it is renamed later',
        then: 'the report’s export and its totals by category and type keep the names it was submitted with, the parts of a split expense too',
        decided: { by: 'blueprint', source: 'arch §6.7' },
        checks: [
          'db/approval.int › keeps a submitted claim’s category and type names when they are renamed later',
          'api/approval.int › submits once the lower claim says why, keeping its category’s name as it went in',
        ],
      },
      {
        id: 'AC2',
        given: 'a report that came back to its member',
        when: 'its expenses are shown',
        then: 'they read their categories’ and types’ names as they are now, and take them again when it is submitted again',
        decided: { by: 'claude', source: 'ADR-0043' },
        checks: [
          'db/approval.int › keeps a submitted claim’s category and type names when they are renamed later',
        ],
      },
    ],
    note: 'Your requirement of snapshot fields (NFR-DAT-04), found missing for names merging PR #58 (GAP-27) and built in PR #60 (#70).',
  },
];
