import type { Story } from '../model.ts';

const CLAUDE = { by: 'claude' } as const;
const ARCH_69 = { by: 'blueprint', source: 'arch §6.9' } as const;
const ADR_0013 = { by: 'blueprint', source: 'ADR-0013' } as const;
const ADR_0015 = { by: 'blueprint', source: 'ADR-0015' } as const;
const ADR_0017 = { by: 'blueprint', source: 'ADR-0017' } as const;
const ADR_0020 = { by: 'blueprint', source: 'ADR-0020' } as const;
const ARCH_65 = { by: 'blueprint', source: 'arch §6.5' } as const;
const DELIVERY_73 = { by: 'blueprint', source: 'delivery §7.3' } as const;
const DELIVERY_74 = { by: 'blueprint', source: 'delivery §7.4' } as const;
const OWNER_OCT_4 = { by: 'owner', source: 'owner 2026-10-04' } as const;
const ADR_0035 = { by: 'claude', source: 'ADR-0035' } as const;

/** Security (NFR-SEC-01 to NFR-SEC-13) and privacy (NFR-PRV-02 to NFR-PRV-04). */
export const SECURITY_STORIES: readonly Story[] = [
  {
    id: 'US-SEC-01',
    title: 'Keep our data apart from every other organization',
    as: 'the organization’s owner',
    want: 'nobody in another organization ever to see or change our expenses, receipts, trips or keys',
    soThat: 'our spending and our evidence stay ours, even if the app’s own checks go wrong',
    feature: 'F-34',
    requirements: ['NFR-SEC-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'two organizations, each with its own records',
        when: 'a member of one works in the app',
        then: 'they see only their own organization’s records, and nothing of the other’s',
        decided: ARCH_69,
        checks: [
          'db/tenancy.int › sees only its own organization',
          'db/receipts.int › keeps receipts inside their organization',
        ],
      },
      {
        id: 'AC2',
        given: 'a request that names no organization',
        when: 'it reads any records',
        then: 'it gets nothing at all',
        decided: CLAUDE,
        checks: ['db/tenancy.int › sees nothing at all without an organization context'],
      },
      {
        id: 'AC3',
        given: 'a member of one organization',
        when: 'the app tries to write a record into another organization, or to move one of ours there',
        then: 'the database refuses it',
        decided: ARCH_69,
        checks: [
          'db/tenancy.int › cannot insert rows for another organization',
          'db/tenancy.int › cannot move its rows into another organization',
        ],
      },
      {
        id: 'AC4',
        given: 'one of our records',
        when: 'it is linked to another organization’s record, such as our expense to their trip',
        then: 'the link is refused',
        decided: CLAUDE,
        checks: [
          "db/tenancy.int › cannot point at another organization's rows through a foreign key",
        ],
      },
      {
        id: 'AC5',
        given: 'a sign-in',
        when: 'someone tries to attach it to a member of another organization',
        then: 'it is refused',
        decided: ARCH_69,
        checks: ['db/sign-ins.int › cannot add a sign-in to another organization'],
      },
      {
        id: 'AC6',
        given: 'any table that holds an organization’s records',
        when: 'the database is checked',
        then: 'row-level security keeps each organization to its own rows, and binds even the table’s owner on every table but the outbox of pending work',
        decided: CLAUDE,
        checks: ['db/tenancy.int › puts a forced tenant policy on every table that holds org data'],
      },
      {
        id: 'AC7',
        given: 'a table without that protection, or a database not yet set up',
        when: 'the readiness check runs',
        then: 'it reports not ready, naming the tables',
        decided: CLAUDE,
        checks: [
          'db/readiness › names tables without enforced RLS',
          'db/readiness › fails when migrations have not run',
        ],
      },
    ],
    note: 'The outbox of pending work is the one table the workflow relay reads across organizations; the app’s own role is still held to one organization there. Within one organization, members are kept apart too since PR #58: each sees and changes only their own records (US-SEC-14 to US-SEC-17).',
  },
  {
    id: 'US-SEC-02',
    title: 'Never let the running app switch tenant isolation off',
    as: 'the product owner, who runs ExpenseWise',
    want: 'the app to refuse to serve data whenever its database connection could ignore row-level security',
    soThat: 'a wrong connection string can never quietly let one organization see another’s data',
    feature: 'F-34',
    requirements: ['NFR-SEC-02'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'the app connects as its own runtime role, which row-level security applies to',
        when: 'it starts work on an organization’s data',
        then: 'it goes ahead',
        decided: ADR_0013,
        checks: ['db/tenancy.int › accepts expensewise_app, which row-level security applies to'],
      },
      {
        id: 'AC2',
        given:
          'the app’s connection is a role that bypasses row-level security, such as Supabase’s postgres role or a superuser',
        when: 'it starts work on an organization’s data',
        then: 'it refuses, and serves nothing',
        decided: ADR_0013,
        checks: ['db/tenancy.int › refuses a role that bypasses row-level security'],
      },
      {
        id: 'AC3',
        given: 'such a connection, or any role but the runtime role',
        when: 'the readiness check runs',
        then: 'it reports not ready and names the role it found',
        decided: CLAUDE,
        checks: [
          'db/readiness.int › is not ready as a role that bypasses row-level security',
          'db/readiness.int › is not ready as the relay role',
          'db/readiness › passes only expensewise_app without bypass rights',
        ],
      },
      {
        id: 'AC4',
        given: 'a readiness report',
        when: 'anyone asks for it',
        then: 'the answer is 200 only when every check passes and 503 otherwise, and it is never cached',
        decided: CLAUDE,
        checks: [
          'api/ready › answers 200 with the report when every check passes, never cached',
          'api/ready › answers 503 with the report when a check fails',
          'e2e/shell › reports readiness with a status that matches the report',
        ],
      },
    ],
  },
  {
    id: 'US-SEC-03',
    title: 'Leave Supabase’s Data API no way into our data',
    as: 'the product owner, who runs ExpenseWise',
    want: 'Supabase’s built-in Data API to reach none of our tables or functions, though it stays switched on',
    soThat: 'our own API, with its checks, is the only way to our data',
    feature: 'F-34',
    requirements: ['NFR-SEC-03'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'the roles Supabase’s Data API connects as: anonymous, signed-in and service',
        when: 'their rights are listed',
        then: 'they hold none on any of our tables or sequences',
        decided: ADR_0013,
        checks: ['db/supabase-roles.int › hold no privileges on any table or sequence in public'],
      },
      {
        id: 'AC2',
        given: 'those roles',
        when: 'they try to run one of our database functions',
        then: 'they have no right to',
        decided: ADR_0013,
        checks: ['db/supabase-roles.int › cannot execute our functions'],
      },
      {
        id: 'AC3',
        given: 'a query made as any of those roles',
        when: 'it asks for expenses',
        then: 'the database refuses it',
        decided: ADR_0013,
        checks: ['db/supabase-roles.int › are refused at query time too'],
      },
      {
        id: 'AC4',
        given:
          'grants that come back without a database change, as a restore into a new project gives them',
        when: 'the lock-down step that every release runs is applied',
        then: 'they are taken away again, and a second run finds nothing left to take',
        decided: CLAUDE,
        checks: [
          'db/supabase-roles.int › lose grants that come back without a migration, as after a restore',
        ],
      },
    ],
  },
  {
    id: 'US-SEC-04',
    title: 'Keep our AI provider keys encrypted and out of sight',
    as: 'the organization’s owner, who pays for the AI provider keys',
    want: 'the keys I save to be stored encrypted, bound to our organization, and never shown again',
    soThat:
      'a leaked backup, a copied row or a curious colleague can’t spend our money with a provider',
    feature: 'F-04',
    requirements: ['NFR-SEC-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I save a key in Settings, AI providers',
        when: 'it is stored',
        then: 'it is encrypted, and neither the screen nor the API ever shows it again: only its last four characters',
        decided: ADR_0015,
        checks: [
          'api/workspace › checks a key with the provider, stores it encrypted and never returns it',
          'api/secret-box › shows only the last four characters as a hint',
          'db/ai-keys.int › stores at most four characters of the key as its hint',
        ],
      },
      {
        id: 'AC2',
        given:
          'a stored key’s encrypted form copied to another organization’s row, or to another provider’s',
        when: 'the app tries to open it',
        then: 'it won’t open',
        decided: ADR_0015,
        checks: [
          'api/secret-box › refuses to open a ciphertext under another organization or provider',
        ],
      },
      {
        id: 'AC3',
        given:
          'an encrypted key that was altered, or a server secret that has changed since it was saved',
        when: 'the app tries to open it, or I press Test',
        then: 'it won’t open, and Test reports that the stored key can no longer be decrypted',
        decided: ADR_0015,
        checks: [
          'api/secret-box › refuses to open with a different secret, or a tampered ciphertext',
          'api/workspace › reports a stored key that no longer works, or cannot be decrypted, without failing',
        ],
      },
      {
        id: 'AC4',
        given: 'a key saved by our organization',
        when: 'another organization lists, replaces or removes keys, or the app reads keys without naming an organization',
        then: 'ours is neither seen nor touched',
        decided: ADR_0015,
        checks: ["db/ai-keys.int › keeps one organization's keys away from every other"],
      },
      {
        id: 'AC5',
        given: 'a member who is not an owner or finance admin, or someone not signed in',
        when: 'they try to see, save, test or remove a key',
        then: 'they are refused',
        decided: ADR_0015,
        checks: [
          'api/workspace › lets only owners and finance admins manage keys',
          'e2e/settings › refuses the key endpoints without a signed-in user',
        ],
      },
      {
        id: 'AC6',
        given: 'an owner or finance admin',
        when: 'they save, test or remove a key',
        then: 'the audit trail records it',
        decided: ADR_0015,
        checks: [
          'api/workspace › re-checks a stored key with its stored scheme, and records the check',
          'api/workspace › removes a key, and says when there is none',
        ],
      },
    ],
    note: 'Anyone who can run the server can decrypt every key. While the organization has the second factor switched on, saving, testing or removing a key also needs the code from an authenticator app (F-11, US-ACC-12); while it is off, a stolen password lets someone replace or remove keys (ADR-0015).',
  },
  {
    id: 'US-SEC-05',
    title: 'Keep secrets out of error reports, logs and answers',
    as: 'the product owner, who runs ExpenseWise',
    want: 'no password, sign-in token or key to appear in an error report, a log line or an answer from the API, even when a provider repeats one back',
    soThat: 'reading an error never hands anyone the means to get in',
    feature: 'F-32',
    requirements: ['NFR-SEC-05'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given:
          'an error whose text holds a database password, a bearer or sign-in token, or an Anthropic, Supabase, Inngest, PostHog or Stripe key',
        when: 'it is sent to error tracking',
        then: 'each is replaced with [redacted] in its message, exceptions and breadcrumbs, and the rest is kept',
        decided: CLAUDE,
        checks: [
          'api/redact › removes credentials from connection strings but keeps the host',
          'api/redact › removes bearer tokens, JWTs and vendor keys',
          'api/redact › redacts the message, exception values and breadcrumbs, and keeps the rest',
        ],
      },
      {
        id: 'AC2',
        given: 'a provider whose answer to a key check, or to a reading, repeats the key',
        when: 'its message is shown or stored',
        then: 'the key is replaced, and the rest of the message kept',
        decided: ADR_0015,
        checks: [
          'api/ai-providers › never repeats the key, even if the provider echoes it',
          "extraction/openai › throws the provider's status, message and code, without the key",
        ],
      },
      {
        id: 'AC3',
        given: 'a key check that gets no answer from the provider',
        when: 'the result is shown',
        then: 'it says the provider could not be reached, without the error’s own text, which can hold the key',
        decided: CLAUDE,
        checks: [
          'api/ai-providers › reports no answer as unreachable, without the error text or trying further',
        ],
      },
      {
        id: 'AC4',
        given:
          'a readiness check that fails, even with a wrong password or a broken connection string',
        when: 'anyone asks for the report',
        then: 'it gives a fixed reason, such as password rejected, and never the connection string or the raw error',
        decided: CLAUDE,
        checks: [
          'api/ready › answers 503, not 500, when the probe throws, without echoing the error',
          'db/readiness.int › reports a wrong password without echoing the connection string',
          'db/readiness › reports an unusable connection string without echoing it',
        ],
      },
      {
        id: 'AC5',
        given: 'a database command about to connect',
        when: 'it says where it is connecting',
        then: 'it names the user, host, port and database, but never the password',
        decided: CLAUDE,
        checks: ['db/connection › names the user, host, port and database but never the password'],
      },
      {
        id: 'AC6',
        given: 'error tracking is on',
        when: 'it records an error',
        then: 'it collects no request or response bodies, cookies, query strings, headers other than the browser and content type, database values or user details',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Error tracking has no destination yet, so nothing is sent to it today (GAP-07). Redaction covers what goes to error tracking; the server’s own log lines are not redacted, so they rely on never being handed a secret. OpenAI keys have no pattern of their own: the key check and the fallback reader remove the key from OpenAI’s messages, but one in any other error text would not be removed.',
  },
  {
    id: 'US-SEC-06',
    title: 'Keep receipt files private',
    as: 'the organization’s owner',
    want: 'our receipt files kept in a private store, reached only through links the app hands our own signed-in members, which soon stop working',
    soThat: 'a guessed address, or a link passed on later, shows nobody our receipts',
    feature: 'F-05',
    requirements: ['NFR-SEC-06'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'I capture a receipt',
        when: 'the app asks where to upload it',
        then: 'it is given an upload for that one file, at a place the server picks inside our organization’s folder',
        decided: ARCH_69,
        checks: ['api/receipts › hands out a one-time upload for a path inside the organization'],
      },
      {
        id: 'AC2',
        given: 'the app files that receipt',
        when: 'it says where the file is',
        then: 'the server records its own place for the file, inside our organization, whatever the app sends',
        decided: ADR_0017,
        checks: [
          'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
        ],
      },
      {
        id: 'AC3',
        given: 'the store for receipt files',
        when: 'it is first set up',
        then: 'it is private, and the server signs each upload and each link with its secret key',
        decided: ARCH_69,
        checks: [
          'storage/supabase › creates the private bucket once, then signs uploads with the secret key',
        ],
      },
      {
        id: 'AC4',
        given: 'a receipt I open',
        when: 'its page shows the file',
        then: 'the image comes through a link that works for 5 minutes',
        decided: CLAUDE,
        checks: [
          'api/receipts › shows each model pending while the receipt is read',
          'storage/supabase › signs a short-lived download URL',
        ],
        rules: ['R-IMAGE-LINK'],
      },
      {
        id: 'AC5',
        given: 'the file in storage is not the one described when the receipt was filed',
        when: 'the receipt is read',
        then: 'no model is sent it, and the receipt is marked failed because its file changed',
        decided: ADR_0017,
        checks: [
          'workflows/receipts › reads nothing when the stored file is not the one described',
        ],
      },
      {
        id: 'AC6',
        given: 'a receipt in another organization',
        when: 'one of our members asks for it',
        then: 'it is not found',
        decided: ARCH_69,
        checks: ['db/receipts.int › keeps receipts inside their organization'],
      },
      {
        id: 'AC7',
        given: 'someone who is not signed in',
        when: 'they ask for an upload, a receipt or its file',
        then: 'they are refused',
        decided: CLAUDE,
        checks: [
          'e2e/receipts › refuses the receipt endpoints without a signed-in user',
          'api/receipts › needs storage, a signed-in user and an organization',
        ],
      },
    ],
    note: 'A link works for anyone who holds it until it expires. Only the receipt’s own member, and owners, finance admins and auditors, can open a receipt to get one (US-SEC-14).',
  },
  {
    id: 'US-SEC-07',
    title: 'Treat every receipt as untrusted',
    as: 'Sam, a finance admin, who relies on what the app reads from receipts',
    want: 'the AI models that read receipts to be able to do nothing but return a reading in our format',
    soThat: 'text printed on a receipt can never make the app do something, only be read',
    feature: 'F-06',
    requirements: ['NFR-SEC-07'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt sent to a Claude model, or to the fallback reader',
        when: 'the request is made',
        then: 'it sets the exact shape the answer must take: our receipt schema',
        decided: ARCH_65,
        checks: [
          'extraction/claude › sends the image, the schema and the tier effort, and prices the call',
          'extraction/openai › sends the image, the strict schema and the effort, stores nothing, and prices the call',
        ],
      },
      {
        id: 'AC2',
        given: 'that request',
        when: 'it is sent',
        then: 'it offers the model no tools, so nothing a receipt says can make it act',
        decided: ARCH_65,
        checks: [
          'extraction/no-tools › offers Claude no tools',
          'extraction/no-tools › offers OpenAI no tools',
          'extraction/no-tools › is built for every addition, on, off and left out',
          'extraction/no-tools › finds a tool wherever one is added, so the checks above can fail',
        ],
      },
      {
        id: 'AC3',
        given: 'an answer that doesn’t fit the schema, such as plain text or data of another shape',
        when: 'it comes back',
        then: 'it is recorded as an invalid reading, and nothing from it is filed',
        decided: ARCH_65,
        checks: [
          'extraction/openai › text that is not JSON',
          'extraction/openai › JSON that is not a receipt',
        ],
      },
    ],
    note: 'Since PR #60 (#38, GAP-15 closed) every request a reader can build is checked as it leaves for Anthropic or OpenAI: every model, with source lines and journeys each on, off and left out, a photo and a PDF. A tool, a tool choice, a function or any new field fails CI, and a new kind of addition fails to compile in the test until it is checked too.',
  },
  {
    id: 'US-SEC-08',
    title: 'Have the browser guard every page',
    as: 'the product owner, who runs ExpenseWise',
    want: 'every page and API answer to tell the browser how to protect it',
    soThat:
      'another site can’t frame our screens to trick someone, and a file can’t be passed off as something else',
    feature: 'F-29',
    requirements: ['NFR-SEC-08'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'any page or API answer',
        when: 'a browser receives it',
        then: 'it is told never to show it inside another site’s frame and not to guess a file’s type from its contents, and the answer doesn’t name the framework behind it',
        decided: CLAUDE,
        checks: ['e2e/shell › sends security headers'],
      },
      {
        id: 'AC2',
        given: 'any page',
        when: 'it asks for the camera',
        then: 'only ExpenseWise’s own pages may use it',
        decided: CLAUDE,
        checks: ['e2e/shell › sends security headers'],
      },
      {
        id: 'AC3',
        given: 'any page or API answer',
        when: 'a browser receives it',
        then: 'it is told to use only HTTPS for this site and its subdomains, for two years',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC4',
        given: 'any page',
        when: 'a browser receives it',
        then: 'no page may use the microphone or location, and a link to another site passes on only which site it came from, not the page',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
    ],
  },
  {
    id: 'US-SEC-09',
    title: 'Accept only sign-ins our own project issued',
    as: 'the product owner, who runs ExpenseWise',
    want: 'the API to accept a sign-in only when Supabase signed it for our project, with keys it publishes',
    soThat: 'nobody can forge a sign-in, and the server holds no secret that could sign one',
    feature: 'F-01',
    requirements: ['NFR-SEC-09'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given:
          'a sign-in token signed with our project’s published keys, issued by our project to a signed-in person',
        when: 'the app calls the API with it',
        then: 'the API knows who it is',
        decided: ADR_0013,
        checks: ['api/auth › returns the identity proven by a valid token'],
      },
      {
        id: 'AC2',
        given: 'a token signed with a shared secret, the older kind',
        when: 'it reaches the API',
        then: 'it is refused, so the server needs no signing secret at all',
        decided: ADR_0013,
        checks: [
          'api/auth › rejects shared-secret (HS256) tokens: this backend holds no signing secret',
        ],
      },
      {
        id: 'AC3',
        given:
          'a token signed by another key, issued by another project, meant for another audience, or from an anonymous sign-in',
        when: 'it reaches the API',
        then: 'it is refused',
        decided: ADR_0013,
        checks: [
          'api/auth › a token signed by another key',
          'api/auth › a token from another project',
          'api/auth › a token for another audience',
          'api/auth › an anonymous sign-in',
        ],
      },
      {
        id: 'AC4',
        given: 'an expired token',
        when: 'it reaches the API',
        then: 'it is refused, and the app is told it has expired',
        decided: CLAUDE,
        checks: ['api/auth › distinguishes an expired token'],
      },
      {
        id: 'AC5',
        given: 'no token',
        when: 'someone calls a part of the API that needs a sign-in',
        then: 'they are asked to sign in',
        decided: CLAUDE,
        checks: ['api/auth › asks for a token when none is sent'],
      },
    ],
  },
  {
    id: 'US-SEC-10',
    title: 'Let in only the people I add',
    as: 'the organization’s owner',
    want: 'only people whose accounts I create to be able to sign in',
    soThat: 'a stranger can’t make an account and start using ExpenseWise',
    feature: 'F-01',
    requirements: ['NFR-SEC-10'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'someone without an account',
        when: 'they try to create one',
        then: 'they can’t: sign-ups are off in Supabase, and the Sign in page offers no way to make an account',
        decided: { by: 'blueprint', source: 'D-15' },
        checks: [],
        untested: 66,
      },
      {
        id: 'AC2',
        given: 'someone signing in for the first time who belongs to no organization',
        when: 'the app opens',
        then: 'it makes them a one-person organization of their own, with them as its owner, records that in the audit trail, and shows them nothing of anyone else’s',
        decided: CLAUDE,
        checks: [
          'db/ai-keys.int › creates a one-person organization with the user as owner, and an audit event',
          'api/workspace › creates the organization on first sign-in, then returns it',
        ],
      },
      {
        id: 'AC3',
        given: 'a visitor who is not signed in',
        when: 'they open Receipts or Settings, or call the API',
        then: 'they are asked to sign in and shown nothing',
        decided: CLAUDE,
        checks: [
          'e2e/receipts › asks a signed-out visitor to sign in before showing any receipts',
          'e2e/settings › asks a signed-out visitor to sign in before showing any keys',
          'e2e/receipts › refuses the receipt endpoints without a signed-in user',
        ],
      },
    ],
    note: 'Sign-ups were turned off by hand in the Supabase dashboard, and nothing checks the setting. With Invite people switched on (F-23), the owner makes the person’s account, then sends them a link to join the owner’s organization (US-TEAM-01); without it, the person gets an organization of their own.',
  },
  {
    id: 'US-SEC-11',
    title: 'Encrypt and verify the connection to the database',
    as: 'the product owner, who runs ExpenseWise',
    want: 'every connection to the database to be encrypted and to prove it has reached Supabase',
    soThat: 'nobody between the app and the database can read or change our data',
    feature: 'F-30',
    requirements: ['NFR-SEC-11'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'the database is on Supabase',
        when: 'the app connects',
        then: 'the connection is encrypted and checked against Supabase’s root certificate, which ships with the app, whatever the connection string says about encryption',
        decided: CLAUDE,
        checks: [
          'db/connection › verifies Supabase hosts against the Supabase root CA and drops URL ssl params',
        ],
      },
      {
        id: 'AC2',
        given: 'a connection to Supabase',
        when: 'the readiness check runs',
        then: 'its encryption check passes',
        decided: CLAUDE,
        checks: [
          'db/readiness › passes for Supabase, which is verified against its root certificate',
        ],
      },
      {
        id: 'AC3',
        given: 'a database on any other host, whose certificate isn’t checked',
        when: 'the readiness check runs',
        then: 'it reports not ready; a database on the same machine, as in development, is skipped',
        decided: CLAUDE,
        checks: ['db/readiness › skips a local database and fails any other unverified host'],
      },
    ],
  },
  {
    id: 'US-SEC-12',
    title: 'Catch known weaknesses before they merge',
    as: 'an auditor, who checks how changes are kept safe',
    want: 'every change scanned for leaked secrets, vulnerable dependencies and unsafe code before it merges',
    soThat: 'a known weakness is caught by a machine, not found later in production',
    feature: 'F-35',
    requirements: ['NFR-SEC-12'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a pull request, or a push to main',
        when: 'CI runs',
        then: 'the Security check scans its commits for secrets and fails on one',
        decided: DELIVERY_74,
        checks: ['ci:security'],
      },
      {
        id: 'AC2',
        given: 'a dependency with a high or critical advisory',
        when: 'CI runs',
        then: 'the dependency audit fails the Security check',
        decided: DELIVERY_74,
        checks: ['ci:security'],
      },
      {
        id: 'AC3',
        given: 'a pull request, or a push to main',
        when: 'CI runs',
        then: 'CodeQL analyses the code with GitHub’s security and quality queries',
        decided: DELIVERY_74,
        checks: ['ci:codeql'],
      },
      {
        id: 'AC4',
        given:
          'an advisory with no fixed version, which reaches only the tools that check our code and never the app',
        when: 'the product owner lets it through',
        then: 'the audit ignores that one advisory and still fails on any other, and the exception is recorded as a gap',
        decided: { by: 'owner', source: 'owner 2026-10-03' },
        checks: ['ci:security'],
      },
      {
        id: 'AC5',
        given: 'an advisory let through',
        when: 'Advisory watch runs each Monday',
        then: 'it fails once a fixed version exists, so the dependency is updated and the exception removed',
        decided: CLAUDE,
        checks: [],
        untested: 66,
      },
    ],
    note: 'CI runs on every pull request and every push to main, not on a push to a branch with no pull request. Whether a failed check stops a merge is a GitHub branch setting, which nothing here checks. The blueprint’s Security gate also names a license check and a nightly run; neither exists, and CodeQL runs again every Monday. One advisory is let through today (GAP-19, #49).',
  },
  {
    id: 'US-SEC-13',
    title: 'Keep production’s keys out of preview builds',
    as: 'the product owner, who runs ExpenseWise',
    want: 'preview builds of unreviewed branches to hold none of production’s credentials',
    soThat: 'code nobody has reviewed can’t read our data or our receipts',
    requirements: ['NFR-SEC-13'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a preview build of a branch',
        when: 'it runs',
        then: 'it has no database address and no Supabase secret key, so it can reach no data and no receipt file',
        decided: DELIVERY_73,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC2',
        given: 'production',
        when: 'a page is sent to a browser',
        then: 'it carries only the publishable Supabase key, never the secret key or the database address',
        decided: DELIVERY_73,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Since Oct 3 Vercel holds the database address and the Supabase secret key for Production only (GAP-02). Vercel’s scoping enforces it, and nothing automated checks the scoping.',
  },
  {
    id: 'US-PRV-01',
    title: 'Keep no more about me than a receipt needs',
    as: 'Alex, who travels for work and photographs receipts on the road',
    want: 'the app to keep only the last four digits of my card, and none of my photos’ location',
    soThat: 'my receipts don’t become a record of my card number or of where I have been',
    requirements: ['NFR-PRV-02', 'NFR-PRV-03'],
    status: 'Partial',
    criteria: [
      {
        id: 'AC1',
        given: 'a receipt that shows the card it was paid with',
        when: 'the models read it',
        then: 'they are asked for the card’s last four digits only, which the receipt page shows as Card',
        decided: ARCH_69,
        checks: [],
        untested: 66,
      },
      {
        id: 'AC2',
        given: 'a model answers with anything but exactly four digits for the card',
        when: 'its reading is checked',
        then: 'the card is left blank on the receipt and marked as not read',
        decided: CLAUDE,
        checks: [
          'extraction/normalize › flags values it cannot read instead of rounding or guessing',
        ],
      },
      {
        id: 'AC3',
        given: 'I take or choose a photo in Capture',
        when: 'it is uploaded',
        then: 'the browser first redraws it as a new picture, so its location and other camera details never leave my phone',
        decided: ADR_0017,
        checks: [],
        untested: 66,
      },
    ],
    note: 'Each model’s answer is also stored as it came back, and the schema asks for four digits without enforcing them, so a model that returned more would have them kept there. A PDF is stored as it is, with its own details. A photo the browser can’t redraw is sent unchanged if it is a JPEG, PNG, WebP or GIF, and a photo emailed in is stored as it arrived, location included.',
  },
  {
    id: 'US-PRV-02',
    title: 'Send a receipt to OpenAI only when Claude can’t read it',
    as: 'the organization’s owner',
    want: 'a receipt to go to OpenAI only when neither Claude model could read it, and only if we saved an OpenAI key',
    soThat: 'as few vendors as possible see our receipts',
    feature: 'F-08',
    requirements: ['NFR-PRV-04'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'at least one Claude model read the receipt',
        when: 'reading finishes',
        then: 'nothing is sent to OpenAI',
        decided: ADR_0020,
        checks: [
          'workflows/receipts › is not called when a Claude model read the receipt',
          'workflows/receipts › keeps the other reading when the provider rejects one request for good',
        ],
      },
      {
        id: 'AC2',
        given: 'neither Claude model could read the receipt, and we saved an OpenAI key',
        when: 'the fallback reads it',
        then: 'OpenAI reads it once, and the receipt needs a look',
        decided: ADR_0020,
        checks: [
          'workflows/receipts › reads the receipt when Anthropic has no credit, and asks for a look',
        ],
      },
      {
        id: 'AC3',
        given: 'no OpenAI key is saved',
        when: 'no Claude model can read the receipt either',
        then: 'nothing is sent to OpenAI, and the receipt is marked failed',
        decided: ADR_0020,
        checks: [
          'workflows/receipts › records a missing key as a failed reading, and calls no model',
        ],
      },
      {
        id: 'AC4',
        given: 'the fallback reads a receipt',
        when: 'the request is made',
        then: 'it tells OpenAI not to store the response',
        decided: { by: 'claude', source: 'ADR-0020' },
        checks: [
          'extraction/openai › sends the image, the strict schema and the effort, stores nothing, and prices the call',
        ],
      },
    ],
    note: 'What OpenAI keeps of a request beyond that is set by its own terms, which GAP-13 and Q3 are about.',
  },
  {
    id: 'US-PRV-03',
    title: 'Bind every vendor that sees our receipts to protect them',
    as: 'the organization’s owner',
    want: 'every vendor that sees our receipts or personal data to be bound by a data processing agreement',
    soThat: 'each one is held to protect what it sees, as tax evidence and personal data deserve',
    requirements: ['NFR-PRV-04'],
    status: 'Planned',
    criteria: [
      {
        id: 'AC1',
        given: 'a vendor that sees our receipts or personal data',
        when: 'it handles them',
        then: 'it does so under a data processing agreement',
        decided: { by: 'blueprint', source: 'ADR-0010' },
        checks: [],
      },
    ],
    note: 'Unconfirmed (GAP-13, #36): Q3 asks whether each vendor’s standard terms are enough for Phase 1. Supabase, Vercel, Inngest and Anthropic see receipts, and OpenAI on the fallback path. Bird, which receives emailed receipts (ADR-0026), sees them too, and GAP-13 does not name it yet.',
  },
  {
    id: 'US-SEC-14',
    title: 'Keep my receipts, expenses and trips to me inside a team',
    as: 'Sam, who files expenses in a team',
    want: 'no one in my organization who is a member or approver to see or change my receipts, expenses, trips or reports',
    soThat: 'joining a team doesn’t show my colleagues my spending, or let them change my claims',
    feature: 'F-61',
    requirements: ['FR-GOV-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'two members of one organization, each with receipts, expenses and trips',
        when: 'one opens Receipts, Expenses or Trips, or opens one of the other’s by its link',
        then: 'they see only their own, and the other’s is not found',
        decided: OWNER_OCT_4,
        checks: [
          "api/own-records.int › can't see each other's receipts, expenses or trips",
          "db/own-records.int › can't see another member's receipts, expenses or trips, or their readings",
        ],
      },
      {
        id: 'AC2',
        given: 'two members of one organization',
        when: 'one tries to change or delete the other’s trip, expense or receipt, or to make one in the other’s name',
        then: 'nothing changes: the app answers as if it weren’t there, and the database refuses it even if the app didn’t',
        decided: OWNER_OCT_4,
        checks: [
          "api/own-records.int › can't change each other's receipts, expenses or trips",
          "db/own-records.int › can't change, delete or file another member's records",
        ],
      },
      {
        id: 'AC3',
        given:
          'what hangs off my records: each receipt’s readings, my reports, and my duplicate pairs, confirmations, mileage and emails',
        when: 'a colleague who is a member or approver reads the organization’s data',
        then: 'those are kept to me too',
        decided: CLAUDE,
        checks: [
          "db/own-records.int › can't see another member's receipts, expenses or trips, or their readings",
          'db/own-records.int › keeps reports to their member too',
          'db/own-records.int › keeps every table of a member’s records to that member, for reading and changing',
        ],
      },
      {
        id: 'AC4',
        given: 'a file a colleague already filed',
        when: 'I file the same file',
        then: 'it is refused, since a file is claimed once in an organization, and I am not shown their receipt',
        decided: CLAUDE,
        checks: [
          'api/own-records.int › refuses the same file a colleague filed, without showing theirs',
        ],
      },
      {
        id: 'AC5',
        given: 'an organization of one person',
        when: 'its owner captures, edits and deletes',
        then: 'everything works as it did before',
        decided: CLAUDE,
        checks: [
          'db/own-records.int › works for its owner as it did before',
          'api/own-records.int › works for its owner as before, and joining another replaces it while it is empty',
        ],
      },
      {
        id: 'AC6',
        given: 'an approver, while approval isn’t built (#24) and no report is routed to them',
        when: 'they work in the app',
        then: 'they see and change only their own records, as a member does',
        decided: CLAUDE,
        checks: [
          "db/own-records.int › can't see another member's receipts, expenses or trips, or their readings",
        ],
      },
    ],
    note: 'Your choice of Oct 4: #50 before anyone is invited (GAP-20). Approvers see the reports they approve once approval routes them (#24).',
  },
  {
    id: 'US-SEC-15',
    title: 'Let owners and finance admins see everyone’s records, and change only their own',
    as: 'Jordan, the finance admin',
    want: 'to open any member’s receipt, expense or trip, while changing only my own',
    soThat:
      'I can check the team’s spending without being able to change what someone else claimed',
    feature: 'F-61',
    requirements: ['FR-GOV-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'a finance admin or an owner',
        when: 'they open any member’s receipt, expense or trip by its link',
        then: 'they see it',
        decided: OWNER_OCT_4,
        checks: [
          "api/own-records.int › lets a finance admin open both members' records, and change neither",
          "db/own-records.int › lets a finance admin see both members' records, and change neither",
        ],
      },
      {
        id: 'AC2',
        given: 'a finance admin or an owner looking at another member’s record',
        when: 'they try to change it',
        then: 'it is refused: they can change only their own records, and nothing changes',
        decided: { by: 'owner', source: 'Q30' },
        checks: [
          "api/own-records.int › lets a finance admin open both members' records, and change neither",
          "db/own-records.int › lets a finance admin see both members' records, and change neither",
          'db/own-records.int › deletes the copy through delete_receipt(), and refuses a finance admin doing it for them',
        ],
      },
      {
        id: 'AC3',
        given: 'anyone, whatever their role',
        when: 'they open Receipts, Expenses or Trips',
        then: 'those list their own records, as Home, Needs you and Reports do',
        decided: { by: 'owner', source: 'Q30' },
        checks: [
          'api/expenses › searches by merchant, dates, amount in any currency, and trip (FR-INS-02)',
          'api/trips › searches by text and dates, and refuses a date that does not exist',
          "api/own-records.int › lets a finance admin open both members' records, and change neither",
        ],
      },
    ],
    note: 'Your answer to Q30: owners and finance admins see everyone’s records and change only their own; a list of everyone’s waits until the first team approves reports. Today an owner who opens a colleague’s record still sees its buttons, and the server refuses them.',
  },
  {
    id: 'US-SEC-16',
    title: 'Let an auditor read everything and change nothing',
    as: 'an auditor, who checks the organization’s spending',
    want: 'to read every member’s receipts, expenses, trips and reports',
    soThat: 'I can audit the organization with no chance of changing what I audit',
    feature: 'F-61',
    requirements: ['FR-GOV-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'an auditor',
        when: 'they open any member’s records',
        then: 'they can read them',
        decided: OWNER_OCT_4,
        checks: [
          'api/own-records.int › lets an auditor read every record and change nothing',
          'db/own-records.int › lets an auditor read every record and change nothing, not even their own',
        ],
      },
      {
        id: 'AC2',
        given: 'an auditor',
        when: 'they try to change any record, or to make one of their own, such as a trip or a receipt',
        then: 'it is refused',
        decided: ARCH_69,
        checks: [
          'api/own-records.int › lets an auditor read every record and change nothing',
          'db/own-records.int › lets an auditor read every record and change nothing, not even their own',
        ],
      },
    ],
  },
  {
    id: 'US-SEC-17',
    title: 'Enforce whose records are whose in the database',
    as: 'the product owner, who runs ExpenseWise',
    want: 'the database itself to keep each member to what their role allows, for every request a member makes',
    soThat:
      'a route that forgets to check, today or in a later change, still can’t show or change a colleague’s records',
    feature: 'F-61',
    requirements: ['FR-GOV-01'],
    status: 'Delivered',
    criteria: [
      {
        id: 'AC1',
        given: 'any request a member makes',
        when: 'it reads or changes receipts, expenses, trips or reports',
        then: 'it does so as that member, and the database applies their role',
        decided: ADR_0035,
        checks: [
          "api/own-records.int › can't see each other's receipts, expenses or trips",
          'db/own-records.int › refuses a member that is not a member id and role',
        ],
      },
      {
        id: 'AC2',
        given: 'background work, such as reading a receipt or closing reports on day 28',
        when: 'it runs',
        then: 'it acts for the system and sees and changes every member’s records in its organization, as before',
        decided: ADR_0035,
        checks: [
          'db/own-records.int › acts for the system, as workflows do, when no member is named',
          'db/own-records.int › acts for the system again after moving to an organization',
        ],
      },
      {
        id: 'AC3',
        given: 'a table that holds a member’s records, by its member column, or hangs off one',
        when: 'the tests run',
        then: 'they fail unless the table keeps members to their own, for reading and for changing',
        decided: ADR_0035,
        checks: [
          'db/own-records.int › keeps every table of a member’s records to that member, for reading and changing',
        ],
      },
      {
        id: 'AC4',
        given: 'a change the database refuses',
        when: 'it was asked for',
        then: 'the whole change, its audit event included, is undone, and the app answers that you can change only your own records',
        decided: ADR_0035,
        checks: [
          "api/own-records.int › lets a finance admin open both members' records, and change neither",
          "db/own-records.int › lets a finance admin see both members' records, and change neither",
        ],
      },
    ],
    note: 'The audit trail and the outbox are kept to the organization, not to each member, because every member’s change reads the trail to chain its event (GAP-31, #74). No screen shows either to a member.',
  },
];
