import type { BacklogItem } from './model.ts';

/**
 * Open work, ranked. Numbers are permanent: a closed item keeps its number in Done. Edit
 * here; the backlog page is generated from this file and republished only after a
 * successful release, so it always describes what is live.
 */
export const BACKLOG: readonly BacklogItem[] = [
  // P1: next
  {
    num: 1,
    title: 'Production holds real receipts, and nothing backs them up',
    type: 'Ops',
    detail:
      'Supabase’s Free plan keeps no backups. Build the nightly job from ADR-0014: an encrypted dump of the database (auth users included) and new receipt images to Backblaze B2, a heartbeat so the project never pauses, and alerts at 70% of the 500 MB and 1 GB limits. It can be built and tested now; it first runs once #2 is done.',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none', note: 'None to build it; it runs once #2 is done' },
    source: 'GAP-01, ADR-0014',
    affects: ['GAP-01', 'NFR-REL-01', 'NFR-REL-05', 'F-37', 'F-42'],
    done: { date: '2026-10-02', in: 'PR #23' },
  },
  {
    num: 2,
    title: 'The backup has nowhere to go yet',
    type: 'Ops',
    detail:
      'The backup is built (#1). Runbook section 5: the Backblaze account and bucket key are done; still to do are the backup passphrase in your password manager, a Supabase S3 key, and the GitHub environment `backup` with its seven secrets. Then run **Nightly backup** once from Actions (step 8). Never paste a key into the conversation.',
    priority: 'P1',
    effort: 'S',
    severity: 'High',
    blocker: {
      kind: 'owner',
      ask: 'Your setup: runbook section 5, steps 5–8, about 15 minutes',
    },
    source: 'ADR-0014',
    affects: ['GAP-01', 'NFR-REL-01', 'NFR-REL-05', 'F-37', 'F-42'],
    done: {
      date: '2026-10-03',
      in: 'Your setup; the first run backed up 51 tables and the receipt image',
    },
  },
  {
    num: 5,
    title: 'The OpenAI fallback waits on your merge',
    type: 'Feature',
    detail:
      'PR #20: when neither Claude model can read a receipt, GPT-5.6 Luna reads it once on your OpenAI key, and the receipt Needs a look (ADR-0020).',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your word on PR #20: merge' },
    source: 'PR #20',
    affects: ['FR-INT-09', 'F-08'],
    done: { date: '2026-10-02', in: 'PR #20' },
  },
  {
    num: 46,
    title: 'The fallback hasn’t read a real receipt yet',
    type: 'Verify',
    detail:
      'The OpenAI reader was tested against stand-in answers only, to spend nothing on your key. Upload one receipt while Anthropic still has no credit: it should come back as Needs a look with a GPT-5.6 Luna column. If OpenAI rejects the request, its own message shows on the receipt and I fix it. Your OpenAI account needs credit. Do this before #4, or Claude reads it instead.',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your test: upload one receipt before buying Anthropic credit' },
    source: 'PR #20',
    affects: ['FR-INT-09', 'F-08'],
    done: { date: '2026-10-02', in: 'Your test: a photographed receipt, read by GPT-5.6 Luna' },
  },
  {
    num: 47,
    title: 'A receipt that needs a look is a dead end',
    type: 'Gap',
    detail:
      'The receipt page says Needs a look and offers only Read again. Add the two actions from the receipt review design: **Looks right**, which confirms a reading as it is (choosing which one, when the readings differ), and **Edit a field**. Either makes the receipt Ready, records who confirmed what in the audit trail, and keeps each correction as an eval candidate. Every fallback reading lands here by design (ADR-0020), so this matters more while Anthropic has no credit.',
    priority: 'P1',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-17, your observation on Oct 2',
    affects: ['GAP-17', 'FR-INT-15', 'F-40'],
    done: { date: '2026-10-03', in: 'PR #26' },
  },
  {
    num: 6,
    title: 'Ready readings don’t become expenses',
    type: 'Feature',
    detail:
      'Increment 1 ends when a receipt is filed as an expense within 30 seconds. The expense table, its lifecycle and the money rules exist; the step that turns a settled reading into a Ready or Needs-review expense, with an audit event, does not. Your rules (Oct 3): the receipt stays linked as the expense’s proof, and the expense can be edited once it exists (FR-EXP-08, FR-EXP-09).',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 1',
    affects: ['FR-EXP-01', 'FR-EXP-03', 'FR-EXP-08', 'FR-EXP-09', 'NFR-UX-04', 'F-09'],
    done: { date: '2026-10-03', in: 'PR #28' },
  },
  {
    num: 16,
    title: 'Trips, trip history and search',
    type: 'Feature',
    detail:
      'Trips with dates and a purpose; expenses file to the trip whose dates they fall in; past trips can be browsed and searched. Raised to P1 on Oct 3 at your direction. It needs expenses to exist first (#6).',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 2',
    affects: ['FR-EXP-01', 'FR-EXP-04', 'FR-INS-02', 'F-12'],
    done: { date: '2026-10-03', in: 'PR #30' },
  },
  {
    num: 10,
    title: 'No backup has ever been restored',
    type: 'Ops',
    detail:
      'A backup nobody has restored is only a hope. The monthly drill (PR #35, F-41) restored production’s backup on Oct 3 at your request and every check passed: 50 tables and 137 rows, migrations, schema, isolation and all 6 receipt images, in 1 min 11 s. It runs again on the 2nd of each month.',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none' },
    source: 'ADR-0014',
    affects: ['NFR-REL-02', 'NFR-REL-03', 'F-41'],
    done: { date: '2026-10-03', in: 'PR #35' },
  },
  {
    num: 3,
    title: 'Preview builds hold production credentials',
    type: 'Security',
    detail:
      '`DATABASE_URL` and `SUPABASE_SECRET_KEY` are set for Preview as well as Production, so every branch push builds unreviewed code that could read production data and every stored receipt. Previews sit behind Vercel’s sign-in, which limits the damage. Untick Preview on both. CI tests against its own database, so nothing is lost; previews get data again with staging (#30).',
    priority: 'P1',
    effort: 'S',
    severity: 'High',
    blocker: { kind: 'owner', ask: 'Your go-ahead, or five minutes in Vercel' },
    source: 'GAP-02',
    affects: ['GAP-02', 'NFR-SEC-13'],
    done: {
      date: '2026-10-03',
      in: 'Your change in Vercel; both now target Production only (read Oct 3, names and targets only)',
    },
  },
  {
    num: 7,
    title: 'Sums and dates aren’t checked before Ready',
    type: 'Gap',
    detail:
      'Add the guardrail from journeys §4.6: subtotal, taxes and tip must reconcile with the total within a cent per line, and the date must not be in the future or implausibly old. A failure makes the receipt Need a look and says why.',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-04',
    affects: ['GAP-04', 'FR-INT-04'],
    done: { date: '2026-10-03', in: 'PR #40' },
  },
  {
    num: 8,
    title: 'Sign-in has no second factor',
    type: 'Security',
    detail:
      'Real financial records sit behind a password alone. Add TOTP enrollment and the challenge at sign-in, and require `aal2` for approving someone else’s spend and for admin actions. Increment 1 planned it.',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none' },
    source: 'GAP-03, roadmap increment 1',
    affects: ['GAP-03', 'FR-PLT-03', 'FR-GOV-04', 'F-11'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 9,
    title: 'The Needs you inbox shows nothing',
    type: 'Feature',
    detail:
      'Home has the inbox layout and an empty state only. Start with what exists: receipts that need a look or failed, each with its reason and one action. Missing receipts and returned reports join as trips and reports arrive; a returned report lists each rejected expense with why (FR-GOV-12).',
    priority: 'P1',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 1, design DP2',
    affects: ['FR-EXP-02', 'FR-GOV-12', 'F-10'],
    done: {
      date: '2026-10-03',
      in: 'PR #41; returned reports join it with #24, missing receipts with card transactions',
    },
  },

  {
    num: 54,
    title: 'Check every signed-in screen in CI',
    type: 'Gap',
    detail:
      'Gate G5 saw only sign-in prompts (GAP-21). Now a bench runs the real API on its own database with a test sign-in, seeded through the real reading workflow, and every signed-in screen is opened in each state, at 375, 393, 440 and 1280 px in light and dark: nothing off-screen or overlapping, values not cut off, no date field drawn natively, targets big enough to tap, and WCAG 2.2 AA. Real iOS Safari is #57.',
    priority: 'P1',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-21',
    affects: ['GAP-21', 'NFR-UX-01', 'NFR-UX-02'],
    done: { date: '2026-10-03', in: 'PR #38' },
  },
  {
    num: 57,
    title: 'Check changed screens on iOS Safari',
    type: 'Gap',
    detail:
      'Gate G5’s iPhone engine is WebKit on Linux, not iOS Safari (GAP-22). Until something better, a changed screen is checked on an iPhone in production right after its release (your answer to Q13, ADR-0025), as the pull request template asks. A device cloud (BrowserStack, Sauce Labs) would run the signed-in checks on real iPhones for a monthly fee: worth it once more than one person relies on the app.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'owner', ask: 'Whether a device cloud is worth paying for, and when' },
    source: 'GAP-22',
    affects: ['GAP-22', 'NFR-UX-02'],
  },

  {
    num: 65,
    title: 'Detailed requirements as user stories with acceptance criteria',
    type: 'Gap',
    detail:
      'Your request of Oct 4 (GAP-24). Add user stories to these records, each with numbered Given/When/Then acceptance criteria, each criterion marked as decided by you or assumed by Claude and traced to the test that proves it or shown as untested; a register of the numbers the rules share (28 days, 30 minutes, 500 characters…); integrity checks that refuse a delivered story whose criteria no test covers; and a fifth published page. Then write the stories for everything delivered, starting with duplicates and expense reports, and for what is planned. Untested criteria found on the way become backlog items.',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['GAP-24', 'NFR-DEL-09', 'F-53'],
    done: { date: '2026-10-04', in: 'PR #57' },
  },
  {
    num: 67,
    title: 'Error reports don’t redact OpenAI keys',
    type: 'Security',
    detail:
      'Found writing the user stories (#65). The scrubber that removes secrets from error-tracking events knows Anthropic keys, bearer tokens and database URLs but has no pattern for an OpenAI key (`sk-proj-…`), and server log lines aren’t scrubbed at all. Error tracking is off today (GAP-07), so nothing has leaked. Add the pattern, scrub log lines the same way, and test both, before error tracking is switched on.',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'US-SEC-05, NFR-SEC-05',
    affects: ['NFR-SEC-05', 'F-32'],
  },
  {
    num: 68,
    title: 'Photos emailed in keep their location',
    type: 'Gap',
    detail:
      'Found writing the user stories (#65), GAP-25. A photo taken in the app or uploaded is redrawn in the browser, which drops its location and other metadata (NFR-PRV-03). A photo attached to an email is stored exactly as it arrived, location included, and so is an image the browser couldn’t decode. Strip the metadata on the server for every image before it is stored, and test it with a photo that carries a location.',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'US-PRV-01, NFR-PRV-03',
    affects: ['GAP-25', 'NFR-PRV-03', 'F-16', 'F-05'],
  },
  {
    num: 69,
    title: 'Requirements that say more than the build does',
    type: 'Gap',
    detail:
      'Found writing the user stories (#65), GAP-26. Each needs either its wording brought to what is built, or the missing part built; Claude proposes which, item by item, for you to choose. FR-CAP-02 promises a personal receipts address; there is one shared address and you are known by your sign-in. FR-INT-03 promises to show the receipt already filed; only an upload refused before it starts opens it, without saying it is a copy. FR-INT-01: line items and document type carry no confidence. FR-INT-06: cache tokens aren’t kept per reading. NFR-AI-03: cost is kept rounded to whole micro-dollars. NFR-AI-04: How the models compare looks at the newest 100 receipts only. FR-EXP-05: a trip joining a report that is still filling up shows on Home and Reports, not in Needs you. FR-INS-01: the Trips figure opens every trip, not this month’s. FR-INS-02: the Expenses screen can’t search by trip. NFR-DAT-01: the lint ban on floats covers only the domain, extraction and evals code. NFR-DAT-03: emailed receipts take UUIDv5 ids by design. FR-GOV-05 and NFR-DAT-05: the hash chain is checked by the tests and, since #26, on screen in Settings › Audit trail, but has no copy outside the database, and the table’s owner can switch the guard off. NFR-DEL-05: only one flag exists; every screen since receipts shipped without one, and the note cites Q5, which you haven’t answered. NFR-UX-04: a move is refused once submitted, before approval. NFR-SEC-08: no test checks HSTS. NFR-SEC-12 and NFR-DEL-01: CI runs on pull requests and on main, not every push, and G4 has no license check. FR-EXP-14: whether a local expense with no reason holds its report open is recorded as both yours and Claude’s.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none', note: 'Claude proposes each change; you choose' },
    source: 'User stories, Oct 4',
    affects: [
      'GAP-26',
      'FR-CAP-02',
      'FR-INT-03',
      'FR-INT-01',
      'FR-INT-06',
      'NFR-AI-03',
      'NFR-AI-04',
      'FR-EXP-05',
      'FR-INS-01',
      'FR-INS-02',
      'NFR-DAT-01',
      'NFR-DAT-03',
      'FR-GOV-05',
      'NFR-DAT-05',
      'NFR-DEL-05',
      'NFR-UX-04',
      'NFR-SEC-08',
      'NFR-SEC-12',
      'NFR-DEL-01',
      'FR-EXP-14',
    ],
  },

  {
    num: 66,
    title: 'Tests for the acceptance criteria no test proves yet',
    type: 'Verify',
    detail:
      'Writing the user stories (#65) lists every acceptance criterion of a built story that no automated test proves; the stories page shows each one against this item. Add a test for each, most of them end-to-end steps through a screen, such as the one-tap Delete the copy and Replace the earlier one on a duplicate, and mark the story Delivered.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'NFR-DEL-09',
    affects: ['NFR-DEL-09', 'F-53'],
  },

  // P2: this month
  {
    num: 79,
    title: 'Read where a journey went, and a hotel stay’s nights',
    type: 'Feature',
    detail:
      'Your requirement of Oct 4. A ride receipt reads its pickup and drop-off, an airline ticket its origin and destination, a rail ticket its stations (your answer to Q39); a hotel folio reads its check-in and check-out dates and works out the nights. Each shows on the expense. A new reading version asks for them, a few output tokens more a reading; receipts already read gain them when read again.',
    priority: 'P2',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['FR-INT-20', 'FR-INT-21', 'F-54'],
    done: { date: '2026-10-04', in: 'PR #59' },
  },
  {
    num: 83,
    title: 'Show a journey’s from and to and a stay’s nights in a report’s export',
    type: 'Feature',
    detail:
      'Follows #79. A journey and a stay show on the expense, but a report’s CSV and PDF don’t carry them yet: the export’s columns were being changed for splits (#81) at the same time, so they were left for after. Two columns, From and to, and Stay, only when a report has one, so every other report exports as before.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Claude, building #79',
    affects: ['FR-INT-20', 'FR-INT-21', 'FR-SET-01', 'F-54'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 84,
    title: 'Run the eval set against the models',
    type: 'Gap',
    detail:
      'The eval harness has never read a receipt with a model (GAP-32), so accuracy by layer is unmeasured. Run it once on the public, synthetic and real-capture layers and report each, with the spend estimated before it starts and nothing spent without your approval. Receipt images and eval data stay out of git.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'owner', ask: 'Your approval of a run’s spend, estimated first' },
    source: 'GAP-32',
    affects: ['GAP-32', 'NFR-AI-01', 'NFR-AI-04'],
  },
  {
    num: 85,
    title: 'Refuse a session that skipped the code everywhere, not only for admin actions',
    type: 'Security',
    detail:
      'The second factor (#8) asks for the code at sign-in in the app, and the API refuses admin actions and approving at aal1, but a token from a password alone, used directly, still reads the person’s records, changes their own and links another sign-in (GAP-33). Have the API know who has a verified authenticator, through an owner-run function over Supabase’s factors or a record of our own kept as they enroll, and refuse aal1 for them on every request while the organization has the second factor on; linking a sign-in needs aal2 too. Your answer to Q41.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-33, Claude, building #8',
    affects: ['GAP-33', 'FR-PLT-03', 'F-11'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 80,
    title: 'Show a receipt’s itemized lines under the total',
    type: 'Feature',
    detail:
      'Your requirement of Oct 4. The lines the reading already holds show in an expandable section under the expense’s total, each with its amount. The view the split (#81) and exclusions (#82) work in.',
    priority: 'P2',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['FR-INT-22', 'F-55'],
    done: { date: '2026-10-04', in: 'PR #59' },
  },
  {
    num: 81,
    title: 'Split an expense into parts by category and type',
    type: 'Feature',
    detail:
      'Your requirement of Oct 4 and your answers to Q35 to Q37: one expense with one receipt, made of parts, each with a category, type and amount; from itemized lines where it has them, each line given a category and type, or by amounts where it doesn’t; tax and service charges spread across the other lines in proportion, in whole cents, the largest share taking any cent left over. The parts always add up to the claim. Reports and exports total by category and type.',
    priority: 'P2',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['FR-EXP-15', 'FR-EXP-06', 'F-55'],
    done: { date: '2026-10-04', in: 'PR #59' },
  },
  {
    num: 82,
    title: 'Exclude a line from reimbursement, with its reason',
    type: 'Feature',
    detail:
      'Your requirement of Oct 4 and your answer to Q38: in the itemized view, include or exclude each line. An excluded line takes a reason (personal, paid by someone else, not reimbursable, other) and an optional note, needed for other; the claim drops by the line and its share of tax and service charges (Q37), and a reviewer sees each excluded line and why. This is how an expense claims less than its receipt with a reason (FR-EXP-10, Q6).',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['FR-EXP-16', 'FR-EXP-10', 'F-55'],
    done: { date: '2026-10-04', in: 'PR #59' },
  },
  {
    num: 11,
    title: 'The outbox relay isn’t running',
    type: 'Ops',
    detail:
      '`RELAY_DATABASE_URL` is not set, so the relay is not registered and a failed eager send waits for Read again. Add it in Vercel for Production: the same address as `DATABASE_URL`, with the `expensewise_relay` user and its password (runbook section 6).',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your action: one setting in Vercel' },
    source: 'GAP-05',
    affects: ['GAP-05', 'NFR-DAT-07', 'F-33'],
  },
  {
    num: 12,
    title: 'Nothing finds a receipt stuck in Reading',
    type: 'Gap',
    detail:
      'An hourly workflow that finds receipts left in Reading for more than ten minutes, settles them from what was stored or reads them again, and reports how many. It makes the “receipt never lost” SLO measurable.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-06',
    affects: ['GAP-06', 'NFR-DAT-07'],
  },
  {
    num: 13,
    title: 'Errors go nowhere anyone looks',
    type: 'Ops',
    detail:
      'Error tracking is built, with secrets redacted, but `NEXT_PUBLIC_SENTRY_DSN` is not set. Create a free Sentry project for Next.js and paste its DSN into Vercel.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your action: a Sentry project and its DSN' },
    source: 'GAP-07',
    affects: ['GAP-07', 'NFR-OPS-01', 'F-32'],
  },
  {
    num: 14,
    title: 'Nothing outside the app notices when production is down',
    type: 'Ops',
    detail:
      'A scheduled GitHub Actions workflow that calls `/api/v1/health/ready` every 15 minutes and fails if it isn’t ready. GitHub emails you on a failed run, so it needs no new account.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-08',
    affects: ['GAP-08', 'NFR-REL-04'],
  },
  {
    num: 15,
    title: 'The release script has no test',
    type: 'Gap',
    detail:
      '`promote-production.mjs` decides what goes live and refuses to roll production back past a newer commit. Commit its test with stand-in Vercel and GitHub answers, and run it in G2.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-09',
    affects: ['GAP-09', 'NFR-DEL-03', 'F-36'],
  },
  {
    num: 73,
    title: 'Business miles on Home',
    type: 'Gap',
    detail:
      'Home’s month shows spend, expenses and trips, but not the miles driven for business, which FR-INS-01 asks for once mileage exists. Sum the person’s own drives dated this month and show the figure, opening their drives, behind the expenses.mileage flag. A drive already counts in this month’s spend like any expense.',
    priority: 'P2',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-30',
    affects: ['GAP-30', 'FR-INS-01', 'F-22'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 19,
    title: 'Email-in: receipts and purchase summaries by email',
    type: 'Feature',
    detail:
      'A personal address that takes receipts and purchase summaries, emailed or forwarded, and reads the body and any PDF or image like a receipt. Only mail from the person’s own sign-in addresses is read; anything else is dropped. The only automatic route for travel receipts (ADR-0011). It comes in through Bird, your choice of Oct 3 (ADR-0024), at the agent mailbox jpdf7j4q5ukxcliugqji@inbox.ai with its allowlist on (Q16). The webhook checks Bird’s Standard Webhooks signature and hands the email on; a workflow fetches it as it arrived, proves the sender by a DKIM signature aligned with the From domain, and files each PDF or photo like an upload (ADR-0026). Forwarding by hand works; an automatic forwarding rule keeps the merchant’s From address, so it doesn’t. Reading the body itself, and purchase summaries, is #58.',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 2, ADR-0024, ADR-0026',
    affects: ['FR-CAP-02', 'F-16'],
    done: {
      date: '2026-10-03',
      in: 'PR #44, for attachments; email bodies and purchase summaries are #58',
    },
  },
  {
    num: 58,
    title: 'Email-in: read the body, and purchase summaries',
    type: 'Feature',
    detail:
      'The second half of #19, first at your direction of Oct 3. An email with nothing attached that can be a receipt, such as an Uber, airline or hotel email, is filed as its text laid out as a PDF and read like an upload (ADR-0027). Readings now count fees that are neither tax nor tip, such as a booking fee, so a ride receipt can add up. Your answer to Q10: a purchase summary is marked as one and always waits for review; a receipt in the body follows the photo rule. No email had reached the app before this, so there were none to read again.',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 3 (FR-CAP-02), split from #19',
    affects: ['FR-CAP-02', 'F-16', 'FR-INT-04'],
    done: { date: '2026-10-03', in: 'PR #45' },
  },
  {
    num: 59,
    title: 'Show an email that came but filed nothing',
    type: 'Feature',
    detail:
      'An email from your address that couldn’t be proved, for example one a mail system changed after signing it, or one with nothing in it to read, is kept but shown nowhere. Show it in Needs you with why and what to do: send it from your own mailbox, or attach the receipt. Mail from anyone who isn’t a member stays unrecorded. Built in PR #60 behind `receipts.unfiled-emails`: each such email of yours is in your Needs you after the receipts, with its subject, the address it came from and why in plain words, never its text, with Attach the receipt and Dismiss. Dismissing is yours alone, audited and final; the email stays kept, and it is in the audit trail. One not dismissed leaves Needs you 30 days after it arrived (US-INBOX-02).',
    priority: 'P2',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Split from #58',
    affects: ['FR-CAP-02', 'F-16', 'FR-EXP-02'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 60,
    title: 'Possible duplicates: flag in review, then merge, delete or keep both',
    type: 'Feature',
    detail:
      'Your requirement of Oct 3. Once a receipt is read, compare it with the person’s other receipts: same currency and total, dated within a day, a similar merchant. A match waits in Needs you as a possible duplicate of the other, so it isn’t Ready and isn’t counted twice. Delete: the copy, its readings, its expense and its file go, and the audit trail records what it duplicated. Merge (your answer): choose the primary; the other fills its missing fields, or you pick which fields to take, and the other is then deleted. Not a duplicate: both stay and the pair is never flagged again. Submitted or approved expenses are never deleted. Receipts already filed are checked once when it ships. Repeat forwards of one email could later be caught before reading, to save the two model reads each costs.',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 3',
    affects: ['FR-INT-18', 'F-48', 'FR-EXP-02'],
    done: { date: '2026-10-04', in: 'PR #49' },
  },
  {
    num: 61,
    title: 'Duplicates matched on time and place: exact or possible',
    type: 'Gap',
    detail:
      'Your amendment of Oct 4 (GAP-23). Match on the same vendor, date, time and location; the total may differ, since a tip or an amended receipt changes it. Everything the same, the total too, is a duplicate; a match with another total is a possible duplicate, to merge or replace. Replace keeps the newer receipt and deletes the older, as for an amended receipt. Your answers: until #53, matching stays on the total (Q18); an exact duplicate is deleted with one tap, and a possible one can replace the earlier receipt (Q19). Needs the time and address read from each receipt (#53).',
    priority: 'P1',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['FR-INT-18', 'F-48', 'GAP-23'],
    done: { date: '2026-10-04', in: 'PR #54' },
  },
  {
    num: 20,
    title: 'Route-based mileage',
    type: 'Feature',
    detail:
      'Your go-ahead of Oct 4, with your OpenRouteService account made: the key lives in Settings, checked on save (Q31); each address is sent as typed (Q32); you may change the measured miles with a reason, and the claim shows both (Q33). Start, stops and end, with a round trip and saved places. Researched Oct 4 at your request for a free, open-source option: OpenRouteService (HeiGIT, on OpenStreetMap) has a free key with no card that does both address lookup (1,000 a day) and driving distance through up to 50 ordered stops (2,000 a day), with commercial use allowed and attribution required; one call covers a whole trip. Google Routes needs billing enabled, so it is out. GraphHopper’s free plan allows only 5 points and no commercial use; Mapbox won’t let free lookups be stored, which saved places need; self-hosting a US map needs far more memory than any free host. Fallbacks: manual miles (#17), and for lookups the US Census geocoder or Nominatim on submit only. Each claim freezes its points, the distance in metres, the provider and when it was routed, and is never re-routed. OpenRouteService’s terms bar sending personal data, and a home address arguably is, so only addresses and coordinates would be sent.',
    priority: 'P2',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 2',
    affects: ['FR-CAP-04', 'F-14'],
    done: { date: '2026-10-04', in: 'PR #59' },
  },
  {
    num: 48,
    title: 'The backup key can delete the backups',
    type: 'Security',
    detail:
      'The Backblaze key is Read and Write, which includes deleting. Object Lock stops that for each file’s first 30 days only, so anyone holding the key could then erase the monthly dumps and every older receipt image. The nightly job never deletes. Replace the key with one that can list, read and write but not delete, made with the Backblaze command-line tool (the web console can’t), then run the backup once to prove it.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: {
      kind: 'owner',
      ask: 'About 15 minutes: a new key from the Backblaze command-line tool, then swap two secrets',
    },
    source: 'GAP-18',
    affects: ['GAP-18', 'NFR-REL-01', 'F-37'],
  },

  {
    num: 76,
    title: 'Add the 2027 IRS mileage rate before January',
    type: 'Ops',
    detail:
      'Mileage is paid at the IRS business rate on the drive’s date (R-MILEAGE-RATE, ADR-0038), known through Dec 31, 2026. A drive dated in 2027 is refused, not paid at the old rate, until the IRS announces the 2027 rate, usually in mid-December, and it is added. Each year the same: a one-line change and its test.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Found merging PR #58',
    affects: ['FR-CAP-03', 'F-13'],
  },

  {
    num: 77,
    title: 'Your own mileage rate in Settings',
    type: 'Feature',
    detail:
      'Your answer to Q28: drives are paid at the IRS business rate by default, and Settings lets you set your own rate a mile instead whenever you want, applying to drives dated from the day it takes effect. Each drive keeps the rate it was paid at (NFR-DAT-04). Built in PR #59 behind `expenses.mileage`: Settings › Mileage shows the rate in force today and each change; an owner or finance admin sets your own rate from a day, in your home currency, or goes back to the IRS rate from a day, each change audited (US-MILE-11).',
    priority: 'P2',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Q28',
    affects: ['FR-CAP-03', 'F-13', 'NFR-DAT-04'],
    done: { date: '2026-10-04', in: 'PR #59' },
  },

  // P3: this quarter
  {
    num: 70,
    title: 'Keep a claim’s category and type names as they were',
    type: 'Gap',
    detail:
      'GAP-27, found merging PR #58. Copy the category and type names onto an expense when its report is submitted, so renaming one later never changes a submitted claim or its export (NFR-DAT-04).',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-27',
    affects: ['GAP-27', 'NFR-DAT-04'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 23,
    title: 'Expense reports: trips join once they end, closed within 28 days',
    type: 'Feature',
    detail:
      'Your answers of Oct 4. A report holds trips and local expenses. Twenty-four hours after a trip’s return date it joins the open report, or a new report opens for it. Trips can move between reports. You’re told in the app, on Home and in Needs you. Close a report within 28 days of it opening, or it closes automatically; it can’t close while any of its trips has expenses needing review, and a warning that reimbursement will be delayed shows as day 28 nears. On day 28 a trip still needing review moves to the next report and the rest closes (Q20). An expense on no trip is local and needs a justification (Q21, FR-EXP-14). Closing never submits: only a closed report can be submitted (#24); a closed report can be reopened until it is submitted, and then it is locked. Until #62, totals are per currency. Brings reports to finish to Home (Q15).',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 3; product owner Oct 4',
    affects: ['FR-EXP-05', 'FR-EXP-12', 'FR-EXP-14', 'F-17', 'F-50', 'FR-INS-01'],
    done: { date: '2026-10-04', in: 'PR #52' },
  },
  {
    num: 24,
    title: 'Single-step approval',
    type: 'Feature',
    detail:
      'Approve, or return with a comment. A one-person organization self-attests; in a team no one approves their own spend; approving someone else’s needs the second factor. Your rules (Oct 3): an expense that doesn’t match its receipt is rejected, one rejected expense returns the whole report, and the rejected ones are surfaced with why (FR-GOV-10–12). Your Q6 answer: an expense may claim less than its receipt with a reason, never more, and a report can’t be submitted while a difference has no reason (FR-EXP-10, FR-GOV-13). Your answer to Q29: from then, export takes submitted and approved reports only.',
    priority: 'P3',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 3',
    affects: [
      'FR-GOV-02',
      'FR-GOV-03',
      'FR-GOV-10',
      'FR-GOV-11',
      'FR-GOV-12',
      'FR-GOV-13',
      'FR-EXP-10',
      'F-18',
    ],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 86,
    title: 'Choose who approves each member’s reports',
    type: 'Feature',
    detail:
      'Found building #24. A report goes to its member’s manager when one is set and can approve it, but nothing sets a manager yet, so every report goes to the longest-standing approver, then finance admin, then owner (ADR-0043). Let an owner choose each member’s approver in Settings › People, if your answer to Q42 asks for it. Your answer to Q42: keep the routing as built, and let an owner choose now. Built behind Approval: in People an owner chooses each person’s approver from those who can approve, or Automatic; a report then goes to them while they can approve it, else as Automatic finds, and People says so (US-TEAM-06).',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Claude, building #24',
    affects: ['FR-GOV-02', 'F-18'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 87,
    title: 'Correct an approved expense with a reversal and a new version',
    type: 'Gap',
    detail:
      'GAP-34, found building #24. An approved expense is locked, in the app and in the database, but nothing makes the reversal and new version that correct one (FR-EXP-03): reverse it with a copy that cancels it, pointing at it, and file a new version for its member to correct and submit, each in the audit trail. Until then an approved mistake stays as approved.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-34',
    affects: ['GAP-34', 'FR-EXP-03', 'F-18'],
  },
  {
    num: 27,
    title: 'Email notifications',
    type: 'Feature',
    detail:
      'Report drafted, returned or approved, and a reading that needs a look. Supabase’s built-in email reaches only its own team’s members (D-15), so a second recipient needs a sender domain.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: {
      kind: 'owner',
      ask: 'Your decision: a sender domain, or owner-only email for now',
    },
    source: 'Roadmap increment 3, D-15',
    affects: ['FR-PLT-06', 'F-21'],
  },
  {
    num: 28,
    title: 'Home dashboard, beneath Needs you',
    type: 'Feature',
    detail:
      'Your requirement of Oct 3. Needs you stays first. Beneath it: the trip under way (its day, spend so far, Add a receipt) or the next within 14 days; this month’s spend, expenses, trips and how many are ready; expenses on no trip as a figure; receipts being read as one quiet line; the last three trips, each with whether all its expenses are Ready. One request, `GET /v1/home`, built from the same views as Expenses and Trips, the person’s own figures only. Reports to finish join with #23, business miles with #17, money awaiting reimbursement when payouts exist. Design: https://claude.ai/artifact/F7Z3J245BXqftu17hWwzYh',
    priority: 'P1',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 3, product owner Oct 3',
    affects: ['FR-INS-01', 'F-22', 'FR-EXP-02'],
    done: {
      date: '2026-10-03',
      in: 'PR #43; reports to finish join with #23, business miles with #17',
    },
  },
  {
    num: 30,
    title: 'No staging environment, by your decision',
    type: 'Ops',
    detail:
      'The delivery lifecycle runs previews and the release candidate on a second, free Supabase project with synthetic data. It doesn’t exist yet. Since #3, previews hold no production credentials and so no data: a signed-in screen on a preview shows nothing to check. You chose not to set one up (Q13, ADR-0025): a changed screen is checked on an iPhone in production after its release. Revisit before a second organization holds data, or when gate G6 is built.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your call to revisit; declined for Phase 1 on Oct 3' },
    source: 'Roadmap increment 4, delivery §7.3',
    affects: ['NFR-SEC-13', 'NFR-UX-02'],
  },
  {
    num: 31,
    title: 'Security review and accessibility pass at the Phase 1 exit',
    type: 'Ops',
    detail:
      'An OWASP ASVS Level 2 review of everything built in Phase 1, and a manual accessibility pass beyond the automated axe checks.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'items', items: [87], then: 'the rest of increment 4' },
    source: 'Roadmap increment 4',
    affects: ['NFR-SEC-14'],
  },
  {
    num: 75,
    title: 'Nobody has read how long capture to Ready takes in production',
    type: 'Verify',
    detail:
      'The time is measured now (#32), but only you can switch on Capture-to-Ready time in Settings › Features and read it. After a week of real receipts, check that 95 in every 100 are read within 30 seconds; if not, the slowest step shows in each reading’s time.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: {
      kind: 'owner',
      ask: 'Your check: switch on Capture-to-Ready time, then read it after a week',
    },
    source: 'NFR-PERF-01',
    affects: ['NFR-PERF-01', 'US-READ-16'],
  },
  {
    num: 33,
    title: 'The app could hard-delete financial records',
    type: 'Gap',
    detail:
      '`expensewise_app` holds DELETE on every tenant table; only the audit log refuses changes. Migration 0017 took DELETE on receipts, readings, confirmations and expenses away from the app; only `delete_receipt()` removes a receipt, for a duplicate you decide to delete (ADR-0028). Still to do: reports (an empty open report is dropped today, ADR-0029), approval steps and mileage logs, with a test.',
    priority: 'P3',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-10',
    affects: ['GAP-10', 'NFR-DAT-05'],
  },
  {
    num: 34,
    title: 'A breaking API change would pass CI',
    type: 'Gap',
    detail:
      'Diff `openapi.json` against `main` in G3 and fail on a breaking change without a new version. It matters from the first iPhone build; cheap to add now.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-11',
    affects: ['GAP-11', 'NFR-ARC-04', 'NFR-DEL-01'],
  },
  {
    num: 35,
    title: 'Retention and legal hold have no design',
    type: 'Decision',
    detail:
      'Seven years by default, configurable, with legal hold, promised for Phase 0. Your answer to Q2 sets the scope; then an ADR and the fields.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your decision: Q2' },
    source: 'GAP-12',
    affects: ['GAP-12', 'NFR-PRV-01'],
  },
  {
    num: 36,
    title: 'Subprocessor agreements are unconfirmed',
    type: 'Decision',
    detail:
      'Supabase, Vercel, Inngest and Anthropic see receipts today, and OpenAI on the fallback path. Your answer to Q3 decides whether their standard terms are enough for Phase 1.',
    priority: 'P3',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your decision: Q3' },
    source: 'GAP-13',
    affects: ['GAP-13', 'NFR-PRV-04'],
  },
  {
    num: 38,
    title: 'Nothing proves the model is called without tools',
    type: 'Gap',
    detail:
      'Receipts are untrusted input. Assert in the extractor tests that no tools are sent, so adding one fails CI.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-15',
    affects: ['GAP-15', 'NFR-SEC-07'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 39,
    title: 'The eval set has no real-world layer',
    type: 'Decision',
    detail:
      'D-12 is still Proposed: may I search your Gmail for past travel receipts to label? The Gmail connector also needs authorizing in your claude.ai settings. Real captures can join the set either way. Closed on Oct 5: you don’t want your Gmail connected, so it is never searched; the eval set keeps its public, synthetic and real-capture layers.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'owner', ask: 'Your decision on D-12, and the Gmail connector' },
    source: 'ADR-0012',
    affects: ['NFR-AI-01'],
    done: { date: '2026-10-05', in: 'Closed at your word: your Gmail is not searched' },
  },

  {
    num: 49,
    title: 'One dependency advisory is let through until it has a fix',
    type: 'Security',
    detail:
      'braces’ high advisory (GHSA-vfj7-8cjw-p6xm) has no fixed version, so the audit ignores it (pnpm-workspace.yaml). It reaches us only through lint tooling. When Advisory watch fails on a Monday, a fix exists: update to it, remove the ignore and close GAP-19.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none', note: 'Waits on an upstream fix; Advisory watch says when' },
    source: 'GAP-19',
    affects: ['GAP-19', 'NFR-SEC-12'],
  },
  {
    num: 74,
    title: 'Keep the audit trail and the outbox to who may read them',
    type: 'Security',
    detail:
      'GAP-31, found building #50. Members now see only their own records, but every member’s transaction can still read the whole organization’s audit trail, which it reads to chain the next event, and the outbox. No screen or operation shows either to a member. Hold reading the trail to owners, finance admins and auditors, with the chain’s last link read by an owner-run function, and the outbox to the system, each with a test.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-31',
    affects: ['GAP-31', 'FR-GOV-01'],
  },
  {
    num: 71,
    title: 'List an expense without a category and type in Needs you',
    type: 'Gap',
    detail:
      'Your answer to Q27: an expense without a category and type appears in Needs you, as well as saying so on its page and in the list; it holds nothing up. Built in PR #59 behind `expenses.categories`: each of your Ready expenses with neither is in Needs you, after local expenses needing a reason and before reports ready to close, with the suggestion when there is one, and Home counts it (US-RPT-18). Hanging rules on types moved to #78.',
    priority: 'P3',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-28',
    affects: ['FR-EXP-11', 'F-43'],
    done: { date: '2026-10-04', in: 'PR #59' },
  },
  {
    num: 78,
    title: 'Hang each rule on its type as the rule is built',
    type: 'Gap',
    detail:
      'As each rule is built, such as meal attendees or a receipt needed above a limit, attach it to the type, as US-RPT-12 assumes. The mileage rate is the organization’s, by your answer to Q28 (#77), so it stays off the type.',
    priority: 'P3',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-28',
    affects: ['GAP-28', 'FR-EXP-11', 'F-43'],
  },
  {
    num: 72,
    title: 'Ask to re-confirm the AI model after about 100 receipts',
    type: 'Gap',
    detail:
      'You now choose the primary model in Settings › AI models, with each model’s record beside it (#52), but nothing asks you to look again once it has read about 100 of your receipts, as NFR-AI-04 says. Count the receipts read since the primary was last chosen, and at about 100 put it in Needs you: keep it, or change it, with the record beside it. Withdrawn on Oct 5: you don’t need a reminder to confirm the model.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-29',
    affects: ['GAP-29', 'NFR-AI-04', 'F-45'],
    done: { date: '2026-10-05', in: 'Withdrawn at your word: no reminder to re-confirm the model' },
  },
  {
    num: 53,
    title: 'Read the time and address on a receipt',
    type: 'Feature',
    detail:
      'Add the time of purchase and the merchant’s address to the reading, both optional and each with its confidence, and to the expense, editable (your answer to Q9). The address as printed, with city and country picked out; the time as printed, with a time zone worked out from the address or set by the person. Proposed: the time zone comes from an offline lookup of city and country, so no address leaves ExpenseWise. A new schema and prompt version, and labels in the eval set. Moved up on Oct 4: duplicates are to be matched on time and place (#61).',
    priority: 'P1',
    effort: 'L',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Product owner, Oct 3',
    affects: ['FR-INT-17', 'F-46', 'FR-INT-01'],
    done: { date: '2026-10-04', in: 'PR #53' },
  },
  {
    num: 56,
    title: 'Rehearse a whole recovery once a year',
    type: 'Ops',
    detail:
      'The monthly drill proves the backup restores and checks it, on a runner. A real recovery also needs a new Supabase project, the Release run to set role passwords and take back Data API grants, the receipt images copied back, and Vercel pointed at it, which the runbook does by hand and nobody has timed against the 4-hour recovery time. Do it once a year into the staging project, timing each step.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'items', items: [30] },
    source: 'NFR-REL-03',
    affects: ['NFR-REL-03'],
  },
  {
    num: 89,
    title: 'What awaits reimbursement on Home',
    type: 'Feature',
    detail:
      'Home’s month shows business miles since #73; the last figure FR-INS-01 asks for is the money approved and not yet paid to the person, which first exists with approval (#24). Total the person’s approved expenses not yet paid, per currency and never converted, opening their approved reports, and leave it out when there is none.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none', note: 'Builds on approval (#24)' },
    source: 'FR-INS-01, US-HOME-04',
    affects: ['FR-INS-01', 'F-22'],
  },
  {
    num: 88,
    title: 'Hold a person’s other emails until each adds its own authenticator',
    type: 'Security',
    detail:
      'GAP-35, found building #85. The second factor holds each email a person signs in with by its own authenticators (ADR-0044), so another email of theirs with none still opens everything on its password. Once a person has an authenticator on any sign-in, hold their others that have none, as #85 holds a session that skipped the code, while the organization has the second factor on; the app says which email needs one and keeps Settings › Sign-ins open to add it. If your answer to Q43 asks for it.',
    priority: 'P3',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-35, Claude, building #85',
    affects: ['GAP-35', 'FR-PLT-03', 'FR-PLT-04', 'F-11'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 90,
    title: 'Only an email you let in signs in, once you have an authenticator',
    type: 'Security',
    detail:
      'GAP-36, found building #88; your answer to Q44. Once a person has an authenticator, only an email of theirs that is let in signs in: the first to pass its code is let in, and their other emails still forward receipts but can’t open the app. From an email that passed its code, the person may let another email in, after which it adds its own authenticator and passes its code; an authenticator added to an email that wasn’t let in doesn’t count. Letting one in is kept with the sign-in and audited.',
    priority: 'P2',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-36, Q44',
    affects: ['GAP-36', 'FR-PLT-03', 'FR-PLT-04', 'F-11'],
    done: { date: '2026-10-05', in: 'PR #60' },
  },
  {
    num: 91,
    title: 'Let in first only the email a person first signed in with',
    type: 'Security',
    detail:
      'GAP-37, found building #90. The first of a person’s emails to pass its code is let in, so until then whoever holds another email’s password could add an authenticator to it and be let in first. If your answer to Q45 asks for it: while none of a person’s emails is let in, only the one they first signed in with may add its own authenticator and is let in once it passes its code; any other is refused until it is let in from it. The runbook’s reset stays for an email that is lost.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-37, Claude, building #90',
    affects: ['GAP-37', 'FR-PLT-03', 'FR-PLT-04', 'F-11'],
  },
  {
    num: 92,
    title: 'Read a folio’s credits and per-night charges as printed',
    type: 'Gap',
    detail:
      'Your report of Oct 5 (GAP-38). A credit, refund or reversal, such as a hotel’s $68 credit for two $34 parking charges, is read as its own line with a negative amount, so the charges and the credit both show and net out; every line is read each time it is printed, so a folio’s taxes for each night are all there and add up to the tax it prints; and a reading whose lines don’t add up to its total is held for a look even when no subtotal is printed. A receipt read before needs Read again.',
    priority: 'P1',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 5',
    affects: ['GAP-38', 'FR-INT-22', 'FR-INT-04', 'F-55'],
  },
  // Done
  {
    num: 17,
    title: 'Manual mileage',
    type: 'Feature',
    detail:
      'Date, destination, purpose and miles, with the rate in force on the day copied onto the entry. The rate rules are built and tested.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 2',
    affects: ['FR-CAP-03', 'NFR-DAT-04', 'F-13'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 18,
    title: 'Category suggestions',
    type: 'Feature',
    detail:
      'Suggest a type, and so a category, for each expense, marked as a suggestion until confirmed. It suggests from the categories and types an organization defines (#51).',
    priority: 'P2',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 2',
    affects: ['FR-INT-10', 'F-15'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 21,
    title: 'Choose the model tier: Haiku or Sonnet',
    type: 'Decision',
    detail:
      'The tier is no longer a one-off decision from a spike: with #52 you choose the primary model in Settings, with how each model has read your receipts beside the choice, and can change it at any time. Without Anthropic credits (#4, withdrawn Oct 4) the comparison has only the readings it has. Done when #52 is.',
    priority: 'P3',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'ADR-0017',
    affects: ['FR-INT-08', 'NFR-AI-04', 'F-07'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 22,
    title: 'Was Phase 0’s flagged change switched on in production?',
    type: 'Verify',
    detail:
      'Phase 0 exits when a trivial change reaches production behind a flag. The build-version flag shipped dark. With your approval of Oct 4, `FLAG_OVERRIDES=shell.build-version=on` is set in Vercel production; it takes effect with the next production build. Done with this release: Home shows the build once it is live, which the release check confirms.',
    priority: 'P2',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Roadmap Phase 0 exit',
    affects: ['NFR-DEL-05'],
    done: { date: '2026-10-04', in: 'PR #58, with FLAG_OVERRIDES set in Vercel production' },
  },
  {
    num: 25,
    title: 'CSV and PDF export',
    type: 'Feature',
    detail:
      'Export approved reports as CSV and PDF. You asked for it on Oct 4, before approval (#24), so until approval exists it exports closed reports: Export CSV and Export PDF on a closed report’s page, behind the reports.export feature. The CSV has a row per expense and a total per currency; the PDF heads the same table with who, where and when, with no receipt images. Whether export waits for approval once #24 exists is Q29.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 3',
    affects: ['FR-SET-01', 'F-19'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 26,
    title: 'Audit trail view',
    type: 'Feature',
    detail:
      'Every record’s history for finance admins and auditors, with the chain verified on screen. The events are already written.',
    priority: 'P3',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 3',
    affects: ['FR-GOV-06', 'F-20'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 29,
    title: 'Invites and roles',
    type: 'Feature',
    detail:
      'Invite a person with a role, change it, revoke it. The whole Phase 1 admin console. Flags apply again from the first invite (Q5). Your choice of Oct 4: invite by link, so no email is sent and email notifications (#27) aren’t needed; members kept to their own records (#50) landed first, in the same pull request. Built behind `team.invites` (ADR-0035): Settings › People lists people and roles, makes a one-time link with a role that works for 7 days and can be revoked, changes a role and removes someone, keeping their records, never the last owner; `/invite/[token]` lets a signed-in person join, leaving behind an empty organization their first sign-in made and refused if theirs has work in it. Sign-ups stay off: the owner makes the person’s account in Supabase first.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: {
      kind: 'none',
      note: 'No longer waits on #27, since a link needs no email, nor on #50, built first in the same pull request',
    },
    source: 'Roadmap increment 4',
    affects: ['FR-PLT-07', 'FR-GOV-01', 'F-23'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 32,
    title: 'Capture to Ready isn’t measured',
    type: 'Gap',
    detail:
      'Record the time from filing to settlement on each receipt and show the 95th percentile beside the model comparison. The SLO is under 30 seconds. Built in PR #58: each receipt keeps when its first reading settled (those read before were filled in from the audit trail), and with Capture-to-Ready time switched on, Receipts shows the 95th percentile and how many receipts it is over, against 30 seconds. Reading production’s figure is #75.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-16',
    affects: ['GAP-16', 'NFR-PERF-01', 'F-07'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 37,
    title: 'A field doesn’t show where it came from, or take a correction',
    type: 'Gap',
    detail:
      'Ask the model for each field’s source line, highlight it on the receipt, and let one tap correct the value. Each correction becomes an eval candidate. Built in PR #58, behind Where each field was read: the models are asked for each field’s line only where it is on (`extract-v4`, `receipt-v4`), shown as text beside the value; it isn’t highlighted on the image, since the models give no position (Claude’s decision). A Ready receipt’s field is corrected with a tap through its expense, kept beside what was read. An approved expense stays locked: its correction is a reversal, which comes with approval (#24).',
    priority: 'P3',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-14, design DP3',
    affects: ['GAP-14', 'FR-INT-11', 'F-40'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 50,
    title: 'Members see and change only their own records',
    type: 'Security',
    detail:
      'Inside an organization, a member sees and changes only their own receipts, expenses and trips. An approver sees the reports they approve, finance admins see everything, and auditors read it. Must land before anyone is invited (#29). Built in the database (ADR-0035, F-61), unflagged as a security control: each request names its caller to Postgres, a policy shows a member or approver only their own records and what hangs off them, owners, finance admins and auditors see everyone’s, and a trigger refuses any change that isn’t the caller’s own, and every change by an auditor. Background work acts for the system. Approval isn’t built, so today an approver sees only their own records; seeing the reports they approve comes with #24.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-20',
    affects: ['GAP-20', 'FR-GOV-01', 'F-61'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 51,
    title: 'Categories and types an organization defines',
    type: 'Feature',
    detail:
      'Owners and finance admins define categories and types as two lists, each able to nest, and which types each category allows. Every expense gets a category and a type, the type chosen from those its category allows (your answer to Q7). An organization starts from a ready-made set it can rename, add to or retire; one in use is retired, never deleted, so old claims keep it.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner, Oct 3',
    affects: ['FR-EXP-11', 'F-43', 'FR-INT-10', 'F-15'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 52,
    title: 'Turn AI models on and off',
    type: 'Feature',
    detail:
      'A switch for each AI model in Settings and a choice of exactly one primary, for owners and finance admins, recorded in the audit trail, plus an operator switch per model as a flag. The primary reads every receipt; models that are on but not primary are back-ups, read in the order set only when the primary can’t (your answer to Q11). Any model can be primary, OpenAI’s included, and the fallback rule goes (Q8). With every model off, receipts are filed for a person to fill in; a model with no key stays off; read again uses the settings as they are then. Ready then rests on one confident reading, not two that agree, which needs a decision record replacing ADR-0017. Any model that is on can be made primary at any time (your answer, Oct 3); Settings shows how each has read your receipts beside the choice, so it is an informed one.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner, Oct 3',
    affects: ['FR-INT-16', 'F-45', 'FR-INT-08', 'FR-INT-09'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 55,
    title: 'Show dates one way everywhere',
    type: 'Feature',
    detail:
      'Screens show 2026-09-30, 10/3/2026, 1:12:47 PM and Sep 29 – Oct 1, 2026 today. One formatter for the web app: Sep 30, 2026, and 1:12 PM where a time matters (your answer to Q12). A model’s reading table keeps each date as read, so a difference between readings stays visible.',
    priority: 'P2',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Q12',
    affects: ['NFR-UX-06'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 62,
    title: 'Amounts converted to your reimbursement currency',
    type: 'Feature',
    detail:
      'Your answer of Oct 4: everything in a report is converted to the currency you’re reimbursed in, beside the amount as spent. Your reimbursement currency is set in Settings and starts as your organization’s home currency. Your answer to Q22: cards convert at purchase, so the amount to reimburse is usually what the card charged. Your answer to Q23: in your preferred currency, as set in the app. Your answer to Q25: at the purchase date’s reference rate. Each conversion keeps its rate, the rate’s date and its source (NFR-DAT-02), copied on so a later rate never changes it (NFR-DAT-04). Report totals (#23) use it.',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['FR-EXP-13', 'F-49', 'NFR-DAT-02'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 63,
    title: 'Organization details in Settings',
    type: 'Feature',
    detail:
      'Your requirement of Oct 4. An owner edits the organization’s name, home currency, country, locale, time zone, address, industry and size in Settings. The time zone also tells background work, such as reports opening and closing, what day it is for you.',
    priority: 'P2',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['FR-PLT-11', 'F-51'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 64,
    title: 'Set the duplicate time window in Settings',
    type: 'Feature',
    detail:
      'Your request of Oct 4. The window within which two receipts at the same place count as one purchase (ADR-0031) becomes a setting: 0 to 120 minutes, 30 by default, 0 meaning the same minute only. A change judges pairs from then on; pairs already decided stay decided, and the audit trail records each change. Your answer to Q24: the organization’s owner sets it, for everyone. Settings also shows your role, so you can confirm that each of your addresses is the owner.',
    priority: 'P1',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Product owner Oct 4',
    affects: ['FR-INT-19', 'F-52', 'FR-INT-18'],
    done: { date: '2026-10-04', in: 'PR #58' },
  },
  {
    num: 4,
    title: 'Claude can’t read receipts: the Anthropic account has no credit',
    type: 'Ops',
    detail:
      'Claude readings failed with “Your credit balance is too low”, so GPT-5.6 Luna reads every receipt and each one waits in Needs a look until you confirm it (#47). Withdrawn on Oct 4: you won’t buy credits and asked not to be reminded. Which model reads first becomes your choice in Settings (#52).',
    priority: 'P3',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    affects: ['FR-INT-08', 'NFR-AI-04', 'F-07'],
    done: {
      date: '2026-10-04',
      in: 'Withdrawn at your word: no credits will be bought, and no reminder',
    },
  },
  {
    num: 40,
    title: 'Two sign-ins couldn’t reach the same receipts',
    type: 'Feature',
    detail:
      'Your Gmail and work addresses each made their own organization. A member can now have several sign-ins, linked with proof of both (ADR-0016).',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none' },
    affects: ['FR-PLT-04', 'F-03'],
    done: { date: '2026-10-02', in: 'PR #15' },
  },
  {
    num: 41,
    title: 'Migrations re-set role passwords and broke the pooler',
    type: 'Gap',
    detail:
      'Every migration run re-set the runtime passwords, and the pooler kept the old ones. Passwords are now set only when a role can’t sign in.',
    priority: 'P1',
    effort: 'S',
    severity: 'High',
    blocker: { kind: 'none' },
    affects: ['F-34'],
    done: { date: '2026-10-02', in: 'PR #14' },
  },
  {
    num: 42,
    title: 'A build went live before its migration',
    type: 'Ops',
    detail:
      'Vercel published each build on its own while migrations waited. A release now migrates first, then promotes that commit’s build and checks it is live (ADR-0018).',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none' },
    affects: ['NFR-DEL-03', 'NFR-REL-07', 'F-36'],
    done: { date: '2026-10-02', in: 'PR #17' },
  },
  {
    num: 43,
    title: 'Saving a key said “Anthropic could not be reached” when it had answered',
    type: 'Gap',
    detail:
      'Pasted keys are now cleaned, every answer is classified (rejected, refused, unreachable) and the provider’s own message is shown.',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    affects: ['FR-PLT-05', 'F-04'],
    done: { date: '2026-10-02', in: 'PR #18' },
  },
  {
    num: 44,
    title: 'Every release waited on a second approval click',
    type: 'Ops',
    detail:
      'Your word to merge is now the release approval; the Release run starts straight after the merge (ADR-0019).',
    priority: 'P2',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    affects: ['NFR-DEL-04'],
    done: { date: '2026-10-02', in: 'PR #19' },
  },
  {
    num: 45,
    title: 'The model tier would have been chosen on synthetic receipts',
    type: 'Feature',
    detail:
      'The receipt page reads each of your receipts with Haiku and Sonnet side by side, so the tier decision rests on your own receipts (ADR-0017).',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    affects: ['FR-INT-08', 'F-06', 'F-07'],
    done: { date: '2026-10-02', in: 'PR #16' },
  },
];

/** How to order the open work, beyond priority. */
export const SEQUENCING: readonly string[] = [
  'Your batch of Oct 5 is built in PR #60: approval (#24) with the second factor (#8), a submitted claim keeping its names (#70), emails that filed nothing (#59), journeys and stays in the export (#83), business miles on Home (#73) and proof that no tools reach a model (#38), each behind its switch and off until you switch it on.',
  'With #85, #88 and #90 in PR #60, a session that skipped the code gets nothing for someone with an authenticator, and once a person has one, only an email they let in signs in; their other emails still forward receipts (Q44). #91, letting in first only the email a person first signed in with (your answer to Q45), is next; until then, set up your authenticator soon after release.',
  'Approval in a team needs the second factor switched on too. #87 corrects an approved expense; #89 shows what awaits reimbursement on Home.',
  '#48 needs you, not code: it keeps a leaked key from erasing the backups.',
  '#11–#15 are small, independent and each closes a gap; take them between features.',
];
