import type { BacklogItem } from './model.ts';

/**
 * Open work, ranked. Numbers are permanent: a closed item keeps its number in Done. Edit
 * here; the backlog page is generated from this file and republished only after a
 * successful release, so it always describes what is live.
 */
export const BACKLOG: readonly BacklogItem[] = [
  // P1: next
  {
    num: 1,
    title: 'Production holds real receipts, and nothing backs them up',
    type: 'Ops',
    detail:
      'Supabase’s Free plan keeps no backups. Build the nightly job from ADR-0014: an encrypted dump of the database (auth users included) and new receipt images to Backblaze B2, a heartbeat so the project never pauses, and alerts at 70% of the 500 MB and 1 GB limits. It can be built and tested now; it first runs once #2 is done.',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none', note: 'None to build it; it runs once #2 is done' },
    source: 'GAP-01, ADR-0014',
    affects: ['GAP-01', 'NFR-REL-01', 'NFR-REL-05', 'F-37', 'F-42'],
    done: { date: '2026-10-02', in: 'PR #23' },
  },
  {
    num: 2,
    title: 'The backup has nowhere to go yet',
    type: 'Ops',
    detail:
      'The backup is built (#1). Runbook section 5: the Backblaze account and bucket key are done; still to do are the backup passphrase in your password manager, a Supabase S3 key, and the GitHub environment `backup` with its seven secrets. Then run **Nightly backup** once from Actions (step 8). Never paste a key into the conversation.',
    priority: 'P1',
    effort: 'S',
    severity: 'High',
    blocker: {
      kind: 'owner',
      ask: 'Your setup: runbook section 5, steps 5–8, about 15 minutes',
    },
    source: 'ADR-0014',
    affects: ['GAP-01', 'NFR-REL-01', 'NFR-REL-05', 'F-37', 'F-42'],
    done: {
      date: '2026-10-03',
      in: 'Your setup; the first run backed up 51 tables and the receipt image',
    },
  },
  {
    num: 5,
    title: 'The OpenAI fallback waits on your merge',
    type: 'Feature',
    detail:
      'PR #20: when neither Claude model can read a receipt, GPT-5.6 Luna reads it once on your OpenAI key, and the receipt Needs a look (ADR-0020).',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your word on PR #20: merge' },
    source: 'PR #20',
    affects: ['FR-INT-09', 'F-08'],
    done: { date: '2026-10-02', in: 'PR #20' },
  },
  {
    num: 46,
    title: 'The fallback hasn’t read a real receipt yet',
    type: 'Verify',
    detail:
      'The OpenAI reader was tested against stand-in answers only, to spend nothing on your key. Upload one receipt while Anthropic still has no credit: it should come back as Needs a look with a GPT-5.6 Luna column. If OpenAI rejects the request, its own message shows on the receipt and I fix it. Your OpenAI account needs credit. Do this before #4, or Claude reads it instead.',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your test: upload one receipt before buying Anthropic credit' },
    source: 'PR #20',
    affects: ['FR-INT-09', 'F-08'],
    done: { date: '2026-10-02', in: 'Your test: a photographed receipt, read by GPT-5.6 Luna' },
  },
  {
    num: 47,
    title: 'A receipt that needs a look is a dead end',
    type: 'Gap',
    detail:
      'The receipt page says Needs a look and offers only Read again. Add the two actions from the receipt review design: **Looks right**, which confirms a reading as it is (choosing which one, when the readings differ), and **Edit a field**. Either makes the receipt Ready, records who confirmed what in the audit trail, and keeps each correction as an eval candidate. Every fallback reading lands here by design (ADR-0020), so this matters more while Anthropic has no credit.',
    priority: 'P1',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-17, your observation on Oct 2',
    affects: ['GAP-17', 'FR-INT-15', 'F-40'],
    done: { date: '2026-10-03', in: 'PR #26' },
  },
  {
    num: 6,
    title: 'Ready readings don’t become expenses',
    type: 'Feature',
    detail:
      'Increment 1 ends when a receipt is filed as an expense within 30 seconds. The expense table, its lifecycle and the money rules exist; the step that turns a settled reading into a Ready or Needs-review expense, with an audit event, does not. Your rules (Oct 3): the receipt stays linked as the expense’s proof, and the expense can be edited once it exists (FR-EXP-08, FR-EXP-09).',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 1',
    affects: ['FR-EXP-01', 'FR-EXP-03', 'FR-EXP-08', 'FR-EXP-09', 'NFR-UX-04', 'F-09'],
    done: { date: '2026-10-03', in: 'PR #28' },
  },
  {
    num: 16,
    title: 'Trips, trip history and search',
    type: 'Feature',
    detail:
      'Trips with dates and a purpose; expenses file to the trip whose dates they fall in; past trips can be browsed and searched. Raised to P1 on Oct 3 at your direction. It needs expenses to exist first (#6).',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 2',
    affects: ['FR-EXP-04', 'FR-INS-02', 'F-12'],
  },
  {
    num: 10,
    title: 'No backup has ever been restored',
    type: 'Ops',
    detail:
      'A backup nobody has restored is only a hope. Backups run nightly since Oct 3 (#2). A monthly workflow restores the latest one into a throwaway database and checks migrations, row counts, row-level security and image checksums against what the dump recorded.',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none' },
    source: 'ADR-0014',
    affects: ['NFR-REL-02', 'NFR-REL-03', 'F-41'],
  },
  {
    num: 3,
    title: 'Preview builds hold production credentials',
    type: 'Security',
    detail:
      '`DATABASE_URL` and `SUPABASE_SECRET_KEY` are set for Preview as well as Production, so every branch push builds unreviewed code that could read production data and every stored receipt. Previews sit behind Vercel’s sign-in, which limits the damage. Untick Preview on both. CI tests against its own database, so nothing is lost; previews get data again with staging (#30).',
    priority: 'P1',
    effort: 'S',
    severity: 'High',
    blocker: { kind: 'owner', ask: 'Your go-ahead, or five minutes in Vercel' },
    source: 'GAP-02',
    affects: ['GAP-02', 'NFR-SEC-13'],
  },
  {
    num: 7,
    title: 'Sums and dates aren’t checked before Ready',
    type: 'Gap',
    detail:
      'Add the guardrail from journeys §4.6: subtotal, taxes and tip must reconcile with the total within a cent per line, and the date must not be in the future or implausibly old. A failure makes the receipt Need a look and says why.',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-04',
    affects: ['GAP-04', 'FR-INT-04'],
  },
  {
    num: 8,
    title: 'Sign-in has no second factor',
    type: 'Security',
    detail:
      'Real financial records sit behind a password alone. Add TOTP enrollment and the challenge at sign-in, and require `aal2` for approving someone else’s spend and for admin actions. Increment 1 planned it.',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none' },
    source: 'GAP-03, roadmap increment 1',
    affects: ['GAP-03', 'FR-PLT-03', 'FR-GOV-04', 'F-11'],
  },
  {
    num: 9,
    title: 'The Needs you inbox shows nothing',
    type: 'Feature',
    detail:
      'Home has the inbox layout and an empty state only. Start with what exists: receipts that need a look or failed, each with its reason and one action. Missing receipts and returned reports join as trips and reports arrive; a returned report lists each rejected expense with why (FR-GOV-12).',
    priority: 'P1',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 1, design DP2',
    affects: ['FR-EXP-02', 'FR-GOV-12', 'F-10'],
  },

  // P2: this month
  {
    num: 11,
    title: 'The outbox relay isn’t running',
    type: 'Ops',
    detail:
      '`RELAY_DATABASE_URL` is not set, so the relay is not registered and a failed eager send waits for Read again. Add it in Vercel for Production: the same address as `DATABASE_URL`, with the `expensewise_relay` user and its password (runbook section 6).',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your action: one setting in Vercel' },
    source: 'GAP-05',
    affects: ['GAP-05', 'NFR-DAT-07', 'F-33'],
  },
  {
    num: 12,
    title: 'Nothing finds a receipt stuck in Reading',
    type: 'Gap',
    detail:
      'An hourly workflow that finds receipts left in Reading for more than ten minutes, settles them from what was stored or reads them again, and reports how many. It makes the “receipt never lost” SLO measurable.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-06',
    affects: ['GAP-06', 'NFR-DAT-07'],
  },
  {
    num: 13,
    title: 'Errors go nowhere anyone looks',
    type: 'Ops',
    detail:
      'Error tracking is built, with secrets redacted, but `NEXT_PUBLIC_SENTRY_DSN` is not set. Create a free Sentry project for Next.js and paste its DSN into Vercel.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your action: a Sentry project and its DSN' },
    source: 'GAP-07',
    affects: ['GAP-07', 'NFR-OPS-01', 'F-32'],
  },
  {
    num: 14,
    title: 'Nothing outside the app notices when production is down',
    type: 'Ops',
    detail:
      'A scheduled GitHub Actions workflow that calls `/api/v1/health/ready` every 15 minutes and fails if it isn’t ready. GitHub emails you on a failed run, so it needs no new account.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-08',
    affects: ['GAP-08', 'NFR-REL-04'],
  },
  {
    num: 15,
    title: 'The release script has no test',
    type: 'Gap',
    detail:
      '`promote-production.mjs` decides what goes live and refuses to roll production back past a newer commit. Commit its test with stand-in Vercel and GitHub answers, and run it in G2.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-09',
    affects: ['GAP-09', 'NFR-DEL-03', 'F-36'],
  },
  {
    num: 17,
    title: 'Manual mileage',
    type: 'Feature',
    detail:
      'Date, destination, purpose and miles, with the rate in force on the day copied onto the entry. The rate rules are built and tested.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 2',
    affects: ['FR-CAP-03', 'NFR-DAT-04', 'F-13'],
  },
  {
    num: 18,
    title: 'Category suggestions',
    type: 'Feature',
    detail:
      'Suggest a type, and so a category, for each expense, marked as a suggestion until confirmed. It suggests from the categories and types an organization defines (#51).',
    priority: 'P2',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'items', items: [51] },
    source: 'Roadmap increment 2',
    affects: ['FR-INT-10', 'F-15'],
  },
  {
    num: 19,
    title: 'Email-in forwarding address',
    type: 'Feature',
    detail:
      'A personal address that takes forwarded airline, hotel and ride emails and reads the body and any PDF like a receipt. The only automatic route for travel receipts (ADR-0011).',
    priority: 'P2',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'A Postmark account from you' },
    source: 'Roadmap increment 2',
    affects: ['FR-CAP-02', 'F-16'],
  },
  {
    num: 20,
    title: 'Route-based mileage',
    type: 'Feature',
    detail:
      'Start, stops and end, with a round trip and saved places; distance from the Google Routes API. The first item to cut if increment 2 runs long.',
    priority: 'P2',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'items', items: [17], then: 'a Google Routes API key from you' },
    source: 'Roadmap increment 2',
    affects: ['FR-CAP-04', 'F-14'],
  },
  {
    num: 22,
    title: 'Was Phase 0’s flagged change switched on in production?',
    type: 'Verify',
    detail:
      'Phase 0 exits when a trivial change reaches production behind a flag. The build-version flag shipped dark; turning it on needs `FLAG_OVERRIDES=shell.build-version=on` in Vercel and a redeploy. It isn’t set now, which is right either way. Tell me whether you did it.',
    priority: 'P2',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'owner', ask: 'Your answer: done, or ten minutes in Vercel' },
    source: 'Roadmap Phase 0 exit',
    affects: ['NFR-DEL-05'],
  },
  {
    num: 48,
    title: 'The backup key can delete the backups',
    type: 'Security',
    detail:
      'The Backblaze key is Read and Write, which includes deleting. Object Lock stops that for each file’s first 30 days only, so anyone holding the key could then erase the monthly dumps and every older receipt image. The nightly job never deletes. Replace the key with one that can list, read and write but not delete, made with the Backblaze command-line tool (the web console can’t), then run the backup once to prove it.',
    priority: 'P2',
    effort: 'S',
    severity: 'Medium',
    blocker: {
      kind: 'owner',
      ask: 'About 15 minutes: a new key from the Backblaze command-line tool, then swap two secrets',
    },
    source: 'GAP-18',
    affects: ['GAP-18', 'NFR-REL-01', 'F-37'],
  },

  // P3: this quarter
  {
    num: 4,
    title: 'Claude can’t read receipts: the Anthropic account has no credit',
    type: 'Ops',
    detail:
      'Every reading fails with “Your credit balance is too low”. Buy credits in the Claude Console under Settings → Billing; $5 covers about 250 receipts with both models. Then press Read again on each receipt that failed. Lowered on Oct 3 at your direction: GPT-5.6 Luna reads every receipt meanwhile, and each one waits in Needs a look until you confirm it (#47). The model-tier decision (#21) waits on this.',
    priority: 'P3',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your action: buy Anthropic credits' },
    affects: ['FR-INT-08', 'NFR-AI-04', 'F-07'],
  },
  {
    num: 21,
    title: 'Choose the model tier: Haiku or Sonnet',
    type: 'Decision',
    detail:
      'Proposed rule: Haiku if it agrees with Sonnet on at least 95% of receipts and is never confidently wrong where Sonnet was right; otherwise Sonnet. Needs about 20 of your receipts read by both, so it waits on #4. The decision takes effect by turning the other model off (#52).',
    priority: 'P3',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'items', items: [4], then: 'about 20 receipts, then your decision' },
    source: 'ADR-0017',
    affects: ['FR-INT-08', 'NFR-AI-04', 'F-07'],
  },
  {
    num: 23,
    title: 'Reports drafted 48 hours after a trip',
    type: 'Feature',
    detail:
      'Forty-eight hours after a trip ends, draft its report and tell the traveler. Skip trips with no expenses; the traveler can reopen.',
    priority: 'P3',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'items', items: [16] },
    source: 'Roadmap increment 3',
    affects: ['FR-EXP-05', 'F-17'],
  },
  {
    num: 24,
    title: 'Single-step approval',
    type: 'Feature',
    detail:
      'Approve, or return with a comment. A one-person organization self-attests; in a team no one approves their own spend; approving someone else’s needs the second factor. Your rules (Oct 3): an expense that doesn’t match its receipt is rejected, one rejected expense returns the whole report, and the rejected ones are surfaced with why (FR-GOV-10–12). Your Q6 answer: an expense may claim less than its receipt with a reason, never more, and a report can’t be submitted while a difference has no reason (FR-EXP-10, FR-GOV-13).',
    priority: 'P3',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'items', items: [23, 8] },
    source: 'Roadmap increment 3',
    affects: [
      'FR-GOV-02',
      'FR-GOV-03',
      'FR-GOV-10',
      'FR-GOV-11',
      'FR-GOV-12',
      'FR-GOV-13',
      'FR-EXP-10',
      'F-18',
    ],
  },
  {
    num: 25,
    title: 'CSV and PDF export',
    type: 'Feature',
    detail: 'Export approved reports as CSV and PDF.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'items', items: [23] },
    source: 'Roadmap increment 3',
    affects: ['FR-SET-01', 'F-19'],
  },
  {
    num: 26,
    title: 'Audit trail view',
    type: 'Feature',
    detail:
      'Every record’s history for finance admins and auditors, with the chain verified on screen. The events are already written.',
    priority: 'P3',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 3',
    affects: ['FR-GOV-06', 'F-20'],
  },
  {
    num: 27,
    title: 'Email notifications',
    type: 'Feature',
    detail:
      'Report drafted, returned or approved, and a reading that needs a look. Supabase’s built-in email reaches only its own team’s members (D-15), so a second recipient needs a sender domain.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: {
      kind: 'owner',
      ask: 'Your decision: a sender domain, or owner-only email for now',
    },
    source: 'Roadmap increment 3, D-15',
    affects: ['FR-PLT-06', 'F-21'],
  },
  {
    num: 28,
    title: 'Personal dashboard',
    type: 'Feature',
    detail: 'Spent this month, expenses and trips, business miles, awaiting reimbursement.',
    priority: 'P3',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'Roadmap increment 3',
    affects: ['FR-INS-01', 'F-22'],
  },
  {
    num: 29,
    title: 'Invites and roles',
    type: 'Feature',
    detail:
      'Invite a person with a role, change it, revoke it. The whole Phase 1 admin console. Flags apply again from the first invite (Q5).',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'items', items: [27] },
    source: 'Roadmap increment 4',
    affects: ['FR-PLT-07', 'FR-GOV-01', 'F-23'],
  },
  {
    num: 30,
    title: 'No staging environment',
    type: 'Ops',
    detail:
      'The delivery lifecycle runs previews and the release candidate on a second, free Supabase project with synthetic data. It doesn’t exist yet, so previews either hold production credentials (#3) or no data.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your action: create the second Supabase project' },
    source: 'Roadmap increment 4, delivery §7.3',
    affects: ['NFR-SEC-13'],
  },
  {
    num: 31,
    title: 'Security review and accessibility pass at the Phase 1 exit',
    type: 'Ops',
    detail:
      'An OWASP ASVS Level 2 review of everything built in Phase 1, and a manual accessibility pass beyond the automated axe checks.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'items', items: [24, 25, 29], then: 'the rest of increment 4' },
    source: 'Roadmap increment 4',
    affects: ['NFR-SEC-14'],
  },
  {
    num: 32,
    title: 'Capture to Ready isn’t measured',
    type: 'Gap',
    detail:
      'Record the time from filing to settlement on each receipt and show the 95th percentile beside the model comparison. The SLO is under 30 seconds.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-16',
    affects: ['GAP-16', 'NFR-PERF-01'],
  },
  {
    num: 33,
    title: 'The app could hard-delete financial records',
    type: 'Gap',
    detail:
      '`expensewise_app` holds DELETE on every tenant table; only the audit log refuses changes. Revoke DELETE on expenses, reports, receipts, readings and approvals, or add a trigger that refuses it, with a test. Nothing deletes them today.',
    priority: 'P3',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    source: 'GAP-10',
    affects: ['GAP-10', 'NFR-DAT-05'],
  },
  {
    num: 34,
    title: 'A breaking API change would pass CI',
    type: 'Gap',
    detail:
      'Diff `openapi.json` against `main` in G3 and fail on a breaking change without a new version. It matters from the first iPhone build; cheap to add now.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-11',
    affects: ['GAP-11', 'NFR-ARC-04', 'NFR-DEL-01'],
  },
  {
    num: 35,
    title: 'Retention and legal hold have no design',
    type: 'Decision',
    detail:
      'Seven years by default, configurable, with legal hold, promised for Phase 0. Your answer to Q2 sets the scope; then an ADR and the fields.',
    priority: 'P3',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your decision: Q2' },
    source: 'GAP-12',
    affects: ['GAP-12', 'NFR-PRV-01'],
  },
  {
    num: 36,
    title: 'Subprocessor agreements are unconfirmed',
    type: 'Decision',
    detail:
      'Supabase, Vercel, Inngest and Anthropic see receipts today, and OpenAI on the fallback path. Your answer to Q3 decides whether their standard terms are enough for Phase 1.',
    priority: 'P3',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your decision: Q3' },
    source: 'GAP-13',
    affects: ['GAP-13', 'NFR-PRV-04'],
  },
  {
    num: 37,
    title: 'A field doesn’t show where it came from, or take a correction',
    type: 'Gap',
    detail:
      'Ask the model for each field’s source line, highlight it on the receipt, and let one tap correct the value. Each correction becomes an eval candidate.',
    priority: 'P3',
    effort: 'M',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-14, design DP3',
    affects: ['GAP-14', 'FR-INT-11'],
  },
  {
    num: 38,
    title: 'Nothing proves the model is called without tools',
    type: 'Gap',
    detail:
      'Receipts are untrusted input. Assert in the extractor tests that no tools are sent, so adding one fails CI.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    source: 'GAP-15',
    affects: ['GAP-15', 'NFR-SEC-07'],
  },
  {
    num: 39,
    title: 'The eval set has no real-world layer',
    type: 'Decision',
    detail:
      'D-12 is still Proposed: may I search your Gmail for past travel receipts to label? The Gmail connector also needs authorizing in your claude.ai settings. Real captures can join the set either way.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'owner', ask: 'Your decision on D-12, and the Gmail connector' },
    source: 'ADR-0012',
    affects: ['NFR-AI-01'],
  },

  {
    num: 49,
    title: 'One dependency advisory is let through until it has a fix',
    type: 'Security',
    detail:
      'braces’ high advisory (GHSA-vfj7-8cjw-p6xm) has no fixed version, so the audit ignores it (pnpm-workspace.yaml). It reaches us only through lint tooling. When Advisory watch fails on a Monday, a fix exists: update to it, remove the ignore and close GAP-19.',
    priority: 'P3',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none', note: 'Waits on an upstream fix; Advisory watch says when' },
    source: 'GAP-19',
    affects: ['GAP-19', 'NFR-SEC-12'],
  },
  {
    num: 51,
    title: 'Categories and types an organization defines',
    type: 'Feature',
    detail:
      'Owners and finance admins define expense categories and the types inside them, and every expense gets a type. An organization starts from a ready-made set it can rename, add to or retire; a type in use is retired, never deleted, so old claims keep it. Its shape waits on your answer to Q7.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your answer to Q7: what a type is beside a category' },
    source: 'Product owner, Oct 3',
    affects: ['FR-EXP-11', 'F-43', 'FR-INT-10', 'F-15'],
  },
  {
    num: 52,
    title: 'Turn AI models on and off',
    type: 'Feature',
    detail:
      'A switch for each AI model in Settings, for owners and finance admins, recorded in the audit trail. The reading workflow asks only the models that are on; a model with no key stays off. Read again uses the switches as they are then. Its shape waits on your answer to Q8.',
    priority: 'P2',
    effort: 'M',
    severity: 'Medium',
    blocker: { kind: 'owner', ask: 'Your answer to Q8: what turning a model off covers' },
    source: 'Product owner, Oct 3',
    affects: ['FR-INT-16', 'F-45', 'FR-INT-08', 'FR-INT-09'],
  },
  // Done
  {
    num: 40,
    title: 'Two sign-ins couldn’t reach the same receipts',
    type: 'Feature',
    detail:
      'Your Gmail and work addresses each made their own organization. A member can now have several sign-ins, linked with proof of both (ADR-0016).',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none' },
    affects: ['FR-PLT-04', 'F-03'],
    done: { date: '2026-10-02', in: 'PR #15' },
  },
  {
    num: 41,
    title: 'Migrations re-set role passwords and broke the pooler',
    type: 'Gap',
    detail:
      'Every migration run re-set the runtime passwords, and the pooler kept the old ones. Passwords are now set only when a role can’t sign in.',
    priority: 'P1',
    effort: 'S',
    severity: 'High',
    blocker: { kind: 'none' },
    affects: ['F-34'],
    done: { date: '2026-10-02', in: 'PR #14' },
  },
  {
    num: 42,
    title: 'A build went live before its migration',
    type: 'Ops',
    detail:
      'Vercel published each build on its own while migrations waited. A release now migrates first, then promotes that commit’s build and checks it is live (ADR-0018).',
    priority: 'P1',
    effort: 'M',
    severity: 'High',
    blocker: { kind: 'none' },
    affects: ['NFR-DEL-03', 'NFR-REL-07', 'F-36'],
    done: { date: '2026-10-02', in: 'PR #17' },
  },
  {
    num: 43,
    title: 'Saving a key said “Anthropic could not be reached” when it had answered',
    type: 'Gap',
    detail:
      'Pasted keys are now cleaned, every answer is classified (rejected, refused, unreachable) and the provider’s own message is shown.',
    priority: 'P1',
    effort: 'S',
    severity: 'Medium',
    blocker: { kind: 'none' },
    affects: ['FR-PLT-05', 'F-04'],
    done: { date: '2026-10-02', in: 'PR #18' },
  },
  {
    num: 44,
    title: 'Every release waited on a second approval click',
    type: 'Ops',
    detail:
      'Your word to merge is now the release approval; the Release run starts straight after the merge (ADR-0019).',
    priority: 'P2',
    effort: 'S',
    severity: 'Low',
    blocker: { kind: 'none' },
    affects: ['NFR-DEL-04'],
    done: { date: '2026-10-02', in: 'PR #19' },
  },
  {
    num: 45,
    title: 'The model tier would have been chosen on synthetic receipts',
    type: 'Feature',
    detail:
      'The receipt page reads each of your receipts with Haiku and Sonnet side by side, so the tier decision rests on your own receipts (ADR-0017).',
    priority: 'P1',
    effort: 'L',
    severity: 'Medium',
    blocker: { kind: 'none' },
    affects: ['FR-INT-08', 'F-06', 'F-07'],
    done: { date: '2026-10-02', in: 'PR #16' },
  },
];

/** How to order the open work, beyond priority. */
export const SEQUENCING: readonly string[] = [
  'Your order, Oct 3: #47, then #16, then #10, with #6 before #16 because trips need expenses. #47 and #6 are done, so #16 is next, then #10. Claude’s recommendation was #10 first, since until a backup has been restored it is only a hope; keep the paper or email originals until it passes.',
  '#3 needs you, not code. So does #48, which keeps a leaked key from erasing the backups; any time this month. #4 can wait: the OpenAI fallback reads receipts meanwhile, and #21 waits on it.',
  'With #6 done, increment 2 (#16–#19) and the dashboard (#28) are open. #9 should come soon: receipts and expenses that need a look have nowhere to gather yet. #7 is small and touches the same code.',
  '#8 is security, not polish: it should land before #24, which needs it, and before anyone else is invited (#29).',
  '#11–#15 are small, independent and each closes a gap; take them between features.',
];
