import type { Feature } from './model.ts';

/**
 * What a person can do, or what the product stands on, shipped or planned. Every API
 * operation, web page, workflow function and feature flag in the code is claimed by exactly
 * one feature here; `integrity.ts` fails when something new appears unclaimed.
 */
export const FEATURES: readonly Feature[] = [
  // Access and organizations
  {
    id: 'F-01',
    title: 'Sign in with email and password',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #13',
    decisions: ['ADR-0013'],
    code: ['apps/web/app/sign-in/page.tsx', 'apps/web/lib/supabase.ts', 'packages/api/src/auth.ts'],
    api: ['GET /v1/me'],
    screens: ['/sign-in'],
    checks: ['api/auth', 'e2e/settings › serves the sign-in page'],
    note: 'Password only for now; the second factor is F-11.',
  },
  {
    id: 'F-02',
    title: "The owner's one-person organization, created on first sign-in",
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #13',
    decisions: ['ADR-0001', 'ADR-0015'],
    code: ['packages/db/src/members.ts', 'packages/api/src/workspace-routes.ts'],
    api: ['POST /v1/me/organization'],
    checks: [
      'api/workspace › creates the organization on first sign-in, then returns it',
      'db/ai-keys.int › creates exactly one organization when first sign-ins race',
    ],
  },
  {
    id: 'F-03',
    title: 'Several sign-ins for one person',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #15',
    decisions: ['ADR-0016'],
    code: ['packages/db/src/sign-ins.ts', 'apps/web/app/settings/sign-ins/page.tsx'],
    api: ['GET /v1/me/sign-ins', 'POST /v1/me/sign-ins', 'DELETE /v1/me/sign-ins/{signInId}'],
    screens: ['/settings/sign-ins'],
    checks: ['api/workspace › links a second sign-in with proof of both, once', 'db/sign-ins.int'],
  },
  {
    id: 'F-04',
    title: 'AI provider keys in Settings: checked on save, stored encrypted',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #13, PR #18',
    decisions: ['ADR-0015'],
    code: [
      'packages/api/src/ai-providers.ts',
      'packages/api/src/secret-box.ts',
      'packages/api/src/provider-keys.ts',
      'packages/db/src/ai-keys.ts',
      'apps/web/app/settings/ai/page.tsx',
    ],
    api: [
      'GET /v1/settings/ai-providers',
      'PUT /v1/settings/ai-providers/{provider}',
      'DELETE /v1/settings/ai-providers/{provider}',
      'POST /v1/settings/ai-providers/{provider}/test',
    ],
    screens: ['/settings/ai'],
    checks: [
      'api/ai-providers',
      'api/secret-box',
      'api/workspace › checks a key with the provider, stores it encrypted and never returns it',
      'db/ai-keys.int › saves, replaces, verifies and removes a key within one organization',
    ],
  },
  {
    id: 'F-11',
    title: 'Second factor at sign-in (TOTP), and step-up before approving',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    decisions: ['ADR-0013'],
    backlog: 8,
  },
  {
    id: 'F-23',
    title: 'Invites and roles (the whole Phase 1 admin console)',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 29,
  },

  // Receipts
  {
    id: 'F-05',
    title: 'Capture a receipt: camera, upload or PDF',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #16',
    decisions: ['ADR-0017', 'ADR-0013', 'ADR-0014'],
    code: [
      'apps/web/app/receipts/page.tsx',
      'apps/web/lib/receipt-file.ts',
      'apps/web/lib/receipts.ts',
      'packages/api/src/receipt-routes.ts',
      'packages/db/src/receipts.ts',
      'packages/storage/src',
    ],
    api: ['POST /v1/receipts/uploads', 'POST /v1/receipts', 'GET /v1/receipts'],
    screens: ['/receipts'],
    checks: [
      'api/receipts › hands out a one-time upload for a path inside the organization',
      'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
      'api/receipts › refuses a file that is already filed, before and after upload',
      'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
      'storage/supabase',
      'e2e/receipts',
    ],
  },
  {
    id: 'F-06',
    title: 'Read each receipt with two models, side by side',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #9, PR #16',
    decisions: ['ADR-0006', 'ADR-0017'],
    code: [
      'packages/extraction/src',
      'packages/workflows/src/receipts.ts',
      'packages/workflows/src/receipt-ports.ts',
      'packages/api/src/receipt-views.ts',
      'apps/web/app/receipts/[id]/page.tsx',
    ],
    api: ['GET /v1/receipts/{receiptId}', 'POST /v1/receipts/{receiptId}/read'],
    screens: ['/receipts/[id]'],
    workflows: ['receipt-reading'],
    checks: [
      'workflows/receipts',
      'extraction/claude',
      'extraction/anthropic',
      'extraction/normalize',
      'extraction/review',
      'api/receipts › shows both readings, where they differ, and money as minor units',
      "api/receipts › shows tax and tip the receipt doesn't print as zero, marked as assumed",
      'db/receipts.int › records each model once per request, then settles once',
    ],
  },
  {
    id: 'F-07',
    title: 'Running model comparison for the tier decision',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Partial',
    delivered: 'PR #16',
    decisions: ['ADR-0006', 'ADR-0017'],
    code: ['packages/api/src/receipt-views.ts', 'packages/extraction/src/models.ts'],
    checks: ['api/receipts › keeps a running comparison of the two models', 'extraction/models'],
    shortfalls: ['#4', '#21'],
    note: 'Collecting nothing while the Anthropic account has no credit.',
  },
  {
    id: 'F-08',
    title: "Fallback reader: GPT-5.6 Luna reads when Claude can't",
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #20',
    decisions: ['ADR-0020'],
    code: [
      'packages/extraction/src/openai.ts',
      'packages/workflows/src/receipts.ts',
      'packages/api/src/receipt-views.ts',
    ],
    checks: [
      'extraction/openai',
      'workflows/receipts › reads the receipt when Anthropic has no credit, and asks for a look',
      'workflows/receipts › reads the receipt when the Claude steps run out of retries',
      'workflows/receipts › is not called when a Claude model read the receipt',
      'api/receipts › shows the fallback reading when no Claude model could read the receipt',
    ],
    note: 'Read its first real receipt on Oct 2 (#46).',
  },
  {
    id: 'F-40',
    title: 'Confirm or correct a reading that needs a look',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #26',
    decisions: ['ADR-0021'],
    api: ['POST /v1/receipts/{receiptId}/confirm'],
    code: [
      'packages/extraction/src/confirm.ts',
      'packages/db/src/receipts.ts',
      'packages/db/migrations/0010_receipt_reviews.sql',
      'packages/db/migrations/0011_receipt_reviews_rls.sql',
      'packages/api/src/receipt-routes.ts',
      'apps/web/app/receipts/[id]/page.tsx',
    ],
    checks: [
      'extraction/confirm',
      'db/receipts.int › makes it Ready with the values, the corrections and an audit event, together',
      'db/receipts.int › refuses a receipt that is no longer waiting, or was read again since',
      'db/receipts.int › keeps reviews inside their organization, and never edits or deletes one',
      'api/receipts › makes the fallback reading Ready with Looks right, and says who confirmed it',
      'api/receipts › files corrected fields with Edit a field, keeping what the model read',
      'api/receipts › names the field that is not valid, or the filing fields still missing',
      'api/receipts › starts over when the receipt is read again',
      'api/receipts › lets a receipt no model could read be filled in by hand',
    ],
    note: 'Looks right and Edit a field on the receipt page. Since #6 a receipt no model could read can be filled in by hand too, so its expense is never stuck (ADR-0022). The confirmed values are stored apart from the readings, in typed columns; each correction keeps what the model read, as an eval candidate (ADR-0012). The page itself was checked by hand: the end-to-end tests run signed out.',
  },
  {
    id: 'F-16',
    title: 'Email-in forwarding address for travel and ride receipts',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    decisions: ['ADR-0011'],
    backlog: 19,
  },

  // Expenses, trips and reports
  {
    id: 'F-09',
    title: 'A Ready reading becomes a Ready expense',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #28',
    decisions: ['ADR-0022'],
    api: ['GET /v1/expenses', 'GET /v1/expenses/{expenseId}', 'PATCH /v1/expenses/{expenseId}'],
    screens: ['/expenses', '/expenses/[id]'],
    code: [
      'packages/domain/src/expense-values.ts',
      'packages/extraction/src/proof.ts',
      'packages/db/src/expenses.ts',
      'packages/db/migrations/0012_expense_edited_at.sql',
      'packages/api/src/expense-routes.ts',
      'apps/web/app/expenses/[id]/page.tsx',
    ],
    checks: [
      'domain/expense-values',
      'extraction/proof',
      'db/expenses.int',
      'api/expenses',
      'e2e/expenses',
      'workflows/receipts › files it as Ready when both read it with confidence and agree',
    ],
    note: 'Every receipt has an expense from capture, linked as its proof. It follows the receipt until a person edits it, and is Ready only when its receipt is Ready and the claim is complete. Receipts filed before this get their expense on release.',
  },
  {
    id: 'F-10',
    title: 'The Needs you inbox, with real items',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 9,
  },
  {
    id: 'F-12',
    title: 'Trips, trip history and search',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 16,
  },
  {
    id: 'F-13',
    title: 'Manual mileage, with the rate snapshotted',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 17,
  },
  {
    id: 'F-14',
    title: 'Route-based mileage',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 20,
  },
  {
    id: 'F-43',
    title: 'Expense categories and types',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 51,
  },
  {
    id: 'F-15',
    title: 'Category suggestions',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 18,
  },
  {
    id: 'F-17',
    title: 'Reports drafted 48 hours after a trip ends',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 23,
  },
  {
    id: 'F-18',
    title: 'Single-step approval: self-attestation solo, separation of duties in teams',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 24,
  },
  {
    id: 'F-19',
    title: 'CSV and PDF export',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 25,
  },
  {
    id: 'F-20',
    title: 'Audit trail view',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 26,
  },
  {
    id: 'F-22',
    title: 'Personal dashboard',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 28,
  },

  // Domain rules: built and tested ahead of the screens that will use them
  {
    id: 'F-24',
    title: 'Money, decimals, FX, dates and ids',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0008'],
    code: [
      'packages/domain/src/money.ts',
      'packages/domain/src/decimal.ts',
      'packages/domain/src/fx.ts',
      'packages/domain/src/dates.ts',
      'packages/domain/src/ids.ts',
      'packages/domain/src/currency.ts',
    ],
    checks: ['domain/money', 'domain/decimal', 'domain/fx', 'domain/dates', 'domain/ids'],
  },
  {
    id: 'F-25',
    title: 'Mileage reimbursement: the rate in force on the day, snapshotted',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0008'],
    code: ['packages/domain/src/mileage.ts'],
    checks: ['domain/mileage'],
  },
  {
    id: 'F-26',
    title: 'Expense and report lifecycles',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    code: ['packages/domain/src/lifecycle'],
    checks: ['domain/lifecycle/expense', 'domain/lifecycle/report'],
  },
  {
    id: 'F-27',
    title: 'Who may approve: canApprove()',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0001'],
    code: ['packages/domain/src/approvals.ts'],
    checks: ['domain/approvals'],
  },
  {
    id: 'F-28',
    title: 'Append-only, hash-chained audit log',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0008'],
    code: [
      'packages/domain/src/audit.ts',
      'packages/db/src/audit.ts',
      'packages/db/migrations/0001_tenant_isolation_and_audit.sql',
    ],
    checks: ['domain/audit', 'db/audit.int'],
  },

  // Platform and operations
  {
    id: 'F-29',
    title: 'App shell: the inbox layout and five-destination tab bar',
    group: 'Platform and operations',
    kind: 'product',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0004'],
    code: ['apps/web/app/page.tsx', 'apps/web/app/layout.tsx', 'apps/web/next.config.ts'],
    screens: ['/'],
    checks: [
      'e2e/shell › opens on the inbox with the five-destination tab bar',
      'e2e/shell › sends security headers',
    ],
  },
  {
    id: 'F-30',
    title: 'Health and readiness checks',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1, PR #8',
    code: ['packages/api/src/routes', 'packages/db/src/readiness.ts'],
    api: ['GET /v1/health', 'GET /v1/health/ready'],
    checks: [
      'api/api › reports health and the deployed version',
      'api/ready',
      'db/readiness',
      'db/readiness.int',
      'e2e/shell › reports readiness with a status that matches the report',
    ],
  },
  {
    id: 'F-31',
    title: 'Feature flags, off by default',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #11',
    code: ['packages/flags/src'],
    flags: ['shell.build-version'],
    checks: [
      'flags/flags',
      'flags/posthog',
      'e2e/shell › ships the build-version change dark: its flag is off by default',
    ],
  },
  {
    id: 'F-32',
    title: 'Error tracking, with secrets redacted',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Partial',
    delivered: 'PR #11',
    code: [
      'apps/web/sentry.shared.ts',
      'apps/web/sentry.server.config.ts',
      'apps/web/instrumentation.ts',
      'apps/web/instrumentation-client.ts',
      'packages/api/src/redact.ts',
    ],
    checks: ['api/redact'],
    shortfalls: ['GAP-07'],
  },
  {
    id: 'F-33',
    title: 'Outbox, eager dispatch and the workflow runner',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Partial',
    delivered: 'PR #11, PR #16',
    decisions: ['ADR-0002', 'ADR-0017'],
    code: [
      'packages/db/src/outbox.ts',
      'packages/workflows/src/relay.ts',
      'packages/workflows/src/functions.ts',
      'apps/web/app/api/inngest/route.ts',
    ],
    workflows: ['outbox-relay'],
    checks: [
      'workflows/relay',
      'workflows/functions',
      'db/outbox.int',
      'api/receipts › still files the receipt when the runner is unreachable; the relay sends it later',
    ],
    shortfalls: ['GAP-05', 'GAP-06'],
  },
  {
    id: 'F-34',
    title: 'Tenant isolation and the database roles',
    group: 'Platform and operations',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1, PR #7, PR #14',
    decisions: ['ADR-0013'],
    code: [
      'packages/db/src/client.ts',
      'packages/db/src/connection.ts',
      'packages/db/src/role-passwords.ts',
      'packages/db/migrations/0002_supabase_data_api_lockdown.sql',
    ],
    checks: [
      'db/tenancy.int',
      'db/supabase-roles.int',
      'db/connection',
      'db/role-passwords',
      'db/role-passwords.int',
    ],
  },
  {
    id: 'F-35',
    title: 'Quality gates G1–G5 on every push',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Partial',
    delivered: 'PR #1, PR #7',
    decisions: ['ADR-0009'],
    code: ['.github/workflows/ci.yml', '.github/workflows/codeql.yml'],
    checks: ['ci:static', 'ci:unit', 'ci:integration', 'ci:security', 'ci:e2e', 'ci:codeql'],
    shortfalls: ['GAP-11'],
  },
  {
    id: 'F-36',
    title: 'Release: migrate, promote this commit, verify it is live',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Partial',
    delivered: 'PR #17, PR #19',
    decisions: ['ADR-0018', 'ADR-0019'],
    code: [
      '.github/workflows/release.yml',
      '.github/scripts/promote-production.mjs',
      'packages/db/src/set-role-passwords.ts',
    ],
    shortfalls: ['GAP-09'],
  },
  {
    id: 'F-37',
    title: 'Nightly encrypted off-site backup',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Partial',
    delivered: 'PR #23',
    decisions: ['ADR-0014'],
    code: ['.github/workflows/backup.yml', 'scripts/backup/backup.sh'],
    shortfalls: ['#10', 'GAP-18'],
    note: 'Runs every night since Oct 3; each run downloads its upload again and checks it decrypts to the same dump. Rehearsed on Oct 2 against Supabase’s Postgres 17 image: the dump restored with every row count, the auth user and both image checksums matching. On Oct 3 you decrypted the first copy with the passphrase from your password manager. Not yet restored from production (#10).',
  },
  {
    id: 'F-42',
    title: 'Heartbeat and Free plan quota alerts',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #23',
    decisions: ['ADR-0014'],
    code: [
      'packages/db/migrations/0009_ops_heartbeat.sql',
      'scripts/backup/backup.sh',
      '.github/workflows/backup.yml',
    ],
    checks: ['db/heartbeat.int'],
    note: 'The nightly job writes the heartbeat before anything else, then fails at 70% of the 500 MB database or 1 GB storage limit, and GitHub emails the owner; that email reached you for the first, failed run on Oct 3. The quota alert was rehearsed by hand, not in CI.',
  },
  {
    id: 'F-41',
    title: 'Monthly restore drill',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Planned',
    decisions: ['ADR-0014'],
    backlog: 10,
  },
  {
    id: 'F-38',
    title: 'Extraction eval harness: public and synthetic layers',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #9',
    decisions: ['ADR-0006', 'ADR-0012'],
    code: ['evals/src'],
    checks: ['evals/score', 'evals/datasets/cord', 'evals/synthetic/synthetic'],
  },
  {
    id: 'F-21',
    title: 'Email notifications',
    group: 'Platform and operations',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 27,
  },
  {
    id: 'F-39',
    title: 'These records: requirements, traceability and backlog pages',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #21',
    code: ['tools/records/src', 'CLAUDE.md', '.claude/hooks/after-merge.sh'],
    checks: ['records/integrity', 'records/render'],
  },
];
