import type { Feature } from './model.ts';

/**
 * What a person can do, or what the product stands on, shipped or planned. Every API
 * operation, web page, workflow function and feature flag in the code is claimed by exactly
 * one feature here; `integrity.ts` fails when something new appears unclaimed.
 */
export const FEATURES: readonly Feature[] = [
  // Access and organizations
  {
    id: 'F-01',
    title: 'Sign in with email and password',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #13',
    decisions: ['ADR-0013'],
    code: ['apps/web/app/sign-in/page.tsx', 'apps/web/lib/supabase.ts', 'packages/api/src/auth.ts'],
    api: ['GET /v1/me'],
    screens: ['/sign-in'],
    checks: ['api/auth', 'e2e/settings › serves the sign-in page'],
    note: 'Password only for now; the second factor is F-11.',
  },
  {
    id: 'F-02',
    title: "The owner's one-person organization, created on first sign-in",
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #13',
    decisions: ['ADR-0001', 'ADR-0015'],
    code: ['packages/db/src/members.ts', 'packages/api/src/workspace-routes.ts'],
    api: ['POST /v1/me/organization'],
    checks: [
      'api/workspace › creates the organization on first sign-in, then returns it',
      'db/ai-keys.int › creates exactly one organization when first sign-ins race',
    ],
  },
  {
    id: 'F-03',
    title: 'Several sign-ins for one person',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #15',
    decisions: ['ADR-0016'],
    code: ['packages/db/src/sign-ins.ts', 'apps/web/app/settings/sign-ins/page.tsx'],
    api: ['GET /v1/me/sign-ins', 'POST /v1/me/sign-ins', 'DELETE /v1/me/sign-ins/{signInId}'],
    screens: ['/settings/sign-ins'],
    checks: ['api/workspace › links a second sign-in with proof of both, once', 'db/sign-ins.int'],
  },
  {
    id: 'F-04',
    title: 'AI provider keys in Settings: checked on save, stored encrypted',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #13, PR #18',
    decisions: ['ADR-0015'],
    code: [
      'packages/api/src/ai-providers.ts',
      'packages/api/src/secret-box.ts',
      'packages/api/src/provider-keys.ts',
      'packages/db/src/ai-keys.ts',
      'apps/web/app/settings/ai/page.tsx',
    ],
    api: [
      'GET /v1/settings/ai-providers',
      'PUT /v1/settings/ai-providers/{provider}',
      'DELETE /v1/settings/ai-providers/{provider}',
      'POST /v1/settings/ai-providers/{provider}/test',
    ],
    screens: ['/settings/ai'],
    checks: [
      'api/ai-providers',
      'api/secret-box',
      'api/workspace › checks a key with the provider, stores it encrypted and never returns it',
      'db/ai-keys.int › saves, replaces, verifies and removes a key within one organization',
    ],
  },
  {
    id: 'F-11',
    title: 'Second factor at sign-in (TOTP), and step-up before approving',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    decisions: ['ADR-0013'],
    backlog: 8,
  },
  {
    id: 'F-23',
    title: 'Invites and roles (the whole Phase 1 admin console)',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0035', 'ADR-0016'],
    code: [
      'packages/domain/src/people.ts',
      'packages/db/src/people.ts',
      'packages/api/src/people.ts',
      'packages/api/src/people-routes.ts',
      'apps/web/app/settings/people/page.tsx',
      'apps/web/app/invite/[token]/page.tsx',
      'apps/web/lib/people.ts',
    ],
    api: [
      'GET /v1/settings/people',
      'POST /v1/settings/people/invites',
      'DELETE /v1/settings/people/invites/{inviteId}',
      'PATCH /v1/settings/people/{memberId}',
      'DELETE /v1/settings/people/{memberId}',
      'POST /v1/invites/look-up',
      'POST /v1/invites/accept',
    ],
    screens: ['/settings/people', '/invite/[token]'],
    flags: ['team.invites'],
    checks: [
      'api/people',
      'db/people.int',
      'domain/people › work for 7 days from when they are made',
      'api/own-records.int › works for its owner as before, and joining another replaces it while it is empty',
      'e2e/signed-in',
    ],
    note: 'By link, your choice of Oct 4: no email is sent. Sign-ups stay off, so the owner makes the person’s account in Supabase first and the screen says so. Only owners manage people.',
  },
  {
    id: 'F-61',
    title: 'Members see and change only their own records',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0035'],
    code: [
      'packages/db/src/client.ts',
      'packages/api/src/caller.ts',
      'packages/domain/src/people.ts',
    ],
    checks: [
      'db/own-records.int',
      'api/own-records.int',
      'domain/people › lets owners, finance admins and auditors see everyone’s, and members and approvers their own',
    ],
    note: 'No flag: a security control, on before anyone is invited (#50). Enforced by Postgres for every request a member makes; background work acts for the system. An approver sees only their own records until approval routes reports to them (#24). Whether owners and finance admins should change others’ records, or list them, is Q30.',
  },
  {
    id: 'F-51',
    title: 'Organization details in Settings',
    group: 'Access and organizations',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0037', 'ADR-0029', 'ADR-0032'],
    code: [
      'packages/domain/src/organization.ts',
      'packages/domain/src/time-zones.ts',
      'packages/domain/src/reports.ts',
      'packages/db/src/organizations.ts',
      'packages/db/src/reports.ts',
      'packages/db/migrations/0023_organization_settings.sql',
      'packages/db/migrations/0024_report_work_due_time_zone.sql',
      'packages/api/src/organization.ts',
      'packages/api/src/organization-routes.ts',
      'packages/api/src/routes/organization.ts',
      'apps/web/app/settings/organization/page.tsx',
    ],
    api: ['GET /v1/settings/organization', 'PATCH /v1/settings/organization'],
    screens: ['/settings/organization'],
    flags: ['settings.organization'],
    checks: [
      'domain/organization',
      'domain/time-zones',
      'domain/reports › in the organization’s time zone, waits 24 hours after its day ends there (FR-PLT-11)',
      'domain/reports › in the organization’s time zone, closes on its day 28 at the time it opened there',
      'db/organizations.int',
      'api/organization',
      'e2e/signed-in',
      'e2e/settings',
    ],
    note: 'Settings › Organization opens with the role of whoever is signed in, then the details the owner keeps: name, home currency, country, locale, time zone, address, industry and size. Everyone else reads them. Each change is one audit event, from and to. With the feature on and a time zone kept, the report schedule counts the organization’s days in it: something joins 24 hours after its day ends there, day 28 is on its calendar, and a report is named by its date (ADR-0037). A new home currency opens reports in it from then on; nothing already made is converted. The locale is kept but nothing formats by it yet. The page shows while this feature or the duplicate window (F-52) is on, each section only with its own.',
  },

  // Receipts
  {
    id: 'F-05',
    title: 'Capture a receipt: camera, upload or PDF',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #16',
    decisions: ['ADR-0017', 'ADR-0013', 'ADR-0014'],
    code: [
      'apps/web/app/receipts/page.tsx',
      'apps/web/lib/receipt-file.ts',
      'apps/web/lib/receipts.ts',
      'packages/api/src/receipt-routes.ts',
      'packages/db/src/receipts.ts',
      'packages/storage/src',
    ],
    api: ['POST /v1/receipts/uploads', 'POST /v1/receipts', 'GET /v1/receipts'],
    screens: ['/receipts'],
    checks: [
      'api/receipts › hands out a one-time upload for a path inside the organization',
      'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
      'api/receipts › refuses a file that is already filed, before and after upload',
      'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
      'storage/supabase',
      'e2e/receipts',
    ],
  },
  {
    id: 'F-06',
    title: 'Read each receipt with two models, side by side',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #9, PR #16, PR #40',
    decisions: ['ADR-0006', 'ADR-0017'],
    code: [
      'packages/extraction/src',
      'packages/workflows/src/receipts.ts',
      'packages/workflows/src/receipt-ports.ts',
      'packages/api/src/receipt-views.ts',
      'apps/web/app/receipts/[id]/page.tsx',
    ],
    api: ['GET /v1/receipts/{receiptId}', 'POST /v1/receipts/{receiptId}/read'],
    screens: ['/receipts/[id]'],
    workflows: ['receipt-reading'],
    checks: [
      'workflows/receipts',
      'extraction/claude',
      'extraction/anthropic',
      'extraction/normalize',
      'extraction/review',
      'extraction/checks',
      'extraction/schema',
      'api/receipts › shows both readings, where they differ, and money as minor units',
      "api/receipts › shows tax and tip the receipt doesn't print as zero, marked as assumed",
      'db/receipts.int › records each model once per request, then settles once',
    ],
  },
  {
    id: 'F-07',
    title: 'Running model comparison for the tier decision',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #16; the tier chosen with it in PR #58',
    decisions: ['ADR-0006', 'ADR-0017'],
    code: [
      'packages/api/src/receipt-views.ts',
      'packages/extraction/src/models.ts',
      'packages/domain/src/capture-time.ts',
      'packages/api/src/receipt-evidence.ts',
      'packages/db/src/receipts.ts',
      'packages/db/migrations/0025_receipt_settled_at.sql',
      'packages/db/migrations/0026_receipt_settled_at_backfill.sql',
      'apps/web/app/receipts/page.tsx',
    ],
    checks: [
      'api/receipts › keeps a running comparison of the two models',
      'extraction/models',
      'domain/capture-time',
      'db/receipt-corrections.int › keeps when the first reading settled, never before filing, and not a later one',
      'db/receipt-corrections.int › fills the time of receipts read before it was kept, from the audit trail, once',
      'api/receipts › shows the 95th percentile beside the comparison, over the receipts read, with the feature on',
      'api/receipts › is left out with the feature off, so Receipts is as it was',
      'api/model-settings › shows each model, the primary, what each does now and how each has read our receipts',
    ],
    note: 'The tier decision (#21) is now your choice of primary in Settings › AI models (F-45), with each model’s record from this comparison beside it. With AI model settings on, one model reads each receipt, so the two-model agreement stops growing while each model’s own record keeps counting. Claude reads nothing while the Anthropic account has no credit, which you chose on Oct 4 not to buy (#4, withdrawn). Since PR #58 each receipt keeps when its first reading settled, and with Capture-to-Ready time switched on the comparison shows the 95th-percentile time from capture to read over the receipts shown, against the 30-second goal (GAP-16, NFR-PERF-01).',
    flags: ['receipts.capture-time'],
  },
  {
    id: 'F-08',
    title: "Fallback reader: GPT-5.6 Luna reads when Claude can't",
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #20',
    decisions: ['ADR-0020'],
    code: [
      'packages/extraction/src/openai.ts',
      'packages/workflows/src/receipts.ts',
      'packages/api/src/receipt-views.ts',
    ],
    checks: [
      'extraction/openai',
      'workflows/receipts › reads the receipt when Anthropic has no credit, and asks for a look',
      'workflows/receipts › reads the receipt when the Claude steps run out of retries',
      'workflows/receipts › is not called when a Claude model read the receipt',
      'api/receipts › shows the fallback reading when no Claude model could read the receipt',
    ],
    note: 'Read its first real receipt on Oct 2 (#46). Still how an organization reads with AI model settings off; with them on, GPT-5.6 Luna is a model like the others, primary or back-up (F-45, ADR-0033).',
  },
  {
    id: 'F-40',
    title: 'Confirm or correct a reading, and see where each field was read',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #26, PR #58',
    decisions: ['ADR-0021', 'ADR-0022'],
    api: ['POST /v1/receipts/{receiptId}/confirm', 'POST /v1/receipts/{receiptId}/corrections'],
    code: [
      'packages/extraction/src/confirm.ts',
      'packages/extraction/src/variant.ts',
      'packages/extraction/src/prompt.ts',
      'packages/extraction/src/schema.ts',
      'packages/db/src/receipts.ts',
      'packages/db/src/receipt-corrections.ts',
      'packages/db/migrations/0010_receipt_reviews.sql',
      'packages/db/migrations/0011_receipt_reviews_rls.sql',
      'packages/workflows/src/features.ts',
      'packages/workflows/src/receipt-ports.ts',
      'packages/api/src/receipt-routes.ts',
      'packages/api/src/receipt-evidence.ts',
      'apps/web/app/receipts/[id]/page.tsx',
    ],
    checks: [
      'extraction/claude › asks for the line each field was read from only when told to, under its own versions',
      'extraction/claude › sends exactly the prompt and schema of receipt-v3 when source lines are not asked for',
      'extraction/openai › asks for source lines in strict mode only when told to, and keeps them',
      'extraction/openai › sends the receipt-v3 prompt and schema unchanged when source lines are not asked for',
      'extraction/schema › reads the line behind each field of a reading that has them, and none from one without',
      'workflows/features',
      'workflows/receipts › stores the line each field was read from with the reading, under the version asked',
      'api/receipts › shows the line each field was read from beside it, with the feature on',
      'api/receipts › shows no source lines and takes no correction with the feature off, as before',
      'api/receipts › corrects a field of a Ready receipt through its expense, keeping what the model read',
      'api/receipts › refuses a receipt not Ready, a locked expense, a value not valid, and one filed so already',
      'db/receipt-corrections.int › files the correction, edits its expense and records both, together',
      'db/receipt-corrections.int › refuses one not Ready, read again since, or locked, and leaves nothing behind',
      'extraction/confirm',
      'db/receipts.int › makes it Ready with the values, the corrections and an audit event, together',
      'db/receipts.int › refuses a receipt that is no longer waiting, or was read again since',
      'db/receipts.int › keeps reviews inside their organization, and never edits or deletes one',
      'api/receipts › makes the fallback reading Ready with Looks right, and says who confirmed it',
      'api/receipts › files corrected fields with Edit a field, keeping what the model read',
      'api/receipts › names the field that is not valid, or the filing fields still missing',
      'api/receipts › starts over when the receipt is read again',
      'api/receipts › lets a receipt no model could read be filled in by hand',
    ],
    note: 'Looks right and Edit a field on the receipt page. Since #6 a receipt no model could read can be filled in by hand too, so its expense is never stuck (ADR-0022). The confirmed values are stored apart from the readings, in typed columns; each correction keeps what the model read, as an eval candidate (ADR-0012). Since PR #58, with Where each field was read switched on, each model is asked for the line of the receipt behind each field (`extract-v4`, `receipt-v4`), shown as text beside the value, and a Ready receipt’s field is corrected with a tap through its expense, until the expense is submitted (GAP-14). Organizations with it off are asked exactly what they were before.',
    flags: ['receipts.field-sources'],
  },
  {
    id: 'F-16',
    title: 'Email-in: receipts and purchase summaries by email',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #44, PR #45',
    decisions: ['ADR-0011', 'ADR-0024', 'ADR-0026', 'ADR-0027'],
    code: [
      'packages/api/src/inbound-routes.ts',
      'packages/api/src/routes/inbound.ts',
      'packages/api/src/webhooks.ts',
      'packages/workflows/src/email.ts',
      'packages/workflows/src/email-pdf.ts',
      'packages/workflows/src/email-ports.ts',
      'packages/db/src/inbound.ts',
      'packages/db/migrations/0015_inbound_emails_rls.sql',
    ],
    api: ['POST /v1/inbound/bird'],
    workflows: ['email-reading'],
    checks: [
      'api/inbound',
      'workflows/email',
      'workflows/email-pdf',
      'workflows/email-ports',
      'db/inbound.int',
      'extraction/checks › always flags a purchase summary, however well it reads',
    ],
    note: 'Email or forward a receipt to the Bird mailbox: the webhook checks Bird’s signature, and a workflow fetches the email as it arrived, proves the sender by DKIM aligned with the From domain, finds the member who signs in with that address, and files each PDF or photo like an upload. With nothing attached, the email’s own text is filed as a PDF (ADR-0027). A purchase summary always waits for review. Mail from anyone else is dropped with nothing kept; only sign-in addresses send receipts in (Q17).',
  },

  // Expenses, trips and reports
  {
    id: 'F-09',
    title: 'A Ready reading becomes a Ready expense',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #28',
    decisions: ['ADR-0022'],
    api: ['GET /v1/expenses', 'GET /v1/expenses/{expenseId}', 'PATCH /v1/expenses/{expenseId}'],
    screens: ['/expenses', '/expenses/[id]'],
    code: [
      'packages/domain/src/expense-values.ts',
      'packages/extraction/src/proof.ts',
      'packages/db/src/expenses.ts',
      'packages/db/migrations/0012_expense_edited_at.sql',
      'packages/api/src/expense-routes.ts',
      'apps/web/app/expenses/[id]/page.tsx',
    ],
    checks: [
      'domain/expense-values',
      'extraction/proof',
      'db/expenses.int',
      'api/expenses',
      'e2e/expenses',
      'workflows/receipts › files it as Ready when both read it with confidence and agree',
    ],
    note: 'Every receipt has an expense from capture, linked as its proof. It follows the receipt until a person edits it, and is Ready only when its receipt is Ready and the claim is complete. Receipts filed before this get their expense on release.',
  },
  {
    id: 'F-10',
    title: 'The Needs you inbox, with real items',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #41',
    decisions: ['ADR-0017', 'ADR-0020'],
    code: [
      'apps/web/app/needs-you.tsx',
      'apps/web/lib/receipts.ts',
      'packages/api/src/routes/inbox.ts',
      'packages/api/src/receipt-views.ts',
    ],
    api: ['GET /v1/inbox'],
    checks: [
      'api/receipts › lists what needs a look or could not be read, newest first, each with why',
      'api/receipts › says which check failed when the models agree',
      'api/receipts › is empty when nothing needs the person, and needs a signed-in member',
      'db/receipts.int › lists only the receipts in the statuses asked for, newest first',
      'e2e/signed-in',
    ],
    note: 'Home lists the receipts that need a look or couldn’t be read, newest first, each with why and one action: Check it, Fill it in, or Open settings when a key is the problem. Home itself is F-29’s screen.',
  },
  {
    id: 'F-12',
    title: 'Trips, trip history and search',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #30',
    decisions: ['ADR-0023'],
    api: [
      'GET /v1/trips',
      'POST /v1/trips',
      'GET /v1/trips/{tripId}',
      'PATCH /v1/trips/{tripId}',
      'DELETE /v1/trips/{tripId}',
      'PUT /v1/expenses/{expenseId}/trip',
    ],
    screens: ['/trips', '/trips/[id]'],
    code: [
      'packages/domain/src/trips.ts',
      'packages/db/src/trips.ts',
      'packages/db/migrations/0013_expense_trip_pinned.sql',
      'packages/api/src/trip-routes.ts',
      'apps/web/app/trips/[id]/page.tsx',
    ],
    checks: ['domain/trips', 'db/trips.int', 'api/trips', 'e2e/trips'],
    note: 'Expenses file to the trip their date falls in, and file again when their date or a trip changes. A person can put one on another trip, such as a flight booked ahead, or on none, and dates leave it there. On a day two trips share, the trip that ends first keeps it. Submitted expenses never move. The signed-in pages were checked by hand against a stand-in API: the end-to-end tests run signed out.',
  },
  {
    id: 'F-13',
    title: 'Manual mileage, with the rate snapshotted',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0038'],
    code: [
      'packages/domain/src/mileage.ts',
      'packages/db/src/mileage.ts',
      'packages/api/src/mileage.ts',
      'packages/api/src/mileage-routes.ts',
      'packages/api/src/mileage-views.ts',
      'packages/api/src/routes/mileage.ts',
      'apps/web/app/mileage/mileage-form.tsx',
      'apps/web/app/mileage/new/page.tsx',
      'apps/web/app/expenses/[id]/page.tsx',
      'apps/web/lib/mileage.ts',
    ],
    api: [
      'GET /v1/mileage/quote',
      'POST /v1/mileage',
      'GET /v1/mileage/{expenseId}',
      'PATCH /v1/mileage/{expenseId}',
    ],
    screens: ['/mileage/new'],
    flags: ['expenses.mileage'],
    checks: ['domain/mileage', 'db/mileage.int', 'api/mileage', 'e2e/expenses', 'e2e/signed-in'],
    note: 'A drive is an expense of the person’s, source mileage, for miles × the IRS business rate in force on its date, with the drive and that rate on its mileage log (ADR-0038). So it lists with expenses, files to the trip its date falls in, joins its report and counts in every total with no change to them; its destination is its merchant and its purpose its justification. Add mileage is on the Expenses page and the drive on its expense’s page, both hidden while the flag is off. The IRS rates are known through 2026; a drive dated later is refused until the 2027 rate is added (Q28).',
  },
  {
    id: 'F-14',
    title: 'Route-based mileage',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 20,
  },
  {
    id: 'F-45',
    title: 'Turn AI models on and off',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0033'],
    code: [
      'packages/extraction/src/model-settings.ts',
      'packages/db/src/ai-models.ts',
      'packages/workflows/src/reading-plan.ts',
      'packages/workflows/src/features.ts',
      'packages/workflows/src/receipts.ts',
      'packages/api/src/model-settings.ts',
      'packages/api/src/model-settings-routes.ts',
      'packages/api/src/receipt-views.ts',
      'apps/web/app/settings/ai-models/page.tsx',
      'apps/web/app/receipts/[id]/page.tsx',
    ],
    api: ['GET /v1/settings/ai-models', 'PUT /v1/settings/ai-models'],
    screens: ['/settings/ai-models'],
    flags: [
      'receipts.model-settings',
      'operator.claude-sonnet-5-5',
      'operator.claude-haiku-4-5',
      'operator.gpt-5.6-luna',
      'operator.claude-opus-5-5',
      'operator.claude-fable-5-1',
    ],
    checks: [
      'extraction/model-settings',
      'db/ai-models.int',
      'workflows/reading-plan',
      'workflows/receipts › files it as Ready on one confident reading by the primary, and asks no back-up',
      'workflows/receipts › reads with the back-ups in the order set, only while the ones before could not',
      'workflows/receipts › files it for a person to fill in when every model is off',
      'api/model-settings',
      'flags/flags › stops a model only when its operator switch is set off',
      'e2e/signed-in',
    ],
    note: 'Behind receipts.model-settings: with it off, receipts are read side by side as before (F-06, F-08). Every model in the price table can be chosen; until a choice is saved, Sonnet 5.5 is primary, then Haiku 4.5 and GPT-5.6 Luna, with Opus 5.5 and Fable 5.1 off (R-MODEL-DEFAULTS). The operator’s switch per model is set in FLAG_OVERRIDES.',
  },
  {
    id: 'F-47',
    title: 'Every signed-in screen checked in CI',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #38',
    code: [
      'apps/web/e2e/bench/server.ts',
      'apps/web/e2e/bench/config.ts',
      'apps/web/e2e/layout.ts',
      'apps/web/playwright.config.ts',
      '.github/workflows/ci.yml',
    ],
    checks: ['e2e/signed-in'],
    note: 'A bench runs the real API on its own database with a test sign-in, seeded through the API and the real reading workflow with scripted answers; its receipt images are drawn, never real. Every signed-in screen in each state it can be in (47 on Oct 4), desktop Chromium at 1280 px and iPhone WebKit at 375, 393 and 440 px, light and dark. Put back on Oct 3, the date overlap and the contrast failure both failed it.',
  },
  {
    id: 'F-46',
    title: 'Time and address from the receipt',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #53',
    decisions: ['ADR-0030'],
    code: [
      'packages/extraction/src/place.ts',
      'packages/domain/src/expense-details.ts',
      'packages/db/migrations/0020_expense_time_place.sql',
      'apps/web/app/expenses/[id]/page.tsx',
    ],
    checks: [
      'extraction/normalize › reads the time as HH:MM and the address with its city, region and country',
      'extraction/place',
      'domain/expense-details',
      'db/expense-details.int',
      'api/expenses › edits when and where it was bought, working out the time zone from the place',
      'evals/score › scores the time and place a document prints (FR-INT-17)',
      'e2e/signed-in',
    ],
    note: 'Each reading captures the time of purchase and the merchant’s address, each optional and with its confidence, and the expense carries them. The expense page shows them beside its receipt’s and edits them; the time zone follows the place unless the person picks one. A blank never holds a receipt for a look.',
  },
  {
    id: 'F-54',
    title: 'Journeys and stays read from transport receipts and folios',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #59',
    decisions: ['ADR-0040', 'ADR-0030', 'ADR-0022'],
    code: [
      'packages/domain/src/journeys.ts',
      'packages/extraction/src/variant.ts',
      'packages/extraction/src/schema.ts',
      'packages/extraction/src/prompt.ts',
      'packages/extraction/src/normalize.ts',
      'packages/extraction/src/checks.ts',
      'packages/workflows/src/receipt-ports.ts',
      'packages/db/src/expenses.ts',
      'packages/db/migrations/0036_expense_journeys_and_stays.sql',
      'packages/api/src/travel-views.ts',
      'packages/api/src/expense-routes.ts',
      'apps/web/app/expenses/[id]/page.tsx',
      'apps/web/app/receipts/[id]/page.tsx',
    ],
    flags: ['receipts.journeys'],
    checks: [
      'extraction/variant › is byte for byte the request sent before, to Claude and to OpenAI',
      'extraction/variant › is unchanged with only source lines asked for, still receipt-v4',
      'extraction/variant › add their instructions and structure, and their version to the base’s',
      'extraction/variant › compose with source lines, each addition independent of the other',
      'extraction/journeys',
      'domain/journeys',
      'workflows/receipt-ports',
      'workflows/receipts › files a journey with its expense from a reading asked for it, and none from one not asked',
      'db/journeys.int',
      'api/journeys',
      'e2e/signed-in',
    ],
    note: 'With Journeys and stays switched on, each reading also asks where a ride, flight or train went and a hotel folio’s check-in and check-out (`+journeys-v1` on the request’s version); a rail ticket becomes a kind of document. They follow the receipt onto the expense until a person edits them, show under the merchant, “SFO → ORD” and “2 nights, Sep 29 – Oct 1, 2026”, and in the reading table as read. The nights are worked out from the dates, never kept; a check-out before check-in or more than 31 nights needs a look. Organizations with it off are asked exactly what they were before. The report export doesn’t carry them yet.',
  },
  {
    id: 'F-52',
    title: 'Duplicate time window in Settings',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0037', 'ADR-0031'],
    code: [
      'packages/domain/src/duplicates.ts',
      'packages/db/src/organizations.ts',
      'packages/db/src/duplicates.ts',
      'packages/db/src/features.ts',
      'packages/api/src/organization-routes.ts',
      'packages/api/src/routes/organization.ts',
      'apps/web/app/settings/organization/page.tsx',
    ],
    api: ['GET /v1/settings/duplicate-window', 'PUT /v1/settings/duplicate-window'],
    flags: ['settings.duplicate-window'],
    checks: [
      'domain/duplicates › is 30 minutes unless the owner sets another, from 0 to 120 whole minutes',
      'domain/duplicates › judges a pair by the window it is given: wider catches more, narrower less',
      'domain/duplicates › at 0 is the same minute only, exact or possible',
      'db/organizations.int › judges receipts read from then on by the window the owner set, and leaves pairs already decided',
      'db/organizations.int › with the setting off, keeps to 30 minutes whatever the owner set',
      'api/organization › lets only the owner set it, for everyone, from 0 to 120 whole minutes, each change audited',
      'e2e/signed-in',
    ],
    note: 'A section of Settings › Organization (F-51’s page): the window, 0 to 120 minutes and 30 until the owner sets another, 0 meaning the same minute only. Everyone sees it; only the owner sets it, for everyone (Q24). Each change is in the audit trail. Receipts read from then on are judged by it; pairs already flagged or kept stay as they are. With the feature off, receipts are judged by 30 minutes whatever was set.',
  },
  {
    id: 'F-48',
    title: 'Possible duplicates in review: merge, delete or keep both',
    group: 'Receipts',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #49, PR #54',
    decisions: ['ADR-0028', 'ADR-0031'],
    code: [
      'packages/domain/src/duplicates.ts',
      'packages/db/src/duplicates.ts',
      'packages/db/migrations/0016_receipt_duplicates.sql',
      'packages/db/migrations/0017_receipt_duplicates_rls.sql',
      'packages/api/src/receipt-routes.ts',
      'packages/api/src/receipt-views.ts',
      'packages/storage/src/supabase.ts',
      'apps/web/app/receipts/[id]/page.tsx',
    ],
    api: ['POST /v1/receipts/{receiptId}/duplicates/{otherReceiptId}'],
    checks: [
      'domain/duplicates',
      'db/duplicates.int',
      'api/receipts › keeps both: nothing is deleted',
      'api/receipts › deletes the one not kept, then its file',
      'api/receipts › merges into the primary chosen, from either receipt’s page',
      'api/receipts › still deletes when the file can’t be removed, and needs a signed-in member',
      'api/receipts › says whether a pair is exact or possible, from the time, place and total (ADR-0031)',
      'e2e/signed-in',
    ],
    note: 'On the receipt page of either receipt: the two side by side, their time and place too, then what to do. An exact copy: Delete the copy, one tap, or Keep both, with Delete one and Merge under Other choices. A possible one: Replace the earlier one, keeping the later as for an amended receipt, Keep both, Delete one (you choose which) or Merge (you choose the one to keep and tick the fields to take). Deleting the copy and replacing are merges, so a note or trip only the deleted receipt has moves across. Deleting goes through one database function, since the app can no longer delete receipts or expenses itself, and the file goes after that commits. Five screens in the signed-in checks.',
  },
  {
    id: 'F-49',
    title: 'Amounts converted to your reimbursement currency',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0034', 'ADR-0008', 'ADR-0032'],
    code: [
      'packages/domain/src/reference-rates.ts',
      'packages/domain/src/reimbursement.ts',
      'packages/db/src/conversions.ts',
      'packages/db/src/report-amounts.ts',
      'packages/db/migrations/0031_reimbursement_currency.sql',
      'packages/db/migrations/0032_expense_conversions_rls.sql',
      'packages/workflows/src/conversions.ts',
      'packages/api/src/reimbursement-routes.ts',
      'packages/api/src/report-views.ts',
      'apps/web/app/settings/currency/page.tsx',
      'apps/web/app/reports/[id]/page.tsx',
    ],
    api: ['GET /v1/me/reimbursement-currency', 'PUT /v1/me/reimbursement-currency'],
    screens: ['/settings/currency'],
    workflows: ['amount-conversion', 'amount-conversion-sweep'],
    flags: ['reports.currency-conversion'],
    checks: [
      'domain/reference-rates',
      'domain/reimbursement',
      'db/conversions.int',
      'workflows/conversions',
      'api/reimbursement',
      'e2e/signed-in',
    ],
    note: 'Behind `reports.currency-conversion`. Every amount on a report is shown in your reimbursement currency beside what was spent, and the report, Home and Needs you total in it. You choose the currency in Settings › Currency; until you do, it is your organization’s home currency. Each amount is converted at the ECB’s reference rate for its purchase date, the last one before a weekend or holiday, fetched in the background and copied onto the expense with its date and source; the report lists the rates used. A currency the ECB doesn’t publish, such as dirhams, stays as spent and is listed apart; an amount still being converted says so. Off, reports read exactly as before.',
  },
  {
    id: 'F-50',
    title: 'Local expenses, each with a justification',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #52',
    decisions: ['ADR-0029'],
    code: ['packages/db/src/reports.ts', 'apps/web/app/expenses/[id]/page.tsx'],
    api: ['PUT /v1/expenses/{expenseId}/justification', 'PUT /v1/expenses/{expenseId}/report'],
    checks: [
      'db/reports.int › refuses a justification on a trip’s expense, or one too long',
      'api/reports › refuses to close while anything needs a justification, then closes and reopens',
      'api/reports › asks for a justification, and says when a report is ready to close',
      'e2e/signed-in',
    ],
    note: 'An expense dated on a day no trip covers is local. Its page asks why it was for business, up to 500 characters, and Needs you asks too once it is Ready; its report can’t close until it says.',
  },
  {
    id: 'F-43',
    title: 'Expense categories and types',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0036'],
    code: [
      'packages/domain/src/categories.ts',
      'packages/db/src/categories.ts',
      'packages/db/migrations/0027_expense_types.sql',
      'packages/db/migrations/0028_expense_types_rls.sql',
      'packages/api/src/categories.ts',
      'packages/api/src/category-routes.ts',
      'packages/api/src/category-schemas.ts',
      'packages/api/src/category-views.ts',
      'packages/api/src/routes/categories.ts',
      'apps/web/app/settings/categories/page.tsx',
      'apps/web/app/expenses/[id]/page.tsx',
      'apps/web/lib/categories.ts',
    ],
    api: [
      'GET /v1/categories',
      'POST /v1/settings/categories',
      'PATCH /v1/settings/categories/{categoryId}',
      'DELETE /v1/settings/categories/{categoryId}',
      'POST /v1/settings/expense-types',
      'PATCH /v1/settings/expense-types/{typeId}',
      'DELETE /v1/settings/expense-types/{typeId}',
      'PUT /v1/expenses/{expenseId}/category',
    ],
    screens: ['/settings/categories'],
    flags: ['expenses.categories'],
    checks: ['domain/categories', 'db/categories.int', 'api/categories', 'e2e/signed-in'],
    note: 'Two lists that each nest, and the types each category allows (Q7). Every organization starts with five categories and nine types, seeded for those that existed and for each new one; owners and finance admins rename, add, move, code and retire them, and delete one only while no expense has it. An expense without a category and type says so on its page and in the list, and blocks nothing (Q27, GAP-28). Behind `expenses.categories`, which also brings suggestions (F-15). Seven screens in the signed-in checks.',
  },
  {
    id: 'F-55',
    title: 'Itemized lines: shown, split by category and type, and excluded',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 80,
  },
  {
    id: 'F-15',
    title: 'Category suggestions',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0036'],
    code: ['packages/domain/src/categories.ts', 'packages/api/src/category-views.ts'],
    checks: [
      'domain/categories › suggests what the person last chose for the same merchant, matched loosely',
      'domain/categories › goes by what the reading says the document is before any word',
      'api/categories › suggests one from what the expense shows, marked as a suggestion, or says it has none',
      'api/categories › suggests what its owner last chose for the same merchant first',
      'db/categories.int › learns from each member’s own choices, newest first, for expenses that name a merchant',
    ],
    note: 'By rules, never a model, so it costs nothing (ADR-0036): first what the expense’s owner last chose for a similar merchant, matched as duplicates are, then what its reading says the document is, then keywords in the merchant’s name. Shown as a suggestion until the person confirms it with Use this; nothing is stored until then. Switched on with categories (`expenses.categories`, claimed by F-43).',
  },
  {
    id: 'F-17',
    title: 'Expense reports: trips join once they end, closed within 28 days',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #52',
    decisions: ['ADR-0029'],
    code: [
      'packages/domain/src/reports.ts',
      'packages/domain/src/lifecycle/report.ts',
      'packages/db/src/reports.ts',
      'packages/db/src/report-touch.ts',
      'packages/db/migrations/0018_expense_reports.sql',
      'packages/db/migrations/0019_report_work_due.sql',
      'packages/workflows/src/reports.ts',
      'packages/api/src/report-routes.ts',
      'packages/api/src/report-views.ts',
      'apps/web/app/reports/page.tsx',
      'apps/web/app/reports/[id]/page.tsx',
    ],
    api: [
      'GET /v1/reports',
      'GET /v1/reports/{reportId}',
      'POST /v1/reports/{reportId}/close',
      'POST /v1/reports/{reportId}/reopen',
      'PUT /v1/trips/{tripId}/report',
    ],
    screens: ['/reports', '/reports/[id]'],
    workflows: ['report-schedule'],
    checks: [
      'domain/reports',
      'db/reports.int',
      'workflows/reports',
      'api/reports',
      'e2e/signed-in',
    ],
    note: 'A trip goes on the open report 24 hours after its return day has ended everywhere, a local expense likewise after its own date, both on the hour. A report closes within 28 days, by you or by the schedule, which moves what still needs review to the next report; any change to a closed report reopens it (ADR-0029). Needs you shows a report only when it is overdue, in its last week with something left, or ready to close; Home lists open and closed reports. Totals are per currency as spent; with currency conversion on, in your reimbursement currency too (F-49). Six screens in the signed-in checks.',
  },
  {
    id: 'F-18',
    title: 'Single-step approval: self-attestation solo, separation of duties in teams',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 24,
  },
  {
    id: 'F-19',
    title: 'CSV and PDF export',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    decisions: ['ADR-0029'],
    code: [
      'packages/domain/src/report-export.ts',
      'packages/db/src/report-export.ts',
      'packages/api/src/report-export-routes.ts',
      'packages/api/src/report-pdf.ts',
      'packages/api/src/routes/report-export.ts',
      'apps/web/app/reports/[id]/page.tsx',
      'apps/web/lib/api.ts',
    ],
    api: ['GET /v1/reports/{reportId}/export.csv', 'GET /v1/reports/{reportId}/export.pdf'],
    flags: ['reports.export'],
    checks: ['domain/report-export', 'db/report-export.int', 'api/report-export'],
    note: 'Export CSV and Export PDF on a closed report’s page. Until approval (#24) exists, a closed report is what is exported; an open one is refused (409 not_closed), and a report stays exportable at every state after closing. The CSV has a row per expense (date, merchant, category, type, trip, purpose, note, amount and currency as spent), then a total per currency, never converted; UTF-8 with a byte order mark so Excel reads accents and currency signs, and text that starts like a formula written as text. The PDF heads the same table with the person, organization, status and dates, with no receipt images; both are built from one table in the domain, so a converted amount (#62) is one more column. Category and type are the ones chosen for the expense (#51), empty where none was. The member whose report it is exports it, as do the owner, finance admins and auditors; anyone else is answered as if it did not exist. Both files are made in the request: a database read and a layout in memory, with no other service.',
  },
  {
    id: 'F-20',
    title: 'Audit trail view',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #58',
    code: [
      'apps/web/app/settings/audit/page.tsx',
      'apps/web/app/history-link.tsx',
      'apps/web/lib/audit.ts',
      'packages/api/src/audit.ts',
      'packages/api/src/audit-routes.ts',
      'packages/api/src/routes/audit.ts',
      'packages/db/src/audit.ts',
      'packages/domain/src/audit.ts',
    ],
    api: ['GET /v1/audit/events', 'GET /v1/audit/verification'],
    screens: ['/settings/audit'],
    flags: ['governance.audit-trail'],
    checks: [
      'api/audit',
      'db/audit.int › lists the trail newest first, a page at a time, by record and by who made it',
      'db/audit.int › recomputes the chain on request, and finds the first event an edit broke',
      'domain/audit › lets owners, finance admins and auditors read it, and no one else',
      'e2e/signed-in › a receipt opens its history in the audit trail, under the chain checked intact',
      'e2e/signed-in › the audit trail holds no key or token in any event’s details',
    ],
    note: 'Settings › Audit trail, for owners, finance admins and auditors: the hash chain recomputed from every stored event at the top, then every change newest first, 50 a page, with when, who, what and which record, and its details as stored. A receipt, an expense and a report link to their own history. Behind governance.audit-trail: switched off, the routes answer 404 and the page and links are hidden. The chain is checked in full each time the page opens.',
  },
  {
    id: 'F-22',
    title: 'Home dashboard, beneath Needs you',
    group: 'Expenses, trips and reports',
    kind: 'product',
    phase: 'P1',
    status: 'Partial',
    delivered: 'PR #43',
    code: [
      'apps/web/app/home-dashboard.tsx',
      'apps/web/lib/home.ts',
      'packages/api/src/home.ts',
      'packages/api/src/home-views.ts',
      'packages/api/src/routes/home.ts',
      'packages/db/src/home.ts',
    ],
    api: ['GET /v1/home'],
    checks: [
      'db/home.int',
      'api/home',
      'api/expenses › finds the expenses on no trip, or on some trip (Home’s figures open them)',
      'e2e/signed-in',
    ],
    shortfalls: ['GAP-30'],
    note: 'Needs you, then the trip under way or next, this month, receipts being read, reports to finish (since PR #52) and recent trips, from one request built for the person’s own day. Each figure opens its list; the Expenses page takes the search from the link. Mileage exists since PR #58 (#17), and a drive counts in this month’s spend like any expense; the business miles figure itself is #73.',
  },

  // Domain rules: built and tested ahead of the screens that will use them
  {
    id: 'F-24',
    title: 'Money, decimals, FX, dates and ids',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0008'],
    code: [
      'packages/domain/src/money.ts',
      'packages/domain/src/decimal.ts',
      'packages/domain/src/fx.ts',
      'packages/domain/src/dates.ts',
      'packages/domain/src/ids.ts',
      'packages/domain/src/currency.ts',
    ],
    checks: ['domain/money', 'domain/decimal', 'domain/fx', 'domain/dates', 'domain/ids'],
  },
  {
    id: 'F-25',
    title: 'Mileage reimbursement: the rate in force on the day, snapshotted',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0008'],
    code: ['packages/domain/src/mileage.ts'],
    checks: ['domain/mileage'],
  },
  {
    id: 'F-26',
    title: 'Expense and report lifecycles',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    code: ['packages/domain/src/lifecycle'],
    checks: ['domain/lifecycle/expense', 'domain/lifecycle/report'],
  },
  {
    id: 'F-27',
    title: 'Who may approve: canApprove()',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0001'],
    code: ['packages/domain/src/approvals.ts'],
    checks: ['domain/approvals'],
  },
  {
    id: 'F-28',
    title: 'Append-only, hash-chained audit log',
    group: 'Domain rules',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1',
    decisions: ['ADR-0008'],
    code: [
      'packages/domain/src/audit.ts',
      'packages/db/src/audit.ts',
      'packages/db/migrations/0001_tenant_isolation_and_audit.sql',
    ],
    checks: ['domain/audit', 'db/audit.int'],
  },

  // Platform and operations
  {
    id: 'F-29',
    title: 'App shell: the inbox layout and five-destination tab bar',
    group: 'Platform and operations',
    kind: 'product',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1, PR #36',
    decisions: ['ADR-0004'],
    code: [
      'apps/web/app/page.tsx',
      'apps/web/app/layout.tsx',
      'apps/web/app/tab-bar.tsx',
      'apps/web/app/globals.css',
      'apps/web/next.config.ts',
    ],
    screens: ['/'],
    checks: [
      'e2e/shell › opens on the inbox with the five-destination tab bar',
      'e2e/shell › shows the tab bar on every screen but sign-in, marking where you are',
      'e2e/shell › keeps two date fields side by side inside a narrow card',
      'e2e/shell › sends security headers',
    ],
    note: 'The tab bar was on Home only until PR #36; it is now on every screen but sign-in, as the design has it.',
  },
  {
    id: 'F-30',
    title: 'Health and readiness checks',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1, PR #8',
    code: ['packages/api/src/routes', 'packages/db/src/readiness.ts'],
    api: ['GET /v1/health', 'GET /v1/health/ready'],
    checks: [
      'api/api › reports health and the deployed version',
      'api/ready',
      'db/readiness',
      'db/readiness.int',
      'e2e/shell › reports readiness with a status that matches the report',
    ],
  },
  {
    id: 'F-31',
    title: 'Feature flags, off by default, switched per organization',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #11; switches per organization in PR #58',
    decisions: ['ADR-0032'],
    code: [
      'packages/flags/src',
      'packages/db/src/features.ts',
      'packages/api/src/features.ts',
      'apps/web/lib/features.ts',
      'apps/web/app/settings/features/page.tsx',
    ],
    api: ['GET /v1/features', 'PUT /v1/settings/features/{key}'],
    screens: ['/settings/features'],
    flags: ['shell.build-version'],
    checks: [
      'flags/flags',
      'flags/posthog',
      'api/features',
      'api/workspace › lists every feature switched off, and lets only the owner switch one',
      'api/workspace › switches a feature on and off for the organization, with an audit event each time',
      'api/workspace › lets the server override beat the switch, and refuses a switch it would ignore',
      'db/features.int',
      'e2e/shell › ships the build-version change dark: its flag is off by default',
    ],
  },
  {
    id: 'F-32',
    title: 'Error tracking, with secrets redacted',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Partial',
    delivered: 'PR #11',
    code: [
      'apps/web/sentry.shared.ts',
      'apps/web/sentry.server.config.ts',
      'apps/web/instrumentation.ts',
      'apps/web/instrumentation-client.ts',
      'packages/api/src/redact.ts',
    ],
    checks: ['api/redact'],
    shortfalls: ['GAP-07'],
  },
  {
    id: 'F-33',
    title: 'Outbox, eager dispatch and the workflow runner',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Partial',
    delivered: 'PR #11, PR #16',
    decisions: ['ADR-0002', 'ADR-0017'],
    code: [
      'packages/db/src/outbox.ts',
      'packages/workflows/src/relay.ts',
      'packages/workflows/src/functions.ts',
      'apps/web/app/api/inngest/route.ts',
    ],
    workflows: ['outbox-relay'],
    checks: [
      'workflows/relay',
      'workflows/functions',
      'db/outbox.int',
      'api/receipts › still files the receipt when the runner is unreachable; the relay sends it later',
    ],
    shortfalls: ['GAP-05', 'GAP-06'],
  },
  {
    id: 'F-34',
    title: 'Tenant isolation and the database roles',
    group: 'Platform and operations',
    kind: 'foundation',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #1, PR #7, PR #14, PR #35',
    decisions: ['ADR-0013'],
    code: [
      'packages/db/src/client.ts',
      'packages/db/src/connection.ts',
      'packages/db/src/role-passwords.ts',
      'packages/db/migrations/0002_supabase_data_api_lockdown.sql',
      'packages/db/src/data-api.ts',
    ],
    checks: [
      'db/tenancy.int',
      'db/supabase-roles.int',
      'db/connection',
      'db/role-passwords',
      'db/role-passwords.int',
    ],
  },
  {
    id: 'F-35',
    title: 'Quality gates G1–G5 on every push',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Partial',
    delivered: 'PR #1, PR #7',
    decisions: ['ADR-0009'],
    code: ['.github/workflows/ci.yml', '.github/workflows/codeql.yml'],
    checks: ['ci:static', 'ci:unit', 'ci:integration', 'ci:security', 'ci:e2e', 'ci:codeql'],
    shortfalls: ['GAP-11'],
  },
  {
    id: 'F-36',
    title: 'Release: migrate, promote this commit, verify it is live',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Partial',
    delivered: 'PR #17, PR #19',
    decisions: ['ADR-0018', 'ADR-0019'],
    code: [
      '.github/workflows/release.yml',
      '.github/scripts/promote-production.mjs',
      'packages/db/src/set-role-passwords.ts',
    ],
    shortfalls: ['GAP-09'],
  },
  {
    id: 'F-37',
    title: 'Nightly encrypted off-site backup',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Partial',
    delivered: 'PR #23',
    decisions: ['ADR-0014'],
    code: ['.github/workflows/backup.yml', 'scripts/backup/backup.sh'],
    shortfalls: ['GAP-18'],
    note: 'Runs every night since Oct 3; each run downloads its upload again and checks it decrypts to the same dump. On Oct 3 you decrypted the first copy with the passphrase from your password manager, and the restore drill (F-41) restored production’s backup with every check passing.',
  },
  {
    id: 'F-42',
    title: 'Heartbeat and Free plan quota alerts',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #23',
    decisions: ['ADR-0014'],
    code: [
      'packages/db/migrations/0009_ops_heartbeat.sql',
      'scripts/backup/backup.sh',
      '.github/workflows/backup.yml',
    ],
    checks: ['db/heartbeat.int'],
    note: 'The nightly job writes the heartbeat before anything else, then fails at 70% of the 500 MB database or 1 GB storage limit, and GitHub emails the owner; that email reached you for the first, failed run on Oct 3. The quota alert was rehearsed by hand, not in CI.',
  },
  {
    id: 'F-41',
    title: 'Monthly restore drill',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #35',
    decisions: ['ADR-0014', 'ADR-0013'],
    code: [
      '.github/workflows/restore-drill.yml',
      'scripts/backup/restore-drill.sh',
      'scripts/backup/prepare-restore.sh',
      'packages/db/src/restore-drill.ts',
      'packages/db/scripts/restore-check.ts',
    ],
    checks: ['db/restore-drill.int'],
    note: 'On the 2nd of each month, restores the newest backup into a throwaway Supabase stack (Postgres, auth and storage, as a new project has) and checks the dump’s checksums, row counts, migrations, the schema against schema.json, row-level security, isolation signed in as expensewise_app, a sample of 100 receipt images, the 24-hour recovery point and the 4-hour recovery time. Rehearsed on Oct 3 end to end against a stand-in backed up by the real nightly script: passed in 37 s, and failed as it should for a missing image, a 30-hour-old dump and a wrong passphrase. Its first rehearsals found three things that would have broken a real restore, all fixed here. First run on production’s backup on Oct 3: the dump 22 minutes old, all 50 tables (137 rows), the schema, isolation and all 6 receipt images matched, in 1 min 11 s.',
  },
  {
    id: 'F-38',
    title: 'Extraction eval harness: public and synthetic layers',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P0',
    status: 'Verified',
    delivered: 'PR #9',
    decisions: ['ADR-0006', 'ADR-0012'],
    code: ['evals/src'],
    checks: ['evals/score', 'evals/datasets/cord', 'evals/synthetic/synthetic'],
  },
  {
    id: 'F-21',
    title: 'Email notifications',
    group: 'Platform and operations',
    kind: 'product',
    phase: 'P1',
    status: 'Planned',
    backlog: 27,
  },
  {
    id: 'F-39',
    title: 'These records: requirements, traceability and backlog pages',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #21',
    code: ['tools/records/src', 'CLAUDE.md', '.claude/hooks/after-merge.sh'],
    checks: ['records/integrity', 'records/render'],
  },
  {
    id: 'F-53',
    title: 'User stories and acceptance criteria page',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #57',
    code: [
      'tools/records/src/stories',
      'tools/records/src/rules.ts',
      'tools/records/src/integrity-stories.ts',
      'tools/records/src/render/stories.ts',
    ],
    checks: [
      'records/integrity › refuses a built requirement or feature that no delivered story covers',
      'records/integrity › refuses a test that doesn’t exist, and a decision credited to a question that doesn’t',
      'records/render › says who decided each criterion, and points an untested one at the item that adds its test',
      'records/render › lists each requirement’s user stories, linked to the stories page',
    ],
    note: 'Every built requirement and feature, and every planned requirement from your own words, written as user stories with Given/When/Then acceptance criteria, each saying who decided it and which test proves it; a register of the numbers the rules share, held to the code; a fifth published page, linked from each requirement on the traceability page.',
  },
  {
    id: 'F-44',
    title: 'Technical architecture and data model pages',
    group: 'Platform and operations',
    kind: 'operations',
    phase: 'P1',
    status: 'Verified',
    delivered: 'PR #32',
    code: [
      'tools/records/src/architecture.ts',
      'tools/records/src/data-model.ts',
      'tools/records/src/integrity-pages.ts',
      'tools/records/src/render/architecture.ts',
      'tools/records/src/render/data-model.ts',
      'packages/db/src/schema-snapshot.ts',
      'packages/db/schema.json',
      '.github/pull_request_template.md',
    ],
    checks: [
      'db/schema-snapshot.int',
      'records/integrity',
      'records/render › the architecture page',
      'records/render › the data model page',
    ],
    note: 'Generated from the repository and from a snapshot of the migrated database, with a written half the tests hold to completeness. Published with the traceability and backlog pages after each successful release, each with what changed since the last one.',
  },
];
