import type { Requirement } from './model.ts';

/**
 * Functional requirements, one area per row of the capability map. Every capability-map
 * cell is delivered by at least one requirement here, whatever its phase, so the map and
 * this list can't drift apart.
 */
export const FUNCTIONAL: readonly Requirement[] = [
  // Capture
  {
    id: 'FR-CAP-01',
    text: 'Capture a receipt by camera or upload, as JPEG, PNG, WebP, GIF or a PDF of any length, up to 10 MB. The file goes straight to private storage and is filed in about a second.',
    sources: ['capmap P1', 'ADR-0017', 'arch §6.4'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Capture · Camera and upload', 'Capture · PDF and multi-page'],
    features: ['F-05'],
    checks: [
      'api/receipts › rejects files over 10 MB and types it cannot read',
      'api/receipts › hands out a one-time upload for a path inside the organization',
      'e2e/receipts › opens from the Capture button on the home page',
    ],
  },
  {
    id: 'FR-CAP-02',
    text: 'Forward airline, hotel and ride emails to a personal receipts address; the email body and any PDF are read like a receipt.',
    sources: ['ADR-0011', 'D-11', 'arch §6.11', 'roadmap inc 2'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Capture · Email-in forwarding'],
    features: ['F-16'],
    backlog: [19],
  },
  {
    id: 'FR-CAP-03',
    text: 'Log mileage by hand: date, destination, business purpose and miles, the elements IRS Publication 463 asks for. The rate in force on the travel date is copied onto the entry.',
    sources: ['journeys §4.3', 'arch §6.7', 'roadmap inc 2'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Capture · Manual mileage'],
    features: ['F-13', 'F-25'],
    backlog: [17],
    note: 'The rate rules are built and tested (F-25); the screen is not.',
  },
  {
    id: 'FR-CAP-04',
    text: 'Log mileage by route: start, stops and end, with a round-trip toggle and saved places. The distance comes from a routing service and its source is recorded.',
    sources: ['journeys §4.3', 'roadmap inc 2'],
    priority: 'Should',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Capture · Route-based mileage'],
    features: ['F-14'],
    backlog: [20],
    note: 'The first item to cut if increment 2 runs long.',
  },
  {
    id: 'FR-CAP-05',
    text: 'Opt-in, read-only Gmail and Outlook sync back-fills receipts from past trips.',
    sources: ['ADR-0011', 'arch §6.11', 'roadmap P2'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
    capabilities: ['Capture · Inbox sync (Gmail, Outlook)'],
  },
  {
    id: 'FR-CAP-06',
    text: 'Read-only bank and card transactions arrive through Plaid; ExpenseWise never issues a card.',
    sources: ['ADR-0007', 'roadmap P2'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
    capabilities: ['Capture · Bank and card feeds'],
  },
  {
    id: 'FR-CAP-07',
    text: 'The iPhone app captures offline and syncs each receipt exactly once.',
    sources: ['ADR-0004', 'arch §6.10', 'roadmap P3'],
    priority: 'Could',
    phase: 'P3',
    status: 'Planned',
    capabilities: ['Capture · Offline capture queue'],
  },
  {
    id: 'FR-CAP-08',
    text: 'The iPhone app detects drives over a mile in work hours and drafts mileage entries for a swipe decision. Opt-in; drives stay private until marked business.',
    sources: ['journeys §4.3', 'journeys §4.6', 'roadmap P3'],
    priority: 'Could',
    phase: 'P3',
    status: 'Planned',
    capabilities: ['Capture · Automatic GPS mileage'],
  },
  {
    id: 'FR-CAP-09',
    text: 'Capture by SMS or chat, and trips created by booking through a travel partner.',
    sources: ['capmap P4', 'roadmap P4'],
    priority: "Won't",
    phase: 'P4',
    status: 'Deferred',
    capabilities: ['Capture · SMS and chat capture', 'Capture · Travel booking via partner'],
    note: 'Each Phase 4 item needs its own business case.',
  },

  // Intelligence
  {
    id: 'FR-INT-01',
    text: 'Read merchant, date, currency, total, subtotal, taxes, tip, card last four, line items and document type into a fixed schema, each field with its confidence. No free-text parsing.',
    sources: ['arch §6.5', 'ADR-0006'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Intelligence · Field extraction'],
    features: ['F-06'],
    checks: [
      'extraction/claude › sends the image, the schema and the tier effort, and prices the call',
      'extraction/normalize › turns decimal strings into integer minor units in the stated currency',
    ],
  },
  {
    id: 'FR-INT-02',
    text: 'A receipt is Ready only when merchant, date, currency and total are read with high confidence and, until the tier is chosen, both compared models agree on them. Otherwise it Needs a look; it is Failed only when nothing could read it.',
    sources: ['ADR-0017', 'ADR-0006', 'journeys §4.5'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Intelligence · Confidence-gated review'],
    features: ['F-06'],
    checks: [
      'extraction/review › needs merchant, date, currency and total read with high confidence',
      'workflows/receipts › files it as Ready when both read it with confidence and agree',
      'workflows/receipts › asks for a look when the models disagree',
    ],
  },
  {
    id: 'FR-INT-03',
    text: 'The same file is never filed twice: an exact duplicate is refused by its SHA-256, before and after upload, and the person is shown the receipt already filed.',
    sources: ['capmap P1', 'arch §6.5', 'roadmap inc 1'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Intelligence · Exact-duplicate detection'],
    features: ['F-05'],
    checks: [
      'api/receipts › refuses a file that is already filed, before and after upload',
      'db/receipts.int › treats a retried request as done, and a second copy of a file as a duplicate',
    ],
  },
  {
    id: 'FR-INT-04',
    text: 'A reading is Ready only if its arithmetic and dates pass: subtotal, taxes and tip reconcile with the total, and the date is plausible, not in the future.',
    sources: ['journeys §4.6', 'arch §6.5', 'design §5.3'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    features: ['F-06'],
    checks: ['extraction/normalize › flags values it cannot read instead of rounding or guessing'],
    shortfalls: ['GAP-04'],
    note: 'Dates are checked for format only, and nothing compares the parts with the total.',
  },
  {
    id: 'FR-INT-05',
    text: 'The stored file is checked before any model sees it: its size, its SHA-256 and its real type from its first bytes must match what the client described.',
    sources: ['ADR-0017'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-06'],
    checks: [
      'workflows/receipts › reads nothing when the stored file is not the one described',
      'workflows/receipts › rejects anything else',
    ],
  },
  {
    id: 'FR-INT-06',
    text: 'Every reading keeps the model, prompt and schema versions, outcome, latency, tokens and cost, keyed to the request that asked for it, so any figure can be traced to what read it.',
    sources: ['arch §6.5', 'ADR-0006', 'ADR-0017'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-06'],
    checks: [
      'db/receipts.int › records each model once per request, then settles once',
      'workflows/receipts › files it as Ready when both read it with confidence and agree',
    ],
  },
  {
    id: 'FR-INT-07',
    text: 'A person can ask for a receipt to be read again; the new reading is kept beside the old one.',
    sources: ['ADR-0017'],
    priority: 'Should',
    phase: 'P1',
    status: 'Verified',
    features: ['F-06'],
    checks: [
      'api/receipts › reads a receipt again on request',
      'db/receipts.int › reads again on request, with a new request id',
    ],
  },
  {
    id: 'FR-INT-08',
    text: 'Until the model tier is chosen, two compared models read every receipt, and a running comparison shows agreement, confidence, time and spend per model.',
    sources: ['ADR-0017', 'ADR-0006', 'roadmap inc 0'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    features: ['F-06', 'F-07'],
    checks: ['api/receipts › keeps a running comparison of the two models'],
    shortfalls: ['#4', '#21'],
  },
  {
    id: 'FR-INT-09',
    text: "When no Claude model can read a receipt, a fallback model reads it once on the organization's own OpenAI key. Its reading can make a receipt Needs a look, never Ready.",
    sources: ['ADR-0020'],
    priority: 'Should',
    phase: 'P1',
    status: 'Verified',
    features: ['F-08'],
    checks: [
      'workflows/receipts › reads the receipt when Anthropic has no credit, and asks for a look',
      'workflows/receipts › settles as failed when the fallback has no credit either',
      'api/receipts › shows the fallback reading when no Claude model could read the receipt',
    ],
  },
  {
    id: 'FR-INT-14',
    text: 'A tax or tip the receipt doesn’t print counts as $0 in its currency, shown as “not on receipt” and kept apart from what was read. Never when the line is printed but unreadable, or when the printed subtotal and lines don’t reach the total.',
    sources: ['owner 2026-10-02'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-06'],
    checks: [
      'extraction/normalize › counts tax and tip a receipt does not print as zero',
      'extraction/normalize › assumes nothing when the printed figures leave an amount unaccounted for',
      'extraction/normalize › leaves the reading itself as read',
      "api/receipts › shows tax and tip the receipt doesn't print as zero, marked as assumed",
    ],
    note: 'Refined from the request: no tax line means none was itemized, not necessarily none was paid, so the reading keeps the difference.',
  },
  {
    id: 'FR-INT-15',
    text: 'A receipt that needs a look always offers a next step: confirm the reading as right, or correct a field. Either makes it Ready, records who did it, and keeps the correction.',
    sources: ['owner 2026-10-02', 'design §5.3', 'journeys §4.5'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-40'],
    checks: [
      'api/receipts › makes the fallback reading Ready with Looks right, and says who confirmed it',
      'api/receipts › files corrected fields with Edit a field, keeping what the model read',
      'db/receipts.int › makes it Ready with the values, the corrections and an audit event, together',
    ],
  },
  {
    id: 'FR-INT-10',
    text: 'Each expense gets a suggested category, marked as a suggestion until confirmed.',
    sources: ['capmap P1', 'arch §6.5', 'roadmap inc 2'],
    priority: 'Should',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Intelligence · Category suggestion'],
    features: ['F-15'],
    backlog: [18],
  },
  {
    id: 'FR-INT-11',
    text: 'Each extracted field shows the receipt text it came from and how sure the reading is; one tap corrects it, and the correction becomes an eval candidate.',
    sources: ['design DP3', 'delivery §7.5'],
    priority: 'Should',
    phase: 'P1',
    status: 'Partial',
    features: ['F-06', 'F-40'],
    checks: [
      'api/receipts › shows both readings, where they differ, and money as minor units',
      'extraction/confirm',
    ],
    shortfalls: ['GAP-14'],
    note: 'Confidence and the original image are shown. A reading that needs a look can be corrected, and each correction is kept beside what was read (F-40). Source text is not shown, and a Ready reading can’t be corrected.',
  },
  {
    id: 'FR-INT-12',
    text: 'Receipts match card transactions; duplicates are caught by perceptual hash as well as SHA-256; merchant names are normalized; categories are learned from corrections.',
    sources: ['capmap P2', 'arch §6.5', 'roadmap P2'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
    capabilities: [
      'Intelligence · Receipt ↔ transaction matching',
      'Intelligence · Near-duplicate detection',
      'Intelligence · Merchant normalization',
      'Intelligence · Learned categorization',
    ],
  },
  {
    id: 'FR-INT-13',
    text: 'Anomaly and fraud signals.',
    sources: ['capmap P4', 'roadmap P4'],
    priority: "Won't",
    phase: 'P4',
    status: 'Deferred',
    capabilities: ['Intelligence · Anomaly and fraud signals'],
  },

  // Expense management
  {
    id: 'FR-EXP-01',
    text: 'A Ready reading becomes a Ready expense with no human touch, filed to the trip whose dates it falls in; an unsure one becomes an expense that Needs review.',
    sources: ['journeys §4.6', 'journeys §4.5', 'roadmap inc 1'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Expense management · Expenses'],
    features: ['F-09', 'F-12', 'F-26'],
    checks: [
      'db/expenses.int › is Ready with the reading when the receipt is Ready, together with its audit event',
      'db/expenses.int › needs review, filled in as read, while its receipt needs a look; failed leaves it empty',
      'db/trips.int › files a receipt read after the trip exists to it, with no human touch',
      'db/trips.int › files an expense whose date arrives while the trip is being made',
    ],
    note: "Increment 1's exit test: a receipt is filed as an expense within 30 seconds. Since #16 it files to its trip by date too, unless a person chose another (ADR-0023).",
  },
  {
    id: 'FR-EXP-02',
    text: 'Home is the Needs you inbox: only the things that need the person (receipts to check, missing receipts, returned reports), and it says when everything else is done.',
    sources: ['design DP2', 'design §5.3', 'roadmap inc 1'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-10'],
    backlog: [9],
    note: 'The inbox layout is built (F-29); it has no items behind it yet.',
  },
  {
    id: 'FR-EXP-03',
    text: 'An approved expense is locked. A correction is a reversal plus a new version, so the trail never loses what was approved.',
    sources: ['journeys §4.5', 'arch AP4', 'ADR-0008'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-26'],
    backlog: [24],
    note: 'The lifecycle rules are built and tested (F-26); no expense uses them yet.',
  },
  {
    id: 'FR-EXP-04',
    text: 'Trips have dates and a purpose; expenses file to them by date, and past trips can be browsed and searched.',
    sources: ['capmap P1', 'journeys §4.2', 'roadmap inc 2'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Expense management · Trips and trip history'],
    features: ['F-12'],
    checks: [
      'db/trips.int › files the member’s expenses dated in a new trip, start and end days included',
      'db/trips.int › files again when a trip’s dates change, and records each change',
      'db/trips.int › keeps an expense on the trip a person chose, whatever its date',
      'db/trips.int › gives a day two trips share to the trip that ends first',
      'domain/trips',
      'api/trips',
    ],
    note: 'A purpose is asked for but not required: a trip made ahead may not have one yet. Whether a report may be submitted without one is for #24.',
  },
  {
    id: 'FR-EXP-05',
    text: 'Forty-eight hours after a trip ends, its report is drafted and the traveler notified. Trips with no expenses are skipped, and the traveler can reopen.',
    sources: ['journeys §4.6', 'roadmap inc 3'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Expense management · Reports'],
    features: ['F-17', 'F-26'],
    backlog: [23],
  },
  {
    id: 'FR-EXP-06',
    text: 'Split an expense, record meal attendees for meals over the limit, and hold expenses in several currencies.',
    sources: ['capmap P2', 'roadmap P2'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
    capabilities: [
      'Expense management · Split expenses',
      'Expense management · Multi-currency and FX',
      'Expense management · Meal attendees',
    ],
    features: ['F-24'],
    note: 'Allocation and conversion rules exist (F-24).',
  },
  {
    id: 'FR-EXP-07',
    text: 'Per diem and recurring expenses.',
    sources: ['capmap P3', 'roadmap P3'],
    priority: 'Could',
    phase: 'P3',
    status: 'Planned',
    capabilities: ['Expense management · Per diem', 'Expense management · Recurring expenses'],
  },
  {
    id: 'FR-EXP-08',
    text: 'An expense made from a receipt keeps that receipt linked as its proof. Editing the expense never changes the receipt, its readings or what was confirmed on it.',
    sources: ['owner 2026-10-03'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-09'],
    checks: [
      'db/expenses.int › exists from capture, processing and linked to its receipt as proof',
      'api/expenses › edits an expense and shows where it now differs from its receipt',
    ],
  },
  {
    id: 'FR-EXP-09',
    text: 'An expense can be edited once it exists: while it is Ready or needs review, and again when its report comes back. Each edit records who changed what. An approved expense is locked (FR-EXP-03).',
    sources: ['owner 2026-10-03', 'journeys §4.5'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-09'],
    checks: [
      'db/expenses.int › keeps a person’s edit over any later reading, and is Ready once the receipt is',
      'api/expenses › refuses an edit while the receipt is read, or once submitted',
      'domain/expense-values',
    ],
  },
  {
    id: 'FR-EXP-10',
    text: 'An expense may claim less than its receipt, with a reason such as a personal item removed or a receipt split across expenses, but never more. Expenses split from one receipt may not add up to more than it.',
    sources: ['owner 2026-10-03'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-18'],
    backlog: [24],
    note: 'Your answer to Q6, 1B.',
  },
  {
    id: 'FR-EXP-11',
    text: 'An organization defines its own expense categories and types. Every expense has a type, and every type belongs to one category.',
    sources: ['owner 2026-10-03'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-43'],
    backlog: [51],
    note: 'Your requirement of Oct 3. What a type is beside a category is open as Q7.',
  },

  // Governance
  {
    id: 'FR-GOV-01',
    text: 'Five roles: Member, Approver, Finance admin, Owner and a read-only Auditor. Admin actions are limited to owners and finance admins.',
    sources: ['arch §6.9', 'capmap P1'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    capabilities: ['Governance · Roles and permissions'],
    features: ['F-04'],
    checks: ['api/workspace › lets only owners and finance admins manage keys'],
    shortfalls: ['#29', 'GAP-20'],
    note: 'Roles exist and gate the key settings; no one can be invited or given a role yet. Records are not yet kept to their owner inside an organization (GAP-20).',
  },
  {
    id: 'FR-GOV-02',
    text: 'Every report goes to its approver in one step (auto-approval waits for Phase 2), and the approver can approve, or return it with a comment.',
    sources: ['journeys §4.4', 'roadmap inc 3'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Governance · Single-step approval'],
    features: ['F-18', 'F-26'],
    backlog: [24],
  },
  {
    id: 'FR-GOV-03',
    text: 'In an organization of two or more, no one approves their own spend. A one-person organization self-attests, and the audit event says so.',
    sources: ['journeys §4.4', 'arch §6.9', 'ADR-0001'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-18', 'F-27'],
    backlog: [24],
    note: 'canApprove() is built and tested (F-27); no approval uses it yet.',
  },
  {
    id: 'FR-GOV-04',
    text: "Approving someone else's spend, and every admin action, needs a second factor in this session (aal2). A one-person organization's self-attestation does not.",
    sources: ['arch §6.9'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-11'],
    backlog: [8],
  },
  {
    id: 'FR-GOV-05',
    text: 'Every state change appends an audit event in the same transaction. The log is append-only and hash-chained, so editing, removing or reordering history is detectable.',
    sources: ['arch AP4', 'arch §6.6', 'vision C5'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    capabilities: ['Governance · Audit trail'],
    features: ['F-28'],
    checks: [
      'db/audit.int › chains events so the stored history verifies',
      'db/audit.int › blocks even the table owner from rewriting history',
      'domain/audit › detects removed and reordered events',
      'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
    ],
  },
  {
    id: 'FR-GOV-06',
    text: 'Finance admins and auditors can read the audit trail for any record.',
    sources: ['design §5.2', 'roadmap inc 3'],
    priority: 'Should',
    phase: 'P1',
    status: 'Planned',
    features: ['F-20'],
    backlog: [26],
  },
  {
    id: 'FR-GOV-07',
    text: 'A policy engine flags problems at capture; reports route through several steps and delegates, with a reminder at 48 hours and escalation at 96; clean reports auto-submit, and those under the limit auto-approve with 10% sampled for audit.',
    sources: ['journeys §4.4', 'journeys §4.6', 'capmap P2'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
    capabilities: [
      'Governance · Policy engine',
      'Governance · Multi-step routing and delegation',
      'Governance · Auto-submit and auto-approve rules',
    ],
    features: ['F-26'],
    note: 'The report lifecycle already allows auto-approval (F-26).',
  },
  {
    id: 'FR-GOV-08',
    text: 'Month-end close: cutoff, an exceptions queue, a sample audit, one export batch, then the period locks and later fixes post as reversals.',
    sources: ['journeys §4.7'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
  },
  {
    id: 'FR-GOV-09',
    text: 'Budgets.',
    sources: ['capmap P4'],
    priority: "Won't",
    phase: 'P4',
    status: 'Deferred',
    capabilities: ['Governance · Budgets'],
  },
  {
    id: 'FR-GOV-10',
    text: 'When a report is reviewed, an expense whose merchant, date, currency or amount doesn’t match its receipt is rejected.',
    sources: ['owner 2026-10-03', 'journeys §4.4'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-18'],
    backlog: [24],
    note: 'Matching, per your answer to Q6: merchant (loosely), date and currency the same; the amount the same, or lower with a reason (FR-EXP-10).',
  },
  {
    id: 'FR-GOV-11',
    text: 'If any expense on a report is rejected, the whole report is returned to the person who submitted it.',
    sources: ['owner 2026-10-03', 'journeys §4.5'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-18'],
    backlog: [24],
  },
  {
    id: 'FR-GOV-12',
    text: 'Rejected expenses are surfaced for attention and remediation: on the returned report and in the Needs you inbox, each with why it was rejected.',
    sources: ['owner 2026-10-03'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-10', 'F-18'],
    backlog: [9, 24],
  },
  {
    id: 'FR-GOV-13',
    text: 'A report can’t be submitted while an expense on it differs from its receipt without a reason. The difference shows as soon as the expense is edited.',
    sources: ['owner 2026-10-03', 'journeys §4.4'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-18'],
    backlog: [24],
    note: 'Your answer to Q6, 2B. Showing the difference is built (F-09); refusing the submission arrives with reports.',
  },

  // Settlement
  {
    id: 'FR-SET-01',
    text: 'Export approved reports as CSV and PDF.',
    sources: ['capmap P1', 'roadmap inc 3'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Settlement · CSV and PDF export'],
    features: ['F-19'],
    backlog: [25],
  },
  {
    id: 'FR-SET-02',
    text: 'Post approved reports to QuickBooks or Xero as one idempotent batch per cutoff; closed periods are locked.',
    sources: ['journeys §4.6', 'capmap P2'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
    capabilities: ['Settlement · QuickBooks and Xero sync'],
  },
  {
    id: 'FR-SET-03',
    text: 'Pay reimbursements through a licensed partner; ExpenseWise never holds funds.',
    sources: ['capmap P3', 'risks R8'],
    priority: 'Could',
    phase: 'P3',
    status: 'Planned',
    capabilities: ['Settlement · Reimbursement payouts'],
  },
  {
    id: 'FR-SET-04',
    text: 'ERP connectors, and corporate cards through a partner.',
    sources: ['capmap P4', 'ADR-0007'],
    priority: "Won't",
    phase: 'P4',
    status: 'Deferred',
    capabilities: ['Settlement · ERP connectors', 'Settlement · Corporate cards via partner'],
  },

  // Insights
  {
    id: 'FR-INS-01',
    text: 'A personal dashboard: spent this month, expenses and trips, business miles, and what is awaiting reimbursement.',
    sources: ['design §5.3', 'capmap P1', 'roadmap inc 3'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Insights · Personal dashboard'],
    features: ['F-22'],
    backlog: [28],
  },
  {
    id: 'FR-INS-02',
    text: 'Search past trips and expenses by merchant, date, amount or trip.',
    sources: ['capmap P1', 'roadmap inc 2'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Insights · Trip history and search'],
    features: ['F-12'],
    checks: [
      'db/trips.int › finds trips by name, purpose, city or a merchant on them, and by dates',
      'db/trips.int › finds expenses by merchant, dates, amount in any currency, or trip',
      'api/expenses › searches by merchant, dates, amount in any currency, and trip (FR-INS-02)',
      'domain/trips › amountMatches',
    ],
  },
  {
    id: 'FR-INS-03',
    text: "Mileage and tax summaries, including a year-end summary a solo professional's accountant accepts.",
    sources: ['capmap P2', 'journeys §4.1'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
    capabilities: ['Insights · Mileage and tax summaries'],
  },
  {
    id: 'FR-INS-04',
    text: 'Team spend analytics, then a custom report builder.',
    sources: ['capmap P2', 'capmap P3'],
    priority: 'Could',
    phase: 'P2',
    status: 'Planned',
    capabilities: ['Insights · Team spend analytics', 'Insights · Custom report builder'],
  },

  // Platform
  {
    id: 'FR-PLT-01',
    text: "Every user belongs to an organization from day one. The owner's one-person organization is created on first sign-in, exactly once.",
    sources: ['ADR-0001', 'ADR-0015'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Platform · Organizations and tenancy'],
    features: ['F-02'],
    checks: [
      'api/workspace › creates the organization on first sign-in, then returns it',
      'db/ai-keys.int › creates a one-person organization with the user as owner, and an audit event',
      'db/ai-keys.int › creates exactly one organization when first sign-ins race',
    ],
  },
  {
    id: 'FR-PLT-02',
    text: 'Sign in with email and password; the API accepts only tokens signed by the project and says when one has expired.',
    sources: ['D-15', 'ADR-0013', 'roadmap inc 1'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    capabilities: ['Platform · Sign-in and TOTP MFA'],
    features: ['F-01'],
    checks: [
      'api/auth › returns the identity proven by a valid token',
      'api/auth › distinguishes an expired token',
      'e2e/settings › serves the sign-in page',
    ],
  },
  {
    id: 'FR-PLT-03',
    text: 'Sign-in asks for a second factor (TOTP) once enrolled.',
    sources: ['capmap P1', 'ADR-0013', 'roadmap inc 1'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Platform · Sign-in and TOTP MFA'],
    features: ['F-11'],
    backlog: [8],
    note: 'Planned for increment 1, which has otherwise shipped (GAP-03).',
  },
  {
    id: 'FR-PLT-04',
    text: 'One person can sign in with several emails; each sign-in reaches the same member and the same receipts. Linking needs proof of both sign-ins.',
    sources: ['ADR-0016'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-03'],
    checks: [
      'api/workspace › links a second sign-in with proof of both, once',
      'db/sign-ins.int › lets a fresh sign-in reach the same member and organization',
      'db/sign-ins.int › never takes over another person',
    ],
  },
  {
    id: 'FR-PLT-05',
    text: "An owner or finance admin saves the organization's own Anthropic and OpenAI keys in Settings. Each key is checked with the provider before it is stored, and the provider's answer is shown when it fails.",
    sources: ['ADR-0015'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-04'],
    checks: [
      'api/workspace › checks a key with the provider, stores it encrypted and never returns it',
      'api/workspace › says what the provider answered, so a failed check can be acted on',
      'api/ai-providers › calls a 400 refused, and a 429 or 5xx unreachable, keeping the status and message',
    ],
  },
  {
    id: 'FR-PLT-06',
    text: 'Email notifications: a report is ready, returned or approved, and a reading needs a look.',
    sources: ['capmap P1', 'roadmap inc 3', 'D-15'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Platform · Email notifications'],
    features: ['F-21'],
    backlog: [27],
  },
  {
    id: 'FR-PLT-07',
    text: 'An admin console limited, in Phase 1, to inviting people and giving them roles.',
    sources: ['capmap P1', 'roadmap inc 4'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    capabilities: ['Platform · Admin console'],
    features: ['F-23'],
    backlog: [29],
  },
  {
    id: 'FR-PLT-08',
    text: 'A native SwiftUI iPhone app, the second client of the same API: document-scanner capture, push notifications, passkeys once generally available, and SAML single sign-on.',
    sources: ['ADR-0004', 'roadmap P3', 'capmap P3'],
    priority: 'Should',
    phase: 'P3',
    status: 'Planned',
    capabilities: [
      'Platform · Push notifications',
      'Platform · SAML SSO',
      'Platform · Passkeys, once GA',
    ],
  },
  {
    id: 'FR-PLT-09',
    text: 'A public API and webhooks for other systems.',
    sources: ['capmap P3'],
    priority: 'Could',
    phase: 'P3',
    status: 'Planned',
    capabilities: ['Platform · Public API and webhooks'],
  },
  {
    id: 'FR-PLT-10',
    text: 'SCIM provisioning, once the identity provider supports it.',
    sources: ['capmap P4', 'ADR-0013'],
    priority: "Won't",
    phase: 'P4',
    status: 'Deferred',
    capabilities: ['Platform · SCIM, once the identity provider supports it'],
  },
];

/** Non-functional requirements: what must hold however a feature is built. */
export const NON_FUNCTIONAL: readonly Requirement[] = [
  // Security and tenancy
  {
    id: 'NFR-SEC-01',
    text: 'One organization never sees or writes another organization’s data.',
    enforcedBy:
      '`org_id` on every tenant table, forced row-level security, all data access inside `withOrg()`; the readiness check counts tables without it',
    sources: ['arch AP6', 'arch §6.9', 'risks R4'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-34'],
    checks: [
      'db/tenancy.int › sees only its own organization',
      'db/tenancy.int › cannot insert rows for another organization',
      'db/tenancy.int › puts a forced tenant policy on every table that holds org data',
      'db/receipts.int › keeps receipts inside their organization',
      'db/sign-ins.int › cannot add a sign-in to another organization',
    ],
  },
  {
    id: 'NFR-SEC-02',
    text: 'The running app can never bypass row-level security.',
    enforcedBy:
      'It connects as `expensewise_app`; `assertRowSecurityApplies()` refuses superusers and BYPASSRLS roles, and readiness fails on them',
    sources: ['arch §6.9', 'ADR-0013'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-34', 'F-30'],
    checks: [
      'db/tenancy.int › refuses a role that bypasses row-level security',
      'db/readiness.int › is not ready as a role that bypasses row-level security',
      'db/readiness › passes only expensewise_app without bypass rights',
    ],
  },
  {
    id: 'NFR-SEC-03',
    text: "Supabase's Data API can't reach our data: the API is the only path to it.",
    enforcedBy:
      'Migration 0002 revokes every grant from `anon`, `authenticated` and `service_role`; no supabase-js or PostgREST for data',
    sources: ['ADR-0013', 'arch §6.9'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-34'],
    checks: ['db/supabase-roles.int'],
  },
  {
    id: 'NFR-SEC-04',
    text: 'Stored provider keys are encrypted, bound to their organization and provider, and never shown again: only the last four characters.',
    enforcedBy: 'AES-256-GCM with the organization and provider as additional data',
    sources: ['ADR-0015'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-04'],
    checks: [
      'api/secret-box › refuses to open a ciphertext under another organization or provider',
      'api/secret-box › shows only the last four characters as a hint',
      'db/ai-keys.int › stores at most four characters of the key as its hint',
    ],
  },
  {
    id: 'NFR-SEC-05',
    text: 'No secret reaches a log, an error report or an API answer: keys, tokens and passwords are removed even when a provider echoes them.',
    enforcedBy: 'Redaction before error reporting; provider messages are scrubbed of the key',
    sources: ['ADR-0015'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-04'],
    checks: [
      'api/redact',
      'api/ai-providers › never repeats the key, even if the provider echoes it',
      'db/connection › names the user, host, port and database but never the password',
      'api/ready › answers 503, not 500, when the probe throws, without echoing the error',
    ],
  },
  {
    id: 'NFR-SEC-06',
    text: 'Receipt images live in a private bucket. Each upload is signed for one path inside the organization; images are shown through links that expire in five minutes.',
    enforcedBy: 'The server derives the path; signed upload and read URLs',
    sources: ['arch §6.9', 'ADR-0017'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-05'],
    checks: [
      'api/receipts › hands out a one-time upload for a path inside the organization',
      'api/receipts › shows each model pending while the receipt is read',
      'storage/supabase › creates the private bucket once, then signs uploads with the secret key',
    ],
  },
  {
    id: 'NFR-SEC-07',
    text: 'Receipts are untrusted input: the model gets no tools and can only return data in our schema.',
    enforcedBy: 'Structured outputs only; no tools are passed',
    sources: ['arch §6.5'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    features: ['F-06'],
    checks: [
      'extraction/claude › sends the image, the schema and the tier effort, and prices the call',
    ],
    shortfalls: ['GAP-15'],
  },
  {
    id: 'NFR-SEC-08',
    text: 'Every response carries security headers: HSTS, no framing, no MIME sniffing.',
    enforcedBy: 'Headers set in next.config.ts',
    sources: ['ADR-0010'],
    priority: 'Should',
    phase: 'P0',
    status: 'Verified',
    features: ['F-29'],
    checks: ['e2e/shell › sends security headers'],
  },
  {
    id: 'NFR-SEC-09',
    text: 'Sign-in tokens are verified with the project’s public keys; shared-secret tokens are refused, so this backend holds no signing secret.',
    enforcedBy: 'JWKS verification in the API',
    sources: ['ADR-0013'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-01'],
    checks: [
      'api/auth › rejects shared-secret (HS256) tokens: this backend holds no signing secret',
    ],
  },
  {
    id: 'NFR-SEC-10',
    text: 'Only people the owner adds can sign in: public sign-ups are off.',
    enforcedBy: 'A Supabase Auth setting',
    sources: ['D-15', 'roadmap inc 1'],
    priority: 'Must',
    phase: 'P1',
    status: 'Implemented',
    note: 'A dashboard setting; nothing checks it.',
  },
  {
    id: 'NFR-SEC-11',
    text: 'Connections to the database are encrypted and verified against Supabase’s root certificate.',
    enforcedBy: 'Bundled root CA; readiness fails on an unverified remote host',
    sources: ['ADR-0013'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-34', 'F-30'],
    checks: [
      'db/connection › verifies Supabase hosts against the Supabase root CA and drops URL ssl params',
      'db/readiness › skips a local database and fails any other unverified host',
    ],
  },
  {
    id: 'NFR-SEC-12',
    text: 'Dependency audit, secret scanning and static analysis run on every push and block a merge on a high or critical finding.',
    enforcedBy: 'Gate G4 and CodeQL',
    sources: ['delivery §7.4', 'ADR-0010'],
    priority: 'Must',
    phase: 'P0',
    status: 'Partial',
    checks: ['ci:security', 'ci:codeql'],
    shortfalls: ['GAP-19'],
    note: 'One high advisory with no fix yet, reached only through lint tooling, is let through; a weekly watch fails once it has one.',
  },
  {
    id: 'NFR-SEC-13',
    text: 'Production credentials reach production only: preview builds of unreviewed branches never hold them.',
    enforcedBy: 'Vercel environment scoping',
    sources: ['delivery §7.3', 'arch §6.9'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    shortfalls: ['GAP-02'],
  },
  {
    id: 'NFR-SEC-14',
    text: 'Built to OWASP ASVS Level 2, with a security review at every phase exit; a SOC 2 Type I audit when the product is sold to businesses.',
    enforcedBy: 'Security review at the Phase 1 exit',
    sources: ['ADR-0010', 'risks R4', 'roadmap inc 4'],
    priority: 'Should',
    phase: 'P1',
    status: 'Planned',
    backlog: [31],
  },

  // Privacy and retention
  {
    id: 'NFR-PRV-01',
    text: 'Financial records are kept seven years by default, configurable per organization, with legal hold.',
    enforcedBy: 'Not designed yet',
    sources: ['vision C5', 'arch §6.9'],
    priority: 'Must',
    phase: 'P0',
    status: 'Planned',
    backlog: [35],
    note: 'Promised for Phase 0 (vision C5); see GAP-12.',
  },
  {
    id: 'NFR-PRV-02',
    text: 'Only the last four digits of a card are ever stored.',
    enforcedBy:
      'The extraction schema asks for exactly four digits; normalization drops anything else',
    sources: ['arch §6.9'],
    priority: 'Must',
    phase: 'P1',
    status: 'Implemented',
    features: ['F-06'],
  },
  {
    id: 'NFR-PRV-03',
    text: 'Location metadata is stripped from stored photos.',
    enforcedBy: 'The browser re-encodes each photo as JPEG before upload',
    sources: ['arch §6.9', 'ADR-0017'],
    priority: 'Should',
    phase: 'P1',
    status: 'Implemented',
    features: ['F-05'],
    note: 'PDFs keep their own metadata.',
  },
  {
    id: 'NFR-PRV-04',
    text: 'Every subprocessor that sees personal data is under a data processing agreement; receipts reach OpenAI only on the fallback path, and are not stored there.',
    enforcedBy: 'Contracts, not code',
    sources: ['ADR-0010', 'ADR-0020'],
    priority: 'Should',
    phase: 'P1',
    status: 'Partial',
    shortfalls: ['GAP-13'],
  },
  {
    id: 'NFR-PRV-05',
    text: 'A deletion request is honored, except for records the law requires us to keep.',
    enforcedBy: 'Not designed yet',
    sources: ['arch §6.9'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
  },

  // Data integrity and money
  {
    id: 'NFR-DAT-01',
    text: 'Money is integer minor units with an ISO 4217 code: no floats, and no rounding outside the domain helpers.',
    enforcedBy:
      '`@expensewise/domain`; lint bans parseFloat and Math.round where amounts are handled',
    sources: ['arch AP5', 'ADR-0008'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-24'],
    checks: [
      'domain/money',
      'domain/decimal',
      'extraction/normalize › turns decimal strings into integer minor units in the stated currency',
    ],
  },
  {
    id: 'NFR-DAT-02',
    text: 'A converted amount always carries its rate, the rate’s source and its date.',
    enforcedBy: 'A database constraint, and the FX helpers',
    sources: ['arch AP5', 'arch §6.7', 'ADR-0008'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-24'],
    checks: [
      'db/tenancy.int › refuses a converted amount without its rate provenance',
      'domain/fx',
    ],
  },
  {
    id: 'NFR-DAT-03',
    text: 'Identifiers are UUIDv7; instants are UTC and transaction dates are local calendar dates.',
    enforcedBy: 'Domain id and date helpers',
    sources: ['arch §6.7', 'ADR-0008'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-24'],
    checks: ['domain/ids', 'domain/dates'],
  },
  {
    id: 'NFR-DAT-04',
    text: 'Rates and mappings are copied onto the record when they apply (mileage rate, FX rate, policy version, category mapping), so a later change never alters an old claim.',
    enforcedBy: 'Snapshot fields on each record',
    sources: ['arch §6.7', 'journeys §4.3'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-25'],
    backlog: [17],
    note: 'The mileage snapshot is built and tested (F-25); no record stores one yet.',
  },
  {
    id: 'NFR-DAT-05',
    text: 'Financial records are never hard-deleted; the audit log can never be changed, by anyone.',
    enforcedBy: 'Grants and triggers',
    sources: ['arch AP4', 'arch §6.7', 'ADR-0008'],
    priority: 'Must',
    phase: 'P0',
    status: 'Partial',
    features: ['F-28'],
    checks: [
      'db/audit.int › denies UPDATE and DELETE to the application role',
      'db/audit.int › blocks even the table owner from rewriting history',
    ],
    shortfalls: ['GAP-10'],
  },
  {
    id: 'NFR-DAT-06',
    text: 'A retried request never duplicates anything: filing is idempotent, each model reads once per request, and a receipt settles once.',
    enforcedBy: 'Client-supplied ids, unique request keys, outbox ids as event ids',
    sources: ['arch §6.4', 'ADR-0017'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-05', 'F-06'],
    checks: [
      'db/receipts.int › treats a retried request as done, and a second copy of a file as a duplicate',
      'db/receipts.int › records each model once per request, then settles once',
      'workflows/relay › uses the outbox id as the event id and the change time as the timestamp',
    ],
  },
  {
    id: 'NFR-DAT-07',
    text: 'No receipt is ever lost: each reaches Ready, Needs a look or Failed, never stays Reading.',
    enforcedBy:
      'Outbox row in the same transaction; eager dispatch; the relay sweep; an on-failure settlement',
    sources: ['arch §6.4', 'delivery §7.7', 'ADR-0017'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    features: ['F-33', 'F-06'],
    checks: [
      'db/receipts.int › stores the row, the event that has it read, and an audit event, together',
      'api/receipts › still files the receipt when the runner is unreachable; the relay sends it later',
      'db/outbox.int',
      'workflows/relay',
    ],
    shortfalls: ['GAP-05', 'GAP-06'],
  },

  // Reliability and recovery
  {
    id: 'NFR-REL-01',
    text: 'Every night, an encrypted copy of the database (auth users included) and of new receipt images goes to a second vendor; dumps kept 30 days plus 12 monthly, images never deleted from the copy.',
    enforcedBy: 'A nightly GitHub Actions job to Backblaze B2',
    sources: ['ADR-0014', 'D-16', 'delivery §7.7'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    features: ['F-37'],
    shortfalls: ['GAP-18'],
    note: 'Runs every night since Oct 3 (F-37). The bucket’s lifecycle rules keep 30 daily and 12 monthly dumps; after each file’s 30-day lock, the job’s own key could still delete it (GAP-18).',
  },
  {
    id: 'NFR-REL-02',
    text: 'A monthly drill restores the latest backup into a throwaway database and checks row counts, row-level security and image checksums.',
    enforcedBy: 'A monthly workflow',
    sources: ['ADR-0014', 'roadmap inc 1', 'roadmap inc 4'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    features: ['F-41'],
    backlog: [10],
  },
  {
    id: 'NFR-REL-03',
    text: 'Recovery point 24 hours; recovery time 4 hours.',
    enforcedBy: 'The nightly backup and a rehearsed restore',
    sources: ['delivery §7.7'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
    backlog: [10],
  },
  {
    id: 'NFR-REL-04',
    text: 'API availability 99.9% a month, measured from outside the app.',
    enforcedBy: 'Synthetic checks against the readiness endpoint',
    sources: ['delivery §7.7'],
    priority: 'Should',
    phase: 'P1',
    status: 'Partial',
    features: ['F-30'],
    checks: ['api/ready › answers 503 with the report when a check fails'],
    shortfalls: ['GAP-08'],
  },
  {
    id: 'NFR-REL-05',
    text: 'The Free plan never surprises us: a heartbeat keeps the project from pausing, and alerts fire at 70% of the database and storage limits.',
    enforcedBy: 'The nightly backup job',
    sources: ['ADR-0014', 'risks R10'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-42'],
    checks: ['db/heartbeat.int › takes the nightly write as one row, however often it runs'],
  },
  {
    id: 'NFR-REL-06',
    text: 'A bad release is undone in seconds: the previous build can be promoted again, and flags act as kill switches.',
    enforcedBy: 'Vercel promotion; flags off by default',
    sources: ['delivery §7.7'],
    priority: 'Should',
    phase: 'P0',
    status: 'Implemented',
    features: ['F-31'],
    note: 'Never rehearsed.',
  },
  {
    id: 'NFR-REL-07',
    text: 'Migrations run before the build goes live and work with the code already live: expand, migrate, contract.',
    enforcedBy: 'The Release workflow runs migrations, then promotes',
    sources: ['delivery §7.7', 'ADR-0018'],
    priority: 'Must',
    phase: 'P0',
    status: 'Partial',
    features: ['F-36'],
    shortfalls: ['GAP-09'],
    note: 'The order is enforced; backward compatibility is a review rule with no check.',
  },

  // Performance
  {
    id: 'NFR-PERF-01',
    text: 'Capture to Ready in under 30 seconds at the 95th percentile.',
    enforcedBy: 'Workflow timestamps',
    sources: ['delivery §7.7', 'journeys §4.2', 'roadmap inc 4'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    features: ['F-06'],
    shortfalls: ['GAP-16'],
    note: 'Each reading stores its own latency; nothing measures the whole path.',
  },
  {
    id: 'NFR-PERF-02',
    text: 'The person never waits on AI: filing answers in about a second, and image bytes never pass through the API.',
    enforcedBy: 'Signed direct upload; reading happens in a workflow',
    sources: ['arch AP3', 'arch §6.4'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-05'],
    checks: [
      'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
      'api/receipts › hands out a one-time upload for a path inside the organization',
    ],
  },
  {
    id: 'NFR-PERF-03',
    text: 'Largest contentful paint under 2.5 seconds on 4G; API p95 under 300 ms.',
    enforcedBy: 'Lighthouse CI and k6 in gate G6',
    sources: ['delivery §7.5'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
  },

  // Design and accessibility
  {
    id: 'NFR-UX-01',
    text: 'WCAG 2.2 AA on every screen, in light and dark, checked automatically.',
    enforcedBy: 'axe in gate G5',
    sources: ['design DP5', 'design §5.4', 'delivery §7.4'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-29'],
    checks: [
      'e2e/shell › has no WCAG 2.2 AA violations',
      'e2e/receipts › has no WCAG 2.2 AA violations',
      'e2e/settings › has no WCAG 2.2 AA violations',
    ],
  },
  {
    id: 'NFR-UX-02',
    text: 'Mobile-first and thumb-first: every flow works on a phone, and is tested on iPhone Safari.',
    enforcedBy: 'Gate G5 runs iPhone WebKit as well as desktop Chromium',
    sources: ['design DP4', 'vision C3'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-29'],
    checks: ['ci:e2e'],
  },
  {
    id: 'NFR-UX-03',
    text: 'Legible money: tabular figures, the currency always shown, and status never carried by colour alone.',
    enforcedBy: 'Design tokens and the money formatter',
    sources: ['design DP5'],
    priority: 'Must',
    phase: 'P0',
    status: 'Implemented',
    features: ['F-29'],
  },
  {
    id: 'NFR-UX-04',
    text: 'Predictable automation: every automatic action says what it did and why, and can be undone until approval.',
    enforcedBy: 'Each status carries its reason on screen',
    sources: ['design DP6'],
    priority: 'Should',
    phase: 'P1',
    status: 'Planned',
    backlog: [9],
    note: 'Readings say why a receipt is Ready or needs a look, and each expense why it is (#6); the inbox gathers them (#9).',
  },
  {
    id: 'NFR-UX-05',
    text: 'One set of design tokens for web and iOS.',
    enforcedBy: 'globals.css today; a Style Dictionary export when the iPhone app starts',
    sources: ['design §5.4', 'risks R3'],
    priority: 'Should',
    phase: 'P3',
    status: 'Planned',
  },

  // AI quality and cost
  {
    id: 'NFR-AI-01',
    text: 'Extraction accuracy is measured on a labeled eval set and reported by layer: public, synthetic, the owner’s past emails if permitted, and real captures.',
    enforcedBy: 'The eval harness',
    sources: ['ADR-0012', 'delivery §7.5'],
    priority: 'Must',
    phase: 'P0',
    status: 'Partial',
    features: ['F-38'],
    checks: ['evals/score', 'evals/synthetic/synthetic'],
    shortfalls: ['#39'],
    note: 'The harness has never run against a model; real receipts are compared instead (ADR-0017).',
  },
  {
    id: 'NFR-AI-02',
    text: 'The total is read correctly on at least 98% of the eval set, and no field regresses by more than a point when a prompt or model changes.',
    enforcedBy: 'Gate G6',
    sources: ['delivery §7.7', 'delivery §7.5'],
    priority: 'Must',
    phase: 'P1',
    status: 'Planned',
  },
  {
    id: 'NFR-AI-03',
    text: 'The cost of every reading is known, in exact integer units, per model.',
    enforcedBy: 'List prices in nano-dollars per token; cost stored on each reading',
    sources: ['risks R6', 'ADR-0006'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-06'],
    checks: [
      'extraction/models › prices a call exactly in nano-dollars',
      'api/receipts › keeps a running comparison of the two models',
    ],
  },
  {
    id: 'NFR-AI-04',
    text: 'The model tier is chosen from measured accuracy and cost, and re-confirmed after about 100 real receipts.',
    enforcedBy: 'The running comparison, then a decision',
    sources: ['ADR-0006', 'ADR-0017', 'roadmap P1'],
    priority: 'Must',
    phase: 'P1',
    status: 'Partial',
    features: ['F-07'],
    checks: ['api/receipts › keeps a running comparison of the two models'],
    shortfalls: ['#4', '#21'],
  },

  // Architecture and portability
  {
    id: 'NFR-ARC-01',
    text: 'One versioned API, described by OpenAPI, serves every client; no business rule lives in a client.',
    enforcedBy: 'The contract is generated from code and checked in CI',
    sources: ['arch AP1', 'ADR-0002'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-30'],
    checks: [
      'api/api › serves its own OpenAPI 3.1 contract',
      'e2e/shell › serves health and the OpenAPI contract under /api',
      'ci:integration',
    ],
  },
  {
    id: 'NFR-ARC-02',
    text: 'Slow or external work runs in durable, retried workflows, never inside a request.',
    enforcedBy: 'Outbox events and Inngest functions',
    sources: ['arch AP3', 'ADR-0002'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-06'],
    checks: [
      'workflows/receipts › throws errors a retry may fix, so the step is retried',
      'api/receipts › files the receipt, hands its event to the runner, and is safe to retry',
    ],
  },
  {
    id: 'NFR-ARC-03',
    text: 'Every vendor sits behind an adapter, and each ADR records its exit path.',
    enforcedBy: '`Extractor`, `ObjectStore` and flag-source interfaces',
    sources: ['arch AP7', 'risks R5', 'risks R9', 'ADR-0003'],
    priority: 'Should',
    phase: 'P0',
    status: 'Implemented',
    features: ['F-06', 'F-05', 'F-31'],
  },
  {
    id: 'NFR-ARC-04',
    text: 'The API is versioned in its path with a six-month deprecation window, and CI blocks a breaking change that lacks a new version.',
    enforcedBy: 'A breaking-change diff in gate G3',
    sources: ['arch §6.10', 'delivery §7.4'],
    priority: 'Should',
    phase: 'P1',
    status: 'Partial',
    features: ['F-35'],
    checks: ['ci:integration'],
    shortfalls: ['GAP-11'],
  },

  // Delivery and change control
  {
    id: 'NFR-DEL-01',
    text: 'Gates G1–G5 run on every push and block the merge: static, unit, integration and contract, security, end to end with accessibility.',
    enforcedBy: 'GitHub Actions',
    sources: ['delivery §7.4', 'ADR-0009'],
    priority: 'Must',
    phase: 'P0',
    status: 'Partial',
    features: ['F-35'],
    checks: ['ci:static', 'ci:unit', 'ci:integration', 'ci:security', 'ci:e2e'],
    shortfalls: ['GAP-11'],
    note: 'G3 has no breaking-change diff and no migration rehearsal on a copy.',
  },
  {
    id: 'NFR-DEL-02',
    text: 'The domain package keeps at least 90% line and branch coverage.',
    enforcedBy: 'A coverage floor in gate G2',
    sources: ['delivery §7.4', 'delivery §7.5'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    checks: ['ci:unit'],
  },
  {
    id: 'NFR-DEL-03',
    text: 'A release applies migrations, promotes that commit’s build, and confirms production serves it; an older run never rolls production back.',
    enforcedBy: 'The Release workflow',
    sources: ['ADR-0018'],
    priority: 'Must',
    phase: 'P0',
    status: 'Partial',
    features: ['F-36'],
    shortfalls: ['GAP-09'],
  },
  {
    id: 'NFR-DEL-04',
    text: 'Merging is the release, and Claude merges only when the product owner says so for that pull request.',
    enforcedBy: 'No required reviewers on `production`; the rule in CLAUDE.md',
    sources: ['ADR-0019', 'delivery §7.1'],
    priority: 'Must',
    phase: 'P0',
    status: 'Implemented',
  },
  {
    id: 'NFR-DEL-05',
    text: 'Every capability ships dark behind a flag, off by default, and is released by turning the flag on.',
    enforcedBy: 'The flag registry',
    sources: ['arch AP8', 'delivery §7.6'],
    priority: 'Must',
    phase: 'P0',
    status: 'Partial',
    features: ['F-31'],
    checks: ['e2e/shell › ships the build-version change dark: its flag is off by default'],
    shortfalls: ['#22'],
    note: 'The receipt and settings screens ship without flags by decision (ADR-0017 §7; Q5).',
  },
  {
    id: 'NFR-DEL-06',
    text: 'A flaky test is a bug: never skipped, quarantined or retried to get to green.',
    enforcedBy: 'The rule in CLAUDE.md and the delivery lifecycle',
    sources: ['delivery §7.5'],
    priority: 'Must',
    phase: 'P0',
    status: 'Implemented',
  },
  {
    id: 'NFR-DEL-07',
    text: 'These records stay true: every API operation, page, workflow, flag, ADR, test file and capability is traced, every reference resolves, and the pages are republished after each successful release.',
    enforcedBy: 'Integrity checks in gate G2; the after-merge hook; the rule in CLAUDE.md',
    sources: ['delivery §7.6'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-39'],
    checks: ['records/integrity', 'records/render'],
  },
  {
    id: 'NFR-DEL-08',
    text: 'The technical architecture and the data model are living pages: read from the repository and the migrated database, revised in the same pull request as any change that affects them, republished after each successful release with what changed, and every report of a change, enhancement or fix confirms they were assessed and revised.',
    enforcedBy:
      'Integrity checks in gate G2 refuse an undescribed package, setting, workflow, background function, table or function; the schema snapshot test in G3; the pull request template; the rule in CLAUDE.md',
    sources: ['owner 2026-10-03'],
    priority: 'Must',
    phase: 'P1',
    status: 'Verified',
    features: ['F-44'],
    checks: [
      'db/schema-snapshot.int',
      'records/integrity',
      'records/render › the architecture page › says what changed since the last release',
    ],
    note: 'Your requirement of Oct 3, with the WayPoint pages as the pattern, branded ExpenseWise.',
  },

  // Observability
  {
    id: 'NFR-OPS-01',
    text: 'Server and browser errors reach one place that alerts, with request contents and secrets left out.',
    enforcedBy: 'Sentry, with redaction',
    sources: ['arch §6.3', 'delivery §7.7'],
    priority: 'Should',
    phase: 'P0',
    status: 'Partial',
    features: ['F-32'],
    checks: ['api/redact'],
    shortfalls: ['GAP-07'],
  },
  {
    id: 'NFR-OPS-02',
    text: 'Health and readiness say what is live and whether it is safe: the version, the database role, TLS and row-level security.',
    enforcedBy: '`/api/v1/health` and `/api/v1/health/ready`',
    sources: ['ADR-0018', 'ADR-0013'],
    priority: 'Must',
    phase: 'P0',
    status: 'Verified',
    features: ['F-30'],
    checks: [
      'api/api › reports health and the deployed version',
      'api/ready › answers 200 with the report when every check passes, never cached',
      'db/readiness › passes when every tenant table forces RLS, outbox aside',
    ],
  },
  {
    id: 'NFR-OPS-03',
    text: 'Alerts on SLO burn rate reach the product owner; each incident gets a blameless review within five working days, and a spent error budget pauses feature work.',
    enforcedBy: 'Not built',
    sources: ['delivery §7.7'],
    priority: 'Should',
    phase: 'P2',
    status: 'Planned',
  },
];

export const REQUIREMENTS: readonly Requirement[] = [...FUNCTIONAL, ...NON_FUNCTIONAL];
